### PR TITLE
find post based on user location, sort by time

### LINKED ISSUE #2141: Filter: Search results, based on location(country), are not sorted as per time.
1. Login into STG/PROD "fightpandemics.com"
2. Navigate to Helpboard and apply location filter = 'United States' 

Issue: You will observe that 6 months old posts are displayed on the top for the selected location.
But when you keep scrolling, you will see recent post for the searched location.
So search results are as per location but they are not sorted as per time when they are posted. 

Expected Result: When user apply location filter -> the latest posts for the selected location should be displayed as per the age i.e. latest on top and so on.

See below screenshots/GIFs
Screen Shot 2021-01-13 at 7 47 18 PM

Screen Shot 2021-01-13 at 7 52 06 PM

ezgif com-video-to-gif-4

Please note, This issue is related to #2053 

**Some Exceptions need to be verified while fixing this issue:**
1. When we search on the base of country, this issue always exist, but when user expand the search location i.e. city/state/country, results are better. Please see this in GIF.

If I search 'United States' 'United Kingdom' 'Spain' 'Barcelona, Spain' the results are NOT accurate.

**Note: So, the locations are not matched properly when broader location is searched for.**

### PR DESCRIPTION
**Pull request by ddveloper**
### What does this pull request aim to achieve? 💯
for searching posts near user's location, limit the distance in a fixed range and sort by time
_Please be concise and link any related issue(s):_
for issue 2141

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Comment by ddveloper** [comment]
@rabbi08 please help to check if this PR (another method) can fix the issue

**Comment by CamilaArias** [comment]
Thanks @ddveloper! It fixes the sorting by time for signed in and out users which is very important.
One issue I see is that I get a post if I choose 2, 5 or 30km in range, but nothing if I click city or state. I get two posts in 30km but one in "Country" and both posts are in the same country. It's probably related to missing some data in the posts but it feels contradictory and confusing.

**Comment by rabbi08** [comment]
Thanks @ddveloper 

Following are few observations:

1. While filtering on the base of the country, only the Post having address as 'US' but not all the posts from US. Please see below screen:

https://user-images.githubusercontent.com/67168400/105382510-236ac800-5bde-11eb-8535-d93de0164b3f.mov

2. While applying the option 'Show results near me': 
the search results display not relevant result in between while sorting as per time. For e.g. sorting location is 'New York' but while displaying the results it display the result of 'Princeton NJ' in between the post associated with 'New York' location, because on the basis of time sorting. 
This scenario is like little tricky. i.e. if I want to see post near me sorted as per time, then as time it gets priority over location, so it is displayed over same location but older post.

Query/Issue: so what if the latest post is from a location which is not near me, then that will take priority. 

https://user-images.githubusercontent.com/67168400/105383151-cde2eb00-5bde-11eb-8c44-8ce49fee31e9.mov

For filters, the search is not displayed as expected but, 'show post near me' seems like working, need to look more into this scenario, though. 

Still testing, will keep updates here. Thanks

**Comment by ddveloper** [comment]
Thanks @rabbi08 
for issue 1, I will try to fix it
for issue 2, the reason is I changed to search a range of 100km range from center of the search, since 'Princeton NJ' is within 100km range from New York, so the result is within the search result

> Query/Issue: so what if the latest post is from a location which is not near me, then that will take priority.  

in this case, if you enabled 'near me' it will not show, the search for 'near me' is collecting all result within 100km then sorting them based on latest post

**Comment by ddveloper** [comment]
About issue 1, I found the reason is not all posts has `visibility` set to 'country' or 'worldwide', in this case, if you search for posts in a country but the post sets its visibility to be 'city', it won't show

**Comment by rabbi08** [comment]
> Thanks @rabbi08
> for issue 1, I will try to fix it
> for issue 2, the reason is I changed to search a range of 100km range from center of the search, since 'Princeton NJ' is within 100km range from New York, so the result is within the search result
> 
> > Query/Issue: so what if the latest post is from a location which is not near me, then that will take priority.
> 
> in this case, if you enabled 'near me' it will not show, the search for 'near me' is collecting all result within 100km then sorting them based on latest post

- I am using 'show result' option for this query, I would like add below observations:
   1. 100km is not like near me, like distance of 2hrs, can we keep like 50km/miles.

> About issue 1, I found the reason is not all posts has `visibility` set to 'country' or 'worldwide', in this case, if you search for posts in a country but the post sets its visibility to be 'city', it won't show

@ddveloper as I did consider this scenario and tested it, but It doesn't look like this is the issue. Please see the below video for the same. It looks like while comparing the country names, it is only comparing the post where only country names are given. Thanks

https://user-images.githubusercontent.com/67168400/105411296-380c8780-5c01-11eb-84a4-e1a55677f2ed.mov

**Comment by ddveloper** [comment]
Thanks @rabbi08 , I reduced the search range default to be 50km, also the city/state/country search is fixed, please have a try 😃

**Comment by ddveloper** [comment]
will be covered by issue #2171 , close this one

**Pull request closed without merging**
