### PR TITLE
border radius fixed for the profile page

### LINKED ISSUE #2252: profile background border radius not consistent
image

### PR DESCRIPTION
**Pull request by sujatha-m**
### What does this pull request aim to achieve? 💯

_Please be concise and link any related issue(s):_This PR Resolves #2252

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`** for a regular feature, **`hotfix/<branch_name>`** for a hotfix, and **`service/<branch_name>`** for a microservice, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Comment by adorapham** [comment]
here is what i get @sujatha-m , since the defect is not clear and i guess it works, can you take a look
image
however , the other profile/organization from helpboard not fixed

@sujatha-m ,  for these screenshots, i go the helpboard and search for individual post or organization post, then click on the name to navigate to individual profile or organization profile
image
image

**Review by adorapham — CHANGES_REQUESTED** [review]
however , the other profile/organization clicking from helpboard  page not fixed

**Comment by sujatha-m** [comment]
> however , the other profile/organization clicking from helpboard page not fixed

@adorapham I don't see any issue here..for me it's working fine.. maybe the build has to resolve first...

can you guide me with the steps where you see exactly what the problem is?

**Comment by sujatha-m** [comment]
> > however , the other profile/organization clicking from helpboard page not fixed
> 
> @adorapham I don't see any issue here..for me it's working fine.. maybe the build has to resolve first...
> 
> can you guide me with the steps where you see exactly what the problem is?

image

**Comment by rabbi08** [comment]
Currently , the user profile page is under redesign, so I would like @sarahjliu to have a look on this requirement. 

Hi @sarahjliu 
Please look at this issue and let us know if this will be still valid issue after profile redesign. if so, then we can fix this after new profile feature is merged.

Thanks

**Comment by rabbi08** [comment]
Currently closing this PR as low priority, in case the issue is observed again, please, feel free to reopen or raise a new ticket for the same. Thanks

**Pull request closed without merging**
