### PR TITLE
Adding new SVGs for image buttons on landing page.

### PR DESCRIPTION
**Pull request by Joeu**
### What does this pull request aim to achieve? 💯

_Please be concise and link any related issue(s):_ #1342 

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix. The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [ ] There are no console warnings and errors.
- [ ] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

### CODE REVIEW

**Review by yu-zhao-xyz — APPROVED** [review]

**Comment by tejasm2** [comment]
Hey @Joeu , the request help icon is cut on edges a bit. cc: @Yu-Alexa-Zhao

**Review by idjevm — CHANGES_REQUESTED** [review]
Yeah I agree with @tejasm2, for some reason the edges are not smooth, please investigate why and make sure it gets changed.

**Comment by Joeu** [comment]
Yep, that's the icon from Zeplin, maybe we need another with the borders fixed.

**Comment by yu-zhao-xyz** [comment]
Sorry for my delayed response. The icons in Zeplin are updated. That should solve the edge issue. https://zpl.io/25WxMoJ, https://zpl.io/V10Dm5Q

**Comment by tejasm2** [comment]
Hey @Joeu , wait, we have new designs for this which are ready. Just waiting to be updated on zeplin. cc: @Yu-Alexa-Zhao

**Comment by yu-zhao-xyz** [comment]
Updated design: 
Request/hollow: https://zpl.io/2p9Jd0Q
Request/filled: https://zpl.io/V4WB1dQ
Offer/hollow: https://zpl.io/29W0o1A
Offer/filled: https://zpl.io/a8M0KvJ

Thanks!

**Pull request closed without merging**
