### PR TITLE
label changed from help@fightpandemics.com into support@fightpandemics.com

### LINKED ISSUE #2055: the label has help@fightpandemics.com but href has support@fightpandemics.com
both should be consistent, so far we have support@fightpandemics.com email
image

might be we need to check to make sure it is  support@fightpandmics.com or help@fightpandmics.com.

on notion,, i see we also have  help@fightpandemics.com

Social Media: Users contacting us via Social Media; Social Media team will forward any product-related issues to the Rapid Response team at help@fightpandemics.com. These emails will be routed to Zendesk.

### PR DESCRIPTION
**Pull request by mathigayathri2001**
### What does this pull request aim to achieve? 💯
This PR resolves label changed from help@fightpandemics.com into support@fightpandemics.com in FAQ
_Please be concise and link any related issue(s):_
PR resolves #2055 

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Comment by mathigayathri2001** [comment]
I have changed the label only in English translation .Please review and let me know to apply the same change in all other language translation. Thanks

**Comment by adorapham** [comment]
@mathigayathri2001 , the English version looks fine but other languages , i still see no-change. Would you please check and apply the same change to other languages  as English version. TY
image

**Comment by mathigayathri2001** [comment]
> @mathigayathri2001 , the English version looks fine but other languages , i still see no-change. Would you please check and apply the same change to other languages as English version. TY
> image

@adorapham i changed all languages and i noticed kannada FAQ page is not working .

@mathigayathri2001, it is possible the data issue for Kannada language, I put the  note on translation channel and hopefully  it will be fixed.

**Comment by joshmorel** [comment]
LGTM @mathigayathri2001 but I we could use interpolation and define the email as a constant variable somewhere (@ddveloper did we have a conversation about this in Slack some time ago, I can't recall...) . For interpolation example see: https://github.com/FightPandemics/FightPandemics/blob/5dfd11d419ed00f6b8506f558e528bec25cb9e48/client/src/locales/translations/es_ES.json#L157

**Comment by joshmorel** [comment]
But you decide this will work but might be more efficient as we add more languages to use interpolation.

**Review by joshmorel — APPROVED** [review]

**Comment by adorapham** [comment]
LGTM, see the other languages are changing . for kannada, we have another defect PR#2073. TY @mathigayathri2001 
image

**Review by adorapham — APPROVED** [review]

**Comment by ddveloper** [comment]
> LGTM @mathigayathri2001 but I we could use interpolation and define the email as a constant variable somewhere (@ddveloper did we have a conversation about this in Slack some time ago, I can't recall...) . For interpolation example see:
> 
> https://github.com/FightPandemics/FightPandemics/blob/5dfd11d419ed00f6b8506f558e528bec25cb9e48/client/src/locales/translations/es_ES.json#L157

@joshmorel  yes, we have that proposal last time but I haven't implement that interpolation yet

**Review by Zaydme — APPROVED** [review]
Thanks @mathigayathri2001!

**Pull request merged**
