### PR TITLE
Fix(loader Icon): Update loading spinner

### PR DESCRIPTION
**Pull request by geobde**
### What does this pull request aim to achieve? 💯

_Please be concise and link any related issue(s):_

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix. The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

### CODE REVIEW

**Review by idjevm — CHANGES_REQUESTED** [review]
Mmmmm I am not sure tbh, I would say that we should test it heavily. It does not look good how it looks. Our app loads faster than this gif to go an iterations so not really good so far... Let's wait to see what others think

**Comment by galeza** [comment]
@CamilaArias Should we link this issue: #1421 ?

**Review by galeza — CHANGES_REQUESTED** [review]
@idjevm I agree with you. App loads faster then spinner. I tested on the Help Board page which loads for me faster then the spinner. Spinner is shown only for a second or less.
@rabbi08 @jessica-lau  what you think about it?

**Comment by manualzuru** [comment]
I guess the speed was improved, before it was taking a lot of time to load.

**Comment by jessica-lau** [comment]
Yea I have to agree with both @galeza and @idjevm. I barely see the gif when clicking to view the details of a post. It only appears for a split second. The app loads very fast so I don't think the spinner's necessary.

**Comment by joshmorel** [comment]
Good news things don't take too long to load! 

Bad news - this was a really nice design and effort here just ended up being not quite appropriate for the situation :cry:

**Comment by rabbi08** [comment]
Agree with @idjevm @galeza @jessica-lau The spinner is displayed for very little fraction of second when I apply filter in the help board. 

But I think the spinner should be displayed when user click on the profile and on the profile page, the posts are being loaded. 

Testing on iPhone 11 Pro Max- 
Currently, for eg, when user clicks to view profile of 'sourced by Fightpandemics(other)', initially it says 'Not activity' but then load the post. 

Refer below screenshots 
image

And then the post are loaded in distorted UI, refer below UI

image

Please note this issue does not exist for all post, it exist for those users who have lots of data to load.

**Comment by CamilaArias** [comment]
Good to know it loads fast for you, I can see it for a few seconds on my third-world network 😅 
Should we change it for a faster moving spinner, like what we currently have in some places, but at least with our brand colour?

**Comment by CamilaArias** [comment]
@rabbi08 I mentioned the same issues to Josh and he linked me to this https://github.com/FightPandemics/FightPandemics/pull/1274 (for adding pagination, instead of trying to load eeeeverything)

**Comment by rabbi08** [comment]
We do have loading spinner when the post are loading. Hence we can close this issue as of now. Please feel free to open another issue, in case you see this. Thanks

**Pull request closed without merging**
