### PR TITLE
Lokalise: Translations update (adding 3 new languages)

### PR DESCRIPTION
**Pull request by jyclam**
This pull request was initiated by Lokalise (user Do Hee Kim) at 2020-12-10 22:22:39

### CODE REVIEW

**Comment by rabbi08** [comment]
We have to add gtm tag and index to add it in the main menu language dropdown. Thanks

**Comment by doheekim93** [comment]
@rabbi08 that is done with #2071

**Comment by rabbi08** [comment]
> @rabbi08 that is done with #2071

Thanks @doheekim93

**Comment by doheekim93** [comment]
Closing this to change the json file for Marathi from mr.json to mr_IN.json

**Pull request closed without merging**
