### PR TITLE
fix post header

### LINKED ISSUE #1302: Overlapping issue in the POST with address and Post TAGs.
PR#1182: Still doesn't work on iPhone 11 Pro max and now reproducible in Mac- safari too.

Please note- I have cleared my cache. 
Devices tested on- Mac, iPhone 11 Pro max, ZTE Blade Max(Andriod)

This issue exist on Mac-Safari but not in Chrome

iPhone 11 Pro max: Safari

ZTE Blade Max(Andriod): Working fine

1. Open "staging.fightpandemics.work'
2. Navigate to 'Help Board'

Issue: The Address -> City overlaps the post TAGs.

Please note that I have tried to change the address and re check the view of the new post with new address, the issue still exist.

Few of the posts have overlap of the cities with the post TAGs as shown in below screenshot:

Screen Shot 2020-07-30 at 2 24 23 PM

image

### PR DESCRIPTION
**Pull request by phuclb**
### What does this pull request aim to achieve? 💯
Resolves #1302

_Please be concise and link any related issue(s):_

- [ ] I have checked that no one else is working on similar changes.
- [ ] I have read the latest [**README**](README.md) and understand the development workflow.
- [ ] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix. The branch is created in a cloned version of this repo, **not a forked repo**.
- [ ] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [ ] There are no merge conflicts.
- [ ] There are no console warnings and errors.
- [ ] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

### CODE REVIEW

**Comment by phuclb** [comment]
Hi @rabbi08 @idjevm, please review this issue.

**Review by idjevm — COMMENTED** [review]
I thought this was resolved @rabbi08 @sheeba1 @jyclam ?

**Comment by galeza** [comment]
Tested on desktop: 
Screen Shot 2020-08-05 at 17 43 40
Screen Shot 2020-08-05 at 17 39 25

Mobile tested on xiaomi redmi:
Screenshot_2020-08-05-17-41-05-605_com android chrome

**Review by galeza — APPROVED** [review]

**Comment by jyclam** [comment]
Yeah, this was already resolved, but there was a lingering issue which might have been iPhone specific or maybe specific to @rabbi08's setup. So let's wait for @rabbi08 to verify it's fixed for her.

**Review by rabbi08 — COMMENTED** [review]
This is working fine on my Mac-> safari. refer below screenshot.

image

But on iPhone 11 Pro max still specially for:
Please note all other post are looking great leaving this one only Org.

 "Sourced by FightPandemics (Other)-> the company logo and the post tags are not displayed correctly. Just wanna highlight this issue exist only for this specific company post with "OTHER"

Refer below screenshot.

image

**Comment by rabbi08** [comment]
I want to add my observation to the issue above issue exist in Mac -> Safari and iPhone 11 Pro max when there is NO location present for the post. 

See below screenshot from Mac-> safari browser with different Org but NO loc.

image

So I think we have to fix the location issue to fix the display.

**Comment by joshmorel** [comment]
@rabbi08 cc @phuclb 

The problem is the header design is for "City, Country" but these ones Sourced by FP had no Country so there's nothing there. 

A stop gap solution so it doesn't look like that is to ensure equivalent whitespace if there is no `author.location.country` on the post.

But personally I think having some information on who this post is to be shared with (`post.visibility`) would be useful. The Country might be "US" but the post is for worldwide and that's not clear here. So for example you could have:

If offer:
"US | Help for Worldwide"
"US | Help for Country"
"San Fransisco, US | Help for City"

If request:
"US | Help from Worldwide"
"US | Help from Country"
"San Fransisco, US | Help from City"

Then, for example, the ones without a country would be:
"Help for Worldwide"

But there is no design for this.

Thoughts @ppagarawal @manualzuru ?

**Comment by phuclb** [comment]
Hi @rabbi08,

I know how to fix this issue, it will work with ot without location info.
Let me update it.

Thanks for your information.

**Comment by phuclb** [comment]
Hi @rabbi08, I updated post's header.
Please check it again.
Thanks so much.

**Review by rabbi08 — APPROVED** [review]
Thanks @phuclb 
This issue is working fine on Mac-> Safari as in below screenshots:

image

Working fine on iPhone 11 Pro Max, please see below screenshot:

image

**Comment by phuclb** [comment]
Thanks @rabbi08

**Review by idjevm — CHANGES_REQUESTED** [review]
Please clean up this branch / PR. There are a lot of changes that are not supposed to be going to Staging yet, looks like you have merged branches from many places. 

We might have to close this branch and just reopen a new one, with only the changes you made. Right now I can't really tell which are the changes you made since there are 23 files changed and changes all over the place.

**Comment by phuclb** [comment]
Hi @idjevm, I will close this to open new one with my change only.

Thanks for your review.

**Pull request closed without merging**
