### PR TITLE
Modified Quit filters button to Clear filter button

### LINKED ISSUE #1663: Desktop/Mobile : Quit filter button Caption to be changed to Clear filters
Environment: Windows OS 10 with Chrome Browser
URL used: https://featuremessage-modal1457.fightpandemics.xyz/feed

Steps to reproduce (STR),
1. Open the URL
2. Goto Help Board
3. Click on Filters option

Expected results,
**Clear filters**

Actual results
**Quit filters**

### PR DESCRIPTION
**Pull request by sujatha-m**
### What does this pull request aim to achieve? 💯

_Please be concise and link any related issue(s):_This PR Resolves #1663 

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Review by jyclam — CHANGES_REQUESTED** [review]
You want to make this change in the `en_US.json` as that is the master file that Lokalise (the service we use to manage our translations) watches for changes. 

You can certainly make this change in `en_GB.json` too to avoid the translation lag, but changes are only permanent when translations are changed from Lokalise platform as that is our source of truth. 

See here for more details:
https://github.com/fightPandemics/FightPandemics/#internationalization

**Review by jyclam — APPROVED** [review]
LGTM!

**Review by idjevm — APPROVED** [review]
LGTM! Thank you @sujatha-m

**Comment by shrutigupta1981** [comment]
image
 Checked the issue. Working fine!

**Pull request merged**
