### PR TITLE
Production Release as on 11-11-2020

### PR DESCRIPTION
**Pull request by rabbi08**
### What does this pull request aim to achieve? 💯

_Please be concise and link any related issue(s):_

- [ ] I have checked that no one else is working on similar changes.
- [ ] I have read the latest [**README**](README.md) and understand the development workflow.
- [ ] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [ ] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [ ] There are no merge conflicts.
- [ ] There are no console warnings and errors.
- [ ] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [ ] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Comment by galeza** [comment]
Hi,
I retested #1762 , #1711, #1764 and #1577 , #1636 
LGTM

**Review by galeza — APPROVED** [review]

**Review by jessica-lau — APPROVED** [review]
retested:
1711, 1762, 1764 cypress tests
1683, 1728, 1577, 1653

**Comment by rabbi08** [comment]
Verified PR#1683, 1577, 1728, 1653, 1778 along with regression testing is done.

Note: Email confirmation for 'contact Us' is pending along with translation PR #1780 

@FedericaZn you can run your test for GTM validation. Thanks.

**Review by FedericaZn — APPROVED** [review]

**Review by Zaydme — APPROVED** [review]
LGTM code-wise

**Pull request merged**
