### PR TITLE
Feature/issue 1124

### LINKED ISSUE #1124: Able to enter characters, special characters and negative numbers under Age field in feedback screen [DESKTOP] [MOBILE]
**Environment:**   https://staging.fightpandemics.work/

**Steps to reproduce:**

- 1. Click the feedback icon top right when not signed in or the feedback option under hamburger menu when signed in 
- 2. Select options and enter values in screen 1 and screen 2 . 
- 3. Under screen 3  What is your age ? question . I am able to enter  only  the below other than numbers strangely. 

1. " e " character
2. " - "  hyphen 
3. "+ " plus
4. " . "  period

**In addition I am able to enter:**

0, -1,-2  zero and negative numbers 

**Actual results:**
Able to enter other than only numbers.
**Expected Results:**
Should be able to enter only numbers

**Attached screenshots in the file below:**

[Feedback - AGE ISSUE.docx](https://github.com/FightPandemics/FightPandemics/files/4907188/Feedback.-.AGE.ISSUE.docx)

### LINKED ISSUE #1520: Up and Down Arrows in Age Question Field on Feedback Screen Should Be Removed [DESKTOP]
**Environment:** https://staging.fightpandemics.work/

**Steps to reproduce:**

1. Click the feedback icon on the top right of the homepage when user is not signed in.

2. Answer questions on screens 1 and 2 until user reaches screen 3.

3. On screen 3, hover over the input field for the "What is your age?" question, an up and down arrow appears on the right side of the input box. When no value is entered into the field yet and user clicks the down arrow, the input box populates with a negative number.

**Actual results:**

When user hovers over the input field for the "What is your age?" question in screen 3, an up and down arrow appears on the right side of the input box. When no value is entered into the field yet and user clicks the down arrow, the input box populates with a negative number.

**Expected Results:**

User should not be able to use the arrow to scroll to a negative number. The up and down arrow should be completely removed since it is not necessary. User should just type in their age into the input box.

Attached screenshots in the file below:

image

### PR DESCRIPTION
**Pull request by bittricky**
### What does this pull request aim to achieve? 💯
This PR includes regex validation to prevent the user from entering values that are not numbers 0 - 99;

_Please be concise and link any related issue(s):_
#1124 

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](https://github.com/FightPandemics/FightPandemics/blob/master/README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`** (need to have cloned the repo not forked).
- [x] This branch is rebased/merged with the **latest master**.
- [x] There are no merge conflicts.
- [ ] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

### CODE REVIEW

**Review by adisen — APPROVED** [review]
Deployment link not working. But looks good to me

**Review by joshmorel — CHANGES_REQUESTED** [review]
Hi @bittricky  I don't think this is the right approach. You can't use clear or back button. 

Ideally we'd use input validation and prevent submit on errors.

Even better - most surveys use an age range instead of number so we could use a select. @pthoma14 are you still owning this feature? Any thoughts

**Comment by bittricky** [comment]
@joshmorel I can reimplement this fix. If we want change the input field to a select field for a age range, I can push that implementation up. Is there else you'd like to see change in the PR?

**Comment by joshmorel** [comment]
@nivetheatha this is the PR to resolve being able to put to text for age but as discussed in Slack a limited set of age range options would be better. @bittricky sorry for not getting back earlier.

@emtay are you the PM owning feedback now?

**Comment by emtay** [comment]
@joshmorel I wasn’t but we can find a new pm to take it. This was labeled p4 but not sure I fully understand what it is for... 😬😳

**Comment by joshmorel** [comment]
Ah okay @emtay you had asked about feedback so not sure if you had taken it on. But in any case this is P4-. So maybe pause anything related to feedback feature until we actually launch MVP?

**Comment by kannan1001** [comment]
When user gives special character/characters alone in feedback it accepts it while it should accept special characters with some strings and for age it accepts negative value too whereas it should accept two digit positive number.

**Comment by joshmorel** [comment]
I am closing this as the branch is so far behind.

We can decide to resolve this later via:

1) Use a `select` with age range options
2) Keep `input` but use validation (frontend & backend) instead of preventing key entry

**Pull request closed without merging**
