### PR TITLE
Production Release as on 10-27-2020

### PR DESCRIPTION
**Pull request by rabbi08**
### What does this pull request aim to achieve? 💯

_Please be concise and link any related issue(s):_

- [ ] I have checked that no one else is working on similar changes.
- [ ] I have read the latest [**README**](README.md) and understand the development workflow.
- [ ] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [ ] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [ ] There are no merge conflicts.
- [ ] There are no console warnings and errors.
- [ ] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [ ] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Comment by rabbi08** [comment]
Verified following PRs in STG on mobile (iphone) and desktop(windows), thanks:

- PR #614 : PASS Refer below screenshot.
Screenshot 2020-10-28 at 12 09 29 AM

- PR #1663 : PASS Refer below screenshot
Screenshot 2020-10-27 at 11 58 09 PM

- PR #1696 : PASS refer below screenshot.
FightPandemics (17)

**Comment by rabbi08** [comment]
Thanks @galeza for verifying PR #1674 & #1706 in STG.

@FedericaZn QA testing is done in STG, kindly run your test as per you and update here in STG environment. Thanks

**Comment by FedericaZn** [comment]
Impossible to verify GTM at the moment since the debug mode is not working at present, it doesn't seem that these PR will affect tags as they don't affect IDs or URLs or text so I think we can proceede

**Review by idjevm — APPROVED** [review]
Let's 🚢  it @joshmorel !

**Review by Zaydme — APPROVED** [review]
LGTM (I didn't review the cypress part)

**Review by ddveloper — COMMENTED** [review]
LGTM

**Pull request merged**
