### PR TITLE
changed the edit and delete button to ellipsis

### LINKED ISSUE #1841: Edit & Delete commen's UI should be an ellipsis instead of individual buttons
Currently, the comment section in a post has edit & delete as buttons.
image

It needs to be an ellipsis with the edit and delete as a menu bar.
image

### PR DESCRIPTION
**Pull request by mathigayathri2001**
### What does this pull request aim to achieve? 💯
changed the edit and delete button to ellipsis

_Please be concise and link any related issue(s):_
this PR resolves #1841 

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Comment by mathigayathri2001** [comment]
This is Desktop  and Mobile View
Recording-_4

Recording-_3

**Comment by tejasm2** [comment]
This looks good @mathigayathri2001 . Is it possible to make the color of the 3 dots grey...similar to the color of the 3 dots we have on Posts.

**Review by rabbi08 — CHANGES_REQUESTED** [review]
@mathigayathri2001 
On Mobile-> the ellipsis are covering the comment timestamp on mobile (Device- iphone 11 Pro max). Please see below screenshot.
FightPandemics

Also, as mentioned by @tejasm2 please make them not BOLD so that they should look same as they are for the post.

Thanks

**Comment by rabbi08** [comment]
@mathigayathri2001 @tejasm2 
We need to fix this one, as we will have code freeze by tome. Thanks.

**Comment by mathigayathri2001** [comment]
> @mathigayathri2001 @tejasm2
> We need to fix this one, as we will have code freeze by tome. Thanks.

Hi @rabbi08, @tejasm2 Can you please review the enclosed gif. When I test on my end, the responsive looks like this , this is the way I used to test the responsive functionality during development. The other option is I can bring down the ellipsis little bit down, this will impact the desktop version as well. please review the screen shot , I hope this will resolve this issue. Since I could not able to reproduce the issue in the mobile view . let me know weather i can proceed with this modification and push the modified code .
Recording-_9

Untitled2

**Comment by rabbi08** [comment]
@mathigayathri2001 
currently the build is down, can you please re-run the build, also you can test on simulation 'lamdatest'. Do you have an account on that? if not you can share your email with Agnieszka.

**Comment by rabbi08** [comment]
@mathigayathri2001 
This issue works fine for newly added comments but not for existing/edited. See below screenshot.

Screenshot 2020-11-29 at 7 01 17 PM

**Comment by galeza** [comment]
hi @rabbi08 @mathigayathri2001 
I checked on Android + also for other languages and for newly added post ellipsis overlap test:
Screenshot_2020-11-30-12-08-23-021_com android chrome

**Comment by mathigayathri2001** [comment]
Hi @joshmorel @Zaydme Please review the enclosed screen shot. In my local the responsive is coming good. But testing team is mentioning having issues in responsive  . I need suggestion and help. 
Untitled5

**Comment by Zaydme** [comment]
I am not having an issue as well.
But to be safe, just make the "timestamp+edited" into a block element, so they always show in a new line.
Screenshot_20201130-141528_Chrome

**Comment by galeza** [comment]
Hi @Zaydme @mathigayathri2001 
On Android when I add **a new comment** I see the following overlapping
Screenshot_2020-11-30-14-26-35-452_com android chrome
:

**Comment by skrithiga** [comment]
@mathigayathri2001 This is from my Android phone. I edited one comment as myself and another as an organization. That shouldn't be any different. But I get different experience in both the cases. See the following screenshots.

Screenshot_20201130-113942

Screenshot_20201130-113751

**Comment by skrithiga** [comment]
@mathigayathri2001 Also, When I click edit, can we make the cursor highlighted in the comment section? Right now, the edit is enabled, but its not clear. I have to click on the comment section to get the edit cursor. 
@rabbi08 @galeza @Zaydme Thoughts?

**Comment by CamilaArias** [comment]
I think the timestamp should be outside and under the comment bubble. And @mathigayathri2001 if possible you can keep the text in the container it has now but make the bubble longer and put the ellipsis on that side, then the text will wrap before it gets to overlap with the ellipsis.

This will need more design tweaks in the future so I think the above should work for now.

**Comment by rabbi08** [comment]
Verified the fix on lamdatest simulation for iPhone and Andriod, working fine

Please see below GIF, and screenshot.
Screen Shot 2020-11-30 at 8 48 28 PM
ezgif com-video-to-gif-3

**Review by Zaydme — APPROVED** [review]
LGTM!

(Usually I would have suggested some minor code changes, but due to the PROD release tomorrow, I don't think we have time for that, this should work good.)

Thanks @mathigayathri2001!

**Review by rabbi08 — APPROVED** [review]

**Pull request merged**
