### PR TITLE
Reversed the post visibility dropdown order

### LINKED ISSUE #1696: Create Post Module: Post visibility dropdown - order to be reversed
Expected: Create Post Module: Post visibility dropdown - order to be reversed- for a day, for a week, for a month, forever

Actual: Create Post Module: Post visibility dropdown - order - forever, for a month, for a week, for a day

### PR DESCRIPTION
**Pull request by sujatha-m**
### What does this pull request aim to achieve? 💯

_Please be concise and link any related issue(s):_ This is PR Resolves #1696 

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Review by galeza — CHANGES_REQUESTED** [review]
Hi @sujatha-m 

Order was reversed:
Screen Shot 2020-10-22 at 11 16 39

But could you look at one thing:
I save my post with visibility for a month:
Screen Shot 2020-10-22 at 11 13 56
I click post and then View my post -> Edit
In the edit mode I see - For a week:
Screen Shot 2020-10-22 at 11 14 07

On staging we have a correct behaviour.

**Comment by sujatha-m** [comment]
> Hi @sujatha-m
> 
> Order was reversed:
> Screen Shot 2020-10-22 at 11 16 39
> 
> But could you look at one thing:
> I save my post with visibility for a month:
> Screen Shot 2020-10-22 at 11 13 56
> I click post and then View my post -> Edit
> In the edit mode I see - For a week:
> Screen Shot 2020-10-22 at 11 14 07
> 
> On staging we have a correct behaviour.

@galeza  i don't see any problem here if I choose a month it is showing me a month. can you please specify the where exactly you are see the issue.

**Comment by galeza** [comment]
Hi @sujatha-m 
You compare wrong screenshots. Maybe I should've gave them numbers. You save 'For a moth' and when open for Edit you see 'For a week'.
Screen Shot 2020-10-22 at 18 47 45
Screen Shot 2020-10-22 at 18 47 58
Screen Shot 2020-10-22 at 18 48 08

**Comment by sujatha-m** [comment]
> Hi @sujatha-m
> You compare wrong screenshots. Maybe I should've gave them numbers. You save 'For a moth' and when open for Edit you see 'For a week'.
> Screen Shot 2020-10-22 at 18 47 45
> Screen Shot 2020-10-22 at 18 47 58
> Screen Shot 2020-10-22 at 18 48 08

@galeza I have resolved the issue..

**Review by galeza — APPROVED** [review]
Retested. Thank you.
LGTM

**Comment by galeza** [comment]
@shrutigupta1981 Please check this PR. Build URL: https://feature1696.fightpandemics.xyz.

**Comment by shrutigupta1981** [comment]
image
Working fine

**Comment by shrutigupta1981** [comment]
image

**Review by idjevm — APPROVED** [review]
🤔 @joshmorel I remember last time we updated this caused some issues, should we merge or change somewhere else?

**Comment by joshmorel** [comment]
@idjevm Only if we change the values (due to backend/model). The order doesn't matter I'm close to sure.

**Review by joshmorel — APPROVED** [review]
LGTM

**Comment by rabbi08** [comment]
Verified in STG as working fine, the post retain the visibility after creation and EDIT.

- Post creation:
image

- EDIT the visibility and check again 
image

great @idjevm @joshmorel if you can confirm, this change is for creating new data but will not be applied to the existing data?

**Pull request merged**
