### PR TITLE
initializing gtm in Login page with userId

### LINKED ISSUE #1190: Extra GTM <noscript> added when navigating between pages
**Steps to recreate:**
1. Sign in to your account 
2. Go to homepage on staging https://staging.fightpandemics.work/
3. Click on **any** links eg `About Us`, `Help Board`, `Request Help`, `Offer Help`...
4. Observe that an extra <noscript> tag is added 

It's a GTM related element
```
      <iframe src="https://www.googletagmanager.com/ns.html?id=undefined&gtm_auth=&gtm_preview=&gtm_cookies_win=x"
        height="0" width="0" style="display:none;visibility:hidden" id="tag-manager"></iframe>
```

Screen Shot 2020-07-16 at 12 52 21 PM

Looks like every time we call `TagManager.initialize` it inserts a new one, https://github.com/alinemorelli/react-gtm/blob/master/src/TagManager.js#L43

### PR DESCRIPTION
**Pull request by nr431207**
### What does this pull request aim to achieve? 💯
fixes duplicate `<noscript>` tag that appears when switching between pages.
_Please be concise and link any related issue(s):_
fixes #1190 

- [ ] I have checked that no one else is working on similar changes.
- [ ] I have read the latest [**README**](https://github.com/FightPandemics/FightPandemics/blob/master/README.md) and understand the development workflow.
- [ ] The name of this branch is: **`feature/<branch_name>`** (need to have cloned the repo not forked).
- [ ] This branch is rebased/merged with the **latest master**.
- [ ] There are no merge conflicts.
- [ ] There are no console warnings and errors.
- [ ] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

### CODE REVIEW

**Comment by nr431207** [comment]
@joshmorel @idjevm @kylejvh initially we decided to keep the gtm initializing in the App.js  and also initing it in the NavLayer but that caused the `noscript` tag to appear for each page as the user switched between pages. I now put it in the Home page where the user lands after signing in. if I also keep initing in the App.js as well, there will be one extra `noscript` tag still.. thoughts?

**Comment by jyclam** [comment]
@nr431207 I think the best approach would be to initialize in `App.js` and then pass in the userID in the datalayer after the user has logged in.

**Comment by nr431207** [comment]
@jyclam I tried that approach, along with adding the dataLayer in App.js and then giving it the value of userId in Home component, but it did not include the dataLayer when I tested,  it somehow needs to be re-initialized again after feeding the userId to it. And I just realized, the user doesnt always necessarily land on Home page once they login, so it makes sense to initialize in App as you said, but again userId wont be accessed there since user hasnt logged in.

**Comment by idjevm** [comment]
Talked with Sonia, she will reopen this from Master instead.

**Comment by jyclam** [comment]
@nr431207 Hmm if we init in the login page as is, I don’t think we’re capturing users that don’t hit the login page. I think we also want to track non-logged in users right?

**Comment by idjevm** [comment]
non-logged users do not have an userId... So I think the purpose of this is to only track logged in users.

**Comment by jyclam** [comment]
Right non-logged in users don't have an id, I think we still want to track them? @doheekim93

**Comment by idjevm** [comment]
Yeah but that's a different use case than here. So that would be implemented later for the datalayer where BI wants to track some info

**Comment by jyclam** [comment]
But wouldn't we then need to come back and move the gtm init back to `app.js` at that point? We'd be attaching datalayers to this tagmanager then

**Comment by doheekim93** [comment]
Yeah, we want to be able to track non logged in users as well!

**Comment by idjevm** [comment]
Kind of, yeah working on checking the PR that Sonia open. Again, we are not tracking non logged users this way. Different use case.

**Comment by jyclam** [comment]
Ah maybe there's something I'm missing. How are we tracking non logged in users?

**Pull request closed without merging**
