### PR TITLE
Lokalise: Translations update for existing languages

### PR DESCRIPTION
**Pull request by jyclam**
This pull request was initiated by Lokalise (user Do Hee Kim) at 2020-12-16 22:57:06

### CODE REVIEW

**Comment by doheekim93** [comment]
@adorapham Here is the new PR. Does this look okay? Thanks!

**Review by adorapham — APPROVED** [review]
LGTM. TY

**Review by rabbi08 — APPROVED** [review]
looks good. Thanks

**Review by Zaydme — APPROVED** [review]
LGTM

**Pull request merged**
