### PR TITLE
added horizontal rule between posts

### LINKED ISSUE #1246: Separate posts with horizontal rule
As a user I want to have clear distinction between different posts on Help Board so that I they are readable.

Currently, there is no separation between different posts on helpboard.

### PR DESCRIPTION
**Pull request by OzkanAbdullahoglu**
### What does this pull request aim to achieve? 💯
Resolves #1246 
_Please be concise and link any related issue(s):_

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](https://github.com/FightPandemics/FightPandemics/blob/master/README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`** (need to have cloned the repo not forked).
- [x] This branch is rebased/merged with the **latest master**.
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

### CODE REVIEW

**Comment by idjevm** [comment]
@ppagarawal this is how it is looking like - feel free to add any comments here 
image

**Comment by idjevm** [comment]
image

**Comment by ppagarawal** [comment]
lgtm

**Comment by idjevm** [comment]
@rabbi08 tagged you on slack.

**Comment by sheeba1** [comment]
looks ok on iphone XR (thought its not across on page from Left to right)



image

**Pull request merged**
