### PR TITLE
Feature/add social share buttons

### LINKED ISSUE #853: 'Feed' share link not working as expected (only copy, no links to social media)
1. Open "" 
2. Login using valid email/password
3. Click 'FEED' and click on 'Share' icon to share the FEED

Issue: Mismatch with the FP design, because as per Zeppelin design, the user should be directly be able to share the link on email/whatsapp/msg, etc. But currently it say that the link is copied.

Note: Though user is able to explicitly copy/paste the Link.

Please refer attached screenshots.

image

Screen Shot 2020-06-26 at 7 43 06 PM

### PR DESCRIPTION
**Pull request by jyclam**
### What does this pull request aim to achieve? 💯
Implement native share using [`navigator.share` web API](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share). Fallback to modal with clickable icons and copyable text area when `navigator.share` is not available. 

_Please be concise and link any related issue(s):_
closes #853 

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](https://github.com/FightPandemics/FightPandemics/blob/master/README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`** (need to have cloned the repo not forked).
- [x] This branch is rebased/merged with the **latest master**.
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

Screenshot_20200727-164948
Screenshot_20200727-165215

Screen Shot 2020-07-27 at 4 55 16 PM

### CODE REVIEW

**Comment by jyclam** [comment]
@Yu-Alexa-Zhao please review and make design suggestions for web modal (last picture embedded).

**Review by joshmorel — APPROVED** [review]
LGTM. Thanks @jyclam 

Tested on my own android as well as desktop web and both seem fine. 

I guess the idea behind `fakeShares` `setFakeShares` was there would be a count of the number of times it is shared? Anyways, this seems atypical (you don't see share counts in medium, linkedin etc) and we don't have it in our model so we can add it later if the product team asks for it.

**Comment by jyclam** [comment]
> I guess the idea behind `fakeShares` `setFakeShares` was there would be a count of the number of times it is shared? Anyways, this seems atypical (you don't see share counts in medium, linkedin etc) and we don't have it in our model so we can add it later if the product team asks for it.

Yeah, thanks that's what I was thinking since I didn't see it in our model or in the design. Sorry I forgot to explain it in the initial PR.

**Review by idjevm — APPROVED** [review]
LGTM! This is a great first implementation. Let's get it merged and have the QA team give it a test on the rcv11 environment. 

@galeza @rabbi08 @sheeba1 @nivetheatha Please if you guys could test this on the rcv1.1 that would be awesome! TIA !

**Comment by galeza** [comment]
@idjevm 
ok, I'll put this on the slack channel and request retesting

**Comment by nivetheatha** [comment]
This works well in Samsung Galaxy ( android).

**Comment by jessica-lau** [comment]
Works on iOS as well.

**Comment by yu-zhao-xyz** [comment]
Sorry I joined the party a bit late. I think the web modal design works well. Thanks!

**Comment by sheeba1** [comment]
some suggestions : Sharing via Email  can have info about FP and post creator.
Sharing via FB -can have post details

**Pull request merged**
