### PR TITLE
This PR resolves Issue#1497 --shift + Enter adds new Line

### LINKED ISSUE #1497: Shift+Enter to create a new line while commenting
### Issue
(Staging) The user can't start a new line while writing a new comment. Both Enter or Shift+Enter are considered as sending the comment (The user is able to press Enter to begin the new line while editing the existing comment though.)
> Please check the video in [this post](https://fightpandemics.slack.com/archives/C015KDNRJ7K/p1598774899016200)

### Steps to reproduce
1. Access any post as a logged-in user, write a comment but not press the icon on the right to send it yet
2. Try press "Enter", you will see the comment is sent
3. Try writing a new comment and then press "Shift+Enter", the comment is sent anyway

### Expected behavior
The user should be able to start a new line while commenting by using "Shift+Enter"

### PR DESCRIPTION
**Pull request by AshBha243**
### What does this pull request aim to achieve? 💯

_Please be concise and link any related issue(s):_

- [ ] I have checked that no one else is working on similar changes.
- [ ] I have read the latest [**README**](README.md) and understand the development workflow.
- [ ] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix. The branch is created in a cloned version of this repo, **not a forked repo**.
- [ ] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [ ] There are no merge conflicts.
- [ ] There are no console warnings and errors.
- [ ] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

### CODE REVIEW

**Comment by pemika-me** [comment]
Hey @AshBha243, not sure why but it shows 503 error when I tried to access both on Deasktop and mobile.

**Comment by joshmorel** [comment]
> Hey @AshBha243, not sure why but it shows 503 error when I tried to access both on Deasktop and mobile.

We need to re-deploy as the review branch is expired after 24h. (I think) anyone who is a member of the org can do so.

Click "Checks" tab:
image

Click "Deploy Review Build" > "Re-run Jobs" > "Re-run all Jobs"
image

Wait about 5-10m then it should be ready again - a few moments after all of these are green:
image

**Review by joshmorel — CHANGES_REQUESTED** [review]
Thanks @AshBha243 

See the comment from @ppagarawal , it's still not addressed for mobile as there is no shift button.

> Mobile: use the button to post. Pressing shift must toggle the send button to change to enter a new line.

But  @pemika-me @ppagarawal   I think this is unnecessarily complicated from development perspective and also a little odd from a UX perspective.

I'd suggest with mobile enter is always a newline (see Slack) OR keep it really simple and just make it like a normal textbox - enter is new line for moth mobile & desktop. I get using enter for chat when messaging back and forth to add efficiency but here we're just posting a comment.

**Comment by pemika-me** [comment]
@joshmorel Ah, I see. Thank you so much for your kind explanation. Btw I was assigned to be a collaborator, may have to try your steps next time if it would work. :smiley:   And yeah, I do agree with your point. But I am not sure, I thought this sentence means only post the comment when pressing on the send icon... May you please help clarify? @ppagarawal 

@AshBha243 Tested on Desktop, it works well. Appreciate your work effort. :+1:

**Comment by joshmorel** [comment]
@AshBha243 , @pemika-me 's issue here is good but she's no longer involved with FP so I'll make a decision on what the behaviour should be here. 

1) Enter - new line always - don't need to hold shift
2) Ctrl+Enter - submit (or maybe this is the browser default?) 


So basically the only time you can submit without using the button is via Ctrl+Enter.

**Comment by joshmorel** [comment]
I'm closing this because it's too far behind staging. Better to start afresh.

**Pull request closed without merging**
