### PR TITLE
#1603 - Add medium and bold Poppins font

### LINKED ISSUE #1603: Localisation: Font not showing up correctly for certain characters
As mentioned by @galeza in a previous PR, certain characters are not displayed correctly (i.e. shown in a different font). 

The example images shown here are for Polish, but this may be an issue for other languages that have special characters
image

We found that some parts of the webapp do display the characters correctly, as shown below:

Screen Shot 2020-10-06 at 2 51 48 PM

The font used on the platform is called Poppins.

### PR DESCRIPTION
**Pull request by jyclam**
### What does this pull request aim to achieve? 💯

Certain glyphs were not displaying correctly because we did not have Poppins font at that weight. Browser then uses a fallback font which is not consistent throughout the web app. 

This PR adds the medium and bold weights from Google Fonts api in addition to the regular weight. 

_Please be concise and link any related issue(s):_

resolves #1603 

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Review by joshmorel — APPROVED** [review]
LGTM!

**Review by idjevm — APPROVED** [review]
LGTM @jyclam !

**Comment by idjevm** [comment]
@joshmorel Let's wait for @galeza to give it a try before we merge it!

**Review by galeza — APPROVED** [review]
LGTM

Thank you. Now it looks really better!
Tested on desktop and mobile - Android 10.

**Pull request merged**
