### PR TITLE
Production Release as on 01-13-2021

### PR DESCRIPTION
**Pull request by rabbi08**
### What does this pull request aim to achieve? 💯

_Please be concise and link any related issue(s):_

- [ ] I have checked that no one else is working on similar changes.
- [ ] I have read the latest [**README**](README.md) and understand the development workflow.
- [ ] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [ ] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [ ] There are no merge conflicts.
- [ ] There are no console warnings and errors.
- [ ] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [ ] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Comment by adorapham** [comment]
Wrote additional tests for new languages on header section (#2036)-verified
image

**Review by jessica-lau — COMMENTED** [review]
Retested PRs related to cypress and backend tests:
#2043, #2027, #2036, #2026, #2067, #2056

**Review by jessica-lau — APPROVED** [review]

**Review by TimeaKovacs86 — APPROVED** [review]
Retested PRs related to cypress and backend tests:
#2043, #2027, #2036, #2067, #2056

**Review by galeza — APPROVED** [review]
LGTM

**Review by idjevm — APPROVED** [review]
LGTM! This was rather a huge diff. Looks okayish to me. I saw some usage of pixels and other minor things but if QA has tested it (functionality) and nothing is broken  then we should ship it!

**Comment by adorapham** [comment]
Verify these backend PR #1862,#2114, #2115,#2119 and look good to me. 
image

**Comment by jessica-lau** [comment]
Tested PRs #1862, #2102, #2114, #2115, #2106, #2119, #2105

**Comment by rabbi08** [comment]
- Reverted 'Veriff Badges' feature
- No new GTM IDs are added or affected. currently looks fine, as discussed with @FedericaZn 

Thanks

**Review by ddveloper — APPROVED** [review]

**Pull request merged**
