### PR TITLE
Refactored Accessibility widget per cookies banner

### PR DESCRIPTION
**Pull request by kterry1**
### What does this pull request aim to achieve? 💯
https://github.com/FightPandemics/FightPandemics/pull/1443 was closed out so another PR had to be created.

_Please be concise and link any related issue(s):_
#1309 

- [X] I have checked that no one else is working on similar changes.
- [X] I have read the latest [**README**](README.md) and understand the development workflow.
- [X] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix. The branch is created in a cloned version of this repo, **not a forked repo**.
- [X] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [X] There are no merge conflicts.
- [X] There are no console warnings and errors.
- [X] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

### CODE REVIEW

**Comment by kterry1** [comment]
Keep getting an error once I push the code. Going to play around with it a bit more.

**Comment by kterry1** [comment]
Alright. I played around with this a bunch and settled on putting it in the center right of the page with a square radius instead of round and made it flush with the side of the page for the Desktop view.  
For Mobile view I put it on the left of the page because most people scroll with their dominant handle and more people are right handed than left. 
This can be tested here: https://featureaccessibility-offset1309.fightpandemics.xyz/

**Comment by kterry1** [comment]
Since there is a code freeze until tomorrow afternoon, feel free to approve the PR but Do Not Merge until Josh gives the green light in #engineering(Slack).

**Review by sheeba1 — APPROVED** [review]
My observations:
Tested Accessibility widget : Its fine for tomorrow as its Not obstructing any functionalities/features.
My preferred location would be at bottom right corner. Also, noted 'shiver' of the element.


Tested mobile view too

**Review by joshmorel — APPROVED** [review]
LGTM thanks @kterry1  I will squash and merge.

FYI the code freeze didn't include this one as we're fixing specifically for the prod deploy. :wink:

**Pull request merged**
