### PR TITLE
N/A - Fix black text on home page, for some languages

### PR DESCRIPTION
**Pull request by Zaydme**
### What does this pull request aim to achieve? 💯

Fixes this issue, of black text on the home page for languages like Russian and Arabic
image
 
_Please be concise and link any related issue(s):_
N/A

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [ ] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [ ] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [ ] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Comment by CamilaArias** [comment]
@Zaydme can you left align this?

**Comment by jessica-lau** [comment]
@Zaydme it looks like the subtext font size for the arabic and russian are smaller compared the other languages. 

image

image

Other languages:

image

image

**Comment by rabbi08** [comment]
Other than that verified the fix the text color and alignment looks good. Please see below screenshot.
image

**Comment by Zaydme** [comment]
I can't change the font size depending on language, so I think we should keep the current size 
cc @rabbi08 @jessica-lau

**Review by rabbi08 — APPROVED** [review]

**Review by ddveloper — APPROVED** [review]
LGTM

**Pull request merged**
