### PR TITLE
Fix Post title alignment and background

### LINKED ISSUE #999: Post tags,Post title, and description should be left aligned with name
Issue: Feed Posts are not left aligned on staging(Refer Figure 1)
Expected Result:   Post tags,Post title, and description should be left aligned with name. It is applicable to Feed->Posts,post details for both desktop and mobile

Figure1:
image

### PR DESCRIPTION
**Pull request by jyclam**
### What does this pull request aim to achieve? 💯
Fixes Post title alignment and PostCard background width

_Please be concise and link any related issue(s):_
closes #999

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](https://github.com/FightPandemics/FightPandemics/blob/master/README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`** (need to have cloned the repo not forked).
- [x] This branch is rebased/merged with the **latest master**.
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

### Feed
Screen Shot 2020-07-18 at 9 50 42 PM
Screen Shot 2020-07-18 at 9 50 51 PM

### Profile
Screen Shot 2020-07-18 at 9 50 01 PM
Screen Shot 2020-07-18 at 9 49 48 PM

### Post
Screen Shot 2020-07-18 at 9 49 28 PM
Screen Shot 2020-07-18 at 9 49 36 PM

### Feed
Screen Shot 2020-07-18 at 10 08 41 PM
Screen Shot 2020-07-18 at 10 08 28 PM

### Profile
Screen Shot 2020-07-18 at 10 09 52 PM
Screen Shot 2020-07-18 at 10 09 42 PM

### Post
Screen Shot 2020-07-18 at 10 10 30 PM
Screen Shot 2020-07-18 at 10 10 39 PM

### CODE REVIEW

**Comment by sheeba1** [comment]
I agree  with JV, #999 opened as requested by @ppagarawal , prateek can you please confirm.

**Comment by jyclam** [comment]
How about mobile view? I think it would look awkward on mobile to have everything aligned with the author's name

**Comment by idjevm** [comment]
Yeah I was thinking the same. But Idk @ppagarawal said that everything should be aligned with the name. I think perhaps we should align only the tags aligned with the name, and have the title and description aligned with the avatar.

**Comment by ppagarawal** [comment]
@idjevm @sheeba1 
Please refer to the design for the right mapping for mobile.

image

For desktop, @Yu-Alexa-Zhao Can you please help here, I think that aligning it with avatar will be better as aligning it with the titles leaves a lot of white space.

**Comment by jyclam** [comment]
Comparing with the design @ppagarawal posted above, it seems like my current fixes for mobile is good as is right?

**Comment by ppagarawal** [comment]
> Comparing with the design @ppagarawal posted above, it seems like my current fixes for mobile is good as is right?

Mobile is good @jyclam let's wait for inputs from @Yu-Alexa-Zhao for desktop

**Comment by Yu-Alexa-Zhao** [comment]
Yes I agree that on desktop it can also be left aligned. 
On mobile eventually we will have a "more" icon at the right side (where we used to have tags) so it will look less awkward lol

**Comment by Yu-Alexa-Zhao** [comment]
Frame 64
It will look something like this

**Comment by galeza** [comment]
@idjevm @jyclam 
Can we test it?

**Comment by jyclam** [comment]
@galeza @Yu-Alexa-Zhao @ppagarawal 

I've left aligned Post content for desktop, please take a look: https://featurefix-post-alignment-and-background.fightpandemics.xyz/

**Comment by ppagarawal** [comment]
@jyclam are you sure this is pixel perfect? Does the profile pic, location tag, heading and content, all of them lie on the same line?

**Comment by jyclam** [comment]
@ppagarawal Were you referring to the tags? Fixed now.

**Comment by galeza** [comment]
Hi,

LGTM

Title, text, tags are left aligned.

Tests on mobile:
Screenshot_2020-07-21-10-40-00-934_com android chrome
Screenshot_2020-07-21-10-39-52-094_com android chrome
Screenshot_2020-07-21-10-40-06-484_com android chrome

Tests on desktop:
Screen Shot 2020-07-21 at 10 38 18
Screen Shot 2020-07-21 at 10 37 11
Screen Shot 2020-07-21 at 10 37 26
Screen Shot 2020-07-21 at 10 38 10

**Comment by sheeba1** [comment]
Verified on both moblie and desktop (https://rcv11.fightpandemics.xyz/feed)

**Pull request merged**
