### PR TITLE
Feature/1474

### LINKED ISSUE #1474: Show 404 page for not found profile/organisation
Noted in #1230 - cc @sheeba1 @jpmitri @vsan626 @emtay 

This would be a good first step until we make a decision about the other issue.

Currently if you visit profile/:id or organisation/:id and it is not found you get this ugly error message:
image

Let's instead redirect them to 404 page:
image

### PR DESCRIPTION
**Pull request by vsan626**
### What does this pull request aim to achieve? 💯
re-routes the user to 404 page if user profile does not exist

_Please be concise and link any related issue(s):_

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix. The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

### CODE REVIEW

**Review by idjevm — CHANGES_REQUESTED** [review]
We need to add this for the organisations as well. I will double check once that change is done.

**Comment by vsan626** [comment]
> We need to add this for the organisations as well. I will double check once that change is done.

@idjevm code has been updated for the organisations as well

**Review by joshmorel — CHANGES_REQUESTED** [review]
Thanks @vsan626 

I don't think it was exactly fair to call this a "good first issue" - any time you are dealing with react hooks it's not that case!

Anyways I don't want to re-route I want to show - so we still see the actual URL, e.g.:

image

We can't return the page from `useEffect` but we can set a variable and use that to render it.

E.g.:

```javascript
      } catch (err) {
        if (err?.response?.status === 404) {
          setNotFound(true);
        }
      }
    })();
  }, [setNotFound, pathUserId, userProfileDispatch]);
```

And later

```javascript
  if (notFound) return <NotFoundPage />;
```
 

This will work but we need to use it in many places. There is an Axios interceptor we might be able to use for all 404 errors https://css-tricks.com/stay-dry-using-axios-for-api-requests/? @jpmitri is this what you were referring to in slack about listeners?

But that might be more complicated than it's worth right now.

Currently the most common errors we'll get is:

* 404 - not found
* 500 - server error but this would be because you visited fightpandemics.com/profile/joshs1234 (by accident I guess?) - because it is not a valid Mongoose ObjectId - but I think we'll switch to slugs eventually for more user friendly URLs...

Throwing a 401 on the backend (with `authentication` hook), I don't think that'll work for non logged user when visiting this page as it will cause many headaches - I have a different solution.

**Comment by rabbi08** [comment]
Closing this issue as low priority, please reopen if the priority change

**Pull request closed without merging**
