### PR TITLE
#1737 notification digest emails

### LINKED ISSUE #1737: Daily/Weekly/Biweekly Digest Email Notifications
Notes are based on the discussion we had in the 10/31 meeting with the Notifications team.

@CamilaArias @nfranklin9 Please edit/correct or add to my notes, and also add any sample templates/copy for the emails.

* Send digest email notifications for daily, weekly, and biweekly frequencies, which will contain an aggregation of all notifications received by the recipient over that time period (both read and unread)
* Group notifications by post, and show latest notification for each, along with counts of other notifications for post
* Show top three posts by number of notifications

### PR DESCRIPTION
**Pull request by mannykary**
### What does this pull request aim to achieve? 💯

Adding daily/weekly/biweekly notification digest emails

Resolves #1737 

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [ ] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
NOTE: rebased with latest in `feature/notifications`
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Review by ddveloper — APPROVED** [review]
I am not familiar with the Terraform part and new to the aggregation (learn a lot from the code), I went through the logic, and they all LGTM.

**Review by Zaydme — APPROVED** [review]

**Comment by Zaydme** [comment]
LGTM

**Comment by shrutigupta1981** [comment]
Email notifications only fired when liker liked the author post. It didnt fire when commenter commented or shared the author post.

**Comment by shrutigupta1981** [comment]
The Author is  still not able to scroll through Notifications on web
image

**Comment by shrutigupta1981** [comment]
Khushi Gupta(testindividual12@gmail.com) trying to send message to Harshika Gupta (testindividual11@gmail.com) thats not successful 
image
but vice versa working 
image

**Pull request merged**
