### PR TITLE
#2162 - localization add two new languages (Greek, Hungarian)

### LINKED ISSUE #2162: Localisation: Add 2 New Languages [Greek, Hungarian]
Please add the languages listed below to our platform. The instructions to do so are:
- Edit `client/src/locales/index.js` and `client/src/locales/languages.js` . You will need to import the correct file in `index.js` and also add the language and ISO code to the `localization` and `MENU_MAP` objects.
- Assign the unique ID (listed in the table below) to the new language for GTM (Google Tag Manager) tracking purposes. The ID should be prefixed with `NAV_LS_` followed by the ISO code used in previous step. (Reference [this ticket](https://github.com/FightPandemics/FightPandemics/issues/1611) to see how it has been done previously)

### New 2 languages to be added:
| Language           | ISO code | GTM ID suffix |
|--------------------|----------|------|
| Greek | el | _EL |
| Hungarian | hu_HU | _HU_HU |

EDIT: Will be adding Croatian as well (_HR). Please refer to PR for more info.

### PR DESCRIPTION
**Pull request by emanuelquerty**
### What does this pull request aim to achieve? 💯

This PR resolves #2162 

_Please be concise and link any related issue(s):_

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Comment by aditilamkhede** [comment]
@emanuelquerty you probably need to import json files for Greek and Hungarian. @doheekim93 can help you with that. And then test the change. Write now when I change language, there is difference between english and Greek or Hungarian. So would suggest test with translated json.

**Review by aditilamkhede — CHANGES_REQUESTED** [review]
@emanuelquerty you probably need to import json files for Greek and Hungarian. @doheekim93 can help you with that. And then test the change. Right now when I change language, there is no difference between english and Greek or Hungarian. So would suggest test with translated json. I see that both json files have text in english script.

**Comment by emanuelquerty** [comment]
Hi @aditilamkhede! Yes, the behavior you noticed was expected because I didn't have the translation, so I just added the content from the English file into the files for Greek and Hungarian. I didn't know who to ask for the files. Thanks for letting me know who to ask for. @doheekim93 can you please help me with getting the files for Greek and Hungarian?

**Comment by doheekim93** [comment]
Hey @emanuelquerty and @aditilamkhede, there is already an open PR that we're waiting to get merged with those 2 languages: #2161. I'll let you know once that one has been merged!

**Review by ddveloper — DISMISSED** [review]
LGTM, thanks @emanuelquerty

**Comment by doheekim93** [comment]
@emanuelquerty It seems like the font is inconsistent for Greek (I see different fonts on `About Us` and `Help Board`)

Example from `About Us`:
Screen Shot 2021-01-25 at 11 13 44 AM

We had a similar problem in the past because we didn't have all the correct weights of the font downloaded. Please refer to this [PR](https://github.com/FightPandemics/FightPandemics/pull/1868) to see if we can solve the issue in a similar way, thanks!

**Review by rabbi08 — COMMENTED** [review]
Thanks @emanuelquerty @doheekim93 
The languages looks good in menu and are working fine.

I have only below observation not critical but needs to be addressed:

we have UI issue with 'greek' translation, do we want to fix this in this PR or need another issue. I would like to recommend that if we can have the translator test this site after translation. we can merge this PR and have another ticket for such UI issues related to translation.

image

**Comment by doheekim93** [comment]
Hey @rabbi08, we have that issue with several other languages (I think there was a thread on Slack somewhere about this). I think we should tackle it with a different ticket given that it's an issue affecting multiple languages.

**Comment by rabbi08** [comment]
> Hey @rabbi08, we have that issue with several other languages (I think there was a thread on Slack somewhere about this). I think we should tackle it with a different ticket given that it's an issue affecting multiple languages.

Agree @doheekim93 
Thanks.

**Comment by emanuelquerty** [comment]
Thanks @doheekim93 for letting me know about the merged PR. I will review the [PR](https://github.com/FightPandemics/FightPandemics/pull/1868l) and try to fix the inconsistencies in font weight

**Review by aditilamkhede — COMMENTED** [review]
@LGTM, just to inform that I still see some text in English at the end of el.json i.e. for Greek. I believe that's still pending in lokalise.

**Comment by doheekim93** [comment]
@aditilamkhede We actually don't have 100% for a lot of the languages because by the time all languages are translated, we have more keys added on the engineering side. So, we have been adding languages when they are _close_ to 100%. That being said, we will be updating the translations for all existing languages on the platform for this week's PROD release.

**Comment by doheekim93** [comment]
As discussed with @ddveloper and @rabbi08 , we will add Croatian to this PR as well! We will also need to add the .json file from #2179 to this PR.

### New language to be added:
| Language           | ISO code | GTM ID suffix |
|--------------------|----------|------|
| Croatian | hr | _HR |

**Pull request merged**
