### PR TITLE
#1987/#2017 - always use commentsCount inside post object

### LINKED ISSUE #1987: [Mobile Android] Post Comments counter
env- staging
Steps:
1. Open Help Board
2. Navigate to the Post with Comments
3. Click on a post
4. Number of comments displayed on Help Board on my example is 14, when you click on this post - post is displayed - number of comments displayed is 0 and after a second it displays correct number. Why do we have this latency? I don't see the same behaviour for Like counter. 
Expected behaviour - Correct number is displayed without switching from 0 to correct number.

Nov-30-2020 12-34-40

### LINKED ISSUE #2017: There is a mismatch in number of comments in actual post to the shared post.
Environment-staging 
Device used-Samsung Galaxy s8
Browser-Google chrome 
1.login with valid user name and password 
2.share your post to watsapp / email.
3.log out from the account.
4.click on the link from the watsapp/email.
Result:
There is a mismatch in number of comments from the actual post to the shared post. 
Always shared post comments shows as 0 irrespective of any number of comments the post has.

### PR DESCRIPTION
**Pull request by Zaydme**
### What does this pull request aim to achieve? 💯
Fix the comment count display delay, and 0 comments when user is not logged in.
Always use `commentsCount` within the `post` object for all posts fetching endpoints

_Please be concise and link any related issue(s):_
closes #1987
closes #2017

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Review by ddveloper — APPROVED** [review]
LGTM

**Comment by nivetheatha** [comment]
1.Number of comments of the post shown correctly when we see from shared link.
2.post with comments loads correctly.
Both Works as expected .Looks good to me.

**Review by rabbi08 — APPROVED** [review]
- The comments load with the post : PASS
refer below GIF captured the issue with STG and the feature build with fix.

ezgif com-video-to-gif 9

- The post shared via WhatsApp/email contains the right number of comments/like
refer below Screenshot
IMG_6562D26ED8DD-1

**Comment by galeza** [comment]
@Zaydme 
Tested using postman. commentsCount is a part of Post dict:
```
   "post": {
        "isEdited": false,
        "language": [],
        "likes": [],
        "status": "flagged",
        "types": [
            "Medical Supplies"
        ],
        "_id": "5fc78c10ace74d0011f8f558",
        "title": "Test post moderation",
        "content": "test",
        "visibility": "worldwide",
        "expireAt": "2021-01-02T12:44:00.735Z",
        "objective": "offer",
        "author": {
            "id": "5fc18b22edcb021600e40b18",
            "location": {
                "city": "Rockville",
                "state": "MD",
                "country": "US"
            },
            "name": "Roy Zhang",
            "type": "Individual"
        },
        "createdAt": "2020-12-02T12:44:00.737Z",
        "updatedAt": "2020-12-02T12:44:50.296Z",
        "__v": 0,
        "liked": false,
        "likesCount": 0,
        "elapsedTimeText": {
            "created": {
                "count": 3,
                "unit": "day"
            },
            "isEdited": false
        },
        "reportsCount": 1,
        "commentsCount": 0
    }
```
Thank you

**Review by galeza — APPROVED** [review]

**Pull request merged**
