### PR TITLE
#2262 - Feature/fix Edit and Likes Update

### LINKED ISSUE #2262: Integrate PostTabCard mobile view in Profile Page
Integrate <PostTabCard> mobile view in Profile Page

### PR DESCRIPTION
**Pull request by linadinh2602**
### What does this pull request aim to achieve? 💯
Fixing Edit and Likes Update by adding update reducer
_Please be concise and link any related issue(s):#2262

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`** for a regular feature, **`hotfix/<branch_name>`** for a hotfix, and **`service/<branch_name>`** for a microservice, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Comment by aditilamkhede** [comment]
> Build URL: https://featurefixeditsave.fightpandemics.xyz. Please wait a few minutes for the deployment to complete.

Hi @linadinh2602 here are my Initial Observations 

1. When I go and edit post -> It edit's the content and displays them but Time stamp is not coming through:
Screen Shot 2021-03-18 at 9 02 57 AM
2. After editing the post, click on like doesn't work.
3. After Editing the post, comments also don't work.
4. Also on Help board when you like/unlike a post, it changes the count but image is not changed.

**Review by rabbi08 — CHANGES_REQUESTED** [review]
thanks @linadinh2602 

Please see below observation:
1. The user is able to click on 'Like' button only once, either LIKE or UNLIKE. After that user need to refresh the page,, to initialize the like option. The like feature is having issues on helpboard and user profile pages now. This issues is not existing in STG. 
I have added the GIF below from both STG and feature branches for comparison and for the repo steps.
ezgif com-video-to-gif-7

2. The user is not able to navigate to post details page from user profile page after clicking on the 'post'.

Please see below GIF as compare to STG env behavior:
ezgif com-video-to-gif-6

**Comment by sarahjliu** [comment]
Minor design request: it would be great if there was more bottom padding added to the see all button in the card so the spacing above and below the “See all” text matches. And I assume the reason why the newest test link hasn’t been deployed is because of the merge conflict.

**Comment by rabbi08** [comment]
@linadinh2602 

I have below observation:
- The 'Active' and 'Archived' post are same, or we can the 'Archived' post are not displayed and 'active' post are displayed under 'Archived' category. Please see below screen recording.

https://user-images.githubusercontent.com/67168400/111941909-87a7ec00-8aa8-11eb-84f2-fc3032352955.mov

**Review by rabbi08 — CHANGES_REQUESTED** [review]
Thanks @linadinh2602

**Comment by aditilamkhede** [comment]
@linadinh2602 here are my observations:

1. Add comment in desktop view, It doesn't reflect it in desktop view.
2. Create new post, time stamp is not updated. It will require refetching the post I guess, as currently we are displaying the cached version.
3. Mobile view click on a post, it navigates to post page but clicking on back button takes it to help board page, it should take it back to profile page.

**Comment by rabbi08** [comment]
the issue reported for 'Active ands Archive' is not fixed yet. Thanks.

**Comment by aditilamkhede** [comment]
> the issue reported for 'Active ands Archive' is not fixed yet. Thanks.

@rabbi08 please test the issues. I have fixed Active/Archived issue and @linadinh2602 has fixed others.

**Review by rabbi08 — APPROVED** [review]
Thanks @aditilamkhede @linadinh2602 

The issues reported looks fine, lets merge it into main branch. Thanks

**Pull request merged**
