### PR TITLE
feature/2135 increasing text contrast

### LINKED ISSUE #2135: [Desktop][STG][Front End][bug] Informational text under “Medical Help”, and “Other Help” label has low color contrast.
Environment:
macOS 10.14 Mojave
MacBook Pro (15-inch, Early 2015)
Browser: Firefox 78.6.1esr 
https://staging.fightpandemics.work/

Steps:
1. Navigate to https://staging.fightpandemics.work/
2. Login to FP
3. Click on profile initial icon on top left corner of page. and click “view your profile” option
4. Click on the pencil (edit) located on the left corner 
5. On the next page click on “Edit Account” option located on right side of page
6. Use [TAB] key to to navigate Edit Account page
7. Observe low color contrast on text-leaf  label (div) below the “Medical Help”, and “Other Help”

Expected Behavior: 
Informational text should be visible to every type of user (accessibility violation - color contrast ratio should be greater then 4.5<. (accessibility violation)

Actual Behavior:
 Informational text under “Medical Help”, and “Other Help” (div) label has low color contrast.  Actual ratio 3.07 Expected ratio 4.501< .

color-contrast FP

### PR DESCRIPTION
**Pull request by haoxianZ**
### What does this pull request aim to achieve? 💯

_Please be concise and link any related issue(s):_
#2135 

- [X ] I have checked that no one else is working on similar changes.
- [X ] I have read the latest [**README**](README.md) and understand the development workflow.
- [ X] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [X ] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [X ] There are no merge conflicts.
- [X ] There are no console warnings and errors.
- [X ] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [X ] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Comment by haoxianZ** [comment]
@ddveloper Thank you! Yah I should clone instead of fork, so I closed the previous pull and created this one. So on the Readme it said either clone or fork for local setup, should we change that to just clone but not fork? at least for frontend development I guess?

**Comment by ddveloper** [comment]
> @ddveloper Thank you! Yah I should clone instead of fork, so I closed the previous pull and created this one. So on the Readme it said either clone or fork for local setup, should we change that to just clone but not fork? at least for frontend development I guess?

right @haoxianZ we should update that Readme I believe, thanks for pointing this out 👍

**Review by galeza — APPROVED** [review]
LGTM
Colour is ok. I tested on Android and MacOs Chrome browser.
Screenshot_2021-01-15-14-32-03-148_com android chrome_2
i don't know if we can change font size and make it bigger?

**Review by nadinejuraschek — APPROVED** [review]
lgtm!

**Review by ddveloper — APPROVED** [review]
LGTM

**Comment by ghost** [comment]
Initial problem fixed, **but Informational text under “Address” field (div)  has low color contrast of 1.44.** 

Environment:
7 32 52 PM 2021-01-22 contrast

macOS 10.14 Mojave
MacBook Pro (15-inch, Early 2015)
Browser: Firefox 78.6.1esr 
https://feature2135.fightpandemics.xyz

Steps:
1. Navigate to https://feature2135.fightpandemics.xyz
2. Login to FP
3. Click on profile initial icon on top left corner of page. and click “view your profile” option
4. Click on the pencil (edit) located on the left corner 
5. On the next page click on “Edit Account” option located on right side of page
6. Use [TAB] key to to navigate Edit Account page
7. Observe low color contrast on text-leaf  label (div) below the “Address”

Expected Behavior: 
Informational text should be visible to every type of user (accessibility violation - color contrast ratio should be greater then 4.5<. (accessibility violation).

Actual Behavior: Informational text under “Address” (div) field has low light grey color contrast.  Actual ratio 1.44 Expected ratio 4.51< (initial bug fixed -“ Medical Help, OtherHelp” informational text is fixed).

**Comment by rabbi08** [comment]
Thanks @Rebeccabeesknees @haoxianZ @ddveloper 

As the initial reported issue is fixed and working fine. we can merge this and log new issue for the additional observation. thanks.

**Comment by haoxianZ** [comment]
hmm, I actually cant merge since the commit was not signed.

**Pull request merged**
