### PR TITLE
Scroll Bar added to language menu

### LINKED ISSUE #2099: Localisation: Language select menu scroll needs implementing
As reported by @rabbi08:

> As the language list is getting long in the dropdown, it scrolls the whole page, can we add scroll in the language menu dropdown, to scroll languages rather than page scrolling as in below GIF.
> ezgif com-video-to-gif-2

### PR DESCRIPTION
**Pull request by aditilamkhede**
### What does this pull request aim to achieve? 💯
Scroll Bar added to language menu and components/Header/LanguageMenu.js removed as it was not being used anywhere(Confirmed with Dawei).

_Please be concise and link any related issue(s):_This PR resolves #2099 

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Comment by rabbi08** [comment]
@aditilamkhede 
The fix looks good, the scroll bar is working fine: PASS
Thanks.

I have additional observation with the usability of the scroll bar, i.e. when user open the language menu and try to scroll -> initially the page is scrolled not the menu list. Please refer below GIF

ezgif com-video-to-gif-5

can we change like we have the scroll in switch profile menu i.e. the user's control and focus should be in the language menu bar while scrolling. Please see below the profile menu scroll bar GIF:

ezgif com-video-to-gif-6

**Comment by aditilamkhede** [comment]
> @aditilamkhede
> The fix looks good, the scroll bar is working fine: PASS
> Thanks.
> 
> I have additional observation with the usability of the scroll bar, i.e. when user open the language menu and try to scroll -> initially the page is scrolled not the menu list. Please refer below GIF
> 
> ezgif com-video-to-gif-5
> 
> can we change like we have the scroll in switch profile menu i.e. the user's control and focus should be in the language menu bar while scrolling. Please see below the profile menu scroll bar GIF:
> 
> ezgif com-video-to-gif-6

@rabbi08 did you use the arrow keys to scroll instead of mouse? Just trying to understand the issue. For me if I am using mouse to scroll and I am on language menu(not clicked anywhere) it always scrolls menu but if I use arrow keys and even though I am on language menu it scrolls page not the menu.

**Comment by rabbi08** [comment]
> > @aditilamkhede
> > The fix looks good, the scroll bar is working fine: PASS
> > Thanks.
> > I have additional observation with the usability of the scroll bar, i.e. when user open the language menu and try to scroll -> initially the page is scrolled not the menu list. Please refer below GIF
> > ezgif com-video-to-gif-5
> > can we change like we have the scroll in switch profile menu i.e. the user's control and focus should be in the language menu bar while scrolling. Please see below the profile menu scroll bar GIF:
> > ezgif com-video-to-gif-6
> 
> @rabbi08 did you use the arrow keys to scroll instead of mouse? Just trying to understand the issue. For me if I am using mouse to scroll and I am on language menu(not clicked anywhere) it always scrolls menu but if I use arrow keys and even though I am on language menu it scrolls page not the menu.

@aditilamkhede 
No I didn't use arrow keys, I used mouse cursor placement with touchpad on MacBook.

Thanks

**Comment by aditilamkhede** [comment]
@rabbi08 issue will be ready for review by morning. I had to change few things as it was conflicting with my original fix, I decided to change my approach.

**Comment by aditilamkhede** [comment]
@rabbi08 it's ready for review.  @ddveloper Thanks for your help.
@rabbi08 also if you check carefully the profile menu border on right side is not actually rounded. It should be same for account menu.

**Review by doheekim93 — DISMISSED** [review]
Looks good to me (based on the build URL)!! Thanks @aditilamkhede!

**Review by rabbi08 — DISMISSED** [review]
Verified the fix on the feature branch, as working fine: PASS
Thanks

Refer below screen recording.

https://user-images.githubusercontent.com/67168400/103814819-5afb4100-5030-11eb-86f3-4e782f319230.mov

**Comment by aditilamkhede** [comment]
@Zaydme and @ddveloper I am going to change this a bit. Please wait. There is a shadow appearing, so just style change.
@rabbi08 do you think we should change this as well - " also if you check carefully the profile menu border on right side is not actually rounded. It should be same for account menu".

**Comment by aditilamkhede** [comment]
@rabbi08 @doheekim93 @ddveloper @Zaydme @BMariscal it's ready for review. Thanks for your patience.

**Review by ddveloper — DISMISSED** [review]
LGTM, maybe can remove the comment

**Review by Zaydme — CHANGES_REQUESTED** [review]
I see many unnecessary comments, other than that, it LGTM.

**Comment by aditilamkhede** [comment]
@ddveloper and @Zaydme removed comments.

Profile Menu border corners (left/yellow ones are rounded and right ones are not), should I fix this and deploy in this PR.

Screen Shot 2021-01-07 at 11 40 22 AM

**Review by ddveloper — APPROVED** [review]

**Review by rabbi08 — APPROVED** [review]
looking good, lets merge. Thanks

**Pull request merged**
