### PR TITLE
Feature/#1390

### LINKED ISSUE #1390: Show text that message that IE11 is not support
See issue #1304 for discussion. Due to current usage of libraries without polyfills, use of modern style rules & mechanism for secure persistent login we do not support IE11.

It would be a significant effort to implement and maintain such browser support so a decision to do so would require prioritization against other desired features.

We should display a message - "To ensure a secure and pleasant experience this app requires a modern browser. Please come back with the latest version of Edge, Chrome, or Firefox." We should probably include links that will take them to the right page (by language) in case the visitor does not speak English.

### PR DESCRIPTION
**Pull request by ashminbhandari**
### What does this pull request aim to achieve? 💯

FightPandemics does not support IE 11 and older IE browsers. This pull request displays an appropriate message to notify the user as well as guide them toward updated browser downloads for IE 11 and older IE browsers. This PR resolves #1390 

_Please be concise and link any related issue(s):_

- [✅] I have checked that no one else is working on similar changes.
- [✅] I have read the latest [**README**](README.md) and understand the development workflow.
- [✅] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix. The branch is created in a cloned version of this repo, **not a forked repo**.
- [✅] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [✅] There are no merge conflicts.
- [✅] There are no console warnings and errors.
- [✅] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

### CODE REVIEW

**Review by nadinejuraschek — APPROVED** [review]
lgtm. Thank you :)

**Review by joshmorel — APPROVED** [review]
This looks great. Not sure why review environment wasn't working but this should be fine.

**Comment by rabbi08** [comment]
Tested in STG, and it works fine for IE11. Please see screenshot below, 
thanks.

image

**Comment by manualzuru** [comment]
@ashminbhandari low priority but maybe also add the Brave browser logo which uses chromium.

**Pull request merged**
