### PR TITLE
fix: keep scroll level

### LINKED ISSUE #1827: Navigating to any post -> Back on Help board: The users lands on the TOP of the Help board page rather than on the same post  from where user start.
1. Open 'https://staging.fightpandemics.work/'
2. Navigate to Help Board -> add filter as 'provider ='Individual'
3. Scroll down and select/click any post to view/add comment to it -> Add comment -> Click 'Back' button

Issue: You will observe that user lands on the top of the Help Board page, ideally it should land on the same post/position after viewing the post. 
Refer below GIF.

ezgif com-gif-maker (55)

Note: Tested both on desktop and mobile. This issue is related to #1709 
Also, Please note that filters are retained on the help board page after user navigate to other page and come BACK.

### PR DESCRIPTION
**Pull request by OzkanAbdullahoglu**
* Now scroll level is in the router state even on comment click
Resolves #1827 
### What does this pull request aim to achieve? 💯

_Please be concise and link any related issue(s):_

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Comment by OzkanAbdullahoglu** [comment]
@joshmorel , @Zaydme , @rabbi08 ,

can I have your comments & approvements? so we can close this PR. 😀

**Comment by Zaydme** [comment]
One final thing before merging this, Can we add a condition in the loadPosts function here.
```js
try {
      const {
        data: { data: posts, meta },
      } = await axios.get(endpoint);
...
```
 to not fetch posts at all if postsInState exsists, so this one unnecessary request is not made.
image

**Comment by rabbi08** [comment]
@OzkanAbdullahoglu @Zaydme 
Can I build URL or should I need to test on #1709?

**Comment by Zaydme** [comment]
There is no build URL, but I tested locally and it works as expected. Even when you go to post page by clicking on comment.

**Comment by rabbi08** [comment]
Oh then I can't test that... I don't have laptop to test on local as of now.

**Comment by OzkanAbdullahoglu** [comment]
> One final thing before merging this, Can we add a condition in the loadPosts function here.
> 
> ```js
> try {
>       const {
>         data: { data: posts, meta },
>       } = await axios.get(endpoint);
> ...
> ```
> 
> to not fetch posts at all if postsInState exsists, so this one unnecessary request is not made.
> image

Good point, I am looking  into this.

**Comment by OzkanAbdullahoglu** [comment]
@Zaydme as we discussed I will open a different PR to prevent initial fetch in case we have postsInState. I just did a small logical revision. 
@rabbi08 will you able to perform a test for this PR?

**Comment by rabbi08** [comment]
> @Zaydme as we discussed I will open a different PR to prevent initial fetch in case we have postsInState. I just did a small logical revision.
> @rabbi08 will you able to perform a test for this PR?

@OzkanAbdullahoglu 
Yes plz, I can. Kindly share build URL.

**Comment by Zaydme** [comment]
@rabbi08 can you test locally? This doesn't have a build URL.
Because the branch name is missing "feature/"

**Comment by rabbi08** [comment]
> @rabbi08 can you test locally? This doesn't have a build URL.

I need time for that :)

**Comment by rabbi08** [comment]
> > @rabbi08 can you test locally? This doesn't have a build URL.
> 
> I need time for that :)

That's fine. ok , let me try on local.

**Comment by rabbi08** [comment]
@OzkanAbdullahoglu @Zaydme 
I have limited time on desktop and I messed with my docker, its not working. So, please go ahead and merge into STG. we can verify there. Thanks.

**Pull request merged**
