### PR TITLE
email address correction

### LINKED ISSUE #2050: The email address for "legal@fightpandemics.com" is not valid on T&C page
1. Open FP web app
2. Open 'Terms & Conditions' Page
3. Scroll down on the page, look for 'legal@fightpandemics.com'

Issue: You will observe that all the emails on this page are having invalid email address i.e. legal@fightpandemics[.com is missing from email address] so if user send email on these address, they will get failure notice.

Only email address for legal is valid on this page, all others need to be updated with '.com'

### PR DESCRIPTION
**Pull request by aditilamkhede**
### What does this pull request aim to achieve? 💯
Correct email address on T&C Page.

_Please be concise and link any related issue(s):_ This PR resolves #2050 

- [ ] I have checked that no one else is working on similar changes.
- [ ] I have read the latest [**README**](README.md) and understand the development workflow.
- [ ] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [ ] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [ ] There are no merge conflicts.
- [ ] There are no console warnings and errors.
- [ ] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [ ] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Review by CamilaArias — APPROVED** [review]
LGTM

**Comment by aditilamkhede** [comment]
@ddveloper why did checks failed?

**Comment by ddveloper** [comment]
> @ddveloper why did checks failed?

The log says wrong arguments, it might be the `#` in your branch name
```
invalid argument "fightpandemics/client:feature/#2050-emailCorrectionOnT" for "-t, --tag" flag: invalid reference format
```

**Review by Zaydme — APPROVED** [review]
LGTM!
And as @ddveloper said, the check failed because fo the `#` (since it maybe made everything after it counts as a comment)

**Pull request merged**
