### PR TITLE
#2235 - Join Org US-1.1: "Join Us" CTA on Org profile page 

### LINKED ISSUE #2235: User Story 1.1 - Join CTA, Positions page
Backend dependency: Members tab data & user types

Join Us button and Positions Page [User Story 1.1](https://www.notion.so/fightpandemics/Join-an-Organization-including-in-built-form-00454eb8c6b24b4eb9eeeeff80bea057#712bc6db416e4734b7c96cbb2c840e2a)

Brief Summary of this User Story
1. ‘Join {orgName}’ CTA button  on org profile page.
2. If user is not signed in and click/tap the CTA 'Join Us' button --> display the sign in screen. Once they do sign in they must be taken back back to the Org profile/screen
3. Signed user clicks on Join Us" - > display ‘Positions’ page. Clicking on back arrow of this page should take user back to Org profile page.
4. Also included to be later --> visibility of "Join Us" button is based on user role.

### PR DESCRIPTION
**Pull request by xJamesScott**
### What does this pull request aim to achieve? 💯

_Please be concise and link any related issue(s):_

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`** for a regular feature, **`hotfix/<branch_name>`** for a hotfix, and **`service/<branch_name>`** for a microservice, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Comment by AndersonNY** [comment]
Currently, the ‘Join Org’ CTA is also visible to the org owner on his profile, which is incorrect behavior. It should only be viewable to the user who is not a member. 

Screen Shot 2021-03-23 at 5 16 37 PM
Screen Shot 2021-03-23 at 5 14 35 PM

**Comment by xJamesScott** [comment]
> Currently, the ‘Join Org’ CTA is also visible to the org owner on his profile, which is incorrect behavior. It should only be viewable to the user who is not a member.
> 
> Screen Shot 2021-03-23 at 5 16 37 PM
> 
> Screen Shot 2021-03-23 at 5 14 35 PM

I pushed a fix for that, it should be live now. Let me know if you have any issues

**Comment by AndersonNY** [comment]
Distance between Activity and Members tab doesn't look correct per zeplin requirement. I did measurement manually! Can you check the distance one more time please?  [Screen Shot 2021-03-25 at 12 27 06 AM](https://user-images.githubusercontent.com/56901619/112418959-e10a5800-8d00-11eb-967a-1dce70e1ee48.png)

**Review by AndersonNY — COMMENTED** [review]
the ‘Join Org’ CTA is visible to the user who is not a member which as expected. It's working as expected. 



Screen Shot 2021-03-26 at 11 26 17 PM
Screen Shot 2021-03-26 at 11 25 44 PM

**Pull request merged**
