### PR TITLE
Fixed the Linkedin url validation in edit Organisation Profile #Feature/1712

### LINKED ISSUE #1712: LinkedIn URL in Edit Organization Profile should have validation for '/' like the rest of other media types
https://staging.fightpandemics.work/
Chrome - Window 10
Login as Individual
Click on Profile =>Edit pen =>Edit Profile

provide all the values for these below and see all except LinkedIn URL give the error validation message when entering /
Facebook URL
Instagram URL
LinkedIn URL
Twitter URL
Github URL

Without providing the error message for LinkedIn URL when entering the / at the end, click on the Save Changes button, we have this message on the top
Failed updating profile, reason: error.http.body.urls.linkedin should be null, body.urls.linkedin should match pattern "^[a-zA-Z0-9-]*$", body.urls.linkedin should match some schema in anyOf

Screenshot (132)

Related  to issue #1682

### PR DESCRIPTION
**Pull request by sujatha-m**
### What does this pull request aim to achieve? 💯

_Please be concise and link any related issue(s):_This is PR resolves #1712 

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Review by Zaydme — APPROVED** [review]
LGTM, thank you @sujatha-m

**Comment by rabbi08** [comment]
@Zaydme @sujatha-m 
We don't have latest code base for this fix in this. Can this re-introduce already fixed issues?

Thanks

**Comment by Zaydme** [comment]
@rabbi08 no, since there is no merge conflicts.

**Review by rabbi08 — CHANGES_REQUESTED** [review]
@sujatha-m @Zaydme 
1. The issue for Individual profile fixed in PR#1683, exist in this build, see below screenshot.
image

2. The issue for Organization profile still exist, see below screenshot, error message is displayed after user clicks on 'Save button'
image

Thanks

**Comment by Zaydme** [comment]
@rabbi08 if an issue was fixed in staging, it will not be reintroduced after merging this, even if it exists here. Because not all the files are going to be merged, but only the files chnaged by this PR, you can go to the file changes page and you can see that this PR only changes two lines, these are the only changes that will be merged into staging, and not any other files, so the old code here will no be going back to staging.

**Comment by rabbi08** [comment]
> by this PR, you can go to the file changes page and you can see that this PR only changes two lines, these are the only changes that will be merged into staging, and not any other files, so the old code here will no be going back to staging.

Agree @Zaydme but the exact issue reported for Org profile still exist.

**Comment by rabbi08** [comment]
Please see this comment for this issue:
https://github.com/FightPandemics/FightPandemics/pull/1683#issuecomment-716178402

**Comment by Zaydme** [comment]
@rabbi08 yeah this current fix will only validate that the link doesn't have "/". But it doesn't change when the validation runs, I see that now it runs after clicking "Save changes".
Because I think that's what not included in the ticket #1712.

image

**Comment by rabbi08** [comment]
> @rabbi08 yeah this current fix will only validate that the link doesn't have "/". But it doesn't change when the validation runs, I see that now it runs after clicking "Save changes".
> Because I think that's what not included in the ticket #1712.
> 
> image

Yes, that's what need to fix too to keep it in sync with the same behavior as Individual profile.

**Review by rabbi08 — APPROVED** [review]
Verified the fix on the feature build, the error is displayed when user enter '/' invalid character rather than clicking on the button.
Added '/company/' for Org in Linkedin URL. 

Thanks.

Refer below GIF
ezgif com-gif-maker (53)

**Pull request merged**
