### PR TITLE
fix fonts for Vietnamese, (and other languages)

### LINKED ISSUE #1853: Font for Polish language - About Us page
Please correct fonts for Polish language like in this PR: #1603 - Add medium and bold Poppins font #1669
It was done for Help Board. Could we implement it also for About Us Page? 

Screen Shot 2020-11-18 at 14 10 34

Home Page:
Screen Shot 2020-11-18 at 14 11 53

### PR DESCRIPTION
**Pull request by Zaydme**
### What does this pull request aim to achieve? 💯
Fixes fonts for Vietnamese and others
example:
image
To: 
image
and this
image
into this
image
_Please be concise and link any related issue(s):_
closes #1853 (again)

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Comment by adorapham** [comment]
@Zaydme it seems the area for View Help Board to click to big. would you please recheck

image
FixedFont_1
also confirm new fonts are 
image

@Zaydme , can you please check on about us to see Vietnamese language font is correct
image

**Comment by CamilaArias** [comment]
LGTM @Zaydme bonus points for fixing the click area

**Review by CamilaArias — APPROVED** [review]

**Comment by Zaydme** [comment]
The click area was fixed with #1956

**Review by adorapham — APPROVED** [review]

**Comment by adorapham** [comment]
> The click area was fixed with #1956

@Zaydme , i check on staging and it works. TY

**Pull request merged**
