### PR TITLE
Production Release as on 03-24-2021 

### PR DESCRIPTION
**Pull request by rabbi08**
### What does this pull request aim to achieve? 💯

_Please be concise and link any related issue(s):_

- [ ] I have checked that no one else is working on similar changes.
- [ ] I have read the latest [**README**](README.md) and understand the development workflow.
- [ ] The name of this branch is: **`feature/<branch_name>`** for a regular feature, **`hotfix/<branch_name>`** for a hotfix, and **`service/<branch_name>`** for a microservice, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [ ] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [ ] There are no merge conflicts.
- [ ] There are no console warnings and errors.
- [ ] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [ ] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Review by Jameel139 — APPROVED** [review]
Looks good

**Comment by adorapham** [comment]
Front end automation regression - LGTM including feature/tests-for-health-aid and Added test to helpboard filter panel (#2239)
image
back-end - LGTM
image

**Review by SinghRomika — APPROVED** [review]
LGTM

**Review by jessica-lau — APPROVED** [review]
Ran cypress tests. LGTM

image

**Review by jessica-lau — APPROVED** [review]
LGTM

**Comment by rabbi08** [comment]
#2287 and #2300 are the open issues with high priority. so we should fix these issues for next release. But as they are not blockers, we are going to merge this PR into production. Thanks.

**Review by aditilamkhede — APPROVED** [review]

**Pull request merged**
