### PR TITLE
Fixed FAQ page in Kannada language (which displayed blank page) - Issue #2073

### PR DESCRIPTION
**Pull request by Juan-Moctezuma**
…g of the sentence or text

### What does this pull request aim to achieve? 💯
To close or conclude ticket #2073 
Details: Fixed typo on line 520 on kn_IN.json fixed </0> to <0>at the beginning of the sentence or text. Typo on text was causing the FAQ page to be blank. FAQ Page should no longer be blank when selecting Kannada language. See image below.
Screen Shot 2020-12-15 at 7 58 51 PM

_Please be concise and link any related issue(s):_

- [ x] I have checked that no one else is working on similar changes.
- [ ] I have read the latest [**README**](README.md) and understand the development workflow.
- [ x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [ x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [ x] There are no merge conflicts.
- [ x] There are no console warnings and errors.
- [ ] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [ ] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Review by Zaydme — APPROVED** [review]
LGTM!
Thank you @Juan-Moctezuma!
I think translators need to be more careful with these in the future, it's really dangerous and can break production since we don't test all pages with all languages when we pull in new translations.

cc @Jameel139 @doheekim93

**Comment by Jameel139** [comment]
What was the issue?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by doheekim93** [comment]
@Jameel139, it was supposed to be `<0>text</0>`, but they had `</0>text</0>`. 
Thanks @Juan-Moctezuma for finding the typo!!

**Comment by Jameel139** [comment]
Eagle eye @Juan-Moctezuma

**Review by adorapham — CHANGES_REQUESTED** [review]
please change ಅದಕ್ಕಾಗಿ ನಾವು ವಿಷಾದಿಸುತ್ತೇವೆ. help@fightpandemics.com  to ಅದಕ್ಕಾಗಿ ನಾವು ವಿಷಾದಿಸುತ್ತೇವೆ. support@fightpandemics.com as other languages- see #2055
image

**Comment by doheekim93** [comment]
@adorapham I believe we must change text directly on Lokalise. If we change on the .json file, the changes won't be reflected on Lokalise (only exception is English US) and it will overwrite the "support@fightpandemics.com" next time we update the languages (because I still see `help@fightpandemics.com` on Lokalise). I will change `help` to `support` on Lokalise and trigger a PR for all the existing languages.

**Comment by Jameel139** [comment]
Seems that support and help are used interchangeably - I see both on the FAQ keys on lokalise. Is this the intention?
image
image

**Comment by doheekim93** [comment]
@Jameel139 The first key is for "Contects" which is a wrong key (we have the correct "Contact" key as well) that we deleted, but seems to keep coming back...

**Comment by doheekim93** [comment]
@adorapham @Jameel139 I just changed all `help@fightpandemics.com` to `support@fightpandemics.com` on Lokalise, including the incorrect key "Contects". Will trigger new PR to update all languages!

**Comment by adorapham** [comment]
just FYI @doheekim93 so far the change is applied for all languages except Kannada language in Json file -cc @mathigayathri2001
https://github.com/FightPandemics/FightPandemics/pull/2072/files

**Comment by doheekim93** [comment]
@adorapham I did a PR trigger last night to update all the existing languages (which hasn't been merged yet): https://github.com/FightPandemics/FightPandemics/pull/2094/files
Screen Shot 2020-12-16 at 11 59 55 AM

Unfortunately the auto trigger from Lokalise overwrites the changes made in #2072 :( 
I will close 2094 and trigger a new one with the updated email

@doheekim93 thank you.  i will go ahead and approve this one

**Review by aditilamkhede — APPROVED** [review]
Looks good. Great job debugging the issue @Juan-Moctezuma !!!

**Review by adorapham — APPROVED** [review]

**Comment by Juan-Moctezuma** [comment]
Thank you @aditilamkhede , @adorapham and @Zaydme for approving these changes, I'm glad I could help!

**Pull request merged**
