### PR TITLE
Issue number #1256

### LINKED ISSUE #1256: After  user applies a filter on Help Board, the user focus should be redirected to the  filtered post
Steps:
1. Navigate to https://rcv11.fightpandemics.xyz 
 2.Navigate to View Help Board
3. Scroll Down a few posts on Help Board
4. Click on Filters-> location
5. Enter 'Irvine' ->choose Irvine, CA 92602
6.Click View Result

Filtered Post goes to the top. But the user observes some scroll on the page but not redirected to the filtered post. (I can share video on slack)

Expected: User should be redirected to the filtered posts

### PR DESCRIPTION
**Pull request by MisterRK**
### What does this pull request aim to achieve? 💯
This PR resolves #1256 
When a user applies filters to the help board they should be redirected to the top of the newly filtered posts.

_Please be concise and link any related issue(s):_

- [ √] I have checked that no one else is working on similar changes.
- [ √] I have read the latest [**README**](README.md) and understand the development workflow.
- [√ ] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix. The branch is created in a cloned version of this repo, **not a forked repo**.
- [√ ] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [√ ] There are no merge conflicts.
- [ √] There are no console warnings and errors.
- [ √] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

### CODE REVIEW

**Comment by joshmorel** [comment]
Interesting @MisterRK 

This works okay-ish in Firefox but Chrome not so much. Which I think is because the `antd` layout component is using the (non-standard) `::-webkit-scrollbar`.

But opening the console and entering `window.scrollTo(0,0)` works totally fine so not sure what's going on exactly...

See:

window-scroll-doesnt-work


Anyways, the new pagination component you are working on @OzkanAbdullahoglu - will this also fix that issue or no?

**Comment by MisterRK** [comment]
Hi there. Thanks for taking the time to check this out. I will go in some time today and see if I can can make some improvements and learn more about the Ant D webkit scrollbar to find a solution for this.

**Comment by OzkanAbdullahoglu** [comment]
I think there are a couple of problems which is not related directly with this branch. I can't filter a location which I desire. Only I see my own location. And this is same in staging too. And also there is another bug most possible because of unintentional re-renders. This can be because of what we discussed before with @joshmorel  (I will look into this) 

From fightpandemics.com -unintentional re-renders and re-fetches




From this branch location autocomplete doesn't work. Not related to this branch. 



And for this fix in chrome when I chose type as a filter, It scrolls to top as expected but I couldn't test same action with filtering location.

**Comment by Zaydme** [comment]
This issue is not happening with the current staging anymore.
Thank you!

Please feel free to reopen this if you think it's needed.

**Pull request closed without merging**
