### PR TITLE
Add Fixture Files for Cypress Tests

### PR DESCRIPTION
**Pull request by jessica-lau**
### What does this pull request aim to achieve? 💯

Move reusable error messages, button names, signup/sign credentials, etc to fixture files so that they can be reused across all e2e test specs when needed. Updated all existing applicable e2e tests with fixtures.

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Comment by jessica-lau** [comment]
@galeza this is still a draft PR but before I continue to add more fixtures and update the existing tests, I wanted to see if you think adding the reususable errors msg/button text, etc to the fixture files make more sense than adding them to the constants.js file. When using fixtures we will need to add extra lines of code in the test specs (see the sign in spec for example) but when using the the constants.js we just export/import. I personally think adding them to the constant.js file lessens the amount of code needed but what do you think?

**Comment by galeza** [comment]
Hi @jessica-lau 

There is a possibility to import fixtures: https://glebbahmutov.com/blog/import-cypress-fixtures/

```
import SignIn from '../../../elements/pages/signIn';
import errorMessages from '../../../fixtures/errorMessages.json'
```

and then in test:
```
      import SignIn from '../../../elements/pages/signIn';
import errorMessages from '../../../fixtures/errorMessages.json'
import emailAndPassword from '../../../fixtures/emailAndPassword.json'
import buttonNames from '../../../fixtures/buttonNames.json'


describe('FightPandemics Sign In Page', () => {

    const signIn = new SignIn();


    context('User signs into account', () => {

        beforeEach(() => {
            signIn.visit();
        });

        it('FP logo is visible and clickable', () => {
            cy.checkFpLogoIsVisibleAndClickable(signIn.getFpLogoLocator());

        });

        it('Sign in page contains heading and image', () => {
            var h4Heading = "Sign In";
            signIn.getH4Heading().should('be.visible').contains(h4Heading);
            signIn.getImage().should('be.visible');

        });

        it('Email address field is visible and can be populated', () => {
            var emailField = signIn.getEmailField();
            emailField.should('be.visible').and('have.attr', 'name', 'email');
            emailField.type(emailAndPassword.dummySampleEmail);

        });

        it('Leaving email field blank triggers error', () => {
            var emailField = signIn.getEmailField();
            emailField.should('be.visible').and('have.attr', 'name', 'email').focus().blur();
            var emailRequired = signIn.getEmailRequired();
            emailRequired.should('be.visible');
            emailRequired.contains(errorMessages.requiredEmail);

        });

        it('Entering invalid email triggers error', () => {
            var emailField = signIn.getEmailField();
            emailField.should('be.visible').and('have.attr', 'name', 'email');
            emailField.type(emailAndPassword.invalidSampleEmail).focus().blur();
            var validEmailRequired = signIn.getValidEmailRequired();
            validEmailRequired.should('be.visible');
            validEmailRequired.contains(errorMessages.invalidEmail);

        });

        it('Password field is visible and can be populated', () => {
            var passwordField = signIn.getPasswordField();
            passwordField.should('be.visible').and('have.attr', 'name', 'password');
            passwordField.type(emailAndPassword.validSamplePassword);

        });

        it('Clicking the password eye displays the password entered', () => {
            var passwordField = signIn.getPasswordField();
            passwordField.should('be.visible').and('have.attr', 'name', 'password');
            passwordField.type(emailAndPassword.validSamplePassword);
            var passwordEye = signIn.getPasswordEye();
            passwordEye.should('be.visible').and('have.attr', 'alt', 'Icon').click();

        });

        it('Leaving password field blank triggers error', () => {
            var passwordField = signIn.getPasswordField();
            passwordField.should('be.visible').and('have.attr', 'name', 'password').focus().blur();
            var passwordRequired = signIn.getPasswordRequired();
            passwordRequired.should('be.visible');
            passwordRequired.contains(errorMessages.passwordRequired);

        });

        it('Password entered not meeting 8 characters triggers error', () => {
            var passwordField = signIn.getPasswordField();
            passwordField.should('be.visible');
            passwordField.type('test');
            var passwordLengthRequired = signIn.getPasswordLengthRequired();
            passwordLengthRequired.should('be.visible');
            passwordLengthRequired.contains(errorMessages.passwordLengthRequired);

        });

        it('Password entered not meeting special characters triggers error', () => {
            var passwordField = signIn.getPasswordField();
            passwordField.should('be.visible');
            passwordField.type('testtest');
            var passwordCharacterRequired = signIn.getPasswordCharacterRequired();
            passwordCharacterRequired.should('be.visible');
            passwordCharacterRequired.contains(errorMessages.passwordCharacterRequired);

        });

        it('Sign in button is disabled when required details are not entered', () => {
            var signInButton = signIn.getSignInButton();
            signInButton.should('be.visible').and('have.attr', 'aria-disabled', 'true');

        });

        it('Sign in button is enabled when required details are entered', () => {
            signIn.getEmailField().type(emailAndPassword.dummySampleEmail);
            signIn.getPasswordField().type(emailAndPassword.validSamplePassword);
            var signInButton = signIn.getSignInButton();
            signInButton.should('be.visible').and('have.attr', 'aria-disabled', 'false');

        });


        it('Login fail alert appears when incorrect email & password are entered and submitted by user', () => {
            cy.generateRandomEmail().then((email) => {
                signIn.getEmailField().type(email);
            });
            signIn.getPasswordField().type('WrongPW!wpw3hi');
            signIn.getSignInButton().click();
            var loginFailAlert = signIn.getLoginFailAlert();
            loginFailAlert.should('be.visible');
            loginFailAlert.contains(errorMessages.loginFailWrongEmail);

        });

        it('Login fail alert appears when maximum sign in attempts are exceeded', () => {
            signIn.getEmailField().type(emailAndPassword.dummySampleEmail);
            signIn.getPasswordField().type('WrongPW!wpw3hi');
            for (var i = 0; i < 11; i++) {
                signIn.getSignInButton().click();
            };
            var loginFailAlert = signIn.getLoginFailAlert();
            loginFailAlert.should('be.visible');
            loginFailAlert.contains(errorMessages.loginFailMaximumAttempts);

        });

        it('Forgot password link is visible and clickable', () => {
            var forgotPasswordLink = signIn.getForgotPasswordLink();
            forgotPasswordLink.should('be.visible');
            forgotPasswordLink.contains('a', 'Forgot Password?').click();

        });

        it('Join now link is visible and clickable', () => {
            var joinNowLink = signIn.getJoinNowLink();
            joinNowLink.should('be.visible');
            joinNowLink.contains('u', buttonNames.joinNow).click();

        });

        it('Facebook button for sign in is visible', () => {
            var signInByFbButton = signIn.getSignInFbButton();
            signInByFbButton.should('be.visible');
            signInByFbButton.contains('span', buttonNames.facebook);

        });

        it('Google button for sign in is visible', () => {
            var signInByGoogleButton = signIn.getSignInGoogleButton();
            signInByGoogleButton.should('be.visible');
            signInByGoogleButton.contains('span', buttonNames.google);

        });

        it('LinkedIn button for sign in is visible', () => {
            var signInByLinkedinButton = signIn.getSignInLinkedinButton();
            signInByLinkedinButton.should('be.visible');
            signInByLinkedinButton.contains('span', buttonNames.linkedIn);

        });
    });
});
```

**Comment by galeza** [comment]
Tested on staging:
Screen Shot 2020-10-20 at 13 05 09

**Comment by jessica-lau** [comment]
Ahhh okay, I'll go ahead and fix this. Thanks for the input @galeza, didn't realize it could be done this way!

**Review by galeza — APPROVED** [review]
LGTM! 

I ran tests on this branch and all passed.

**Comment by galeza** [comment]
@idjevm 
Please accept and merge :)

**Review by TimeaKovacs86 — APPROVED** [review]
Looks good to me.

**Review by idjevm — APPROVED** [review]
Thanks Jessica

**Pull request merged**
