### PR TITLE
Add City Gif to the Landing page

### LINKED ISSUE #1968: Add City Gif to the Landing page and update Panvala logo.
- [ ] Adding the City GIF  to landing page. (Only for Desktop version)

- [ ] Update the Panvala logo on About Us page

### PR DESCRIPTION
**Pull request by wadehrarshpreet**
### What does this pull request aim to achieve? 💯

_Please be concise and link any related issue(s):_

Add City Gif to the Landing page

#1968 

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Comment by Zaydme** [comment]
Here is a 500KB animated png file, way more optimized that a gif, with exact quality
ezgif com-gif-maker

**Comment by tejasm2** [comment]
@Zaydme can you make the slower version of car passing more optimized?

**Comment by Zaydme** [comment]
@tejasm2 you mean slow this down, or you have a slower version?

**Comment by tejasm2** [comment]
Yes the cars are moving too fast @wadehrarshpreet is working on that .....but the cars should move a bit slow @Zaydme

**Comment by Zaydme** [comment]
Also this is a clouds Animated Png, without the white borders, but while removing them it lost some details. and now it's looking worse :joy: 
ezgif com-gif-maker (2)

but here is it with the white borders but animated png 
ezgif com-gif-maker (3)

**Review by Zaydme — APPROVED** [review]
LGTM!
I don't know why we didn't keep cloud png but maybe it's not very optimized anyway. in this case, we should delete the home-cloud.png from the assets folder.

**Comment by rabbi08** [comment]
@wadehrarshpreet @tejasm2 
Just thought to confirm the observation that the 'Blue color' of the GIF don't match with our FP blue. Please see below screenshot. Is this expected?

Screen Shot 2020-11-28 at 3 14 35 PM

**Comment by rabbi08** [comment]
> @wadehrarshpreet @tejasm2
> Just thought to confirm the observation that the 'Blue color' of the GIF don't match with our FP blue. Please see below screenshot. Is this expected?
> 
> Screen Shot 2020-11-28 at 3 14 35 PM

Ignore my comment plz, that's should be accepted, looks like, as to see the dark color on light one. Thanks

**Review by tejasm2 — APPROVED** [review]

**Pull request merged**
