### PR TITLE
Display user friendly message if post is deleted

### PR DESCRIPTION
**Pull request by nr431207**
### What does this pull request aim to achieve? 💯
Displays user friendly message if post is deleted, when the user opens up a shared link related to a post that has been deleted:

Screen Shot 2020-07-22 at 2 45 30 PM

_Please be concise and link any related issue(s):_
fixes: #1155 

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](https://github.com/FightPandemics/FightPandemics/blob/master/README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`** (need to have cloned the repo not forked).
- [x] This branch is rebased/merged with the **latest master**.
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

### CODE REVIEW

**Comment by nr431207** [comment]
@ppagarawal please test and let me know if changes need to be made. Thanks!

**Comment by joshmorel** [comment]
@nr431207 @ppagarawal - FYI this is what LinkedIn does. It would handle not only deleted, but post IDs that were never created and 500 server errors due to invalid ID format:

image

**Comment by ppagarawal** [comment]
@nr431207 please change the text to 

_Heading_ Ahh... snap!
_Text_ The post you have been looking for has expired. Please check our Help Board for more such posts. 

The link to the helpboard has to be there to ease the user land to that page. This is much friendly but will revamp more with better design and UX

**Comment by ppagarawal** [comment]
@Yu-Alexa-Zhao it'll be great if you can have a design for us for this page.

**Comment by ppagarawal** [comment]
Cc:@sheeba1 @rabbi08

**Comment by nr431207** [comment]
@ppagarawal I changed the redirect to `help Board` to a button per your request, let me know if it looks ok!

**Comment by ppagarawal** [comment]
The button looks good @nr431207 . However, it'll be good to have some additional space between
- [ ] heading and text
- [ ] text and button

Reference: check the LinkedIn snapshot above

**Pull request merged**
