### PR TITLE
Adding validation for new languages

### PR DESCRIPTION
**Pull request by adorapham**
Adding the validation for Croatian, Greek,Hindi,Hungarian, and Marath languages

### What does this pull request aim to achieve? 💯

_Please be concise and link any related issue(s):_

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`** for a regular feature, **`hotfix/<branch_name>`** for a hotfix, and **`service/<branch_name>`** for a microservice, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Review by jessica-lau — APPROVED** [review]
LGTM. Thanks @adorapham 

image

**Review by TimeaKovacs86 — APPROVED** [review]
LGTM! Thank you!
headerspec test passes language

**Review by galeza — APPROVED** [review]
LGTM

**Comment by galeza** [comment]
@adorapham Should I merge or you want to add/modify?

**Review by JayashreeSamantasinghar — APPROVED** [review]
Looks good, All tests passed!! Thanks

**Review by Selbinyyaz — APPROVED** [review]
LGTM. Thank you @adorapham 
Screen Shot 2021-02-09 at 10 13 48 AM

**Comment by adorapham** [comment]
> @adorapham Should I merge or you want to add/modify?

@galeza @ddveloper  -Would you please merged for tomorrow production release

**Pull request merged**
