### PR TITLE
Set up microservices CI/CD for notifications backend

### LINKED ISSUE #1478: Set up CI/CD for microservices
Set up CI/CD for microservices. In the 8/30 DevOps meeting, we decided to keep the services in the main repo for now, and break out later if necessary. The microservices will live in the `services` folder, and we will create Github Actions workflows for each service and environment.

### PR DESCRIPTION
**Pull request by mannykary**
### What does this pull request aim to achieve? 💯

Setting up microservices CI/CD. Resolves #1478

- [X] I have checked that no one else is working on similar changes.
- [X] I have read the latest [**README**](README.md) and understand the development workflow.
- [X] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix. The branch is created in a cloned version of this repo, **not a forked repo**.
- [X] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [X] There are no merge conflicts.
- [X] There are no console warnings and errors.
- [X] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

### CODE REVIEW

**Comment by mannykary** [comment]
Still a WIP as I need to add the workflow files for staging and production, but I did test that the review workflow works and the Lambda is deployed successfully to the review environment. Please provide as much feedback as possible about possible improvements, etc. 

Also note that currently this is assuming that there is only one Lambda, but there will probably be more than one. If that is the case, then we will need to create `src` folders for each Lambda in the `services/notification` folder, create a Lambda Terraform resource for each additional Lambda, and create a build zip for each Lambda. I'll leave this to @brufen (Marija) to refactor as she sees fit since she's leading the architecture of the notifications backend.

**Comment by brufen** [comment]
Hi @mannykary ,
If we have separate directory services with services inside it (notifications, messages, other functionalities) will it possible this way to deploy only for example notifications? 

I would also like to add test folder to every microservice, but I guess we can add it later.

**Comment by mannykary** [comment]
> Hi @mannykary ,
> If we have separate directory services with services inside it (notifications, messages, other functionalities) will it possible this way to deploy only for example notifications?
> 
> I would also like to add test folder to every microservice, but I guess we can add it later.

Yes, since we have a separate Github Actions file for each service, and we have added a path matcher to trigger the build only if there are changes in the `notification` folder, it should be possible to deploy just one service; see the following https://github.com/FightPandemics/FightPandemics/blob/5b8e2b0d63ba457c3520c240325872c93a056f8e/.github/workflows/review-notification-service.yml#L9

I can add stub unit tests so that they can run as part of the build.

**Comment by mannykary** [comment]
@brufen I have added stub unit tests running in Mocha/Chai, and also added a job to the Github Actions workflow to run the unit tests prior to deploying. If the unit tests fail, then it will not deploy.

**Comment by mannykary** [comment]
I think the review workflow works well now, so I went ahead and added workflow files for staging and production, and moved the PR out of Draft.

**Review by brufen — APPROVED** [review]

**Review by idjevm — APPROVED** [review]
LGTM. Thanks @mannykary

**Pull request merged**
