### PR TITLE
Resolved the mobile blue line issue

### LINKED ISSUE #1628: Mobile-"Blue line" is displayed under profile if user does not select 'I need/want to help' option
1. Login using valid email/pwd and navigate to Profile.
2. Edit the profile as user does NOT select any option from "I want to" and "I need" checkboxes.

Issue: You will observe that 'blue line' is displayed under the user profile icon. refer below image.
Screenshot 2020-10-09 at 12 43 46 PM

Please note this issue exist in PROD as well and this works fine on Desktop.

### PR DESCRIPTION
**Pull request by sujatha-m**
### What does this pull request aim to achieve? 💯

_Please be concise and link any related issue(s):_This PR resolves #1628 

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Review by joshmorel — CHANGES_REQUESTED** [review]
Thanks @sujatha-m sorry for the late response (was ignoring anything not related to recent deployment).

I don't think you want to get rid of that semi-colon:

The result is "width: 30%" and "border-radius: 0.2rem" run into a single rule which is not recognized:

image

If we remove the border we actually don't need the `border-radius` so I'd remove that but make sure the semi-colon is there for `width: 30%;`.

**Comment by joshmorel** [comment]
@rabbi08 I do have two questions for this:

Will this no longer be relevant soon because we have an open PR to replace text with icons (cc @CamilaArias )? #1558

If we're sure maybe we should close issue/pr and focus on #1558

**Comment by rabbi08** [comment]
> @rabbi08 I do have two questions for this:
> 
> Will this no longer be relevant soon because we have an open PR to replace text with icons (cc @CamilaArias )? #1558
> 
> If we're sure maybe we should close issue/pr and focus on #1558

 @joshmorel 
Blue line might not be fixed with the fix or #1558 / #1463  because, this issue exist when both the options, 'I need help' and 'I want to help' are NOT selected. In the other PR we are replacing the text with icon but this is with the process of selection of these options.

**Comment by sujatha-m** [comment]
> Thanks @sujatha-m sorry for the late response (was ignoring anything not related to recent deployment).
> 
> I don't think you want to get rid of that semi-colon:
> 
> The result is "width: 30%" and "border-radius: 0.2rem" run into a single rule which is not recognized:
> 
> image
> 
> If we remove the border we actually don't need the `border-radius` so I'd remove that but make sure the semi-colon is there for `width: 30%;`.

**Comment by Zaydme** [comment]
Thanks @sujatha-m!
But the profile page was changed with #1480 so this issue is not happening anymore.

Please reopen if you feel the need to :+1:

**Pull request closed without merging**
