### PR TITLE
Add mochawesome report for backend tests & fix backend failed tests

### PR DESCRIPTION
**Pull request by jessica-lau**
### What does this pull request aim to achieve? 💯

Added mochawesome report generator for backend tests and made changes to fix backend tests that were failing.

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Comment by jessica-lau** [comment]
image

image

**Comment by JayashreeSamantasinghar** [comment]
Hi @jessica-lau 
I ran docker-compose build mocha-integration and then docker-compose run mocha-integration, mochawesome report folder generated but right clicking on mochawesome.html, can't able to see option 'open containing folder'. Do I have to do anything else here?
but I ran the tests all 23 tests passed. great job.
Thanks

**Comment by jessica-lau** [comment]
> Hi @jessica-lau
> I ran docker-compose build mocha-integration and then docker-compose run mocha-integration, mochawesome report folder generated but right clicking on mochawesome.html, can't able to see option 'open containing folder'. Do I have to do anything else here?
> but I ran the tests all 23 tests passed. great job.
> Thanks

@JayashreeSamantasinghar just DM'ed you on slack

**Review by TimeaKovacs86 — DISMISSED** [review]
LGTM! Got the same result! Great job! Thanks Jessica
Mochawesome report for backend tests   fix backend failed tests
Mochawesome report mochawesome html

**Comment by adorapham** [comment]
LGTM, TY @jessica-lau .  I check both front-end and back-end reports and both work.  Great work!
image
image

image

**Review by adorapham — DISMISSED** [review]

**Review by galeza — CHANGES_REQUESTED** [review]
Hi @jessica-lau 
Could you please rebase or merge staging branch. PR #1862 was merged yesterday. Some tests (mocha/test/login.test.js) were corrected there.

**Comment by jessica-lau** [comment]
Merged latest staging and reran tests and report:

image

**Review by JayashreeSamantasinghar — APPROVED** [review]
I ran the tests after staging merged. Looks good

**Review by TimeaKovacs86 — APPROVED** [review]
Re-tested after staging merge. Looks good to me!
Retest Add mochawesome report for backend tests and fix backend failed tests no 2115
Retest Add mochawesome report for backend tests and fix backend failed tests no 2115 mochawesome html

**Review by galeza — APPROVED** [review]
I tested on feature/mochawesome-for-backend-tests branch. 
All tests passed, report was generated:
Screen Shot 2021-01-05 at 18 21 25
LGTM!

**Comment by adorapham** [comment]
LGTM after getting the latest codes. 
image
image

**Review by adorapham — APPROVED** [review]

**Comment by jessica-lau** [comment]
Please merge @galeza . Thanks!

**Comment by galeza** [comment]
@jessica-lau 
May I merge or you want to commit more?

**Comment by jessica-lau** [comment]
> @jessica-lau
> May I merge or you want to commit more?

@galeza please merge. I was just updating the branch with the latest in staging. Thank you!

**Pull request merged**
