### PR TITLE
remove logo's link in logo-only layout

### LINKED ISSUE #1249: while sign-up, the link for 'FightPandemics' on 'Check your inbox' page is not working
Issue: while sign-up, the link for 'FightPandemics' on 'Check your inbox' page is not working . Refer picture below:

steps:1. Go to  https://rcv11.fightpandemics.xyz/ , Navigate to Join Now

2.Enter email,password and confirm password and click 'Join Now'
3.'Check your Inbox' page is displayed
4. click on FP link on top left
Issue: FP link is not working

image

### PR DESCRIPTION
**Pull request by joshmorel**
### What does this pull request aim to achieve? 💯

Resolves #1249 

Based on @manualzuru quote referenced in issue:

> Comment from Manu, "@sheeba Jose in most of the transactional features we don't want them to click anywhere else. Please check Amazon checkout page"

We had a similar issue come up - clicking the logo on `/create-profile` redirects you back to the same page. This is the unexpected behaviour but it's better and simpler to just make the logo not a link.

@manualzuru please confirm is this is the intended resolution.

Here - I also changed `/create-profile` to use the same layout as the other similar pages. It doesn't make sense that it is the only one using that layout. I'm open to suggestions/changes as well as removing this change from this PR. @robinv85 if you have specific insight let us know.

The pages affected (where you can't click the logo to take you home), are:

`/auth/login`
`/auth/signup`
`/auth/forgot-password`
`/auth/logout`
`/auth/check-email`
`/create-organisation-profile`
`/create-profile`

This is not urgent so no rush on reviewing & providing feedback. 

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](https://github.com/FightPandemics/FightPandemics/blob/master/README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`** (need to have cloned the repo not forked).
- [x] This branch is rebased/merged with the **latest master**.
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

### CODE REVIEW

**Review by idjevm — CHANGES_REQUESTED** [review]
I think we should change all the `auth` pages to have the logo clickable. What if I don't want to change my password? what if I don't want to sign up or log in? Will I have to actually type the address again to go back home? This will create a lot of unneeded friction. Or at least have the clickable logo in a few of these but not removing it completely...

**Review by robvenn — APPROVED** [review]
@joshmorel yep looking at these layouts was my intention when I opened this ticket https://github.com/FightPandemics/FightPandemics/issues/462
But I remember I actually added "navless" while I was working on some feature and probably I just didn't realize that the "logo" layout was intended for those pages or something like that
well for me the "logo layout" name is not very clear about the intention and I have no idea how many layouts etc. so maybe we can also improve this for clarity somehow

**Comment by joshmorel** [comment]
> @joshmorel yep looking at these layouts was my intention when I opened this ticket #462
> But I remember I actually added "navless" while I was working on some feature and probably I just didn't realize that the "logo" layout was intended for those pages or something like that
> well for me the "logo layout" name is not very clear about the intention and I have no idea how many layouts etc. so maybe we can also improve this for clarity somehow

I was thinking of renaming to NavlessLayout because that is more clear. I can do that as well as other changes.

**Comment by joshmorel** [comment]
> I think we should change all the `auth` pages to have the logo clickable. What if I don't want to change my password? what if I don't want to sign up or log in? Will I have to actually type the address again to go back home? This will create a lot of unneeded friction. Or at least have the clickable logo in a few of these but not removing it completely...

@idjevm They can always refresh BUT we can also make it a prop so it's variable.  @manualzuru  @vikjoshi @indirabhowmick (or QAs or anyone) please chime in. 

Here are the 2 that have caused issues thus far where you are redirected to the same page so the clickable logo is confusing:

* `/auth/create-profile`: This one - issue opened by @rabbi08  #1153 by closed - we definitely want them to complete their profile and not go anywhere else accidentally. I'm even thinking an `onunload` confirmation message would be good here.
* `/auth/check-email`: The issue #1249 noted by @sheeba1 . On the fence for this one. The tab is kind of "dead" anyways. The next action for the user is to go to their email client then confirm the email (or change password). They will then be redirected to `/auth/login` in a new tab to continue with authenticated use.

The ones that do currently go back home if the logo is clicked:

* `/auth/login`
* `/auth/signup`
* `/auth/forgot-password`
* `/create-organisation-profile`

FYI I listed `/auth/logout` but it's not relevant here at all (should always redirect to home).

**Comment by joshmorel** [comment]
FYI redirect after verification or change password cannot work in review environment due to variable subdomain.

It does work in prod and staging.

Thanks @sheeba1 for asking about this.

**Comment by joshmorel** [comment]
Closing this as it's way too old now. Can revisit later with further auth refactoring etc.

**Pull request closed without merging**
