### PR TITLE
Backend Test for Signup Endpoint

### PR DESCRIPTION
**Pull request by jessica-lau**
### What does this pull request aim to achieve? 💯

This is the backend test for the signup endpoint. An issue has been opened to include changing some of the error messages returned from the server - PR#[1594](https://github.com/FightPandemics/FightPandemics/issues/1594)

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix. The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

### CODE REVIEW

**Comment by jessica-lau** [comment]
@galeza @idjevm @sheeba1 when running the tests you'll notice two of them will fail (Empty password and confirm password trigger Bad Request error/Email local part has more than 64 characters triggers Bad Request error tests). That's because the actual returned status is a 500 error. I think it would make sense if they are returning a 400 status error instead and had the two test reflect this. Do you agree or think this should be the case? Thanks!

**Comment by galeza** [comment]
Hi @jessica-lau 

I've just got info from Paul Stevenson:

```
Hi Agnieszka, sorry due to some problems and a lack of documentation of Auth0's validation work on this was stalled but it is now nearly finished. Sorry I gave you the wrong format for accepted emails!! It will be as you stated above but with any valid top level domain:
(64max)@+(63max)+‘.’+(tld)
Valid top level domains should be any that appear in this list i believe:
https://data.iana.org/TLD/tlds-alpha-by-domain.txt
```

I will have to update login endpoint test as well.

**Comment by jessica-lau** [comment]
> Hi @jessica-lau
> 
> I've just got info from Paul Stevenson:
> 
> ```
> Hi Agnieszka, sorry due to some problems and a lack of documentation of Auth0's validation work on this was stalled but it is now nearly finished. Sorry I gave you the wrong format for accepted emails!! It will be as you stated above but with any valid top level domain:
> (64max)@+(63max)+‘.’+(tld)
> Valid top level domains should be any that appear in this list i believe:
> https://data.iana.org/TLD/tlds-alpha-by-domain.txt
> ```
> 
> I will have to update login endpoint test as well.


Got it, will make changes in the test to reflect this. Thanks for the update!

**Comment by jessica-lau** [comment]
@galeza I made changes to include testing the tld. An issue has been opened to include changing some of the error messages returned from the server - PR#[1594](https://github.com/FightPandemics/FightPandemics/issues/1594)

**Comment by galeza** [comment]
@jessica-lau 
Review this PR or we will wait when #1594 - add email and password validator in backend (reuse frontend logic) #1598 will be merged?
What you think?

**Comment by jessica-lau** [comment]
@galeza, no let's wait until PR#1598 gets merged first. The messages were fixed on the backend (scenarios 1-4 in PR#1594) so I'll need to make changes to this PR after 1598 merges. I just converted this back to draft. Thanks.

**Comment by jessica-lau** [comment]
Closing PR due to some issues with branch. Will open a new PR.

**Pull request closed without merging**
