### PR TITLE
Backend e2e login endpoint tests

### PR DESCRIPTION
**Pull request by galeza**
This is a start of login endpoint tests.

I added apiEndpoints.js, apiHelper.js, testData.js, validators.js.

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix. The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

### CODE REVIEW

**Comment by galeza** [comment]
Hi @jessica-lau 
Could you look at this structure?
I added apiEndpoints.js, apiHelper.js, validators.js files. Now test seems to be more readable and contains two lines.

```
    it('User is not able to log in with the wrong credentials', async function () {
        let response = await apiHelper.sendPOSTRequest(APP_URL, apiEndPoint, credentialsWithWrongPassword);
        validator.validateStatusCodeErrorAndMessage(response, httpStatus.UNAUTHORIZED, 'Unauthorized', 'Wrong email or password.');
    });
```
Do you prefer utlis or helpers folder name?
More tests will be added.

**Comment by jessica-lau** [comment]
> Hi @jessica-lau
> Could you look at this structure?
> I added apiEndpoints.js, apiHelper.js, validators.js files. Now test seems to be more readable and contains two lines.
> 
> ```
>     it('User is not able to log in with the wrong credentials', async function () {
>         let response = await apiHelper.sendPOSTRequest(APP_URL, apiEndPoint, credentialsWithWrongPassword);
>         validator.validateStatusCodeErrorAndMessage(response, httpStatus.UNAUTHORIZED, 'Unauthorized', 'Wrong email or password.');
>     });
> ```
> 
> Do you prefer utlis or helpers folder name?
> More tests will be added.

Looks great, very nice and clean. Good idea creating those three files since we can add to them as more backend tests are being done. This will definitely help reduce the clutter in the code. As for the utils vs helpers folder name - let's stick with utils. Thanks for setting this up Agnieszka!

**Comment by galeza** [comment]
@jessica-lau @sheeba1 

Tests are organised using: apiEndpoints.js, apiHelper.js, testData.js, validators.js.
Tests for email contain test with domain bigger then 64 characters and email bigger then 254 characters. For frontend these validations will be added in the issue #1437 
-> Following the rules that Auth0 are using the email needs to have 64max for the local part and an overall max of 254 chars
Tests for password will be added when mock auth component will be added #1495 Currently we got 401 status and password is not validated. 
For password - in the before hook we need to do /signup and then in the test /login route.

I focused more on the structure of this framework.

One more question. Backend returns an error message: 'body.email should match format "email"'. I would say that it should be corrected. Please, confirm. What you think about it?

**Review by jessica-lau — APPROVED** [review]
@galeza the code and structure looks great. Ran the tests and they passed. 👍 

Yes, the returned error message: 'body.email should match format "email"' should be changed. For the email field left empty, the backend message should return "Email address is required". When an invalid email is entered, the backend message should return "Email address is invalid". Thanks!

**Review by idjevm — APPROVED** [review]
LGTM! 💜 Amazing work @galeza !!!  This is awesome!

**Comment by galeza** [comment]
@idjevm 
Please merge :)

**Pull request merged**
