### PR TITLE
[Mobile UI bug] Org Account drop-down causes page to stretch up to the limits of the screen

### LINKED ISSUE #1465: [Mobile UI bug] Org Account drop-down causes page to stretch up to the limits of the screen
### The Issue
If user edits organisation's type or industry:
Depending on the length of the option chosen, drop-down width is adjusted, causing the entire screen to be stretched beyond the space it should be within, and therefore length of divider lines and button's padding are stretched out and left-aligned elements are placed in the limit of the screen.

### Steps to reproduce
On mobile, go to organisation's account information.
Choose a long length option on the drop-down menus.

Short option
Screenshot_20200829-030005

Long option
Screenshot_20200829-030016

It'd be great if we can fix this behaviour, and also we could have the drop-downs be a bit longer (within the limits of alignments) so longer options can be read a bit better.

Note this isn't a problem when creating the account, only when editing the settings.

### PR DESCRIPTION
**Pull request by Elohina**
### What does this pull request aim to achieve? 💯

#1465 
It fixes the width of Type and Industry dropdowns to fill the screen length on mobile views.

- [ x] I have checked that no one else is working on similar changes.
- [ x] I have read the latest [**README**](README.md) and understand the development workflow.
- [ x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix. The branch is created in a cloned version of this repo, **not a forked repo**.
- [ x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x ] There are no merge conflicts.
- [x ] There are no console warnings and errors.
- [ x] On the right-hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

### CODE REVIEW

**Review by nadinejuraschek — APPROVED** [review]
lgtm! Thank you!

**Review by galeza — APPROVED** [review]
LGTM

Retested on Android 10 and emulator Samsung, simulator iPhone Max Pro, XS. Creating and editing org:

Screen Shot 2020-09-21 at 11 23 59
Screen Shot 2020-09-21 at 11 26 57
Screen Shot 2020-09-21 at 11 30 10
Screen Shot 2020-09-21 at 11 05 11

**Comment by galeza** [comment]
@CamilaArias 
I like this implementation for mobile. Could we consider this solution for web?
Currently for web desktop we have (options with "..."):
Screen Shot 2020-09-21 at 10 56 51

**Comment by Elohina** [comment]
@galeza the web version of this issue is in this PR https://github.com/FightPandemics/FightPandemics/pull/1484

**Comment by galeza** [comment]
@Elohina Thank you for PR number!

**Comment by galeza** [comment]
@rabbi08 @sheeba1 
Could you check with iOS device. Please. 
I was using simulators for iOS.

**Comment by galeza** [comment]
iPhone 7  simulator:

Screen Shot 2020-09-21 at 13 33 11

**Comment by sheeba1** [comment]
Tested Create/Edit orgs on IPhone XR.    Looking Good!


image

**Review by rabbi08 — APPROVED** [review]
Tested the Org drop down feature for create/Edit Org page, on iphone 11 pro max, this is working fine. Refer below screenshots.

https://share.getcloudapp.com/WnuJLwGg
https://share.getcloudapp.com/YEuo58pn

**Comment by rabbi08** [comment]
@Elohina @CamilaArias 

I have observed that issue #1519 i.e. hid grey drawer area, exist in this feature build. 

Please note that this issue is working fine in STG as of today. Kindly confirm if this PR merge will not break the current functionality in STG and re-introduce the #1519 issue.

Refer below screenshot.
https://share.getcloudapp.com/YEuo58pn

**Comment by Elohina** [comment]
@rabbi08 the branch wasn't updated with the current changes in staging. Now it is updated and that issue is not appearing.

**Pull request merged**
