### PR TITLE
Feature/post more comments button fix

### LINKED ISSUE #1243: [Desktop][Mobile] POST | View more comments button
env: staging

Steps:
1. Go to Help Board
2. Create post with ex. 10 comments
3. Click on a post

First 5 comments is displayed and button Show more comments is displayed. I click Show more comments button and next 5 comments is displayed. There's no more comments but button Show more comments is still shown.

Screen Shot 2020-07-21 at 11 39 12
Screen Shot 2020-07-21 at 12 56 11

### PR DESCRIPTION
**Pull request by Elohina**
### What does this pull request aim to achieve? 💯

Fix bug related to "Show more comments" button appearing when all the comments are already shown. Issue #1243 

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix. The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right-hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

### CODE REVIEW

**Comment by pemika-me** [comment]
Hi @joshmorel, I tried re-deploy twice following the steps you advised recently, but the URL still doesn't work for me. May you help look into this issue and give some suggestions?

**Comment by rabbi08** [comment]
@Elohina @joshmorel 
The deployment fails due to issue in "Deploy Review steps-> 
image

**Comment by mannykary** [comment]
> Hi @joshmorel, I tried re-deploy twice following the steps you advised recently, but the URL still doesn't work for me. May you help look into this issue and give some suggestions?

It looks like something funky happened during the initial deployment which caused the Terraform state file to diverge from the actual state of the infrastructure for this build. I wiped out this build in AWS, deleted the Terraform state file, and rebuilt from scratch. You should now be able to access the build: https://featurepost-more-comments-button-fix.fightpandemics.xyz/

**Comment by pemika-me** [comment]
Ok thanks, the link can work now.

1. For 5 comments rule (<= 5 comments shows no button :heavy_check_mark: ; > 5 comments shows "view more comments" :heavy_check_mark: ; Already shows all comments then shows "view less comments" :heavy_check_mark: )

2. Not sure if what result that team exactly wants, I tried to view comments in [this post](https://featurepost-more-comments-button-fix.fightpandemics.xyz/post/5f618b1b94954b86a99e6797). I observed the numbers of popping up comments after pressed on "view more comments" are not fixed number (e.g. should extend more 15 comments each time the button is pressed, maybe??.) And also when I click on view more comments until it shows "view _**less**_ button" > click on that button > all comments were hidden except the latest 5 comments on the top > press "view _**more**_ comments" again > it shows all comments this time with "view _**less**_ button".

**Comment by Elohina** [comment]
Thanks for your observations @pemika-me. About the number of comments that have to be shown after clicking the button, it looks like it was done to increment the number of comments by the double of the previous amount every time you click the button. Maybe @joshmorel knows if that was the initial intention. I can also fix it to 5 but I would like to confirm if that change is necessary.

**Review by rabbi08 — APPROVED** [review]
As per current functionality:
- Correct total number of comments should be displayed
- Recent comment should be on the top
- 'Show more/Show less" button is displayed when comments are >5, but no count is displayed i.e. how many displayed and how many left.

 I have tested this feature on feature build for below scenarios:
1. Comments greater than 5 (C>5): "Show More comments" button is displayed, when clicked next 5 comments are displayed.  After all the comments are displayed "Show Less comments" is displayed -> clicked-> then only first 5 comments should be displayed: PASS

2. Comments less than and equal to 5(C<=5): All the existing comments are displayed but no "Show" button displayed: PASS

3. Comments greater than 10 (C>10): "Show more comments" button is displayed and when clicked next, 5 comments are displayed -> "Show More" button still exist -> clicked -> next 5 or remaining comments are displayed until all the existing comments are displayed. After all the comments are displayed "Show Less comments" is displayed -> clicked-> then only first 5 comments should be displayed: PASS

Refer below screen recording 
https://share.getcloudapp.com/ApuLBlLy

**Comment by galeza** [comment]
LGTM
tested with the following scenarios: comments > 10, comments == 5, comments < 5. For ind and org profile.

**Review by galeza — APPROVED** [review]

**Review by idjevm — APPROVED** [review]
LGTM ! Thank you so much @Elohina !

**Pull request merged**
