### PR TITLE
fix: back to create post

### LINKED ISSUE #1781: Unsigned user clicks on create post then after login it leads to home page instead of create post page.
Environment : staging 
Device used:Samsung Galaxy s8
Browser:Google chrome 
1.As a  unsigned user go to help board. 
2.click on plus symbol to create post.
3.Redirected to login page.
4.provide valid user name and password and click sign in. 
Expected result:
It lands on post creation page.
Actual result:
It lands on home page.

### PR DESCRIPTION
**Pull request by OzkanAbdullahoglu**
* for non-login users after sign-in page, redirect to feed.js and open create post

### What does this pull request aim to achieve? 💯
Resolves #1781 
_Please be concise and link any related issue(s):_

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Review by Zaydme — APPROVED** [review]
LGTM

**Comment by nivetheatha** [comment]
Works as expected. 
GIF-201111_143431

**Review by joshmorel — APPROVED** [review]
Thanks @OzkanAbdullahoglu ! LGTM.

**Comment by nivetheatha** [comment]
Retested in staging: Works as expected.

**Pull request merged**
