### PR TITLE
Backend Test for Feedback Endpoint & Update Login Endpoint Error Messages

### PR DESCRIPTION
**Pull request by jessica-lau**
### What does this pull request aim to achieve? 💯

- Create backend test for Feedback endpoint
- Update negative Login endpoint test to reflect updated response error messages

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Comment by jessica-lau** [comment]
Hey everyone, you'll notice that two of the test cases in the feedback endpoint will fail when you run the tests. Currently, the actual error messages set for them are incorrect (and needs to be corrected) so I put what error messages are expected. Please let me know if I'm missing anything or any suggestions you have. Thanks!

**Comment by galeza** [comment]
Hi @jessica-lau 
I tested with docker and it's ok (as you said two tests fail).
I was also checking in Postman a situation when we replace strings with int for covidImpact, generalFeedback, mostValuableFeature:
```
  "age": 5,
  "covidImpact": 1,
  "generalFeedback": 2,
  "mostValuableFeature": 3,
  "rating": 3,
  "whatWouldChange": "it's ok"
}
```
In the DB it was saved as strings so it doesn't affect functionality. I think that it's not necessary to add this test. Please confirm.
Second question - do we have max for strings or user can enter as many characters as he wants? In staging I don't see any limit. Maybe we should report an issue? 
For age there is no limit as well. And in the DB we save double instead of Int32.
Screen Shot 2020-11-12 at 13 58 00

**Comment by galeza** [comment]
@jessica-lau 
I don't know if we have an issue for backend api validation when age is negative. 
For frontend we have this issue: https://github.com/FightPandemics/FightPandemics/issues/1124

**Comment by jessica-lau** [comment]
> Hi @jessica-lau
> I tested with docker and it's ok (as you said two tests fail).
> I was also checking in Postman a situation when we replace strings with int for covidImpact, generalFeedback, mostValuableFeature:
> 
> ```
>   "age": 5,
>   "covidImpact": 1,
>   "generalFeedback": 2,
>   "mostValuableFeature": 3,
>   "rating": 3,
>   "whatWouldChange": "it's ok"
> }
> ```
> 
> In the DB it was saved as strings so it doesn't affect functionality. I think that it's not necessary to add this test. Please confirm.
> Second question - do we have max for strings or user can enter as many characters as he wants? In staging I don't see any limit. Maybe we should report an issue?
> For age there is no limit as well. And in the DB we save double instead of Int32.
> Screen Shot 2020-11-12 at 13 58 00

thanks @galeza for the feedback. I don't think we need to create a test case for when the strings are replaced with integers as they're automatically converted to strings as default.

I opened the following issues:
[#1806](https://github.com/FightPandemics/FightPandemics/issues/1806) to set a max limit on how many characters users can enter in the responses for the questions on screen 2 & 3.

[#1807](https://github.com/FightPandemics/FightPandemics/issues/1807) to correct the backend API validation status/messages for the two tests that currently fail.

**Comment by adorapham** [comment]
Hi @jessica-lau , I try to run and see 10 passing (6s) and  2 failing.  I have another concern, when i use the front end to test and enter an invalid age huge number
{rating: 3, age: **1234**, covidImpact: "", generalFeedback: "", mostValuableFeature: "",…}
i see the response is {"success":true}, i think the age has to be a number but in certain range.  
Actually i see you already log defect #1807 which will cover this scenario, but please check what is the max of age so we can test the boundary value.. TY

**Comment by jessica-lau** [comment]
> Hi @jessica-lau , I try to run and see 10 passing (6s) and 2 failing. I have another concern, when i use the front end to test and enter an invalid age huge number
> {rating: 3, age: **1234**, covidImpact: "", generalFeedback: "", mostValuableFeature: "",…}
> i see the response is {"success":true}, i think the age has to be a number but in certain range.

@adorapham yes, you'll see 2 tests failing until this issue [#1807](https://github.com/FightPandemics/FightPandemics/issues/1807) is fixed. I also added onto the issue stating that a large integer shouldn't result in a {"success":true} response. Thanks for pointing that out.

Issue [#1806](https://github.com/FightPandemics/FightPandemics/issues/1806) was also created to limit the characters for age on the frontend.

**Review by galeza — APPROVED** [review]

**Review by adorapham — APPROVED** [review]

**Review by idjevm — APPROVED** [review]
LGTM :)

**Pull request merged**
