### PR TITLE
Updated Validation Message in Backend Test for Feedback Endpoint - Rating & Age

### PR DESCRIPTION
**Pull request by jessica-lau**
### What does this pull request aim to achieve? 💯

Updated response messages in backend test for feedback endpoint when an invalid age or invalid rating is entered. Issue [**#1807**](https://github.com/FightPandemics/FightPandemics/issues/1807) was fixed to return correct backend API validation for the status code and message.

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Review by TimeaKovacs86 — APPROVED** [review]
LGTM! Tests are passing perfectly. Great job!

**Comment by adorapham** [comment]
LGTM -  14 passing (5s) . Thank you .
@jessica-lau , for the test Object.assign(feedbackWithAgeOver150, { age: 555 });, I just wonder why you don't use the data to test with age 151 instead of 555. I test with 151 and see it fails and also rating with 6 instead of 555.  I test rating failing with 6 since rating can't greater than 5.  Possible you might have some intention to use this 5 digit ?

**Review by adorapham — APPROVED** [review]

**Comment by JayashreeSamantasinghar** [comment]
Hi @jessica-lau 
I was testing manually in STG ,there is no success message giving "0" as age, it only gives success message taking age >=1.
one more thing, in https://staging.fightpandemics.work/api/documentation/index.html#/default/post_api_feedback_ the example showed the request body should be
{
  "age": 0,
  "covidImpact": "string",
  "generalFeedback": "string",
  "mostValuableFeature": "string",
  "rating": 0,
  "userId": "string",
  "whatWouldChange": "string"
}
so just wanted to know, is it ok not to consider "userId " in requestBody?
otherwise the code looks good to me. 
Thanks for doing great job

**Comment by jessica-lau** [comment]
@adorapham I just randomly chose 555 as the value to test the over age and over rating limit so there wasn't any reason behind it but I changed them to 151 and 6 as you suggested.

@JayashreeSamantasinghar yes I think the current outcome is correct as there should be no success message when age 0 is entered. The limit is set to an age of being at least 1 for the person entering the feedback. I think the swagger api documentation should be showing "age": int, "rating": int instead of "age": 0, "rating": 0

Regarding the userId, this test is only based on unauthorized user for now. 

@jessica-lau thank you for making a change

**Review by JayashreeSamantasinghar — APPROVED** [review]
thanks @jessica-lau

**Review by idjevm — APPROVED** [review]
Thanks @jessica-lau

**Pull request merged**
