### PR TITLE
User Story 5.1 - See Org Book/Page Link #2273

### LINKED ISSUE #2273: User Story 5.1 - See Org Book/Page Link

### LINKED ISSUE #2358: User Story 5.1- See Org Book Font Size Issue
Steps:
1. Click on the organization name
2. Should see the " See Org Book" link under the org description.

Actual result: the font size is 16 px in a chrome

Expected result: the font size is 14 px in Zeplin 

Environment:

- Browser: Chrome

- Device: Mobile

https://user-images.githubusercontent.com/62081140/117339591-86b6f800-ae65-11eb-858b-1d4f7eb4fa1b.mp4

### PR DESCRIPTION
**Pull request by adroit22**
Resolves #2273 
- PR includes changes for User story 5.1
- Added ‘See Org Book' link underneath the org description
- Using the field 'orgBookLink' from the organization schema  as href value of the link
- added a method to check if the value of orgBookLink contains a complete url with http. If yes then use else append the string in the orgBookLink to the  window.location.pathname

### CODE REVIEW

**Comment by hiran11** [comment]
@adroit22  Observations made: USER STORY 5.1

Issue 1: User Story 5.1- Organization Description Profile -'See  Org Book'  
    The Spacing between Organization Description and 'See Org Book' link is less. As a suggestion some more space can be given 
between description of Organisation and 'See Org Book' link . The Location of 'See Org Book'  link changes based on the  number of lines entered in the organisation description rather having a fixed location for the 'See Org Book'  link.     

image

image

**Comment by hiran11** [comment]
Observations made: USER STORY 5.1

Issue 2: User Story 5.1- Organization Description Profile  box 

The Size of the description box varies based on the number of lines been entered in the  description box rather than being the fixed size.

image


image

**Comment by xJamesScott** [comment]
temporarily closed for troubleshooting

**Comment by hiran11** [comment]
> Observations made: USER STORY 5.1
> 
> Issue 2: User Story 5.1- Organization Description Profile box
> 
> The Size of the description box varies based on the number of lines been entered in the description box rather than being the fixed size.
> 
> image
> 
> image

This issue is fixed . The spacing is gived

**Review by xJamesScott — APPROVED** [review]

**Comment by xJamesScott** [comment]
@adorapham Can you approve this PR so we can merge?

**Review by adorapham — APPROVED** [review]
since we have only one defect User Story 5.1- See Org Book Font Size Issue #2358  and decide to move fw, put the defect to enhancement and work later

**Pull request merged**
