### PR TITLE
Added test  to helpboard filter panel

### PR DESCRIPTION
**Pull request by JayashreeSamantasinghar**
### What does this pull request aim to achieve? 💯
Added test for post fulfillment to helpboard filter panel
_Please be concise and link any related issue(s):_

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`** for a regular feature, **`hotfix/<branch_name>`** for a hotfix, and **`service/<branch_name>`** for a microservice, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Review by jessica-lau — APPROVED** [review]
LGTM

image

**Review by Selbinyyaz — APPROVED** [review]
LGTM @JayashreeSamantasinghar Thank you
Screen Shot 2021-02-27 at 10 14 24 PM

**Comment by adorapham** [comment]
LGTM. TY - next time, if we have  a chance , please change from Quit Filters to Clear Filters to map with the screenshot
image

**Review by adorapham — APPROVED** [review]

**Review by ddveloper — APPROVED** [review]
LGTM 🕺

**Comment by JayashreeSamantasinghar** [comment]
Thanks everyone.
@ddveloper  
please merge this branch in staging.

**Pull request merged**
