### PR TITLE
Production Release as on10-20-2020

### PR DESCRIPTION
**Pull request by rabbi08**
### What does this pull request aim to achieve? 💯

_Please be concise and link any related issue(s):_

- [ ] I have checked that no one else is working on similar changes.
- [ ] I have read the latest [**README**](README.md) and understand the development workflow.
- [ ] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [ ] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [ ] There are no merge conflicts.
- [ ] There are no console warnings and errors.
- [ ] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [ ] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Comment by galeza** [comment]
hi @rabbi08 

I retested on staging:
#1603 - Add medium and bold Poppins font (#1669) and
#1305 - Fix EmailShareButton prop

Fonts are correctly displayed for Polish translation:
Screen Shot 2020-10-20 at 18 42 38

Post title is shown as an email title:
Screen Shot 2020-10-20 at 18 44 48
Screen Shot 2020-10-20 at 18 45 25

I retested using macOS + chrome v. 86 and safari

For tests I checked tests using docker-compose and staging:
Screen Shot 2020-10-20 at 18 50 30

**Review by galeza — APPROVED** [review]
LGTM

**Comment by rabbi08** [comment]
Verified PR #1667 , #1681 (GTM QAtoggle)  in STG as working fine. Thanks Refer below GIF.

ezgif com-gif-maker (21)

**Comment by rabbi08** [comment]
- Rollback 'Search' functionality from the help Board :Done.
- Run the Sanity test after the rollback in STG: Done 
- QA testing in STG: Complete

**Pull request merged**
