### PR TITLE
Fix bug BACK button navigate to the previous page that user navigated

### LINKED ISSUE #1398: Create/EDIT my POST -> Click on Back button -> Lands on FEEDs page, rather than previously navigated page.
Please note this issue occur again. Earlier reported and fixed issue #1018 and #1093 

Earlier I reopened old issue but I think I should open new one and link old. 

1. Open "https://staging.fightpandemics.work/"
2. Login using valid email/pwd
3. Navigate Profile -> My Profile
4. EDIT any comment and after "EDIT or comment" on any Post, click on 'BACK' button

Issue: You will observe that user lands on 'FEED' home page rather that 'My Profile' page from where I navigated.

So actually, BACK button should navigate to the previous page that user navigated, i.e. preserving the history of the user, to user "BACK" button feature.

This issue have been observed again in STG. Hence reopening this same issue, let me know if I should log new one or we should track from here.

Add Post -> https://share.getcloudapp.com/xQuL97BZ
EDIT post -> https://share.getcloudapp.com/kpubyDpP

When user click on 'Back' button, user should be re-directed to previous page visited before.

### PR DESCRIPTION
**Pull request by sujatha-m**
### What does this pull request aim to achieve? 💯

_Please be concise and link any related issue(s):_This PR Resolves #1398 

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix. The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

### CODE REVIEW

**Comment by galeza** [comment]
Hi,

I tested the following scenarios:
1. Login - Profile - open  a post, add a comment, like -> Click Back button. I was navigating to the Profile page. OK
2. Login - Organisation - open  a post, add a comment, like -> Click Back button. I was navigating to the Organisation page. OK
3. Login - Feed - Open a comment, add a comment, like -> Click Back button. I was navigating to the Feed page. OK

LGTM

Waiting for @rabbi08 tests

**Review by joshmorel — APPROVED** [review]
LGTM Thanks.

**Review by galeza — APPROVED** [review]

**Review by rabbi08 — APPROVED** [review]
Verified the fix as working on the feature build, scenarios tested as below:
1. Login -> Profile -> Create Individual post -> View post -> Click 'BACK' button: PASS
2. Login -> Profile -> Create Organisation post -> View post -> Click 'BACK' button: PASS
3. Login -> Organisation -> Create Org post -> View post -> Click 'BACK' button: PASS
4. Login -> Help Board -> Add comment -> Click 'BACK' button : PASS

Refer attached screen recording, thanks.
https://share.getcloudapp.com/5zuweoOm

**Comment by rabbi08** [comment]
Verified in STG, working fine. Refer below GIF:
https://share.getcloudapp.com/6quP279x

**Pull request merged**
