### PR TITLE
#1463 - Replacing text with icon in profile page

### LINKED ISSUE #1463: [Profile] Change text "I Need Help/I want to offer help" for their icons
SVG for I want to offer help [here](https://fightpandemics.com/static/media/offer-help-unselected.aca98093.svg)

image

For I need help [here](https://fightpandemics.com/static/media/request-help-unselected.c4adb941.svg)

image

### PR DESCRIPTION
**Pull request by Amrit-choudhary16**
### What does this pull request aim to achieve? 💯
Addressing issue #1463 by replacing the text with the SVG images. Also moved the location icons as per feedback.
_Please be concise and link any related issue(s):_

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix. The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
Closes #1463

### CODE REVIEW

**Review by rabbi08 — APPROVED** [review]
Verified the icons for Individual profile, the "I want help/I need help" is replaced with the icons mentioned: PASS 

 Refer below screenshot.
https://share.getcloudapp.com/rRuoJ9JJ

**Review by galeza — CHANGES_REQUESTED** [review]
Hi,
On desktop it works fine. 
Screen Shot 2020-09-29 at 11 02 24

But what about mobile screen? Icons are squeezed:
Screen Shot 2020-09-29 at 11 02 01
Screen Shot 2020-09-29 at 11 00 17
I tested on Android 10, 9 and simulator iPhone 11 max. Please correct mobile web :)

**Comment by galeza** [comment]
Screenshot_2020-09-29-11-08-15-023_com android chrome

**Comment by Amrit-choudhary16** [comment]
@galeza I updated the code based on your feedback. Kindly review the same.

**Comment by rabbi08** [comment]
Tested on iPhone 11 Pro Max, icons are displayed, but design looks like it's distorted. Do we have zeplin or figma design expectation.
image

**Comment by galeza** [comment]
Hi @Amrit-choudhary16 ,

I tested using Android 10, simulators and emulators.

@CamilaArias Please verify results on mobile phones. Screen shots below and in the @rabbi08 comment. QAs want to confirm that results are acceptable for you. Do we have any Zeplin design? 
Screen Shot 2020-10-02 at 09 26 59
Screen Shot 2020-10-02 at 09 24 14
Screen Shot 2020-10-02 at 09 34 08
Screenshot_2020-10-02-09-48-55-961_com android chrome

**Comment by CamilaArias** [comment]
@rabbi08 @galeza I'll review this today with @Amrit-choudhary16 to make a small design change :)

**Comment by rabbi08** [comment]
@CamilaArias 
We have new updated profile pages, do we need this change on new pages. Please confirm or we can close this issue. Thanks

**Pull request closed without merging**
