### PR TITLE
Lokalise: Translations update

### PR DESCRIPTION
**Pull request by jyclam**
This pull request was initiated by Lokalise (user Agnieszka Galeza) at 2020-11-30 22:47:27

### CODE REVIEW

**Review by Jameel139 — APPROVED** [review]
Looks good

**Review by Zaydme — APPROVED** [review]
LGTM

**Comment by adorapham** [comment]
@Zaydme @galeza @Jameel139 i still see on staging, do i need to wait some times to check

image
image

**Comment by Zaydme** [comment]
@adorapham yes, we didn't merge this yet.
@Zaydme , please let me know when you are done ,so i can check

**Review by rabbi08 — APPROVED** [review]
looks good

**Pull request merged**
