### PR TITLE
max char limit and related UI error messages are added.

### LINKED ISSUE #1272: [Desktop][Mobile] The name of Individual and Organization needs to be limited to 60 chars max.
Scenario 1: Individual 
As a user,
Given that I am on the Create Individual Account/ Edit Individual Account page,
Then I should be able to enter only 30 chars max in my First Name and 30 chars max in my Last Name.

Scenario 2: Organization
As a user,
Given that I am on the Create Org Account/ Edit Org Account page,
Then I should be able to enter only 60 chars max in my Organization Name.

### PR DESCRIPTION
**Pull request by OzkanAbdullahoglu**
### What does this pull request aim to achieve? 💯
Resolves #1272 
_Please be concise and link any related issue(s):_

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](https://github.com/FightPandemics/FightPandemics/blob/master/README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`** (need to have cloned the repo not forked).
- [x] This branch is rebased/merged with the **latest master**.
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

### CODE REVIEW

**Comment by OzkanAbdullahoglu** [comment]
If you have better ideas for UI error messages I can replace them :)

**Comment by galeza** [comment]
Hi @OzkanAbdullahoglu 

I have a question about edit Account for Individual and edit account for Organisation. Should we add this validation also on these screen as stated here #1272 ?
I saw this validation on the Create Organisation profile but not when I edited org profile.
Screen Shot 2020-07-27 at 13 17 23

@doheekim93 
Please, do you accept this error message: _Max character limit (60) is exceeded!_

**Comment by OzkanAbdullahoglu** [comment]
Hi @galeza, I think we have to implement same error type to edit screens, you are right. Let's decide If we are comfortable with message itself, then I can implement it to the other screens too.

**Comment by tejasm2** [comment]
Yes...we need to implement this for Create as well as Edit screens for Org and Individual. Currently for the Org description this error message is shown.
description limit 0

**Comment by doheekim93** [comment]
Hi @OzkanAbdullahoglu @galeza @tejasm2 -- I think we should keep the error message simple like the "Max. 160 characters" as shown in Tejas' screenshot! Thanks Ozkan!

**Review by joshmorel — CHANGES_REQUESTED** [review]
As mentioned by @galeza and others we need to implement for edit org/user account as well.

Two other things:

1) `minLength: 3` I don't see that mentioned in the issue (or was it slack). We should just make it `required` & `maxLength: 60` IMO. But if a PM requrested this then we need to at least display an error message.
2) In `Organization Name`, the `required`/`minLength` messages aren't being displayed in until submission while `Organisation Contact E-mail` and the user `firstName`/`lastName` fields are? Any idea why? It would be nice to be consistent.

We should also add to B/E schema validators but we can do that later, in another PR.

**Comment by doheekim93** [comment]
@joshmorel @OzkanAbdullahoglu - can we make the min length 2? There are people with 2 letter first/last names

**Comment by joshmorel** [comment]
> @joshmorel @OzkanAbdullahoglu - can we make the min length 2? There are people with 2 letter first/last names

In this PR the min length is only affecting organizations. However, I'd rather just make all of these required (so `minLength: 1`) and leave it at that. For individual's there might be some 1 letter names out there & for organisation's it's not really a big deal IMHO. The `maxLength` is more important for avoiding display bugs.

**Comment by OzkanAbdullahoglu** [comment]
> As mentioned by @galeza and others we need to implement for edit org/user account as well.
> 
> Two other things:
> 
> 1. `minLength: 3` I don't see that mentioned in the issue (or was it slack). We should just make it `required` & `maxLength: 60` IMO. But if a PM requrested this then we need to at least display an error message.
_**I removed minLength limits, required ones also means minLength =  1 ; as you said**_
> 2. In `Organization Name`, the `required`/`minLength` messages aren't being displayed in until submission while `Organisation Contact E-mail` and the user `firstName`/`lastName` fields are? Any idea why? It would be nice to be consistent.
_**This was coming from react-hooks-form I handled that by adding**_
```
  } = useForm({
    mode: "change",
  });
```
> 
> We should also add to B/E schema validators but we can do that later, in another PR.

**Comment by OzkanAbdullahoglu** [comment]
Hi,  I have tried to cover all as much as possible, please check that If I missed something. Also, I added email validation in `edit-organisation`, and I set email max char limit to 30 too. Maybe a refactor should be good later on but I tried to stick to the current structure for this very moment. @joshmorel @idjevm @doheekim93 @tejasm2 @galeza

**Comment by cweave** [comment]
Looks good from an implementation standpoint :)

**Review by cweave — APPROVED** [review]
Looks good from an implementation standpoint :)

**Review by idjevm — APPROVED** [review]
Tested locally and in the review URL! LGTM! Thanks !

**Review by galeza — APPROVED** [review]

**Review by joshmorel — APPROVED** [review]

**Pull request merged**
