### PR TITLE
Cypress e2e - Add cookie banner/logo POM files and refactor tests

### PR DESCRIPTION
**Pull request by jessica-lau**
### What does this pull request aim to achieve? 💯

Created cookie banner and logo POM files to be used across different tests to reduce repetition, and refactored existing tests.

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Review by TimeaKovacs86 — COMMENTED** [review]
Hi Jessica!

The code looks good to me.

I have checked out your branch and run the test suits locally, some of the tests are failing... even if those are mostly not the test you have been working on. 
Capture of all the test suites pass or fail result

Could you please check out if you get the same result, or I did something wrong...

One of the files you have been working on has failed tests: 

 e2eTests/signIn/signIn.spec.js  
 Here I found this: We don't get the appropriate error messages.

SignInSpecJS failed test1
SignInSpecJS failed test2
 
During manual testing I got the same result, so it's definitely development bug.

And there is another file where I found an other localization issue:

offerHelpQuestion spec js OrganisationOrOrganization fails

This is again just the difference between the GB/AM English differences... the test is written with Organization and it fails cause here in my location it is Organisation..

Anyway... You did a great job here!

**Comment by galeza** [comment]
Hi @TimeaKovacs86 

I checked on docker-compose and all tests passed:
Screen Shot 2020-10-23 at 22 03 39

What commits do you see after git log? Maybe something was compiled not correctly? 
When you run using cypress runner - in settings change browser language to EN-US.

**Review by galeza — APPROVED** [review]
LGTM

**Comment by galeza** [comment]
@idjevm 

Please accept and merge :)

**Review by idjevm — APPROVED** [review]
LGTM! Thank you @jessica-lau

**Comment by jessica-lau** [comment]
@TimeaKovacs86 All the tests passed for me and I wasn't able to reproduce your errors. Do you have the backend server up when running the tests?

image

**Comment by TimeaKovacs86** [comment]
Hi Everybody! 

I changed the cypress browser language to EN-US as @galeza  suggested, and it works so that test passed, but I still have issues with the other tests. 

I run the tests on staging and had the same tests fail again. Both automated and manually. I checked out the latest version of the staging branch, for start up the application I used the "docker-compose down" and "docker-compose up --build" commands. And run the tests... It seems to me that the problem is the API calls, but it's specific on my computer.

 Is anybody ever had similar complication? Any suggestions? Thanks for the help.

**Comment by galeza** [comment]
> Hi Everybody!
> 
> I changed the cypress browser language to EN-US as @galeza suggested, and it works so that test passed, but I still have issues with the other tests.
> 
> I run the tests on staging and had the same tests fail again. Both automated and manually. I checked out the latest version of the staging branch, for start up the application I used the "docker-compose down" and "docker-compose up --build" commands. And run the tests... It seems to me that the problem is the API calls, but it's specific on my computer.
> 
> Is anybody ever had similar complication? Any suggestions? Thanks for the help.

@TimeaKovacs86 
I sent a a message on Slack

**Pull request merged**
