### PR TITLE
Added additional test for the About Us page Book a Call section

### PR DESCRIPTION
**Pull request by TimeaKovacs86**
### What does this pull request aim to achieve? 💯
I added an estra test to check if Book a Call button is visible and works properly on the About Us page

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

Hi! I added this test to the About Us page suit, however there is now higher selector to the new button than the xpath, so maybe if you could just add an id @galeza if it's possible, then it would be more consistent. Let me know, what you think. Thank you!

### CODE REVIEW

**Comment by jessica-lau** [comment]
@TimeaKovacs86 @galeza I created PR#[2152](https://github.com/FightPandemics/FightPandemics/pull/2152) to add an id for the Book Call button.

**Comment by TimeaKovacs86** [comment]
Hi Everyone! I did the needed changes, now that we have the ID! The updated test suit should pass! Let me know what you think! Thank you!

**Comment by jessica-lau** [comment]
@TimeaKovacs86 can you please update this branch with the latest staging? Thanks

**Review by jessica-lau — APPROVED** [review]
LGTM. I tested this locally after pulling the updates from staging. Tests passed.

image

**Review by galeza — APPROVED** [review]
Retested with staging URL. All tests passed.
LGTM

**Comment by TimeaKovacs86** [comment]
Yes, I had issues before using PyCharm pulling the changes from staging that's why when I am in a situation like this I usually test it  on the staging URL. Thank you for your help @jessica-lau, @galeza ! Should I ask someone else to review this PR so we can go forward and merge it?

**Comment by jessica-lau** [comment]
@ddveloper can you please merge this PR? Thanks!

**Comment by galeza** [comment]
Merging

**Comment by ddveloper** [comment]
sorry for my late response @TimeaKovacs86  @jessica-lau , code wise LGTM, thanks @galeza

**Pull request merged**
