### PR TITLE
Feature/1002 fix

### LINKED ISSUE #1002: Post Creation without a mandatory field
Steps to create:
-Login with valid userid,password.
-Goto profile.
-Select + symbol to create post.
-Select Individual/Organisation.
-When user left out any mandatory field required to create a post.(I suggest to add * to show the user the mandatory fields)
-User tries to click on post.
-There should be a pop up message saying "You have to Provide title/description{whichever the field the user left out)"
Screenshot_20200704-141106_Chrome

### PR DESCRIPTION
**Pull request by elba3184**
### What does this pull request aim to achieve? 💯

**Achieves:** Creates a red `error` message when the user is missing a field (title, description, or help tag). The `POST` button is already disabled if one of these fields are missing, however, it is not intuitive from the first use that the user could be missing a title or a description to proceed. The error message will disappear when the user fills in the respective field.

Steps to create:
- Login with valid user id and password.
- Go to profile.
- Select + (add) symbol to create a post.
- Select Individual or Organisation.
- When the user leaves out any mandatory field required to create a post, the error message will appear.
- User tries to click on the post.
- Post button will be disabled until all the fields are filled in. Errors for title, description and help tags will stay until the respective fields are filled in.

This PR resolves and closes issue #1002 

- [X] I have checked that no one else is working on similar changes.
- [X] I have read the latest [**README**](README.md) and understand the development workflow.
- [X] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix. The branch is created in a cloned version of this repo, **not a forked repo**.
- [X] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [X] There are no merge conflicts.
- [X] There are no console warnings and errors.
- [X] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

### CODE REVIEW

**Review by rabbi08 — CHANGES_REQUESTED** [review]
@elba3184 @tejasm2 
The error message are displayed at the initial stage only when user click '+' to add post. 
The error message should be displayed only if user miss to fill the specific required fields.

Refer below GIF
https://share.getcloudapp.com/QwukW0y1

**Comment by tejasm2** [comment]
> @elba3184 @tejasm2
> The error message are displayed at the initial stage only when user click '+' to add post.
> The error message should be displayed only if user miss to fill the specific required fields.
> 
> Refer below GIF
> https://share.getcloudapp.com/QwukW0y1

Yes agreed @rabbi08. But I think we should enable the "Post" button then. As the Post button remains disabled until all the details are filled, we have to show the error message at the very beginning only. If we have the Post button always enabled then in that case if a user does not fill some info and clicks the Post button, then we can show the appropriate error message. Maybe instead of showing the error message we can have asterisk mark in red for the required fields? Any suggestions @doheekim93 , @dhruvdpatel , @skrithiga , @emtay ?
Also I think the font size of the error message should match the rest of the font size.

**Comment by rabbi08** [comment]
> > @elba3184 @tejasm2
> > The error message are displayed at the initial stage only when user click '+' to add post.
> > The error message should be displayed only if user miss to fill the specific required fields.
> > Refer below GIF
> > https://share.getcloudapp.com/QwukW0y1
> 
> Yes agreed @rabbi08. But I think we should enable the "Post" button then. As the Post button remains disabled until all the details are filled, we have to show the error message at the very beginning only. If we have the Post button always enabled then in that case if a user does not fill some info and clicks the Post button, then we can show the appropriate error message. Maybe instead of showing the error message we can have asterisk mark in red for the required fields? Any suggestions @doheekim93 , @dhruvdpatel , @skrithiga , @emtay ?
> Also I think the font size of the error message should match the rest of the font size.

@tejasm2 
In such scenario we can mark these fields as mandatory using '*' sign and at the bottom of the post pop up define '*' Required fields. In this way user will know that these are mandatory fields to create a post.

**Comment by tejasm2** [comment]
agreed @rabbi08 , lets have it that way. cc: @elba3184

**Comment by skrithiga** [comment]
> > > @elba3184 @tejasm2
> > > The error message are displayed at the initial stage only when user click '+' to add post.
> > > The error message should be displayed only if user miss to fill the specific required fields.
> > > Refer below GIF
> > > https://share.getcloudapp.com/QwukW0y1
> > 
> > 
> > Yes agreed @rabbi08. But I think we should enable the "Post" button then. As the Post button remains disabled until all the details are filled, we have to show the error message at the very beginning only. If we have the Post button always enabled then in that case if a user does not fill some info and clicks the Post button, then we can show the appropriate error message. Maybe instead of showing the error message we can have asterisk mark in red for the required fields? Any suggestions @doheekim93 , @dhruvdpatel , @skrithiga , @emtay ?
> > Also I think the font size of the error message should match the rest of the font size.
> 
> @tejasm2
> In such scenario we can mark these fields as mandatory using '_' sign and at the bottom of the post pop up define '_' Required fields. In this way user will know that these are mandatory fields to create a post.

Agree with @rabbi08 here. A red * sign seems better visually than showing the error messages. In my opinion, we don't have to define the '*' as they will know they are required fields.

**Comment by elba3184** [comment]
> > > > @elba3184 @tejasm2
> > > > The error message are displayed at the initial stage only when user click '+' to add post.
> > > > The error message should be displayed only if user miss to fill the specific required fields.
> > > > Refer below GIF
> > > > https://share.getcloudapp.com/QwukW0y1
> > > 
> > > 
> > > Yes agreed @rabbi08. But I think we should enable the "Post" button then. As the Post button remains disabled until all the details are filled, we have to show the error message at the very beginning only. If we have the Post button always enabled then in that case if a user does not fill some info and clicks the Post button, then we can show the appropriate error message. Maybe instead of showing the error message we can have asterisk mark in red for the required fields? Any suggestions @doheekim93 , @dhruvdpatel , @skrithiga , @emtay ?
> > > Also I think the font size of the error message should match the rest of the font size.
> > 
> > 
> > @tejasm2
> > In such scenario we can mark these fields as mandatory using '_' sign and at the bottom of the post pop up define '_' Required fields. In this way user will know that these are mandatory fields to create a post.
> 
> Agree with @rabbi08 here. A red * sign seems better visually than showing the error messages. In my opinion, we don't have to define the '*' as they will know they are required fields.

Hi, everyone, so after speaking with @tejasm2, I'm just going to a simple message at the top, across from "Write your post here" to say " * Required fields". I'm also adding an asterisk * in all the required fields - perhaps in red.  My question is would you guys think the 'required fields' message would look better being in the regular black font color or do you want it in red? Same question for the asterisk. I know it's not that important, but I want to only have to commit it once and have it updated right away. Thank you all for your feedback!

**Comment by rabbi08** [comment]
> > > > > @elba3184 @tejasm2
> > > > > The error message are displayed at the initial stage only when user click '+' to add post.
> > > > > The error message should be displayed only if user miss to fill the specific required fields.
> > > > > Refer below GIF
> > > > > https://share.getcloudapp.com/QwukW0y1
> > > > 
> > > > 
> > > > Yes agreed @rabbi08. But I think we should enable the "Post" button then. As the Post button remains disabled until all the details are filled, we have to show the error message at the very beginning only. If we have the Post button always enabled then in that case if a user does not fill some info and clicks the Post button, then we can show the appropriate error message. Maybe instead of showing the error message we can have asterisk mark in red for the required fields? Any suggestions @doheekim93 , @dhruvdpatel , @skrithiga , @emtay ?
> > > > Also I think the font size of the error message should match the rest of the font size.
> > > 
> > > 
> > > @tejasm2
> > > In such scenario we can mark these fields as mandatory using '_' sign and at the bottom of the post pop up define '_' Required fields. In this way user will know that these are mandatory fields to create a post.
> > 
> > 
> > Agree with @rabbi08 here. A red * sign seems better visually than showing the error messages. In my opinion, we don't have to define the '*' as they will know they are required fields.
> 
> Hi, everyone, so after speaking with @tejasm2, I'm just going to a simple message at the top, across from "Write your post here" to say " * Required fields". I'm also adding an asterisk * in all the required fields - perhaps in red. My question is would you guys think the 'required fields' message would look better being in the regular black font color or do you want it in red? Same question for the asterisk. I know it's not that important, but I want to only have to commit it once and have it updated right away. Thank you all for your feedback!

@elba3184 
I would like to suggest that '*' sign should be in red, and should be on the fields text. Also, in "* Required fields"  the '*' should be red and text in normal regular black font.

**Comment by rabbi08** [comment]
@tejasm2 @elba3184 
I have rebuild the feature branch and tested it again. I have following observation:
- There are some conflicting files as shown in this ticket only, which need to be resolved on the latest code base.
- From feature testing perspective:
         - '*' should be in red color
         - 'Post' button should not be enabled until user enters the required data.

See below screenshot.

image

**Comment by rabbi08** [comment]
- As per @tejasm2 "So with this new change the "Post" button will always stay enabled, as we we r not showing the error message by default. The error will be displayed to the user after they clicks on the Post button, if at all anything is left to be filled"

Hence, as per that, I have observed that if user does NOT provide the required detail at the initial level the error is displayed, but if user enter the data and then delete it, OR select and then deselect a TAG, no error is displayed, NOR the post is created.

Please see below GIF.

ezgif com-gif-maker (46)

**Comment by Zaydme** [comment]
Steps to reproduce:
- start creating a post
- while all fields still empty, click "Post"
- error messages will appear normally.
- type in a title and a description.
- delete the title and the description.
image

another minor note:
a line break here would be nice
image

**Review by rabbi08 — CHANGES_REQUESTED** [review]
- After user enter and 'Delete' the post title -> click 'Post' : error as 'Undefined' is displayed. Refer below screenshot.

image

- After user enter 'Post Desc' and Delete it -> click 'Post' : No error is displayed to enter the description. Refer below GIF

ezgif com-gif-maker (52)

**Review by rabbi08 — CHANGES_REQUESTED** [review]
@wadehrarshpreet 
I have following observation while testing this feature:
- The error messages displayed are NOT user friendly i.e. 
Expected Result: 'Please enter title and description to create a post."
Actual Result: 'Title post.description'

- Same issue for 'Post TAG'selection

- After user enter all the required details, user is unable to create a post as nothing happens after user clicks on 'Post' button.

Refer below GIF showing above issues:
ezgif com-gif-maker (54)

**Comment by rabbi08** [comment]
As the post modal is under redesign, we can close this issue. 
Please reopen if this issue exist for new redesign of post fulfillment. Thanks

**Pull request closed without merging**
