### PR TITLE
#1436 - Header: update profile to be logged in user or Org

### LINKED ISSUE #1436: Header: Update Profile to be logged in user (Individual or Organization)
As a user who has both an individual and an organization profile, I want to clearly know when I'm acting as myself or as an organization.

In header, the "Profile" link should be the Individual's name when the individual user is selected.

image

https://www.figma.com/file/4cV84H1jyMo0rJEAl3HNnJ/FightPandemics-landing-page?node-id=17466%3A91934

In header, the "Profile" link should be the organization's name when the user has selected the organization profile.

(I don't have an organization, but it would show up here if I did)
dropdown

AC:
Given user only has individual profile,
When user is logged in
Then user's name should display in the upper right with down arrow to indicate they can modify their profile from this drop down.

Given user has an individual profile and an organization profile,
When user is logged in and has chosen individual profile
Then user's name should display in the upper right with down arrow to indicate they can modify their profile from this drop down.

Given user has an individual profile and an organization profile,
When user is logged in and has chosen organization profile
Then the organization's name should display in the upper right with down arrow to indicate they can modify their profile from this drop down.

### LINKED ISSUE #1470: Add authorization middleware to check user has right to act as organisation
This is backend work to support #1493

See also comment: https://github.com/FightPandemics/FightPandemics/issues/1432#issuecomment-683336966

Code improvement so we're not relating code when checking that user is authorized to act as or update an organisation.

### PR DESCRIPTION
**Pull request by shalinidc**
### What does this pull request aim to achieve? 💯
This PR is the FE for feature >> https://github.com/FightPandemics/FightPandemics/issues/1436.
_Please be concise and link any related issue(s):_

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix. The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

### CODE REVIEW

**Comment by joshmorel** [comment]
Thanks @shalinidc I'll take a look tomorrow. 

I think the best thing for all BE & FE work related to this is to merge/push all work into this one branch before merging into staging. This will touch so many things so merging just FE or partial FE could break existing functionality.

So I will open a PR into this one with my BE work + integration. If there is remaining FE work we can again open a new PR into this one or just push to this branch.

cc @davidoduk @emtay @tejasm2

**Comment by joshmorel** [comment]
I think this is good progress FE wise @shalinidc . 

However looking at this raises a few more product questions (@davidoduk @emtay @tejasm2 ):

1) When I switch users, do you want to navigate to the user's profile? This might make some things easier for us dev, but I don't think so. I can imagine most likely a user would see a post and then want to switch users to interact with that specific post as a specific org. In which case we'd want to stay on the same page.
1) Related to above I was planning to, when you switch users, have the feed reflect that user's location. So if an org has a different location than the user it would be different geo sorting. Can you confirm that you want this and if so I don't think we should refresh the feed immediately, because as with the above they are probably looking at a specific post and want to switch.
1) We are persisting logins (the authenticated individual user) but I didn't think about persisting who you are acting as. Do you want that to be persisted OR is it fine if visit later (or refresh the page) it goes back to the current user.
1) Also what about mobile design? We don't have a header on mobile it's a slide out navbar.

Another thought about acting as an org. I looked into how LinkedIn and Facebook does it and it's actually quite a bit more limited. You can do a lot as yourself but a lot less as a company (LinkedIn) or page (Facebook). Facebook actually used to have theirs like our current design but changed it so you can only switch context for certain interactions - e.g. like or comment on another page's post, instead of globally.

image

Not saying which is right or wrong for our own situation but maybe there is a good UX reason for not having the global toggle? Although more likely it is a business reason - see article here (Facebook never fully confirmed the rationale): https://www.socialmediatoday.com/social-networks/facebook-switches-page-management-and-posting-options-what-you-need-know

**Comment by davidoduk** [comment]
@shalinidc and @joshmorel , thanks for your work so far. See my answers to the issues you raised
1. Let's keep the user on the same post when they switch logins. 
2. Agreed, we shouldn't refresh immediately. Although the user and the org would ideally be in the same location, since the same user is also logging in as org - unless they manually select a different location for both and disable tracking.
3. What's the ~LOE on persisting as who they are acting as? If it's a small change, let's do it. 
4. I haven't looked into the mobile side of things. Let me do that and get back

I did consider how facebook does it and I see the logic behind their method. There are not a lot of things you can do on our platform besides posting, liking and sending messages. On facebook there are a lot more actions such as create and join groups, create events, marketplace, so it makes sense to limit the Organizations options. Also seems more complicated technically? 
Instagram does it similar to ours in that it treats the org and the user as 2 different accounts and you have to switch from one to the other to see/do anything.

**Comment by emtay** [comment]
@joshmorel @davidoduk  + 1 for david's response!

as mush as possible, we should ideally persist whichever user indiv or org was selected last if we're able to track/authenticate that they're still logged in. 

we should not reload the page or change location in same session if they toggle on the feed/helpboard page.

agreed on having both users have all functionality at this point. in future for our platform, organizations may actually get more functionality than individuals based on features for running an organization- so we will have to see how to best manage that over time.

**Comment by joshmorel** [comment]
Thanks @davidoduk - that all sounds good. Persisting the selected organisation shouldn't be too much harder. Not sure if we should in the cookie or localStorage (there is no XSS security concern unlike JWT with localStorage). We can start with localStorage for now @shalinidc .

@shalinidc - as per not changing where the user is that's the big change for now for your work. All we want to do is change the selected org not go to their profile. Let me think a bit more about the selected org persistence approach but if you have an idea please share or even go ahead and implement.

I will check out Instagram approach.

**Comment by shalinidc** [comment]
@joshmorel thank you for reviewing and localStorage for persisting the state = sounds good for now. 👍 

1 ques @joshmorel @davidoduk , We can definitely keep the user on the same post when they switch logins. But how will they go to the profile when they really need to edit something on their profile?

**Comment by joshmorel** [comment]
@shalinidc I think it's the profile button in the dropdown that would have its link updated. https://user-images.githubusercontent.com/66698276/92244584-bb427080-eee0-11ea-959a-6fd0479e7639.png

**Comment by davidoduk** [comment]
@shalinidc , if they're logged in as the organization and click profile, then it takes them to the org's profile page. If they are logged in as the user, it takes them to their individual profile page

**Comment by shalinidc** [comment]
Thanks, @joshmorel @davidoduk. In the recent commit, I removed the profile links from the current user and org menu item so the user will not be navigated to the profile. Clicking on the profile will take the user to the acting user/org profile.
I will work on persistence over the weekend. 
@joshmorel Please do let me know if you have any new/better ideas for state persistence. I am going to do some research as well when I start working on it.

**Comment by emtay** [comment]
@shalinidc can you send a screenshot of what you're seeing? as @davidoduk mentioned, when clicking on "Profile" they should go to whichever profile is connected to the account they have selected:

Individual ✔️ > edit individual profile
Org 1 ✔️ > edit org 1 profile

etc.

**Comment by joshmorel** [comment]
I'm going through process of integrating backend with other required changes there. There is a lot, to do and some weird idiosyncrasies on certain pages based on how they were implemented at the time so may be best for me to take it from here. (thanks @shalinidc I think this will work - you can still work on profile link as per @emtay 's comment above).

Correspondingly there are **a lot of** changes on the frontend to make this work, so I want to get this right so we don't have to undo things due to misunderstandings. So a few things to confirm @tejasm2  @davidoduk @emtay. It is best that we address all these now the way we want to rather then leaving it to a future issue/PR to decide based on the current and potential future implementation.

1. Currently if I'm on my own profile page I can of course edit it. But if I'm acting as an organisation, should these be hidden? 
image
2. Similar for being on organisation page. Currently I can edit if it's an organisation I own. Should it only be such if I'm acting as that organisation? In other words, if I'm still my own user or a different organisation. They are hidden?
image
3. On my own profile it shows "My Activity" while it is just "Activity" (see screen captures above) on other people's profiles as well as any organisation profile. Should we just change them all to "Activity", or should it be "My Activity" when it's that profile I'm acting as?
4. If you create a post from the page's they are available on (feed, my own profile, an org I own's profile) you get this option to post as individual or organisation, if you click organisation you get a list that you own to pick as. Should we get rid of this and just make the profile you are acting as? 
image

**Comment by shalinidc** [comment]
sure @emtay. I am going to post a screen recording in f_loginasorganization slack group so that it's easier to follow.

**Comment by tejasm2** [comment]
> I'm going through process of integrating backend with other required changes there. There is a lot, to do and some weird idiosyncrasies on certain pages based on how they were implemented at the time so may be best for me to take it from here. (thanks @shalinidc I think this will work - you can still work on profile link as per @emtay 's comment above).
> 
> Correspondingly there are **a lot of** changes on the frontend to make this work, so I want to get this right so we don't have to undo things due to misunderstandings. So a few things to confirm @tejasm2 @davidoduk @emtay. It is best that we address all these now the way we want to rather then leaving it to a future issue/PR to decide based on the current and potential future implementation.
> 
> 1. Currently if I'm on my own profile page I can of course edit it. But if I'm acting as an organisation, should these be hidden?
>    image
> 2. Similar for being on organisation page. Currently I can edit if it's an organisation I own. Should it only be such if I'm acting as that organisation? In other words, if I'm still my own user or a different organisation. They are hidden?
>    image
> 3. On my own profile it shows "My Activity" while it is just "Activity" (see screen captures above) on other people's profiles as well as any organisation profile. Should we just change them all to "Activity", or should it be "My Activity" when it's that profile I'm acting as?
> 4. If you create a post from the page's they are available on (feed, my own profile, an org I own's profile) you get this option to post as individual or organisation, if you click organisation you get a list that you own to pick as. Should we get rid of this and just make the profile you are acting as?
>    image

1. I think we should hide the edit icon when a user is acting as an Org. The user should be allowed to edit the profile which he/she has currently chosen from the toggle in the menu bar.

2. Yes here too its should be hidden, same as the above.

3.Yes, I agree we should have it common for all profiles as 'Activity'. I dont know if we should have "My activity" for Orgs.

4. Yes agreed. We should mention in the create post modal the name with which the user is logged in. "Posting as ________"

What do u think @davidoduk @emtay ?

**Comment by shalinidc** [comment]
@joshmorel: @davidoduk & @emtay are good with the user/toggle and profile link. I have already pushed all the work to this branch. So now the pending task is to match the design as per the mockup. I am not familiar with ant design or styled-components, so I'll take a look into it and work on the styling accordingly. The attached Images are the comparision between the current UI and the expected design(from Figma).
image
image

**Comment by joshmorel** [comment]
@tejasm2 @davidoduk @emtay (cc @shalinidc ) I think there is an issue with the expected design from Figma.

Due to variable length name it is a bit jarring when the rest of the header moves around as you toggle. However, more importantly, If I (or my org) has a really long name it WILL break the header (soon) since we have 3 other new features wanting to use real estate there (see also my comment here - https://github.com/FightPandemics/FightPandemics/pull/1508). Not much space left in such a case, e.g.:

image

I suggest we replace it with the avatar - extremely common (scroll up to the navbar of site itself!). If they don't have a pic then we will have a replacement with initials. Open to alternate ideas.

**Comment by tejasm2** [comment]
Agreed @joshmorel , actually we had decided to keep it max 10 chars to display with ".." at the end of the name. But Avatar also seems to be a good idea. Maybe we can also have Avatar + 10 chars max. But I think only Avatar would be much better, keeping in mind that we might have more features coming up to display in menubar. Any suggestions @davidoduk @emtay ?

**Comment by emtay** [comment]
@tejasm2 yes, i agree that we can limit name. is 10 char max the best size? or can it be slightly longer? i think first name only works for individual and can limit chars for organizations.

perhaps we can add avatar later once that feature is done?

**Comment by tejasm2** [comment]
> @tejasm2 yes, i agree that we can limit name. is 10 char max the best size? or can it be slightly longer? i think first name only works for individual and can limit chars for organizations.
> 
> perhaps we can add avatar later once that feature is done?

Yup @emtay , 10 chars would be shorter, maybe we can have 15 or 20 chars? Yup first name would work for individuals but for that too the max size is 30 chars, so we might want to limit it. I think 20 chars for display should be fine. For avatars....I think its almost ready....but until its completely ready and tested...we can go ahead with only Name.

**Comment by emtay** [comment]
@davidoduk @tejasm2 who was the designer? maybe we can get their input on char limit?

**Comment by joshmorel** [comment]
@tejasm2 (cc @davidoduk @emtay) Going back to this one:

> 
> 3.Yes, I agree we should have it common for all profiles as 'Activity'. I dont know if we should have "My activity" for Orgs.
> 
> Yes agreed. We should mention in the create post modal the name with which the user is logged in. "Posting as ________"
> 

So basically this would make this 5-step create post form redundant? (see: https://www.figma.com/file/4cV84H1jyMo0rJEAl3HNnJ/FightPandemics-landing-page?node-id=1628%3A12584)

image

The only ones we would really would then need are "Post Form" (below) & success screen, no? 

image

What I'm starting to struggle with with this feature, is this would affect a lot of the existing FE code base related to feed/post/comment and also, to be frank, our FE code has become a bit of a mess with duplication and hard to reason about code (I think maybe because we've had so many different contributors adding/updating one feature at a time :man_shrugging: ?)

We could either as part of this: 

1) Implement some code refactoring including the entire post form thing
2) Just apply this to what you can't currently do as an org - namely liking posts & commenting on posts. We'll leave everything else the same _for now_. 

The latter is lower effort but would have an inconsistent feel and may lead to more code debt. The former seems like a good idea but it will be a tough slog. 

Thoughts also  @kterry1 @idjevm @OzkanAbdullahoglu @shalinidc  from frontend code base perspective?

**Comment by OzkanAbdullahoglu** [comment]
@joshmorel So far as I understand this will trigger a significant amount of change over the code in a couple components & pages. I think we should go with the tough slog and with a well-planned refactoring work.

On the other hand;

> Thanks, @joshmorel @davidoduk. In the recent commit, I removed the profile links from the current user and org menu item so the user will not be navigated to the profile. Clicking on the profile will take the user to the acting user/org profile.
> I will work on persistence over the weekend.
> @joshmorel Please do let me know if you have any new/better ideas for state persistence. I am going to do some research as well when I start working on it.

Why we did remove these links from items? After I chose the organisation name then I have to click the profile to go to the profile, It feels better to directed to the profile like in the staging state. 

And for state persistence, redux-persist should be considered maybe.

**Comment by joshmorel** [comment]
@tejasm2 @emtay or @davidoduk  (cc @shalinidc ) a few new things since I'm looking at this today.

I'm realizing the design you have here - https://github.com/FightPandemics/FightPandemics/issues/1436#issue-686466241 - is out of date to how we've changed the org list to a sub-menu. So I assume this would just be the same except the checkmark would go next to the org in the sub-menu? "Profile" becomes the "Acting User", "My Profile" becomes well we never decided just initials or avatar?

image

Another thing about the avatar/name question: 

> Yup @emtay , 10 chars would be shorter, maybe we can have 15 or 20 chars? Yup first name would work for individuals but for that too the max size is 30 chars, so we might want to limit it. I think 20 chars for display should be fine. For avatars....I think its almost ready....but until its completely ready and tested...we can go ahead with only Name.

Avatars will be ready before this so let's aim for avatars (I can use initials for now). 10/15/20 chars will never work unless we expand to a 2-level navbar for reasons I've outlined here: https://github.com/FightPandemics/FightPandemics/pull/1508

We just don't have enough header real estate for everything we are wanting to fit in there.

**Comment by joshmorel** [comment]
We've incorporated this work in another branch

**Pull request closed without merging**
