### PR TITLE
#1920 Tweak/fix digest emails

### LINKED ISSUE #1920: Notification - comments appear empty in digest emails
image

This is reproducible for a daily digest when there is a post that has no comment over the past day, but has other activity like likes and shares. For weekly and biweekly, the same thing would happen if the post has no comment over the past week or past two weeks respectively.

### PR DESCRIPTION
**Pull request by mannykary**
### What does this pull request aim to achieve? 💯

Resolves #1920 (empty comment in digest email). Also tweaked a few other things based on what I observed during dev testing:

1. Show post in email digest if the post has had likes or comments since the last digest. If the post only had shares, do not show the post.
2. If all posts in the email digest has had only share activities since the last digest, and no likes or comments, then do not send an email.
3. Do not show the share count in the post's link.

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Comment by mannykary** [comment]
Since this affects every review build, this can be tested on the review build that was created as part of my other PR: https://featureuse-npm-ci.fightpandemics.xyz

I have shared this [post](https://featureuse-npm-ci.fightpandemics.xyz/post/5fa850db82db1a001387bd68), and I expect the post author to receive a digest email tomorrow evening. I will not add another comment to this post so I would expect the email to appear correctly, without the empty comment in the email.

**Review by ddveloper — APPROVED** [review]

**Comment by rabbi08** [comment]
@mannykary 
Below is the screenshot from the daily digest email I got... here the comment is displayed for one of the post but not for second. 

image

**Comment by mannykary** [comment]
Yeah, so I made this fix after the daily email digest was sent today (it's always at 2am UTC). So we need to wait till tomorrow to verify.

**Comment by mannykary** [comment]
Actually I just realized I could just force the daily digest to run. I was able to verify that it now shows up correctly. I think we can just merge this into staging so that QA can verify tomorrow 11/26 after 2am UTC.

Screen Shot 2020-11-24 at 8 13 22 PM

**Comment by mannykary** [comment]
Actually I just realized I could just force the sync to happen. I now notice a new issue (the email is basically empty). I will fix this. 
Screen Shot 2020-11-24 at 8 17 10 PM

**Comment by rabbi08** [comment]
> Actually I just realized I could just force the sync to happen. I now notice a new issue (the email is basically empty). I will fix this.
> Screen Shot 2020-11-24 at 8 17 10 PM

Sure @mannykary we can. Thanks

**Comment by mannykary** [comment]
Okay! This looks better. It shows the post activity, but if there were likes/shares and no comments since the last digest, it won't show the "empty" comment text, just the the count of likes and shares as a link:

Screen Shot 2020-11-24 at 8 30 45 PM

**Comment by mannykary** [comment]
> Okay! This looks better. It shows the post activity, but if there were likes/shares and no comments since the last digest, it won't show the "empty" comment text, just the the count of likes and shares as a link:
> 
> Screen Shot 2020-11-24 at 8 30 45 PM

Although they can't actually see shares 🤔 . @Zaydme @nfranklin9 @ddveloper @CamilaArias - should we only show the link if there are only like and comment activities? I don't think it makes sense for the user to click on "View 2 share(s)" when they can't even see the shares on the post. On a related note, if the activities since the last digest are only shares, we probably shouldn't include that post in the digest.

**Comment by CamilaArias** [comment]
@mannykary imo
Only show the link for likes and comments
If only shares, don't show post

**Comment by mannykary** [comment]
> @mannykary imo
> Only show the link for likes and comments
> If only shares, don't show post

Alright, I updated the behavior so that a post is shown in the digest only if it has likes and comments on them since the last digest. If the post only had shares since the last digest, it is not shown. Also, the link should no longer show the share count.

**Review by ddveloper — APPROVED** [review]
LGTM

**Pull request merged**
