### PR TITLE
Feature/fix post num comments

### LINKED ISSUE #1191: number of comments should reflect Total number of comments ,when there are more than 5 comments and   'show more' button is displayed
Expected:number of comments should reflect Total number of comments ,when there are more than 5 comments and   'show more' button is displayed
Actual: for ex:  When there are 8 comments exist for a post, only 5 comments are displayed (number of comments also shown as 5)and rest of the comments are displayed with 'show more' option.  After clicking,'show more' then the total becomes 8.

Expected behaviour would be , total number of comments should be displayed even if the page shows fewer comments.
Need this fix for post->details page and My profile

From Feed , number of comments =8
image

From Details page
image

### PR DESCRIPTION
**Pull request by Naraujo13**
### What does this pull request aim to achieve? 💯

- Update  `GET /posts/:postId` to return the correct number of total comments for a post 
- Update `GET /posts/:postId` **not** return the list of comments.

Closes #1191

### CODE REVIEW

**Comment by joshmorel** [comment]
@Naraujo13 thanks this looks like it's working but on `/post/:id` page we need F/E to use this count as a base. Since I know you aren't too familiar F/E I can add a commit here. 

image

**Comment by joshmorel** [comment]
Unless @BMariscal you can work on the changes required in `client/src/components/Feed/Post.js`

This is not as straight forward as I thought and it might be easier for you since you worked on this before.

**Comment by nr431207** [comment]
@joshmorel I was working on the FE portion and have a fix for it, will push a commit soon :)

**Comment by galeza** [comment]
Hi @idjevm @Naraujo13 ,

I tested using https://featurefix-post-num-comments.fightpandemics.xyz/
LGTM, @sheeba1 please confirm that it works as expected

I have a question about View more comments button. I have 10 comments. First 5 comments is displayed and button Show more comments is displayed. I click Show more comments button and next 5 comments is displayed. There's no more comments but button Show more comments is still shown.  
If it's not in the scope of this PR, I'll open a new issue.

**Comment by sheeba1** [comment]
Need #1243  completed in order to fix the issue mentioned in this bug. Right now 'show more ' is displayed even when there are no comments

**Comment by galeza** [comment]
@rabbi08 @sheeba1 

I copied your comments to #1243 
My understanding is that this PR is for backend changes. @idjevm please confirm

**Comment by rabbi08** [comment]
> @rabbi08 @sheeba1
> 
> I copied your comments to #1243
> My understanding is that this PR is for backend changes. @idjevm please confirm

@galeza , I agree this is for 'Comments' count, so that is working as expected. Other issues of 'Show less' is different.

**Comment by idjevm** [comment]
So originally was meant to be for backend only but Sonia managed to get the FE change here as well!

**Pull request merged**
