### PR TITLE
rectify editing titles for Account/Profile/Notify

### LINKED ISSUE #1901: Mobile -> Notification-> The page title of the page 'Edit Notification' is NOT displayed correctly on mobile.
1. Open 'https://staging.fightpandemics.work/'
2. On MOBILE -> Login as valid user
3. Navigate to 'View Profile'-> 'Edit Notification'

Issue: You will observe that that the page title on mobile is 'EDIT profile' or 'Edit Org Profile' for ORG.
It should be 'Notification Preference' .

Refer below screenshot from mobile
IMG_4022

Below screenshot from Desktop
image

Query: Why the the heading is 'Email Notification' Can it be more related to 'Notification Settings/preferences'

### PR DESCRIPTION
**Pull request by ddveloper**
### What does this pull request aim to achieve? 💯
fix edit Account/Profile/Notification titles
_Please be concise and link any related issue(s):_
to fix issue #1901 

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Comment by Zaydme** [comment]
@ddveloper please add the "Edit security" link to the edit notifications page.
If you have a password secured account, and you are om "Edit notification" on desktop, you will notice that "edit security" disappears from the side.

**Comment by rabbi08** [comment]
@ddveloper 
As @Zaydme commented, on the desktop, when we select 'Edit Notification' -> Edit Security' doesn't show and vice-versa.

Though on mobile, the edit notification page looks fine.
Screenshot 2020-11-24 at 12 05 23 PM

**Comment by galeza** [comment]
Check page title on iOS and Samsung:
Screen Shot 2020-11-24 at 18 09 40
Screen Shot 2020-11-24 at 18 10 57

As stated above - on desktop missing Edit Notification' -> Edit Security' doesn't show and vice-versa.

**Comment by ddveloper** [comment]
Hi @galeza @rabbi08 I merged the changes to the staging, so other things can move on, the cross-link from Notification and Security is added, please have a check in the staging build and create a new issue if there is a relevant problem

**Pull request merged**
