### PR TITLE
Feature/e2e tests internationalisation

### PR DESCRIPTION
**Pull request by galeza**
Tests designed by Adora Pham.

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Comment by galeza** [comment]
@TimeaKovacs86 @jessica-lau 

When I run tests using docker-compose all tests pass:
Screen Shot 2020-10-16 at 13 55 26

But when I use cypress runner: ./node_modules/.bin/cypress open
My browser always opens with en-GB and two tests fail.

**Comment by galeza** [comment]
Header.spec.js
Screen Shot 2020-10-16 at 13 37 26

**Review by idjevm — CHANGES_REQUESTED** [review]
The formatting looks a bit odd, are you all using prettier in the cypress service too? If so, please be sure to run it...

**Comment by galeza** [comment]
@idjevm 
No we don't run it. I'll check how to do it for cypress. I saw this discussion on slack: https://fightpandemics.slack.com/archives/C010V0DDHLN/p1601247469038200

**Review by TimeaKovacs86 — APPROVED** [review]
Looks good for me

**Comment by galeza** [comment]
@TimeaKovacs86 

Could you check docker-compose? Language should be set correctly and tests should pass.
What do you see after ./node_modules/.bin/cypress open? For me it's always en-GB.

**Comment by TimeaKovacs86** [comment]
@galeza I run the test in local and I got the same result as you... the test fails, just like yours. My browser always opens with en-GB and two tests fail. 

I found this link: http://www.lukasjakob.com/how-to-set-browser-default-language-in-cypress/, not sure if it helps.

**Comment by adorapham** [comment]
@galeza Thank you for the Refactoring and make the codes a lot of better.

**Comment by jessica-lau** [comment]
Hey @galeza, I ran the tests on docker-compose and Cypress test runner and got complete passes for both. Probably because of my US location.

image

image

**Review by jessica-lau — APPROVED** [review]

**Comment by jessica-lau** [comment]
@galeza, below link suggests adding both "languages" and "language" properties in the commands file. Maybe try that and see if it makes a difference.
```
Object.defineProperty(window.navigator, 'language', { value: 'en-GB' });
Object.defineProperty(window.navigator, 'languages', ['en-GB']);
```

https://stackoverflow.com/questions/56791796/how-to-set-the-browsers-language-in-cypress-io-electron-chrome

**Review by idjevm — APPROVED** [review]
LGTM, besides that formatting that looks a bit odd on the header.js though. Do you want me to merge this @galeza ?

**Comment by galeza** [comment]
@TimeaKovacs86  @jessica-lau 

I found a solution for cypress runner. When cypress runner is up and we start tests using chrome -> open chrome preferences and change language to English - US. Now each time when tests run, it uses en-US settings:
Screen Shot 2020-10-18 at 17 39 23

For docker-compose solution that we use with:
`Object.defineProperty(_contentWindow.navigator, 'language', { value: 'en-US' }) `
works very well.

**Comment by galeza** [comment]
@idjevm 
Please merge. I'll add prettier plugin for cypress in a new PR.

**Pull request merged**
