### PR TITLE
#1940-Sorting Languages Alphabetically

### LINKED ISSUE #1940: Reorder languages in the selector menu
Items in the Language selector menu should be sorted alphabetically, as per the language's English name.
image

Just need to sort the index in this file in the correct order, and add in the comment that new languages should be added alphabetically as well.
https://github.com/FightPandemics/FightPandemics/blob/staging/client/src/locales/index.js

### PR DESCRIPTION
**Pull request by aditilamkhede**
### What does this pull request aim to achieve? 💯

_Please be concise and link any related issue(s):_

This PR resolves #1940

- [ ] I have checked that no one else is working on similar changes.
- [ ] I have read the latest [**README**](README.md) and understand the development workflow.
- [ ] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [ ] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [ ] There are no merge conflicts.
- [ ] There are no console warnings and errors.
- [ ] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [ ] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Comment by rabbi08** [comment]
@aditilamkhede 
Thanks for quick fix.
Verified on feature branch, This is looking great. Refer below screenshot.
image

Thanks

**Review by rabbi08 — APPROVED** [review]

**Comment by ddveloper** [comment]
@aditilamkhede how about using a sort function on the array? so we don't need to worry about the index order

**Comment by aditilamkhede** [comment]
> @aditilamkhede how about using a sort function on the array? so we don't need to worry about the index order

@ddveloper I was thinking about the same but I saw @CamilaArias comment that should just change order in index.js and add a comment for future additions. Let me know if we need to change this using sort function.

**Comment by ddveloper** [comment]
I think both ways are fine ; ) let's leave it like this

**Review by Zaydme — APPROVED** [review]
LGTM! Thanks @aditilamkhede

**Comment by CamilaArias** [comment]
Thanks @aditilamkhede!! ❤️

**Pull request merged**
