### PR TITLE
Add city and cloud GIF to the Landing page & adding new supporters logo on About Us page.

### LINKED ISSUE #1879: Add city and cloud GIF to the Landing page & adding new supporters logo on About Us page. Rectifying a bug on mobile edit account/profile not clickable.
- [ ] Adding the City GIF and cloud GIF to landing page. (Only for Desktop version)
-------------------------------------
- [ ] Need to add new logos of supporters on the About Us page. Here is the [design](https://www.figma.com/file/83ZXBNA53FN605ExJZKVBs/About-Us-web-page?node-id=2%3A3422)

- [Vowel](https://www.vowel.com/) & [PCloud](https://www.pcloud.com/) as current supporters.

- [Panvala](https://panvala.com/), [Token Engineering Commons (TEC)](https://tecommons.org/) & [Silkey](https://silkey.io/) as Lifetime supporters.

- Move Nebula from Lifetime to Current supporters.

-----------------------------------------
- [ ] Make the "Edit Account" and "Edit Profile" buttons entirely clickable in the mobile version.

### PR DESCRIPTION
**Pull request by wadehrarshpreet**
### What does this pull request aim to achieve? 💯

_Please be concise and link any related issue(s):_
Add city and cloud GIF to the Landing page & adding new supporters logo on About Us page.

#1879 

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Review by Zaydme — APPROVED** [review]
LGTM! amazing job as usual @wadehrarshpreet 
I just don't like the gif quality itself, I wonder if we can get rid of the white borders, but I guess it's fine
image
image

**Comment by wadehrarshpreet** [comment]
> LGTM! amazing job as usual @wadehrarshpreet
> I just don't like the gif quality itself, I wonder if we can get rid of the white borders, but I guess it's fine
> image

@tejasm2 provide this gifs, I just reduce the frame to half to reduce the size from 8.1MB to 4MB.
The main issue is loading about 5MB gif at the homepage, which increases the load time🕒.

**Comment by Zaydme** [comment]
I can't find original files in Figma

**Comment by tejasm2** [comment]
@Zaydme the files are on slack will send those to u. Yes the white border isn't looking good. If we get it corrected from some designer by tomorrow then maybe we can go ahead, or else we will remove the Gifs.

**Comment by galeza** [comment]
@tejasm2 
Could you send those files to QA. Should we check only added new supporters logo?

**Comment by Zaydme** [comment]
Sad to see that go but乁( . _ . )ㄏ
@tejasm2 are we good to merge this now?

**Comment by tejasm2** [comment]
@galeza we dont have the updated GIF, so had to revert that. For now we just have added logos on about us page. I think we r good to go with this one @Zaydme

**Comment by galeza** [comment]
> @galeza we dont have the updated GIF, so had to revert that. For now we just have added logos on about us page. I think we r good to go with this one @Zaydme

ok. Thank you for info.

Tested on mobile as well (Samsung)
Looks ok.

**Review by galeza — APPROVED** [review]

**Pull request merged**
