### PR TITLE
Localisation: code updated to incorporate 3 new languages added to localisation

### LINKED ISSUE #2071: Localisation: Add 3 New Languages [Hindi, Marathi, and Spanish (Latin America)]
Please add the languages listed below to our platform. The instructions to do so are:
- Edit `client/src/locales/index.js` and `client/src/locales/languages.js` . You will need to import the correct file in `index.js` and also add the language and ISO code to the `localization` and `MENU_MAP` objects.
- Assign the unique ID (listed in the table below) to the new language for GTM (Google Tag Manager) tracking purposes. The ID should be prefixed with `NAV_LS_` followed by the ISO code used in previous step. (Reference [this ticket](https://github.com/FightPandemics/FightPandemics/issues/1611) to see how it has been done previously)

### New 3 languages to be added:
| Language           | ISO code | GTM ID suffix |
|--------------------|----------|------|
| Hindi (India) | hi_IN | _HI_IN |
| Marathi (India) | mr_IN | _MR_IN |
| Spanish (Latin America)    | es_419 | _ES_419 |

### PR DESCRIPTION
**Pull request by aditilamkhede**
### What does this pull request aim to achieve? 💯
This PR will incorporate 3 new languages added to localisation(Hindi, Marathi and Spanish(es_419))

_Please be concise and link any related issue(s):_ This PR Resolves #2071 

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Comment by doheekim93** [comment]
Hey @aditilamkhede, could you double check what what the GTM ID for the Spanish (Latin America) one is please? It shows up as "NAV_LSundefined" when I look at the inspect elements. Thanks!!

Screen Shot 2020-12-14 at 3 13 53 PM

**Comment by aditilamkhede** [comment]
> Hey @aditilamkhede, could you double check what what the GTM ID for the Spanish (Latin America) one is please? It shows up as "NAV_LSundefined" when I look at the inspect elements. Thanks!!
> 
> Screen Shot 2020-12-14 at 3 13 53 PM

@doheekim93 I will check and get back to you.

**Review by doheekim93 — APPROVED** [review]
Looks good to me (at least from the build URL)!!

**Comment by aditilamkhede** [comment]
@adorapham @doheekim93 @Zaydme @Juan-Moctezuma I can fix #2073 along with this fix. Let me know if I should proceed.

**Comment by Zaydme** [comment]
@aditilamkhede please wait for a response from @Juan-Moctezuma the assignee as he might be working on it.

**Review by rabbi08 — CHANGES_REQUESTED** [review]
@aditilamkhede 
1. As the language list is getting long in the dropdown, it scrolls the whole page, can we add scroll in the language menu dropdown, to scroll languages rather than page scrolling as in below GIF.
ezgif com-video-to-gif-2

**Comment by aditilamkhede** [comment]
> @aditilamkhede please wait for a response from @Juan-Moctezuma the assignee as he might be working on it.

@Zaydme yes, @Juan-Moctezuma is working on the issue, we had a conversation on slack and he is working on it.

**Comment by aditilamkhede** [comment]
> @aditilamkhede
> 
> 1. As the language list is getting long in the dropdown, it scrolls the whole page, can we add scroll in the language menu dropdown, to scroll languages rather than page scrolling as in below GIF.
>    ezgif com-video-to-gif-2

@rabbi08 I will look into it, later this week.

**Comment by rabbi08** [comment]
> > @aditilamkhede
> > 
> > 1. As the language list is getting long in the dropdown, it scrolls the whole page, can we add scroll in the language menu dropdown, to scroll languages rather than page scrolling as in below GIF.
> >    ezgif com-video-to-gif-2
> 
> @rabbi08 I will look into it, later this week.

@aditilamkhede 
we have to release this in PROD by tomorrow so need to merge it into STG by today. Great if we can solve this on priority. Thanks

@doheekim93 
Kindly see if we still can go with this open issue. Thanks

**Comment by aditilamkhede** [comment]
@rabbi08 is it possible to open a new issue for scrolling and merge that later this week and assign it to me. And merge existing changes for now?
I am just busy today and won't have time to look into it.

**Comment by doheekim93** [comment]
@aditilamkhede Yes, we just discussed during the release meeting to merge this PR and I will create a new ticket (and assign you to that one) for the scroll issue. Thanks!

**Review by rabbi08 — APPROVED** [review]
We will fix the scroll issues in another ticket, currently lets merge the languages. Thanks

**Review by Zaydme — APPROVED** [review]
LGTM! thank you @aditilamkhede!

**Comment by aditilamkhede** [comment]
@Zaydme , @rabbi08 and @doheekim93 Thanks for the update!! Will look into it and update you all.

**Pull request merged**
