### PR TITLE
Rearranged Profile dropdown menu

### LINKED ISSUE #1369: Not able to logout if user has more than 10 organisation.
Environement: Staging
Device used:Dell (Windows os)
Browser:Google Chrome
Steps to create:
1.Login with valid user name and password.
2.Create 10 Organisation under the profile.
3.Click on profile.
Expected Result:
Able to see all the item in the list/Able to scroll to access all the item in the list.
Actual Result:
Not able to access logout in the menu.Not able to scroll as well.
Logout

### PR DESCRIPTION
**Pull request by Serhazor**
### What does this pull request aim to achieve? 💯
Resolves #1369
_Please be concise and link any related issue(s):_

- [ ] I have checked that no one else is working on similar changes.
- [ ] I have read the latest [**README**](README.md) and understand the development workflow.
- [ ] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix. The branch is created in a cloned version of this repo, **not a forked repo**.
- [ ] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [ ] There are no merge conflicts.
- [ ] There are no console warnings and errors.
- [ ] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

### CODE REVIEW

**Review by adisen — APPROVED** [review]
LGTM. But I think we'll have to find a better solution for the issue this is trying to solve. Cause I think the signout should be the last item.
]

**Comment by Serhazor** [comment]
> LGTM. But I think we'll have to find a better solution for the issue this is trying to solve. Cause I think the signout should be the last item.
> ]

yep, I think that having a sliding out "Ogranisations" menu with "Add organisations" and "Ogranisations list" would looks better. Perhaps this can be done in later development stages.

**Comment by Joeu** [comment]
Yes, the sliding out menu for the organizations list and the fixed at bottom SignOut button is the better approach. Maybe we should open other issue proposing this.

**Comment by galeza** [comment]
@Joeu 
Will you open this issue? If not, just let me know and I'll do this. I like this idea of having sliding menu and logout at the bottom.

**Review by galeza — APPROVED** [review]

**Comment by Serhazor** [comment]
> @Joeu
> Will you open this issue? If not, just let me know and I'll do this. I like this idea of having sliding menu and logout at the bottom.

Please assign to me, I am looking in to how to do that right now.

**Comment by Serhazor** [comment]
> @Joeu
> Will you open this issue? If not, just let me know and I'll do this. I like this idea of having sliding menu and logout at the bottom.

created this:

image

**Comment by idjevm** [comment]
> > @Joeu
> > Will you open this issue? If not, just let me know and I'll do this. I like this idea of having sliding menu and logout at the bottom.
> 
> created this:
> 
> image

I think this would work AMAZINGLY! Thank you so much @Serhazor ! Please others, add comments, and let us know what do you think about this menu that will popup to the side?

**Review by idjevm — CHANGES_REQUESTED** [review]
Could you push that sliding out the organizations implementation? We could revert it easily from this PR if it is not a good idea, but I think it is the best one so far!

**Comment by Serhazor** [comment]
> Could you push that sliding out the organizations implementation? We could revert it easily from this PR if it is not a good idea, but I think it is the best one so far!

Thanks. Pushed it.

**Comment by galeza** [comment]
Tested on desktop MacOs. It looks great!
Screen Shot 2020-08-27 at 11 01 19

**Comment by Joeu** [comment]
That's great! 
@Serhazor , can you remove this bottom margin after the logout option? I think the last element shouldn't have the border-bottom either.

**Comment by Serhazor** [comment]
> That's great!
> @Serhazor , can you remove this bottom margin after the logout option? I think the last element shouldn't have the border-bottom either.

removed the one you've requested and also above the "Add Organisation" and below last organisation in the list. I think it looks cleaner

image

**Comment by jessica-lau** [comment]
@Serhazor Just tested this and it looks awesome! Just wondering, is there a way to remove the bottom margin under the "Add Organization" like how you did with the margin under the Sign Out? The spacing on the bottom disappears after an organization is added but is visible when there isn't an existing list of organizations underneath.

image

image

**Review by jessica-lau — APPROVED** [review]

**Review by idjevm — APPROVED** [review]
LGTM! Thank you @Serhazor !

**Comment by Serhazor** [comment]
> @Serhazor Just tested this and it looks awesome! Just wondering, is there a way to remove the bottom margin under the "Add Organization" like how you did with the margin under the Sign Out? The spacing on the bottom disappears after an organization is added but is visible when there isn't an existing list of organizations underneath.
> 
> image
> 
> image

this margin is due to the separating line that has it (it's part of the "ant design" that is used for the menu). To get rid of the margin, we would need to get rid of that line, but then it might not look all that great when new organisation is added as there will be no separation between the list of organisations and "add organisation" list

**Pull request merged**
