### PR TITLE
added redirection to the main profile on save from edit account/profile

### LINKED ISSUE #861: Redirect to Main Profile page after the editing is complete and saved.
**Currently:**
When we click on “Save Changes” button on the Edit Profile/Edit Account Information page, it redirects to that same page. (Check the gif below).

**Expected:**
As a user, 
Given that I am on the Edit Profile page (same for Edit Account Information/ Profile Information),
When I fill up/edit  the required information and click on “Save Changes” button,
Then I should be redirected to the main profile page.

Edit profile redirection buggg

Main Profile Page:

Main Profile Page 0

### PR DESCRIPTION
**Pull request by idjevm**
### What does this pull request aim to achieve? 💯
This PR resolves #861 adding redirection on save to the main profile

### CODE REVIEW

**Comment by galeza** [comment]
Hi @idjevm 

I tested this build URL: https://featureredirect-from-edit-to-main-profile.fightpandemics.xyz.
When I edit my Profile and click Save I have: Failed updating profile, reason: Internal Server Error
Is this related to this change or is it something else?

**Comment by idjevm** [comment]
@galeza strange, I do not see this error from my end. Can you reproduce it and send me a gif or a video?

**Comment by galeza** [comment]
Retested with a correct user. 
I was redirected from 
1. Edit Account Information -> save -> to the Profile page
2. Edit Profile -> Save -> redirected to the Profile page

**Comment by indirabhowmick** [comment]
@idjevm - I just tested the functionality and looks good. I will get some feedback from other PM's and get back to you if any changes are needed.

**Pull request merged**
