### PR TITLE
Feature/172/style create post

### LINKED ISSUE #172: Create Post - Update Styling for Desktop
- [ ] Update current Create Post page styling for desktop.
Refer to the latest design in FIGMA under Desktop App MVP.
https://www.figma.com/file/4cV84H1jyMo0rJEAl3HNnJ/FightPandemics-landing-page?node-id=1377%3A8027

- [ ]  Designs need to be pixel perfect

Screen Shot 2020-05-18 at 6 19 13 PM

### LINKED ISSUE #405: Create Post desktop modals before Create Post
Create steps before displaying the Create Post Form

Refer to Figma section Post Creation:

https://www.figma.com/file/4cV84H1jyMo0rJEAl3HNnJ/FightPandemics-landing-page?node-id=1377%3A8027

### PR DESCRIPTION
**Pull request by limaneto**
Update Create Post steps before Create Post form on desktop to match Figma design

Close #405

### CODE REVIEW

**Comment by snowiesuet** [comment]
Just a general styling tip: please do not use position: absolute unnecessarily. This can cause issues in different browsers or platform. Flexbox is very useful here.

**Comment by limaneto** [comment]
> Looks really nice! Just a few things:
> 
> * Let's unlink issue #172 from this PR. That issue is for the Desktop UI for the Post Creation page, and not what you've implemented here.
> * Let's add media queries to show the mobile version of what you made:
> 
> Figma (mobile version):
> Screen Shot 2020-05-18 at 6 14 10 PM

hi Annie, I thought the task 172 also was meant to build the steps before the actual Create Post screen.

Also a question: I saw that in the project we also use antd mobile, should we use it? Or use media query? Should the task for mobile be a different ticket?

**Comment by limaneto** [comment]
> Just a general styling tip: please do not use position: absolute unnecessarily. This can cause issues in different browsers or platform. Flexbox is very useful here.

Nice, thanks, going to change in the next PR. In this case you mean the paragraph and the icon right?

**Comment by snowiesuet** [comment]
> > Just a general styling tip: please do not use position: absolute unnecessarily. This can cause issues in different browsers or platform. Flexbox is very useful here.
> 
> Nice, thanks, going to change in the next PR. In this case you mean the paragraph and the icon right?

Yes, thank you!

**Comment by anniegiang** [comment]
> > Looks really nice! Just a few things:
> > 
> > * Let's unlink issue #172 from this PR. That issue is for the Desktop UI for the Post Creation page, and not what you've implemented here.
> > * Let's add media queries to show the mobile version of what you made:
> > 
> > Figma (mobile version):
> > Screen Shot 2020-05-18 at 6 14 10 PM
> 
> yeah, we should probably break this task into smaller ones, the task 172 proved to be big for just one PR.
> 
> Couple of questions:
> 1 - I see that the project uses antd-mobile, should we use it, or use media query? Because there is the Modal componant in antd-mobile.
> 2 - Should the task for mobile be a different ticket?

Good idea, let's create a separate issue for the version of this. I remember creating the mobile version of this, but I thought of refactoring it anyway. After some changes I think this PR can be merged!

**Comment by galeza** [comment]
Compared to Figma design (Continue Posting as Ind/Org, Posting as an Organization). Looks good.

**Pull request merged**
