### PR TITLE
Symptoms-Checker: Arrow Navigation Button fix - Feature/symptoms checker navigation

### LINKED ISSUE #1340: Symptoms Checker Navigation Buttons get hidden/inaccessible behind symptoms
Screen Shot 2020-08-07 at 9 13 02 AM

After starting the symptoms checker, the forwards and backwards navigation buttons get hidden behind the symptoms themself. Need to adjust them to adjust dynamically under the symptoms.

### LINKED ISSUE #1363: Symptoms-Checker [Desktop]: SC-Q3 Page Bugs
**Goal**

Fix the following bugs for SC-Q3 Pages for the Desktop view.

issue # 1 - Previous and Next Arrow buttons are overlapping with the symptom selections. (Mobile). Please add them into the bottom of the page that is visible.

### PR DESCRIPTION
**Pull request by ralbach**
### What does this pull request aim to achieve? 💯
closes #1340 
_Please be concise and link any related issue(s):_

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix. The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

### CODE REVIEW

**Comment by sheeba1** [comment]
> Build URL: https://featuresymptoms-checker-navigation.fightpandemics.xyz. Please wait a few minutes for the deployment to complete.

I am getting ,"503 Service Temporarily Unavailable", when accessing the build url

**Review by sheeba1 — CHANGES_REQUESTED** [review]
After JV did code rebase, manually accessed https://featuresymptoms-checker-navigation.fightpandemics.xyz/symptoms-check.  I tested the feature on windows, Chrome and Microsoft Edge and observed that the navigation buttons appear too low(for both maximize and restore down options) as shown below: Can we reposition the buttons to be clearly visible


image

**Comment by ralbach** [comment]
@sheeba1 This should resolve the issue on desktop. Rehauling the whole system for mobile so note there are a few bugs on mobile that will be resolved with a mobile issue soon.

**Comment by sheeba1** [comment]
@kterry1 , I am unable to access the build url , for the PR review. Please advise. Thanks!

**Comment by kterry1** [comment]
@ralbach Just following up on this one. You've pushed all necessary changes correct? I wanted to confirmed whether sure this was ready for another PR review or if you still needed more time.

**Comment by ralbach** [comment]
> @ralbach Just following up on this one. You've pushed all necessary changes correct? I wanted to confirmed whether sure this was ready for another PR review or if you still needed more time.

Yep! should be good to go.

**Comment by sheeba1** [comment]
What's the build Url for this? Thanks!

**Review by sheeba1 — COMMENTED** [review]
Tried re-triggering build, https://github.com/FightPandemics/FightPandemics/pull/1482#issuecomment-686791180. Still getting "503". Can someone please look into this

**Review by idjevm — CHANGES_REQUESTED** [review]
I will be careful here since you are modifying some components that are also being used elsewhere. Did you make sure that it doesn't mess up some of the styling where these are being used?

**Comment by rabbi08** [comment]
Temporary closing this PR & deleting the branch, but it will stay in 'Symptoms-Checker' as currently the priority for this feature is very low, hence trying to save some AWS credit by deleting the branches of low priority features.

Please feel free to re-open or create new when needed. Thanks.

**Pull request closed without merging**
