### PR TITLE
Merge rc/v1.1 into Master (easier than cherry picking all the commits we need) 

### PR DESCRIPTION
**Pull request by idjevm**
### What does this pull request aim to achieve? 💯

_Please be concise and link any related issue(s):_

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](https://github.com/FightPandemics/FightPandemics/blob/master/README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`** (need to have cloned the repo not forked).
- [x] This branch is rebased/merged with the **latest master**.
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

### CODE REVIEW

**Comment by joshmorel** [comment]
I'm good with it if this is fine with respect to "code freeze" concept - @vikjoshi ?

I think all these are pretty much qualify as hot fixes for soft launch. Going forward we just need to be more precise about what really is or isn't a hotfix for soft launch or not.

**Comment by vikjoshi** [comment]
> I'm good with it if this is fine with respect to "code freeze" concept - @vikjoshi ?
> 
> I think all these are pretty much qualify as hot fixes for soft launch. Going forward we just need to be more precise about what really is or isn't a hotfix for soft launch or not.

@galeza @rabbi08 @sheeba1 - can you take a look at the rc/v1.1 items that are being merged into master and let me know if you have any concerns with any of these from an E2E testing perpsective? @joshmorel and I both took a look at the issues and none of them seem to be large enough to cause us to have to go through full E2E testing again

**Comment by idjevm** [comment]
@vikjoshi so I have already shared the Build URL with Sheeba so now we just have to wait for them to at least scan this. I don't think it will be any breakable issue though, so I feel it should be fine merging this to master + it will give us some nice touch ups that we need.

**Comment by mannykary** [comment]
Build URL: https://rcv11.fightpandemics.xyz

**Comment by galeza** [comment]
lgtm
Button size retested on xiaomi red note 8 viewport 393 x 851 PX
Screenshot_2020-07-15-13-57-54-358_com android chrome
Screenshot_2020-07-15-13-58-29-175_com android chrome
Screenshot_2020-07-15-13-57-45-073_com android chrome
Screenshot_2020-07-15-13-57-37-431_com android chrome

Footer is correctly centered:
Screenshot_2020-07-15-13-54-18-641_com android chrome

Delete confirmation:
Screen Shot 2020-07-15 at 13 59 43

**Pull request merged**
