### PR TITLE
Rearranged Profile dropdown menu and moved Sign Out and Feedback up bef…

### LINKED ISSUE #1369: Not able to logout if user has more than 10 organisation.
Environement: Staging
Device used:Dell (Windows os)
Browser:Google Chrome
Steps to create:
1.Login with valid user name and password.
2.Create 10 Organisation under the profile.
3.Click on profile.
Expected Result:
Able to see all the item in the list/Able to scroll to access all the item in the list.
Actual Result:
Not able to access logout in the menu.Not able to scroll as well.
Logout

### PR DESCRIPTION
**Pull request by Serhazor**
…ore Add Organisation

### What does this pull request aim to achieve? 💯

_Please be concise and link any related issue(s):_

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [ ] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix. The branch is created in a cloned version of this repo, **not a forked repo**.
- [ ] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [ ] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

### CODE REVIEW

**Review by adisen — APPROVED** [review]
Lgtm

**Comment by galeza** [comment]
I assigned QAs but I don't see build URL.

**Comment by adisen** [comment]
I think the reason is thart the branch isn't named in the specified format

**Comment by idjevm** [comment]
I have DM Sergej, I will close this one up for now. Will reopen a new one soon.

**Comment by adisen** [comment]
Okay. Thanks JV

**Pull request closed without merging**
