### PR TITLE
fixed the refresh issue on reset filter during onboarding

### LINKED ISSUE #1640: After onboarding, can't reset filters via refresh
This is in all environments (prod, staging, etc), for both desktop & mobile (dev tools) views.
 
We are storing these answers in local storage so when you refresh they are still there. This doesn't make sense at all we should just store in app (in-memory) state redux/context so if you refresh the page they are not retained.

I don't think this is expected behaviour. Thoughts @rabbi08 @nivetheatha ?

There might be a relation in the resolution to this issue as well as #1629 & #1631 . These two were introduced recently but they all are related to a bad implementation of onboarding answers -> help board filters. 

retaining-filters-from-onboarding

### PR DESCRIPTION
**Pull request by mathigayathri2001**
### What does this pull request aim to achieve? 💯
refresh on reset filter will work correctly
_Please be concise and link any related issue(s):_
this PR resolves #1640 

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [X] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Review by joshmorel — COMMENTED** [review]
Thanks @mathigayathri2001 this does solve the issue although I don't quite know why.... :sweat_smile:  

I find it hard to reason about what's going on with the code for NeedHelp/OfferHelp pages going into the feed. 

The one problem is we get this massive history after going through onboarding, so need to click "back" many times. Not as bad as the existing issue but still not ideal - see:

too-much-history

**Comment by joshmorel** [comment]
FYI @rabbi08 - regarding your comment in #1640:

> Ideally browser refresh should retain user's last state. Thanks 

This resolution to the issue would not do that but instead reset to no filters on refresh.

If we want to retain that state we need to use query string params and that might require quite a bit of refactoring. Also that is not compatible with the work in progress for search (see: https://fightpandemics.slack.com/archives/C01949V0G6A/p1602679135080400?thread_ts=1602609425.074400&cid=C01949V0G6A)

My suggestion would be to create a new issue to migrate to query string params for filters & search after implementation of search that is not required for wide launch. CC @Zaydme @emtay

**Comment by joshmorel** [comment]
Looks good @mathigayathri2001 except the two unrelated changes to cypress test files:

https://github.com/FightPandemics/FightPandemics/pull/1661/files

**Comment by joshmorel** [comment]
> Looks good @mathigayathri2001 except the **two unrelated changes to cypress test files**:

Actually this isn't you. It's in other PRs as well. I don't know why GitHub is recognizing that as a diff...

**Review by joshmorel — APPROVED** [review]
Thanks for the fix @mathigayathri2001 !

We can look into using query string param for retaining filters in a future issue/PR after search is merged.

**Comment by joshmorel** [comment]
Definitely appreciate the work @mathigayathri2001 however we might have a more comprehensive solution to this and other issues with #1723 . I will put this to draft for now and revisit after we've merged that one

**Comment by rabbi08** [comment]
Closing this issue, please reopen if this issues appears again. Thanks.

**Pull request closed without merging**
