### PR TITLE
Production Release as on 02-10-2021

### PR DESCRIPTION
**Pull request by rabbi08**
### What does this pull request aim to achieve? 💯

_Please be concise and link any related issue(s):_

- [ ] I have checked that no one else is working on similar changes.
- [ ] I have read the latest [**README**](README.md) and understand the development workflow.
- [ ] The name of this branch is: **`feature/<branch_name>`** for a regular feature, **`hotfix/<branch_name>`** for a hotfix, and **`service/<branch_name>`** for a microservice, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [ ] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [ ] There are no merge conflicts.
- [ ] There are no console warnings and errors.
- [ ] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [ ] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Review by ddveloper — APPROVED** [review]
LGTM

**Review by TimeaKovacs86 — APPROVED** [review]
Looks good to me!

**Comment by adorapham** [comment]
Verify PR#2151, PR#2194 - Passed
image

**Comment by TimeaKovacs86** [comment]
Run the tests on staging with the result: 
regression tests on staging before release 10 february

**Review by jessica-lau — APPROVED** [review]
LGTM. Retested #2151 and #2194

**Pull request merged**
