### PR TITLE
Feature/1437 validation email

### PR DESCRIPTION
**Pull request by JayashreeSamantasinghar**
### What does this pull request aim to achieve? 💯
 Did changes in command.js  and added new test cases in joinNow.spec.js also added some .tlds  in fixture file  to review test for sign up for email validations .

_Please be concise and link any related issue(s):_

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [ ] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [ ] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Comment by JayashreeSamantasinghar** [comment]
Please review it for validation of email for join now.

**Comment by galeza** [comment]
@JayashreeSamantasinghar 
I would create a branch from staging. If not some checks will fail.
I sent you a message on Slack

**Comment by jessica-lau** [comment]
@JayashreeSamantasinghar yea I agree with @galeza, it looks like the files in this PR don't include the most recent updates from staging. Did you clone the repo?

**Comment by JayashreeSamantasinghar** [comment]
> @JayashreeSamantasinghar
> I would create a branch from staging. If not some checks will fail.
> I sent you a message on Slack

I think I have no permission to create branch. Ok I will again try to create branch and again resend PR

**Comment by JayashreeSamantasinghar** [comment]
> @JayashreeSamantasinghar yea I agree with @galeza, it looks like the files in this PR don't include the most recent updates from staging. Did you clone the repo?

Yes, I 'll again do cloning then

**Comment by idjevm** [comment]
Hey there, please DM so we can send this to the cloned repo and not the forked one. I can help you so you don't have to do anything crazy but just run a few commands. Closing this one for now.

**Comment by JayashreeSamantasinghar** [comment]
> Hey there, please DM so we can send this to the cloned repo and not the forked one. I can help you so you don't have to do anything crazy but just run a few commands. Closing this one for now.

ok Thank you @idjevm

**Pull request closed without merging**
