### PR TITLE
Client-side validation for login/signup and create user profile

### LINKED ISSUE #369: Client Side Error Handling for Web in User Authentication Flow
This ticket is kind of a catch all - basically going through the code and updating every situation of which there is possibility for a client error.

Current Behavior: Right now, I don't believe there is a current Behavior for error handling client side errors.
Expected Behavior: Using inline error messages to handle client side errors

### PR DESCRIPTION
**Pull request by robinv85**
### What does this pull request aim to achieve? 💯
Closes #369 
add client-side validation for login/signup and create user profile pages
integrated with the react-hook-form errors, currently hard coded validation messages, they can be replaced by translation strings later

### CODE REVIEW

**Comment by galeza** [comment]
Hi @robinv85 

I tested SignUp/SignIn scenario:
1. Empty email
2. Empty password
3. Empty confirmation password
4. Too short password
5. Passwords don’t match
6. Password length
Question: We have a validation for too short password. Should we set max? 
Currently very long password are accepted

**Comment by robinv85** [comment]
@galeza good question
I didn't spend time for more advanced validation, for the password, depending on the configuration on Auth0, we can also add more rules like "min. required special characters" for password strength... but I don't know how much max. character length is.

**Comment by galeza** [comment]
Hi @robinv85 

OWASP recommends max 64 characters (https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html)

**Comment by robinv85** [comment]
@galeza yes well Auth0 uses some of OWASP's recommendations but they have different settings
And our client-side validation, and API validation should match the one that is used on their side https://auth0.com/docs/connections/database/password-strength so I configured it as "good" which means 

> "at least 8 characters including at least 3 of the following 4 types of characters: a lower-case letter, an upper-case letter, a number, a special character (such as !@#$%^&*)."

but I just didn't want to spend too much time on these details yet, most important here is the general approach for client-side form validations I guess

**Comment by galeza** [comment]
Hi @robinv85 
128 max is ok.
One more question: we accept this email as valid
- "><script>alert(1);</script>"@example.org
 Security -> (XSS attacks)

**Comment by BMariscal** [comment]
> 
> 
> Since there are several error messages would it be cleaner to organize them in one central object and access errors from there?

Like an Enums file? I think that's a great idea @anniegiang

**Comment by anniegiang** [comment]
> > Since there are several error messages would it be cleaner to organize them in one central object and access errors from there?
> 
> Like an Enums file? I think that's a great idea @anniegiang

@BMariscal Yea, something like storing the errors as constants

**Comment by robinv85** [comment]
@BMariscal nope, I need to remove that console.log
@anniegiang I would prefer to keep it like this right now and later update it with translations, I see in other places people have added objects but I don't see an advantage here because it should all contain the name of the field (was discussed on slack in engineering channel) and if we add translations later it can just use function calls with translation strings and some replacement variables similar to `$t("validation.required", "email")`

**Comment by robinv85** [comment]
@galeza for the XSS vulnerability, the form input only sends this to the backend, which should be sanitized (and which is out of scope here) but React should be safe unless explicitly `dangerouslySetInnerHTML` is used https://reactjs.org/docs/introducing-jsx.html#jsx-prevents-injection-attacks

**Comment by robinv85** [comment]
@galeza I've added more detailed password validation for strong passwords, showing a message that it needs 3 of the 4 types of characters...
For the XSS I don't think it's a problem for now, if you think it is we can still open a ticket for it.

**Pull request merged**
