### PR TITLE
Cypress add logs for failed tests 

### PR DESCRIPTION
**Pull request by galeza**
Add cypress-failed-log plugin to gather more details about failed tests.

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Comment by galeza** [comment]
Hi,

I added a package: cypress-failed-log
Along with reports we will have failed logs saved in the directory: /cypress/logs
Log shows the test commands and details:
```
{
  "specName": "post.spec.js",
  "title": "Unauthorized user is redirected to SignIn page when clicking on Like button",
  "suiteName": "User opens Help Board",
  "testId": "r4",
  "testName": "FightPandemics Post for unauthorized user User opens Help Board Unauthorized user is redirected to SignIn page when clicking on Like button",
  "testError": "Timed out retrying: Expected to find element: `div.feed-posts > div:nth-child(1) > div > div > div:nth-child(1)`, but never found it.",
  "testCommands": [
    "visit feed",
    "xhr  GET http://client:3000/api/posts?includeMeta=true&limit=10&skip=0",
    "xhr  GET https://cdn.acsbapp.com/cache/app/client:3000/config.json",
    "get div.feed-posts > div:nth-child(1) > div > div > div:nth-child(1)"
  ]
}
```

**Review by jessica-lau — APPROVED** [review]
LGTM - got all the failed test logs to generate as expected. thanks!

image

```
{
  "specName": "post.spec.js",
  "title": "Unauthorized user is redirected to SignIn page when clicking on Comment button",
  "suiteName": "User opens Help Board",
  "testId": "r5",
  "testName": "FightPandemics Post for unauthorized user User opens Help Board Unauthorized user is redirected to SignIn page when clicking on Comment button",
  "testError": "Timed out retrying: Expected to find element: `div.feed-posts > div:nth-child(1) > div > div > div:nth-child(1)`, but never found it.",
  "testCommands": [
    "visit feed",
    "xhr  GET http://client:3000/api/posts?includeMeta=true&limit=10&skip=0",
    "get div.feed-posts > div:nth-child(1) > div > div > div:nth-child(1)",
    "xhr  GET https://cdn.acsbapp.com/cache/app/client:3000/config.json"
  ]
}
```

**Review by TimeaKovacs86 — APPROVED** [review]
Looks good! I have run the tests and got the failed ones logged as well. Just one question, I checked and the newest failed test log overwrites the previous, is it possible to add a time/date stamp to the filename or in the json file, just to be able to see which test failed when last time?
Cypress add logs for failed test working

**Comment by adorapham** [comment]
LGTM=I see logs folder with failed tests. Thank you 
image
image

**Review by adorapham — APPROVED** [review]

**Comment by galeza** [comment]
> Looks good! I have run the tests and got the failed ones logged as well. Just one question, I checked and the newest failed test log overwrites the previous, is it possible to add a time/date stamp to the filename or in the json file, just to be able to see which test failed when last time?
> Cypress add logs for failed test working

Hi @TimeaKovacs86 
Yes, the behaviour is the same as for screenshots. They are overwritten/deleted. In this case I can't add timestamp because this is a cypress **plugin** so we don't have an access to its code.

**Comment by galeza** [comment]
@idjevm 
If everything is ok, please merge :)

**Review by idjevm — APPROVED** [review]
There are some extra lines on the .gitignore file but it should be fine!

**Comment by TimeaKovacs86** [comment]
> > Looks good! I have run the tests and got the failed ones logged as well. Just one question, I checked and the newest failed test log overwrites the previous, is it possible to add a time/date stamp to the filename or in the json file, just to be able to see which test failed when last time?
> > Cypress add logs for failed test working
> 
> Hi @TimeaKovacs86
> Yes, the behaviour is the same as for screenshots. They are overwritten/deleted. In this case I can't add timestamp because this is a cypress **plugin** so we don't have an access to its code.

I was just curious! Thank you @galeza !

**Pull request merged**
