### PR TITLE
Lokalise: Translations update

### PR DESCRIPTION
**Pull request by jyclam**
This pull request was initiated by Lokalise (user Agnieszka Galeza) at 2020-11-10 23:12:51

### CODE REVIEW

**Review by Zaydme — APPROVED** [review]

**Comment by galeza** [comment]
@rabbi08 
Email was corrected.
@Zaydme 
Trailing comma is necessary. I double checked that.

**Review by rabbi08 — APPROVED** [review]
Looks good, we can merge. thanks

**Comment by rabbi08** [comment]
@galeza 
In STG -> About US page:
For Chinese, Polish, German, Spanish - translation
we have 'contact email : contact@fightpandemics.com'

But for 'American English and British English'
we have 'contact email : admin@fightpandemics.com'

In PROD we have 'contact@fightpandemics.com' on About US page for all translations.

Note: In zeplin design shared in PR #1577 it should be 'admin@fightpandemics.com'

Great if @tejasm2 @kchan335 can confirm the correct email.

**Comment by Zaydme** [comment]
@rabbi08 do we merge this or do we wait for confirmation about the email?

**Comment by rabbi08** [comment]
@galeza @Zaydme 
As confirmed by @tejasm2 the email for all languages should be-

contact@fightpandemics.com

Can you update this for all languages through this PR or we need to have another PR for other languages?

**Comment by galeza** [comment]
@rabbi08 
I will trigger a new PR

**Pull request closed without merging**
