### PR TITLE
fix: proper fetch after onboarding choices

### LINKED ISSUE #1629: Visiblity of the Post from different account
Environment-Staging
Device Used-Samsung S8
Browser-Google chrome
Steps to create:
1.Login with valid username and password.
2.Create a post as Individual-Request help (location :Bensaelem,Pa Visiblity:To state)
3.Log out.
4.Login with different account.
5.Choose offer help.
6.Choose "As a volunteer"
7.Provide location as "Bensalem,Pa"
Expected Result:
The post should be seen in the help board.
Actual result:
The post is not appeared in the help board.
Similarly for individual-offer help post ,org-req help post,org-offer help post also not visible when searched from different account .

### LINKED ISSUE #1631: Logged in user  and unlogged user gets different posts in the help board.
Environment -Staging 
Device used-Samsung s8
Browser-Google chrome 

Unlogged user
Offer help-->as a volunteer/as a donor-->only individual posts are shown
Offer help-->as a organization-->only organization posts are shown 
Logged in user
Offer help-->as a volunteer/donor-->both individual/organization posts are shown 
Offer help-->as a organization--> both individual/organization posts are shown

### PR DESCRIPTION
**Pull request by OzkanAbdullahoglu**
### What does this pull request aim to achieve? 💯
Resolves #1629 

_Please be concise and link any related issue(s):_

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Comment by joshmorel** [comment]
@nivetheatha can you confirm in https://featurefix-filters.fightpandemics.xyz/ I believe this resolves both:

* #1629
* #1631

Regarding #1631 it is now working like production but I don't this prod is working as originally intended (there should be a filter by Provider depending on option chosen). However, since this is not introduced as a regression to our desired deployment I'd say we create a new issue and fix later (maybe along with #1640 ).

**Review by joshmorel — APPROVED** [review]
LGTM Thanks @OzkanAbdullahoglu

**Comment by nivetheatha** [comment]
@joshmorel 
1.My post is visible when searched from different  account. 
2.Unlogged user,login user got the same results as individual post/organization posts shown in help board. 
Screenshot_20201013-115531_Chrome
Both works as expected.

**Comment by rabbi08** [comment]
Verified in feature branch as working fine. Thanks

**Comment by rabbi08** [comment]
Verified in STG, working fine, refer below screenshot.

image

image

**Pull request merged**
