### PR TITLE
feature/2135 text contrast #2135

### LINKED ISSUE #2135: [Desktop][STG][Front End][bug] Informational text under “Medical Help”, and “Other Help” label has low color contrast.
Environment:
macOS 10.14 Mojave
MacBook Pro (15-inch, Early 2015)
Browser: Firefox 78.6.1esr 
https://staging.fightpandemics.work/

Steps:
1. Navigate to https://staging.fightpandemics.work/
2. Login to FP
3. Click on profile initial icon on top left corner of page. and click “view your profile” option
4. Click on the pencil (edit) located on the left corner 
5. On the next page click on “Edit Account” option located on right side of page
6. Use [TAB] key to to navigate Edit Account page
7. Observe low color contrast on text-leaf  label (div) below the “Medical Help”, and “Other Help”

Expected Behavior: 
Informational text should be visible to every type of user (accessibility violation - color contrast ratio should be greater then 4.5<. (accessibility violation)

Actual Behavior:
 Informational text under “Medical Help”, and “Other Help” (div) label has low color contrast.  Actual ratio 3.07 Expected ratio 4.501< .

color-contrast FP

### PR DESCRIPTION
**Pull request by haoxianZ**
### What does this pull request aim to achieve? 💯

_Please be concise and link any related issue(s):_
Resolve #2135 

- [ X] I have checked that no one else is working on similar changes.
- [X ] I have read the latest [**README**](README.md) and understand the development workflow.
- [X ] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [ X] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [ ] There are no merge conflicts.
- [X ] There are no console warnings and errors.
- [X ] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [X ] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Comment by haoxianZ** [comment]
@ddveloper Hi, Could you please take a look of this pull? It says that it fail to build preview URL. I am wondering if this is a matter of having some sort of access to the organization. Thanks

**Comment by ddveloper** [comment]
it might be the issue of your branch name, try use `feature/...` instead and see if that can be built?

**Comment by haoxianZ** [comment]
hmm, the branch name has been feature/2135, what should I change it to?

**Comment by ddveloper** [comment]
> hmm, the branch name has been feature/2135, what should I change it to?

sorry I misunderstood the branch name, there should be something else ..., let me check

**Comment by ddveloper** [comment]
@haoxianZ it seems you're using forked repo instead of clone the repo directly, that's probably the reason (Thanks @CamilaArias  pointed this out 👍 )

**Pull request closed without merging**
