### PR TITLE
Feature/fix 1545

### LINKED ISSUE #1545: Org Profile page does NOT refresh, as the post of the selected ORG are not displayed.
1. Open "Staging.fightpandemics.com"
2. Log in using valid username/pwd
3.  Navigate to Help board-> click any random user profile to view -> Navigate to profile and click on any own Org to view the Org profile, following issues observed:

1. The navigation side bar doesn’t close after selection as it do, when user click on "Profile" to view its own profile.
2. So, now we have to clicks on ‘x’ to close navigation bar, you will observe that name of the users own org is displayed but the post displayed are from previous visited user profile. Hence the profile page for Org is not updated.

Refer below gif:
https://share.getcloudapp.com/eDuPW54K

Screenshot:
https://share.getcloudapp.com/nOun6RZn

Note: This issue exist on both desktop and mobile. Desktop screenshot
https://share.getcloudapp.com/xQuAPwDx

This issue might have been introduced due to pagination, #927, related PR #1274.

### PR DESCRIPTION
**Pull request by OzkanAbdullahoglu**
### What does this pull request aim to achieve? 💯
Resolves #1545 
_Please be concise and link any related issue(s):_

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix. The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

### CODE REVIEW

**Review by joshmorel — CHANGES_REQUESTED** [review]
Thanks @OzkanAbdullahoglu 

The noted issues are fixed but not for similar cases related to profile page.

Going from another user's profile to own profile does not change activity

activity-issue

No activity in individual user profile should also be empty at bottom

image

**Comment by rabbi08** [comment]
@OzkanAbdullahoglu @joshmorel

Verified below issues on the feature build:

1. The Org profile page refresh when Org is selected from the dropdown after viewing other profiles.: PASS
Refer below GIF
Mobile: https://share.getcloudapp.com/jkuDdeO7
Desktop: https://share.getcloudapp.com/bLuwzAeK

2. Filter Post -> Loading spinner on Mobile is working fine: PASS
Refer below GIF
https://share.getcloudapp.com/geuqv42q

3. The activity page is Blank for the individual user when there is no post to display: PASS
Refer below screenshot.
https://share.getcloudapp.com/7Ku8epEP

4. The "No post and create post" message is displayed for Org Profile as opposite behavior to the Individual Profile : FAIL
I would say we should leave the activity area for Org as BLANK just like for Individual profile.
Refer below screenshot.
https://share.getcloudapp.com/4guJQ12b

**Comment by OzkanAbdullahoglu** [comment]
> Thanks @OzkanAbdullahoglu
> 
> The noted issues are fixed but not for similar cases related to profile page.
> 
> Going from another user's profile to own profile does not change activity
> 

@joshmorel Thanks for your review. This one had come up to my mind too, but I couldn't reproduce the same error. I will look at that.

**Comment by joshmorel** [comment]
@rabbi08 I think the latest commits cover all reported issues. Can you retest?

**Review by joshmorel — APPROVED** [review]
LGTM

**Review by idjevm — APPROVED** [review]
LGTM !

**Comment by galeza** [comment]
I checked (on Android 10) individual and org profile without activity, there are blank, no message:
Screenshot_2020-09-25-15-46-30-692_com android chrome
Screenshot_2020-09-25-15-46-50-273_com android chrome 2

**Comment by OzkanAbdullahoglu** [comment]
@galeza it is requested to be blank in the above posts from @rabbi08, @joshmorel

**Comment by galeza** [comment]
@OzkanAbdullahoglu 
i just wanted to confirm that. I should've added PASS :)

**Review by galeza — APPROVED** [review]

**Review by rabbi08 — APPROVED** [review]
1. Profile page refresh after:
    a. user visit another user profile -> navigate to own profile
    b. user visit another user profile -> navigate to own ORG profile
    c. user visit own profile -> navigate to own ORG profile
Mobile:  https://share.getcloudapp.com/jkuDgYJJ
Desktop: https://share.getcloudapp.com/Z4uylyKZ

2. Filter for Post in Help board on mobile:
Mobile: https://share.getcloudapp.com/wbuPZKmb

3. Blank activity area is displayed when there is no post/activity exist for respective Individual.
https://share.getcloudapp.com/OAuJKWqn

4. Blank activity area is displayed when there is no post/activity exist for respective Organization.
https://share.getcloudapp.com/5zuw8ddL

Thanks

**Comment by OzkanAbdullahoglu** [comment]
> @OzkanAbdullahoglu
> i just wanted to confirm that. I should've added PASS :)

LOL, sorry I totally misunderstand. :)

**Pull request merged**
