### PR TITLE
Changed font-size static values in Heading to be from theme.js

### PR DESCRIPTION
**Pull request by snowiesuet**
### Quick Description of the PR
Changed the static values for `Heading` (#340 ) to use values from `theme.js`

### CODE REVIEW

**Comment by silenceway** [comment]
I'm seeing this error on my console:
> If you want to write it to the DOM, pass a string instead: block="true" or block={value.toString()}.
Related to
`<TextLabel
        block={true}
        color={DARK_GRAY}
        size={theme.typography.size.medium}
      >`
Please review.

**Comment by anniegiang** [comment]
> I'm seeing this error on my console:
> 
> > If you want to write it to the DOM, pass a string instead: block="true" or block={value.toString()}.
> 
> Related to
> `<TextLabel block={true} color={DARK_GRAY} size={theme.typography.size.medium} >`
> Please review.

Good catch, it's a weird warning. Just need to change the boolean  values for the props to be strings.

`<TextLabel block="true" color={DARK_GRAY} size={theme.typography.size.medium} >`

**Comment by snowiesuet** [comment]
Thanks for the catch! Changed the boolean values to string. @anniegiang @silenceway

**Comment by anniegiang** [comment]
> Thanks for the catch! Changed the boolean values to string. @anniegiang @silenceway 


Thanks for making the changes! But I'm seeing many unrelated commits that have already been merged. I think it's still safe to merge but this is my first time encountering a PR like this. @silenceway do you think it's safe to merge?

**Comment by snowiesuet** [comment]
Closing this and opening a new branch as there were some merge errors.

**Pull request closed without merging**
