### PR TITLE
Feature i18next

### PR DESCRIPTION
**Pull request by markthien**
### PR Checklist:

Hey there! It's great to have you here. Here's a quick checklist to help you make a shiny PR:

* [ ] Have you checked out the guidelines in our [Contributing](../CONTRIBUTING.md) document?
* [x] Have you looked if there might be other open [Pull Requests](../../../pulls) for the same update/change?

### Quick Description of the PR

What does it aim to achieve, and why?

### An Overview of the Changes

* A few notes on your commits.
* To help understand them.

### CODE REVIEW

**Comment by anniegiang** [comment]
Thanks for working on this!

Do you plan to add i18next for all the pages or just some?

**Comment by markthien** [comment]
> Thanks for working on this!
> 
> Do you plan to add i18next for all the pages or just some?

if ok then I can go ahead to change the rest. how should we let user change their language? should we provide some link/button/menu?

**Comment by anniegiang** [comment]
> > Thanks for working on this!
> > Do you plan to add i18next for all the pages or just some?
> 
> if ok then I can go ahead to change the rest. how should we let user change their language? should we provide some link/button/menu?

Since this will be a big task, we should ask what everyone thinks before proceeding.

**Comment by anniegiang** [comment]
@markthien I clarified with the product team and they said that page translations is not a MVP. They don't have designs available for page translations so we will need to hold off on doing this. 

But thanks for starting on it! I think it's a good idea and we could try again in the future.

**Pull request closed without merging**
