### PR TITLE
#2181- Fix inconsistencies in font in Greek Translation

### LINKED ISSUE #2181: Localisation - Fix font issue for Greek
As mentioned in #2166, we observed some font inconsistencies for Greek (different fonts seen on `About Us` and `Help Board`).

Example from `About Us`:
Screen Shot 2021-01-25 at 11 13 44 AM

We had a similar problem in the past because we didn't have all the correct weights of the font downloaded. Please refer to this [PR](https://github.com/FightPandemics/FightPandemics/pull/1868) to see if we can solve the issue in a similar way, thanks!

### PR DESCRIPTION
**Pull request by emanuelquerty**
### What does this pull request aim to achieve? 💯

Addresses issue with special glyphs appearing inconsistently when viewing the site in a different language due to not having the correct font weight imported. The problem, although similar to the one fixed by this [PR](https://github.com/FightPandemics/FightPandemics/pull/1868), was being caused by a different reason as fixed by bellow descripition:

- Adds sans-serif fallback to fix inconsistencies in font in Greek Translation

This PR resolves #2181 

_Please be concise and link any related issue(s):_

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`** for a regular feature, **`hotfix/<branch_name>`** for a hotfix, and **`service/<branch_name>`** for a microservice, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Review by doheekim93 — CHANGES_REQUESTED** [review]
Hey @emanuelquerty, the fix looks good on `About Us`, but still see the issue on `Help Board`. Could you check why we aren't seeing the fixes on the `Help Board`? Thanks!
Screen Shot 2021-01-27 at 8 59 19 AM

**Comment by emanuelquerty** [comment]
Hi @doheekim93!

Sorry I missed those fonts still looking different on the `Help Board`. The reason the fix didn't apply to them is that they are not using the css font definition in theme.js. They're using css rules in their component files, which still lack the fallback font fix that i've added in `client/src/constants/theme.js.` I have fixed some of them already and should fix the rest of them asap. 
Thank you!

**Comment by rabbi08** [comment]
@emanuelquerty 
Is this issue updated and ready for review. Thanks

**Comment by emanuelquerty** [comment]
Hi @rabbi08!
Yes the issue is updated and ready for review. I have fixed the `Help Board` that was pointed out by @doheekim93!
So everything should be good for review. Also, @doheekim93 the build url is back to working!

Thanks!

**Review by rabbi08 — APPROVED** [review]
Thanks @emanuelquerty 

Verified the fix on feature branch, it is working fine. Please see below screenshot.

Screen Shot 2021-02-08 at 11 43 09 AM

**Review by doheekim93 — APPROVED** [review]
@emanuelquerty Thanks for working on this fix!!!

**Pull request merged**
