### PR TITLE
fix: update source by fp org name to helpboard+

### LINKED ISSUE #1403: Update valid email address for "Sourced By FightPandemics" post <Discussion Pending>
In STG env:
- The email for "Sourced By FightPandemics" post is not valid and working. Mail delivery failure notification is received while trying to send email on this Org post.

Issue:

Address not found
--
Your message wasn't delivered to sourcedby-type-startup@fightpandemics.com because the address couldn't be found, or is unable to receive mail.

Currently, @joshmorel is discussing the solution for this one, looking this ticket to keep track. Thanks

### PR DESCRIPTION
**Pull request by joshmorel**
### What does this pull request aim to achieve? 💯

Resolves #1403

I will update the review DB with the updated script  

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix. The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

### CODE REVIEW

**Review by idjevm — APPROVED** [review]
LGTM!

**Comment by joshmorel** [comment]
@rabbi08  - can you check here if this is what is expected - https://featureuse-helpboard-at-fp-email.fightpandemics.xyz/organisation/5eff67aa7002103f35cfcaa0

If good I will merge into staging - then I need to run the script again to update the staging database.

**Comment by rabbi08** [comment]
> @rabbi08 - can you check here if this is what is expected - https://featureuse-helpboard-at-fp-email.fightpandemics.xyz/organisation/5eff67aa7002103f35cfcaa0
> 
> If good I will merge into staging - then I need to run the script again to update the staging database.

@joshmorel 
It looks fine as I am no longer getting failure notifications, when I send email on 'Sourced By' post. Just a quick question, is there a way if we can verify that the email is being received and replied?

**Comment by joshmorel** [comment]
> Just a quick question, is there a way if we can verify that the email is being received and replied?

For the sender we can set an auto-reply - "Thank you for your email. We will try to follow-up etc...". Need to be done on the email account side so we can ask Manu in Slack. Of course someone should actually be monitoring the address.

I will merge and ask Manu.

**Pull request merged**
