### PR TITLE
Moved the Accessibility widget up to avoid cookies banner

### LINKED ISSUE #1309: [Accessibility] Create standards for accessibility or use a third party
### We currently don't have any accessibility standards for our Product, Design, or Front End Engineering Team to follow. Although I don't have a lot of experience with accessibility, I've done a bit of research and it actually looks like it would be easier to just use a third party company that uses AI to add accessibility. 
---
### Here is a website I found that would do just that: https://accessibe.com/ and it would cover WCAG 2.1, Section 508, ADA Title III, and EAA/EN 301549. 

It's not free though, at **49/month**, so we may want to see if someone can reach out to them on whether they would provide a service for us at no cost. 

Any other ideas are welcome. This was created more to just get the conversation started.

### PR DESCRIPTION
**Pull request by kterry1**
### What does this pull request aim to achieve? 💯
Moves the Accessibility widget up to avoid the cookies banner

_Please be concise and link any related issue(s):_
It's already closed out but this is in reference to #1309

- [X] I have checked that no one else is working on similar changes.
- [X] I have read the latest [**README**](README.md) and understand the development workflow.
- [X] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix. The branch is created in a cloned version of this repo, **not a forked repo**.
- [X] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [X] There are no merge conflicts.
- [X] There are no console warnings and errors.
- [X] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

### CODE REVIEW

**Comment by rabbi08** [comment]
Tested on feature build, it is working fine. Thanks.

image

**Review by joshmorel — CHANGES_REQUESTED** [review]
Weird - I didn't even think about position before. The placement in Firefox is not working it's sticking with (default I guess) 20px for Firefox `bottom` but in Chrome it is 60px as you specified.

It will probably work fine for Edge/Safari as they use similar JS engine & non-standard features as Chrome these days.

We should report it back to them in the interim can we move to left bottom corner so it doesn't cover the Cookie X for firefox?

Firefox on top, Chrome dev tools below showing `bottom: 60px;`
image

**Comment by kterry1** [comment]
I moved it over and down. Should be good to go now.

**Review by joshmorel — APPROVED** [review]
Thanks. Okay on chrome/firefox desktop (+ mobile dev tools view) - I will merge now.

**Pull request merged**
