### PR TITLE
#1931 - Modify labels on post cards

### LINKED ISSUE #1931: Modify labels on post cards
Should be [**-> This <-**](https://www.figma.com/file/EMKcg0eTnOlr7bRZGFdnZu/Web-app-product-spec?node-id=145%3A328) (Link to Figma). Inspect on Figma for specs.
image

Current:
image

### PR DESCRIPTION
**Pull request by Zaydme**
### What does this pull request aim to achieve? 💯
Modify labels on post cards to look like this, (colors are the same but look different lol)
image

following this design:
img

_Please be concise and link any related issue(s):_
closes #1931

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Comment by rabbi08** [comment]
@Zaydme 
The page gets blank after user navigate to Help board. please see below GIF.
ezgif com-video-to-gif-2

**Comment by Zaydme** [comment]
@rabbi08 this issue is caused by another PR, please check slack

**Review by ddveloper — APPROVED** [review]
LGTM

**Comment by rabbi08** [comment]
@CamilaArias @Zaydme 
If we are updating the labels on the post card, then we should update the label design on 'Create Post' and 'Filters' too. 

Please see below screenshot.

Screen Shot 2020-11-29 at 1 15 10 PM

**Comment by CamilaArias** [comment]
@rabbi08 the problem the new label design is solving is that they looked clickable and they weren't, the filters are clickable so they should stay the same. These are labels. We'll probably also change the UI and UX of the filters in the future as well anyway but the labels will stay.

**Review by rabbi08 — APPROVED** [review]
Thanks @CamilaArias 

Verified the fix on feature branch, the labels are updated on the the post cards. Refer below screenshot.
Screen Shot 2020-11-29 at 1 48 53 PM

**Pull request merged**
