### PR TITLE
Feature/join org us4.1  2

### PR DESCRIPTION
**Pull request by ChunPingYang**
### What does this pull request aim to achieve? 💯
- GIVEN a signed-in user is on their profile page/screen WHEN they go to the ‘notifications’ page/screen, THEN they must see an additional toggle available named ‘Org Posts’ (Notification page already exists. Add app and org posts)
Done
- **Condition**: The ‘Org Posts’ toggle must be toggled off by default.
-Done
- **Condition**: The 'Org Posts' toggle must only be displayed to users who are current members of at least 1 or more organisation. Users who are not current members of organizations must not be able to see the toggle 'Org Posts' in their notification page/screen.
Done

- IF the signed-in user turns on the toggle “ Org posts”, THEN they must receive email notifications whenever the organization they are members of publishes a new post in the help board.
TODO
- IF the user turns off the toggle ‘Org Posts’ THEN they must not receive email notifications whenever the organisation they are members of publishes a new post in the help board.
TODO

_Please be concise and link any related issue(s):_

- [Y ] I have checked that no one else is working on similar changes.
- [ Y] I have read the latest [**README**](README.md) and understand the development workflow.
- [ Y] The name of this branch is: **`feature/<branch_name>`** for a regular feature, **`hotfix/<branch_name>`** for a hotfix, and **`service/<branch_name>`** for a microservice, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [Y ] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [Y ] There are no merge conflicts.
- [Y ] There are no console warnings and errors.
- [Y] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [Y ] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Comment by adorapham** [comment]
https://github.com/FightPandemics/FightPandemics/issues/2386  is passed for 
GIVEN a signed-in user is on their profile page/screen WHEN they go to the ‘notifications’ page/screen, THEN they must see an additional toggle available named ‘Org Posts’ (Notification page already exists. Add app and org posts)
Done

Condition: The ‘Org Posts’ toggle must be toggled off by default.
-Done

Condition: The 'Org Posts' toggle must only be displayed to users who are current members of at least 1 or more organisation. Users who are not current members of organizations must not be able to see the toggle 'Org Posts' in their notification page/screen.
Done

**Review by adorapham — APPROVED** [review]
validation with #2386

**Review by sarmahmili — COMMENTED** [review]
working as expected in mobile (safari, chrome, firefox).

**Comment by xJamesScott** [comment]
Already merged

**Pull request closed without merging**
