### PR TITLE
Feature/1230

### LINKED ISSUE #1230: An unlogged  user can access profile information(email,FB,etc) of another user through the user profile, from a post on View Board
summary/Issue: An unlogged  user can access profile information(email,FB,etc) of another user through the user profile, from a post on View Board

### PR DESCRIPTION
**Pull request by vsan626**
### What does this pull request aim to achieve? 💯
User is redirected to login page or sign up page when trying to access another users profile from help board

_Please be concise and link any related issue(s):_

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix. The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

### CODE REVIEW

**Comment by nivetheatha** [comment]
@idjevm unlogged user still able to view the profile information of the another user from the feed .Its not redirecting to login/signup page.
Am I missing something?

**Comment by vsan626** [comment]
> @idjevm unlogged user still able to view the profile information of the another user from the feed .Its not redirecting to login/signup page.
> Am I missing something?

@nivetheatha sorry about that. The condition was incorrect. please check now. Thank you!

**Comment by jessica-lau** [comment]
@vsan626 For some posts that I click on, I can view other users' info and then for other posts that I click on I am redirected to the sign in page. See below for examples.

Example of post where I can see other user's info without being signed in:

image

image

Example of post where I am redirected to sign in page:

image

image

**Comment by jpmitri** [comment]
was the first post made by an organization instead of a user?

**Review by rabbi08 — CHANGES_REQUESTED** [review]
As mentioned by @nivetheatha @jessica-lau 
I am also able to view the other user profile without being logged-in.

Non-logged-profile

**Comment by jpmitri** [comment]
@rabbi08 could you please send me a screen shot of the session storage found under (f12 , Application, Session Storage, feature1230)

**Review by jessica-lau — CHANGES_REQUESTED** [review]
I tested the same post as @rabbi08 and was not redirected to the sign in page as expected.

**Comment by rabbi08** [comment]
> @rabbi08 could you please send me a screen shot of the session storage found under (f12 , Application, Session Storage, feature1230)

Below are the values displayed while testing:
LocalEmergencyBox = true

image

After viewing 2 more profile without login, it ask me for login at NT profile and then:
afterlogintarget = 5f0e8fa50d472a160030b206

image

**Comment by jpmitri** [comment]
There is a flag that gets created when you log in and is set to false when you log off basically if you try to view any user profile if that flag is not set to true and dose exist the app should redirect you to the log in page but that is not true for the organization profile but i wonder is there a way to get from an organization profile to a user profile with out having to go thru the default function?

i will have to look into it tonight and see if i can find a loop hole since this worked with the scenarios we tested before issuing the pull request.

**Comment by vsan626** [comment]
@sheeba1 
@dhruvdpatel has verified this is working on my local machine
Below is the story from @sheeba1 

Per conversation with @joshmorel and @manualzuru :

1: Individual profiles require users to be logged in
2: Organization profiles can be viewed by logged in or not logged in

AC for individual profile:
Given user Is logged in
When user clicks on profile of another individual user
Then they see the other profile

Given user Is NOT logged in
When user clicks on profile of another individual user
Then they will be redirected to login and
Given they then log in, they’ll proceed to other user‘s individual profile (their original intention)

AC for organization profile:
Given user Is logged in
When user clicks on profile of another organization user
Then they see the organization profile

Given user Is NOT logged in
When user clicks on profile of another organization user
Then they see the organization profile

**Comment by rabbi08** [comment]
@vsan626 
As per the test scenarios mentioned above, I am still able to view the profile of Individual user. 

Please see, below screenshots of these 2 individual users:
https://share.getcloudapp.com/bLuRZw2o
https://share.getcloudapp.com/wbu7LPde

Please note thare are only 6 post of individual user in feature build: 
All Post -> Provider = 'Individual' : Apply Filter

Individual Users profiles:
- SJ : Able to view profile : FAIL
- TT: Able to view profile : FAIL
- AR: Need to login to view the Post : PASS
- NT: Need to login to view the Post : PASS (This is my account)

**Review by idjevm — CHANGES_REQUESTED** [review]
I'd say let's not update the dependencies or update the package-lock.jsoin. @joshmorel I think it is not necessary, but should we do it?

**Comment by rabbi08** [comment]
@vsan626 @idjevm 
I am still seeing "503 Service Temporarily Unavailable"

**Comment by joshmorel** [comment]
@rabbi08 the review instance is terminated after 1 day from running to mitigate against high AWS costs for running too many services in ECS.

But we can re-trigger a build (not sure if just admins or any repo member...) by going to:

1. Click "Checks" image
2. Click "Deploy Review Build" image
3. Click "Re-run jobs" > "Run-run all jobs" image

**Comment by joshmorel** [comment]
Anyways @rabbi08 it's up again.

**Comment by rabbi08** [comment]
> Anyways @rabbi08 it's up again.

Thanks @joshmorel .
will keep note of the instruction with me for future use.

**Comment by joshmorel** [comment]
@vsan626 cc @rabbi08 we need to add backend code to prevent non logged-in viewer from logging in - I noted in the issue https://github.com/FightPandemics/FightPandemics/issues/1230#issuecomment-684807548

---

If we can add this here to line 125 of `backend/lib/endpoints/users.js`. I'm suggesting a 404 error like Facebook does if the user opts to hide their profile from crawlers (and thus also non-logged users).

```javascript
      // Temporary code to return 404 if requesting user not logged in
      // eventually will be determined based on user privacy settings
      if (authUserId === null) {
        throw app.httpErrors.notFound();
      }

```

**Comment by joshmorel** [comment]
Are you still working on this @vsan626 @jpmitri ? I have someone I think can take over if not.

**Comment by vsan626** [comment]
Hi @joshmorel please go ahead and let the other volunteer take over

**Comment by joshmorel** [comment]
Thanks for the prompt response @vsan626 !

@emtay does it matter if we include the redirect stuff here? Maybe it's simpler if we just not have a link for a individual user profile & the visiting user is not logged in.

**Comment by rabbi08** [comment]
Closing this issue as low priority as of now. Please feel free to reopen if priority changes in future. thanks.

**Pull request closed without merging**
