### PR TITLE
Add gtm tags to NeedHelp flow

### LINKED ISSUE #988: Home Page and Nav Bar: Add ID attribute for elements on these pages
**Please make sure the id attributes are updated for the mobile version as well!!**

Please assign the following elements with the listed JSX 'id' attributes.

Please also note, when assigning id attribute, to assign it to the area that encompasses the entire button or element.
Example: not just the text "Next", but the entire button (including Next and arrow symbol)
Screen Shot 2020-07-03 at 6 43 37 PM

Why we need to assign unique IDs: [https://www.optimizesmart.com/event-tracking-in-google-tag-manager-v2-complete-guide/#:~:text=You%20will%20need%20this%20'id,not%20contain%20any%20white%20space.](url)

## Home Page
| #  | Element on page | JSX 'id' attribute |
| --- | --- | --- |
| 1. | Request Help Button | HP_RE |
| 2. | Offer Help Button | HP_OF |
| 3. | "View Community Posting" Button | HP_VHB |

|Desktop |  Mobile |
| --- | --- |
|   |   |

## Nav Bar
**For users _NOT_ signed in:**
| #  | Element on page | JSX 'id' attribute |
| --- | --- | --- |
| 4. | "About Us" Button | NAV_AU |
| 5. | "Feed" Button | NAV_HB |
| 6. | "Login" Button | NAV_SI |
| 7. | "Register" Button | NAV_JN |
| 8. | Feedback Icon | NAV_FDB |

|Desktop |  Mobile |
| --- | --- |
|   |   |

\
**For users signed in:**
_Please note:_ The buttons "About Us" and "Feed" here should have the same 'id' attributes as the above.
| #  | Element on page | JSX 'id' attribute |
| --- | --- | --- |
| 9. | "Add Organisation" Button | NAV_ADO |

|Desktop |  Mobile |
| --- | --- |
|   |   |

### LINKED ISSUE #990: Request Help: Add ID attribute for elements on these pages
**Please make sure the id attributes are updated for the mobile version as well!!**

Please assign the following elements with the listed JSX 'id' attributes.

Please also note, when assigning id attribute, to assign it to the area that encompasses the entire button or element.
Example: not just the text "Next", but the entire button (including Next and arrow symbol)
Screen Shot 2020-07-03 at 6 43 37 PM

Why we need to assign unique IDs: [https://www.optimizesmart.com/event-tracking-in-google-tag-manager-v2-complete-guide/#:~:text=You%20will%20need%20this%20'id,not%20contain%20any%20white%20space.](url)

### url path: /need-help
| #  | Element on page | JSX 'id' attribute |
| --- | --- | --- |
| 1. | Medical Help Button | RES1_MH |
| 2. | Other Help Button | RES1_OH |
| 3. | Back Button | RES1_BA |
| 4. | Next Button | RES1_NE |

Screen Shot 2020-07-03 at 6 29 35 PM

### url path: /need-help#Step2
| #  | Element on page | JSX 'id' attribute |
| --- | --- | --- |
| 5. | "Enter address, zip code, or city" Field | RES2_EAZ |
| 6. | "Share My Location" Button (including icon <br>and the entire clickable whitespace area) | RES2_SL |
| 7. | "Show me postings from anywhere" Button | RES2_SA |
| 8. | Back Button | RES2_BA |
| 9. | Next Button | RES2_NE |

Screen Shot 2020-07-03 at 6 35 32 PM

### url path: /need-help#Step3
| #  | Element on page | JSX 'id' attribute |
| --- | --- | --- |
| 10. | "Enter your email address..." Field | RES3_EE |
| 11. | Submit Button | RES3_SUB |
| 12. | Skip Button (the entire clickable area) | RES3_SK |
| 13. | Back Button | RES3_BA |

Screen Shot 2020-07-03 at 6 56 13 PM

### PR DESCRIPTION
**Pull request by jyclam**
### What does this pull request aim to achieve? 💯
Add gtm tags to Needhelp flow
closes #990

### CODE REVIEW

**Comment by jyclam** [comment]
@doheekim93 Can we count on the tag suffixes to always be consistent when tagging these elements? 

`_EAZ` = **Enter** **a**ddress, **zi**p
`_SL` = **S**hare **l**ocation
`_NE` = **Ne**xt button 
`_BA` = **Ba**ck button

**Comment by jyclam** [comment]
@omarzoghayyer Heads up that this partially solves some of #991.

**Comment by doheekim93** [comment]
@jyclam Hi, yes! This is part of the naming convention BI and marketing came up with. With this, we can make sure all new elements added to the platform will be tagged using the same naming convention :) I will put together a document for the naming convention everyone can refer to!

**Comment by jyclam** [comment]
Perfect! That sounds good

**Comment by jyclam** [comment]
Moved GTM tags to constants file as discussed

**Comment by joshmorel** [comment]
Thanks @jyclam looks good with respect to what we discussed. Wondering - the LocationInput is used elsewhere so if there is no `gtmPrefix` it is like `_EAZ`. Does seem to cause a code issue but will this cause an issue with Google Analytics? Or since we'll have them everywhere eventually will it be okay?

**Comment by doheekim93** [comment]
Hey @joshmorel, we are going to be adding the ids to all the location inputs (with the suffix _EAZ), so we should be okay.

**Pull request merged**
