### PR TITLE
#1582-corrected organisation word to organization in en-us

### LINKED ISSUE #1582: Localisation: en_US.json has references to "organisation" instead of "organization"
I first noticed this in the navbar:
image

Looking at the locale JSON file for [en_US](https://github.com/FightPandemics/FightPandemics/blob/staging/client/src/locales/translations/en_US.json), I noticed that "organization" is being spelled as "organisation" in some places. This should be corrected to "organization" with a z.

### PR DESCRIPTION
**Pull request by guvarallo**
### What does this pull request aim to achieve? 💯

_Please be concise and link any related issue(s):_

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [ ] There are no console warnings and errors.
- [ ] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [ ] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

@mannykary fixes issue #1582

### CODE REVIEW

**Review by idjevm — APPROVED** [review]
LGTM! but @jyclam @doheekim93 isn't this being handled by lokalise??? If so, do we have to change it in lokalise?

**Comment by joshmorel** [comment]
@idjevm en_US are done in the code base. Then Lokalise uses that as a base for people to translate other files in Lokalise which them come back as auto PRs. At least I think that's how it works...

**Comment by jyclam** [comment]
Hi @idjevm @guvarallo, it's okay to edit the `en_US` file directly in the codebase. Any changes to this file should automatically be picked up in Lokalise and changed there too. This is a good opportunity to test that webhook. 

I don't think this needs to be a `hotfix/` though as it's not critical and not yet in production either

**Review by joshmorel — APPROVED** [review]
LGTM Thanks @guvarallo !

I would use feature/ prefix for this kind. hotfix/ is supposed to be for something urgent that must be fixed in prod ASAP. But in any case either prefix will work to deploy to review (just a standard as to the rest of the flow).

**Pull request merged**
