### PR TITLE
Disable location sorting by default, add toggle to enable it

### LINKED ISSUE #2052: Latest posts not visible after logging in
Can't view latest posts after logging in and applying location filter too.
FP1
FP2

Additional info by @rabbi08:
"Actually if you add another filter "provider ='Individual'" then you can see the post posted by individuals recently.
But thats a good point ( looks a bug as of now), it looks we need to fix the filter, that on location filter -> recently logged should have second priority, after the location."
image

Also, issue #376 is somewhat related I guess.

### LINKED ISSUE #2141: Filter: Search results, based on location(country), are not sorted as per time.
1. Login into STG/PROD "fightpandemics.com"
2. Navigate to Helpboard and apply location filter = 'United States' 

Issue: You will observe that 6 months old posts are displayed on the top for the selected location.
But when you keep scrolling, you will see recent post for the searched location.
So search results are as per location but they are not sorted as per time when they are posted. 

Expected Result: When user apply location filter -> the latest posts for the selected location should be displayed as per the age i.e. latest on top and so on.

See below screenshots/GIFs
Screen Shot 2021-01-13 at 7 47 18 PM

Screen Shot 2021-01-13 at 7 52 06 PM

ezgif com-video-to-gif-4

Please note, This issue is related to #2053 

**Some Exceptions need to be verified while fixing this issue:**
1. When we search on the base of country, this issue always exist, but when user expand the search location i.e. city/state/country, results are better. Please see this in GIF.

If I search 'United States' 'United Kingdom' 'Spain' 'Barcelona, Spain' the results are NOT accurate.

**Note: So, the locations are not matched properly when broader location is searched for.**

### PR DESCRIPTION
**Pull request by Zaydme**
### What does this pull request aim to achieve? 💯
To get the latest postings, disable location sorting that is enabled by default when the user logs in, and add a toggle "Show me postings near me" to enable it back

_Please be concise and link any related issue(s):_
closes #2052

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Comment by rabbi08** [comment]
@Zaydme 
1. Initially when user log in -> they want to see relevant post to him like what is there "for him" and "near to him". 
So, I would like to suggest that we should implement the functionality of 'toggle' on **'All Post'** for logged in user, P.S. below for details:

- We don't need extra toggle for this.
**proposed Implementation:**  "All post" option of logged in user should act like "toggle near me"
so < Logged in User -> Help Board -> **All post/[should work like -Toggle near me]** -> No filter: Recently added post with respect to the selected user, of the selected user are displayed on the top: FAIL>

**Current implementation:** 'all post' is showing mixed results.

2. Further the filter of 'Offer/Request post' should be applied on 'All post' result set: PASS
3. Non-Logged In User -> Help Board -> All post -> No filter: Recently added post are displayed irrespective of the location:


**Filters:**
1. When user apply user filter, for e.g. 'New York, US' the "recently added post" having address as "New York" should be displayed: FAIL
See below GIF.
ezgif com-video-to-gif-3

**- Note:** Even if they are mine post, sorting should be based on time they are added, recently added post should be on top for **selected** location.

2. [we can ignore this issue for this PR]
When user combine 2 filters, say Location and provider, then the "selected provider" recently added post for that location should be displayed. 

For e.g. Location = 'France' and provider = individual
Issue: you will observe  that search results are displayed from US. This is not valid results.

**Comment by Zaydme** [comment]
@rabbi08 
You are requesting something that is technically impossible.
> Even if they are mine post, sorting should be based on time they are added, recently added post should be on top for selected location.

You cannot sort something by two factors at the same time, we can either sort by location, or by time.

I will give you this list, I want you to sort it numerically and alphabetically:
- b3, a6, e2, c1, d4, f5
It is impossible.

The point of this PR was "disabling location sorting by default, and adding option to enable it back"
Because this location sorting is causing the feed to show old posts, and it makes the search very bad too. So it should be disabled by default.
The placing of the toggle in the side bar, and not inside the filters (at least on desktop) was to keep it easily visible to the end user, so they can simple enable it if they are looking for something near them, but to not show them "5 months old" posts as the first thing they see, it should be disabled by default...

cc @sankethbe

**Comment by sankethbe** [comment]
@Zaydme From the perspective of the original issue, this PR successfully resolves it i.e. showing most recent posts at top instead of stale ones and brings in the much needed urgent change in terms of UX. This is a very crucial hot fix.

The points by @rabbi08 are good suggestions too which can be looked at in upcoming releases. The "Show results near me" is a nice addition but if it makes the UI inconsistent then the user should still be able to access it intuitively via location filters (city/state/country).
image
eg: Ideally recent posts from India should've been displayed but improvements can be done incrementally over iterations.

**Comment by rabbi08** [comment]
> @Zaydme
> 
> 1. Initially when user log in -> they want to see relevant post to him like what is there "for him" and "near to him".
>    So, I would like to suggest that we should implement the functionality of 'toggle' on **'All Post'** for logged in user, P.S. below for details:
> 
> * We don't need extra toggle for this.
>   **proposed Implementation:**  "All post" option of logged in user should act like "toggle near me"
>   so < Logged in User -> Help Board -> **All post/[should work like -Toggle near me]** -> No filter: Recently added post with respect to the selected user, of the selected user are displayed on the top: FAIL>
> 
> **Current implementation:** 'all post' is showing mixed results.
> 
> 1. Further the filter of 'Offer/Request post' should be applied on 'All post' result set: PASS
> 2. Non-Logged In User -> Help Board -> All post -> No filter: Recently added post are displayed irrespective of the location:
> 
> **Filters:**
> 
> 1. When user apply user filter, for e.g. 'New York, US' the "recently added post" having address as "New York" should be displayed: FAIL
>    See below GIF.
>    ezgif com-video-to-gif-3
> 
> **- Note:** Even if they are mine post, sorting should be based on time they are added, recently added post should be on top for **selected** location.
> 
> 1. [we can ignore this issue for this PR]
>    When user combine 2 filters, say Location and provider, then the "selected provider" recently added post for that location should be displayed.
> 
> For e.g. Location = 'France' and provider = individual
> Issue: you will observe that search results are displayed from US. This is not valid results.

ok @Zaydme we can work on the points I mention, but still if you observe in the GIF, the old post are displayed over the recent ones. 
Also, I added below screenshot.
Screen Shot 2020-12-16 at 11 11 42 AM

**Review by rabbi08 — APPROVED** [review]
- Toggle to show post near me: PASS
- logged in user -> Filter on 'Location': Show post sorted on the base of location

Thanks

**Review by sankethbe — APPROVED** [review]

**Pull request merged**
