### PR TITLE
#787 Enter Key to Login/Sign Up

### LINKED ISSUE #787: user should be able to logged in using <enter> key also.
Steps to reproduce:

1. Open "https://staging.fightpandemics.work"
2. Click on 'Login'
3. Enter valid email/password used during SignUp
Press <enter>
You will observe nothing happen

So then. 4. Click on 'Sign In' button

User is successfully logged in.

Issue: User should be able to SIGN IN using <enter> key along with clicking on 'Sign In' key.
Please note that <enter> key does not work during sign ups too.

### PR DESCRIPTION
**Pull request by guvarallo**
### What does this pull request aim to achieve? 💯

_Please be concise and link any related issue(s):_

- [x ] I have checked that no one else is working on similar changes.
- [ x] I have read the latest [**README**](README.md) and understand the development workflow.
- [ x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [ x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x ] There are no merge conflicts.
- [ x] There are no console warnings and errors.
- [ x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [ x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

@adisen here is the fix for #787

### CODE REVIEW

**Review by idjevm — APPROVED** [review]
I tested and it seems to be working as expected, + no major code changes were done so it should be fine. Any thoughts @joshmorel ?

**Review by adisen — APPROVED** [review]
This seems to fix this. More efficient too and no codebase change

**Review by galeza — CHANGES_REQUESTED** [review]
Hi @guvarallo 

Could you check one thing, please. I tested Login and Join now screens.
Join now screen - I entered email and passwords. Then I hit Enter. On the check-email screen email is not displayed:
We just emailed a link to {email}. Click the link to confirm your account and complete your profile.
Screen Shot 2020-10-05 at 10 41 52

Staging:
Screen Shot 2020-10-05 at 10 42 47

**Comment by guvarallo** [comment]
Hi @galeza, sure let me check this

**Comment by guvarallo** [comment]
Hi @galeza I was not able to reproduce your error, mine is working as expected:

Screenshot from 2020-10-05 08-35-01

**Comment by galeza** [comment]
Hi @guvarallo 

Strange. I'm using: https://feature787-enter-key-to-login.fightpandemics.xyz/
join now screen I hit enter or press Sign In button:
Screen Shot 2020-10-05 at 13 44 20

I don't know how to explain this.
I'll ask other QAs for confirmation.

**Comment by galeza** [comment]
Hi @rabbi08 , @jessica-lau 
Please check this PR. Especially https://feature787-enter-key-to-login.fightpandemics.xyz/auth/check-email screen.
I have a message: _We just emailed a link to {email}. Click the link to confirm your account and complete your profile._

**Comment by guvarallo** [comment]
Hi @galeza, strange indeed, I tried once again and all is ok:
Screenshot from 2020-10-05 08-47-17

**Comment by jessica-lau** [comment]
@guvarallo @galeza I used build https://feature787-enter-key-to-login.fightpandemics.xyz/auth/check-email and I couldn't reproduce the error Agnieszka saw. My message displayed as expected. I'm testing it on Chrome in Windows 10.

image

**Review by jessica-lau — APPROVED** [review]
Tried enter key on both sign in and sign up and LGTM

**Comment by galeza** [comment]
hi @guvarallo 

I think it has something to do with a browser/system version. On Safari I see:
Screen Shot 2020-10-05 at 18 45 59

I have an issue with this configuration: MacOs High Sierra, Chrome 85.0.4183.121 (Official Build) (64-bit).

**Comment by guvarallo** [comment]
Hi @galeza I have no way to test this in your configuration. This code does not change anything in post-signup page, it simply adds the functionality to press enter in the form. Have you tested if this issue happens in the staging branch as well?

**Comment by guvarallo** [comment]
My advice is to add this request as a new issue, since this PR does not affect the post-signup page

**Comment by galeza** [comment]
@guvarallo 
I agree with you.
I'm accepting this PR.

BTW staging works normally for me. It's really strange.

**Review by galeza — APPROVED** [review]

**Pull request merged**
