### PR TITLE
#1561 - Fix Like Button on Profile/OrganizationProfile

### LINKED ISSUE #1561: User(logged IN/NOT) is unable to LIKE a post from the profile of an Individual/Organisation  who posted the post
Scenario 1:
staging - User is not signed in
1. Go to Help board 
2. Go to the Individual profile  OR Org profile -for a particular post.
3. Click on the 'like '  button of a post listed under activity.
Expected: Clicking on 'like' should redirect user to login page.
Actual: 'Like' is not clickable from profile page

Scenario 2:
staging - User is logged in.
1. Go to Help board 
2. Go to the Individual profile  OR Org profile -for a particular post.
3. Click on the 'like '  button of a post listed under activity.
Expected:  'like' should be clickable
Actual: 'Like' is not clickable from profile page

### PR DESCRIPTION
**Pull request by leon-i**
### What does this pull request aim to achieve? 💯  

Like button now functions as intended on Profile/OrganizationProfile screens.  
  
Unauthorized users redirected to sign in page on click  
Authorized users able to like the post  
  
### How to Test
* **Unauthorized**  
    * Go to Help Board  
    * Go to the an organization/individual profile for a post  
    * Like a post  
    * You should be redirected to sign in page  
* **Authorized**  
    * Sign in  
    * Go to Help Board  
    * Go to the orgaization/individual profile for a post  
    * Like a post  
    * The post should now be liked by you

_Please be concise and link any related issue(s):_  
  
Resolves #1561 

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Review by galeza — APPROVED** [review]
LGTM

Tested on Android 10 and desktop MacOs

**Review by rabbi08 — APPROVED** [review]
Tested following scenario on feature build and are working fine, Thanks:

1. No logged in user -> Navigate to Help Board-> organization/individual profile for a post -> Click 'Like' a post -> redirected to sign in page: PASS
Refer below screenshot
https://share.getcloudapp.com/xQuAp1bg

2. Logged in user -> Navigate to Help Board-> organization/individual profile for a post -> Click 'Like' a post -> Post should have 'LIKE' added: PASS
Refer below screenshot
https://share.getcloudapp.com/Z4uyP0r5

**Review by idjevm — APPROVED** [review]
LGTM! Thanks @leon-i

**Comment by rabbi08** [comment]
Verified the fix in STG, as working fine. Thanks

**Pull request merged**
