### PR TITLE
#1305 - Fix EmailShareButton prop

### LINKED ISSUE #1305: Share Post-> While sharing the post via EMAIL, the post title should be added as EMAIL subject
1. Open "staging.fightpandemics.work"
2. Navigate to Help Board
3. Click on any Post to share as select as 'EMAIL'

Issue: You will observe that email is composed with the post description as email body with FP link, but the email SUBJECT is NULL/empty. This is consistency issue over email sharing of the post on the web.

Refer below screenshot.

Screen Shot 2020-07-28 at 6 22 09 PM

As per the share feature via email, the title of the page or the post is added as the email subject.
just for reference refer below GIF for sample. 
https://share.getcloudapp.com/GGuRnD0Z

### PR DESCRIPTION
**Pull request by jyclam**
### What does this pull request aim to achieve? 💯

When sharing posts to email, the email subject is pre-populated with post title.

_Please be concise and link any related issue(s):_

resolves #1305 

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Comment by rabbi08** [comment]
@jyclam 
The 'subject' is still blank the post title is not populated in the subject field of the email. Refer below Gif
image

Also, I have observed another issue please note this issue also exist in STG, the share button is not clickable after user click it one time. Then user need to reload/refresh the page. Pleas see the issue in the above gif too. Let me know if you can fix that issue along with this or I can log another for the same. 
Issue- The share button is not re-clickable.

**Comment by jyclam** [comment]
Thanks @rabbi08! Are you using Safari on mobile and desktop when seeing those issues?

I was only to replicate the unpopulated Subject Line when using Safari on my desktop, but Chrome and Firefox works fine. 

I am not able to replicate the share button only working once.

**Comment by rabbi08** [comment]
@jyclam 
I am using safari and chrome on iPhone and issues exist on mobile.
'Share' button click issue exist on mobile only not on desktop.

But email icon is not chrome desktop is not clickable.  Nothing happen when I click on email button in the share 
Still Will explore more snd update if any, thnx.

**Review by jessica-lau — CHANGES_REQUESTED** [review]
@jyclam I tested the email share using Chrome on desktop, Android, and iOS mobile and they all worked.

However, I have the same issue as @rabbi08 when using Safari on iOS where the mobile share button is not clickable after the user clicks it once. I need to refresh the page to be able to click it again. 

Also when using Safari, I'm experiencing the subject line populating with the post's details and not the post's title resulting in duplicate content appearing in the email's subject line and body.
 
image

image

image

**Comment by jyclam** [comment]
@jessica-lau @rabbi08 
Okay, I've figured out the issue with the email subject in iOS and macOS Safari. Basically, the problem is with Apple in how they are using the information the share feature provides, we give them Title, Text, and URL and they decide how to use them. I think our best approach is to do nothing here and just wait for them fix this. 

For more info see here:
https://www.gyford.com/phil/writing/2020/04/10/web-share-api/

For the only shareable one time thing, it seems like it's Apple's issue again. Regression in their code: https://stackoverflow.com/questions/64101418/navigator-share-doesnt-work-for-second-time

So both issues identified are outside of our control. The sharing works as expected for other platforms / devices.

**Review by idjevm — APPROVED** [review]
This LGTM ! I tested and it seems to do it this time around though...

**Review by jessica-lau — APPROVED** [review]
@jyclam ok, thanks for the update! Everything else LGTM.

**Comment by rabbi08** [comment]
@jyclam 

Agree for the share feature functionality in Apple. Thanks for the update.

But while testing Desktop -> Chrome the email icon is not working, can you please confirm. Please refer below GIF.

ezgif com-gif-maker (19)

Please note the email icon works fine in iphone.

**Review by galeza — APPROVED** [review]
LGTM

Tested on macOS - chrome, firefox, safari
Android - chrome

**Comment by galeza** [comment]
@rabbi08 

I tested macOS  + chrome 86 and it works fine:
Screen Shot 2020-10-20 at 11 24 07

**Pull request merged**
