### PR TITLE
update global user after account update

### LINKED ISSUE #1914: Updated First & last name updated is not reflecting in the profile header bar.
1. Login as valid username
2. Navigate to profile and update the first name and last name
look for your name in profile header menu

Issue: the name is not updated. This issue exist in PROD as well. Manu reported this morning.
Refer below screenshot.
image

image (6)

### PR DESCRIPTION
**Pull request by ddveloper**
### What does this pull request aim to achieve? 💯
update global user so dropdown menu can see user name change
_Please be concise and link any related issue(s):_
to fix issue #1914 

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Review by rabbi08 — APPROVED** [review]
Verified the fix on desktop and mobile, user name and avatar are getting update in the profile header immediately after user update them. Refer below screenshot.
thanks
image

**Review by Zaydme — APPROVED** [review]
LGTM!
@rabbi08 I think we should merge this even with the code freeze.

**Comment by rabbi08** [comment]
> LGTM!
> @rabbi08 I think we should merge this even with the code freeze.

Yes plz, we have to merge this one. Thanks

**Comment by sheeba1** [comment]
on staging, As original individual logged in user, I changed my last name Jose to Thomas . The post reflected the change but not the name icon on top right as shown. Just wanted to make sure this has been fixed for the feed page too. Sorry I couldn't test on build url as I already have a profile pic setup


lastnamechange

**Comment by Zaydme** [comment]
@rabbi08 it should reflect there too now :+1:

**Comment by rabbi08** [comment]
@Zaydme 
We can merge this PR, as this is already verified. Thanks

**Pull request merged**
