### PR TITLE
782 - Logout user from all tabs

### LINKED ISSUE #782: Auth0 user should be logged off from all tabs
env: staging

Steps:
1. Open staging in the first tab and log in. Go to profile screen
2. Open staging in the second tab. You are already logged in and you can open your Profile page. 
3. In the second tab click Logout
4. Go to the first tab
In the first tab Navigation bar shows Profile (it's for a logged in user). When you click Profile you'll see error: Failed loading profile, reason: No Authorization was found in request.cookies

I would expect that my user will be logged of in both tabs. And in the first tab I'll see Login, Register buttons.

Desktop:
Screen Shot 2020-06-22 at 20 01 13

### PR DESCRIPTION
**Pull request by Zaydme**
### What does this pull request aim to achieve? 💯
When the user logs in, starts an interval that checks the remember cookie, if it doesn't exist, store the current location path in localStorage, logout user, clear the interval. If the user was in a logged-in only, they will be redirected to login, and then redirected back to their initial page after login (this is the reason why the current location path is stored in localStorage).

_Please be concise and link any related issue(s):_
closes #782

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Review by rabbi08 — COMMENTED** [review]
@Zaydme 
Verified the fix on Desktop and mobile:
- On desktop -> Chrome: PASS
   Incognito window: PASS
   Refer below GIF
ezgif com-gif-maker (49)

On mobile: 
iphone -> safari: PASS

ezgif com-video-to-gif 17

Mobile -> Private window: FAIL
ezgif com-video-to-gif 16

May be it is expected to be so in private window, but please note that it works well in incognito window. Let me know your thoughts.

Thanks

**Comment by Zaydme** [comment]
@rabbi08 I think that's exclusive for safari private mode, you can find that [here](https://support.apple.com/guide/safari/use-private-browsing-ibrw1069/mac)
> When you use a Private Browsing window:
> - Browsing initiated in one tab is isolated from browsing initiated in another tab, so websites you visit can’t track your browsing across multiple sessions.

this means that each tab will have each own cookie I guess, and there is no relation between them.

here are some details I found here:
> When you click on a link and it takes you to a new tab, it'll keep cookies. If the new tab started off as a blank slate, it would be impossible for you to change that setting. To prevent this shared cookies are allowed between those tabs.

**Review by rabbi08 — APPROVED** [review]
Verify the fix working fine. 'Private window-safari' is an exception as per the functionality of private safari browser explained by @Zaydme .

Thanks

**Review by joshmorel — APPROVED** [review]
Thanks @Zaydme LGTM!

**Pull request merged**
