### PR TITLE
Display profile and org profile comment's icon and comment count correctly

### PR DESCRIPTION
**Pull request by tr1503**
### What does this pull request aim to achieve? 💯

I fixed the issue for #931 and now the user profile and organization's profile can show comment's icon as blue and comment count when the post has comments.

_Please be concise and link any related issue(s):_

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](https://github.com/FightPandemics/FightPandemics/blob/master/README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`** (need to have cloned the repo not forked).
- [x] This branch is rebased/merged with the **latest master**.
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

### CODE REVIEW

**Comment by vikjoshi** [comment]
lgtm too after testing on build- adding comments shows the correct number of comments under My Activity and matches what is on the feed and if we delete comments, that number goes back down. Thanks @tr1503! Will let @idjevm or @joshmorel do the second review before merging to staging.

**Comment by vikjoshi** [comment]
> can we have this also on the post view?

@tr1503  @idjevm - is showing the number in the post view a quick change? If not, lets not include that in this PR so we can get this merged in for MVP. 

@tr1503 - regarding @idjevms comment on showing the word _Comment_ , JV and I discussed this and that can be part of a separate PR so no need to include this for now. 

Thank you both!

**Comment by idjevm** [comment]
Hey @vikjoshi I have fixed these things so we can merge this PR, number of comments are shown both in the profile pages, feed and in the post page, as well as the word "comment" if one comment and "comments" if more than 1 comments :)

**Comment by tr1503** [comment]
@idjevm Thanks! And I just re-requested the pr review to you for merging.

**Pull request merged**
