### PR TITLE
validations for forgot password

### PR DESCRIPTION
**Pull request by JayashreeSamantasinghar**
### What does this pull request aim to achieve? 💯
added test cases for forgot password scenario
_Please be concise and link any related issue(s):_

- [x ] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [ ] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Review by jessica-lau — APPROVED** [review]
hey @JayashreeSamantasinghar the code LGTM and test passed, but I noticed that the code formatting isn't the same as the rest of the spec, did you install prettier in your editor? If not, please refer to this [PR](https://github.com/FightPandemics/FightPandemics/pull/1717)

**Comment by JayashreeSamantasinghar** [comment]
> hey @JayashreeSamantasinghar the code LGTM and test passed, but I noticed that the code formatting isn't the same as the rest of the spec, did you install prettier in your editor? If not, please refer to this [PR](https://github.com/FightPandemics/FightPandemics/pull/1717)

@jessica-lau 
Jessica, I just pulled the updated codes in .pretierrc but didnt install.  I will commit the changes once I install it.
Thanks

**Comment by galeza** [comment]
@JayashreeSamantasinghar 

If you have problems with installing Prettier on VSC, let me know.

I think that both tests are similar. In case of dummySampleEmail and validSampleEmail we have unregistered user. Maybe we can keep only one test?

**Comment by JayashreeSamantasinghar** [comment]
> @JayashreeSamantasinghar
> 
> If you have problems with installing Prettier on VSC, let me know.
> 
> I think that both tests are similar. In case of dummySampleEmail and validSampleEmail we have unregistered user. Maybe we can keep only one test?

@galeza , @jessica-lau 
I installed prettier and kept only one test registered/unregistered . Is this seems ok or not please suggest.
Thanks

**Review by galeza — APPROVED** [review]
LGTM

**Comment by galeza** [comment]
@idjevm 
Please merge ;)

**Review by idjevm — APPROVED** [review]
Alrigthy @galeza

**Pull request merged**
