### PR TITLE
Production Release as on 11-26-2020

### PR DESCRIPTION
**Pull request by rabbi08**
### What does this pull request aim to achieve? 💯

_Please be concise and link any related issue(s):_

- [ ] I have checked that no one else is working on similar changes.
- [ ] I have read the latest [**README**](README.md) and understand the development workflow.
- [ ] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [ ] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [ ] There are no merge conflicts.
- [ ] There are no console warnings and errors.
- [ ] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [ ] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Comment by rabbi08** [comment]
Verified #1863 
This is working fine in STG, After user clicks on 'Back' button on 'Post' page -> user lands on same post on help board from where they navigated. This works if user clicks on 'Post' or 'Comment' to navigate to 'Post' page.

Refer below GIF
ezgif com-gif-maker (70)

Thanks

Verified #1903 
This is working fine in STG. Please see below screenshot.
image

the security option is not displayed for social media logins.: Expected, PASS

Also just an observation, kindly share your points of view:
The notification preferences should be down and 'Security' should be up on 3rd number in TAB display sequence.

Thanks

**Comment by ddveloper** [comment]
Thanks @rabbi08 , the social medial login has no password so it makes sence having no security settings, for the order of Tabs, I agree the security setting has a higher priority, I will adjust it

**Comment by galeza** [comment]
Verified Cypress tests

**Comment by adorapham** [comment]
Verify  Feature/privacy policy-Add validation tests for privacy policy page #1810
image

**Review by jessica-lau — APPROVED** [review]
retested cypress tests - #1810 privacy policy, #1812 about us page

retested #1861 display initials avatar has no picture, #1480 direct messages

**Review by galeza — APPROVED** [review]
LGTM

**Review by mannykary — APPROVED** [review]

**Review by idjevm — APPROVED** [review]
LGMT! Let's ship it !

**Pull request merged**
