### PR TITLE
Feature/keep scroll position

### LINKED ISSUE #1498: To retain the filter values when user clicks back from an individual post
### Issue
When the user clicks on back button from any individual post to go back to the Help Board, found all filters was cleared and lead the user to the top of Help Board.

### Steps to reproduce
1. Log in (to be able to access a post), and go to Help Board
2. Select at least one filter, then scroll down the page for a while
3. Click to access any post there
4. Once redirect to the post, click back button at the bottom of any individual post (or :arrow_left: of the browser) to go back to the Help Board page
5. Observe the result, you will see that all filters the user selected are cleared, also lead the user to the top of the Help Board page

### Expected behavior
When a user clicks on back button at the bottom of any individual post (or :arrow_left: of the browser), all filters should be remained as last selected. Also land the user to where they last left off on the Help Board.

### PR DESCRIPTION
**Pull request by OzkanAbdullahoglu**
### What does this pull request aim to achieve? 💯
Resolves #1498 
_Please be concise and link any related issue(s):_

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [ ] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Comment by Zaydme** [comment]
@OzkanAbdullahoglu I was wondering if this can be extended to preserve filters + search keyword
please check https://github.com/FightPandemics/FightPandemics/issues/1701#issuecomment-716628921

**Comment by OzkanAbdullahoglu** [comment]
> @OzkanAbdullahoglu I was wondering if this can be extended to preserve filters + search keyword
> please check [#1701 (comment)](https://github.com/FightPandemics/FightPandemics/issues/1701#issuecomment-716628921)

Yes, I think we can extend this, but first I will try to improve this solution a bit. If you have time you can take a look at that too, I am open for an alternative idea & view.

**Comment by Zaydme** [comment]
The diff is huge, maybe we should try merge staging into this? or how do we fix this?
image

**Review by Zaydme — APPROVED** [review]
LGTM, maybe in the future we can extend this to also coming back to the feed from a profile page. but for this release, I think it's good enough.

**Review by joshmorel — APPROVED** [review]
Thanks @OzkanAbdullahoglu great work!

I do agree with @Zaydme ideally we'd be able to click from feed>profile>post and still go back twice to the same spot in the post BUT this is still very good for now (not sure how Twitter does it...).

**Comment by OzkanAbdullahoglu** [comment]
@Zaydme, @joshmorel,

Twitter keep scroll level even in your own posts (  I have just checked 😁 ) 
I can extend the same logic for profile &orgprofile. less tricky then feed.js
I will open PR about this in the first opportunity.

**Comment by Zaydme** [comment]
@OzkanAbdullahoglu I would suggest waiting for #1767 before doing that, since there might be major conflicts.

**Pull request merged**
