### PR TITLE
Fix ability to create duplicate organisations

### LINKED ISSUE #1145: Able to create organisation profile with same name,same address,same type of industry.
Steps to create:
1.Login with valid user name and password.
2. Go to profile.
3.Create a new organisation profile with the same name,same address,same type and industry of the organisation already exist.
Expected result:
It should not allow user to create duplicate organisation profile.
Actual result:
It allows user to create duplicate profiles.
Screenshot_20200713-161659_Chrome

### PR DESCRIPTION
**Pull request by Zaydme**
### What does this pull request aim to achieve? 💯
Now users cannot create organizations:

-   with the same name (even if different owners)
-   with the same location (if same owner)
-   of the same type (if same owner)
-   of the same industry (if same owner)

_Please be concise and link any related issue(s):_
fixes #1145 

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix. The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

### CODE REVIEW

**Review by sheeba1 — CHANGES_REQUESTED** [review]
Need user-friendly message with appropriate reason when owner of an organization creates another organisation with same Type and Industry and/or if in same city.

Right Now, its displaying 'Internal Server Error'-
image

**Comment by Zaydme** [comment]
Weird... It should actually show a user friendly message.
I will look into that

**Comment by Zaydme** [comment]
I have updated the pull request with the requested changes.

**Comment by sheeba1** [comment]
@Zaydme , Can you please look into this as current build url is throwing 503 error.thanks!

**Comment by sheeba1** [comment]
@Zaydme , Who has put together the requirements for this bug as I need some clarifications for the requirements,. For ex: Can't a user own 2 orgs (for ex: restaurants)with different names in a same city. so in this case location,type and industry would be same .

@manualzuru @joshmorel @emtay , Please provide your thoughts on this? 
Also should we allow only one user /organization to Post for the Org?

@Zaydme Let us see their feedback. Thanks!

**Comment by Zaydme** [comment]
@sheeba1 I have fixed the build url.

>  For ex: Can't a user own 2 orgs (for ex: restaurants)with different names in a same city. so in this case location,type and industry would be same.

Yes, the location can't be the exact same (street number etc..) and the type/industry cannot be the same too.
Or do you think we should allow them to create multiple orgs regardless of the type and the industry (type and industry aren't the same thing)

**Review by rabbi08 — CHANGES_REQUESTED** [review]
Now users cannot create organizations:

- with the same name (even if different owners) :PASS, refer below screenshot
image
- with the same location (if same owner): PASS, refer below screenshot 
image
- of the same type (if same owner): PASS, refer below screenshot 
image
- of the same industry (if same owner): refer below screenshot 
image
@Zaydme 
But these errors keep displaying in sequence for all the input fields one by one not all of them together, when they exist so. Ideally all the existing errors, if any, should be displayed to the user in one go to fix.

**Comment by Zaydme** [comment]
@rabbi08 true, one error message would be nicer, I will work on that

**Comment by Zaydme** [comment]
now it will display a nice single message, that is well formatted and punctuated 

image

**Comment by rabbi08** [comment]
@Zaydme 
I am getting below error while trying to create Org:
"Creating organisation failed, reason: No Authorization was found in request.cookies"

image

Thanks

**Comment by Zaydme** [comment]
@rabbi08 
> I am getting below error while trying to create Org:
> "Creating organisation failed, reason: No Authorization was found in request.cookies"

Please clear the website's cache and cookies, login and try again, should be working after that, I just tested it.

**Comment by rabbi08** [comment]
@Zaydme 
This is working pretty nice now, Thanks. 
But this message ignores 'EMAIL' validation. Great if we can accommodate that too in the error message. Please see below sceenshot:

Org_msg

@emtay @anjanarao24 @Zaydme 
I wanna highlight a point related to this functionality as per below real test scenario:

Use case: As an individual user, say, an automobile dealer, so this user have Automobile stores in different cities and states or countries.
And the name, location, email of each dealership is different, as expected. 

So, such Org hierarchy in "FP -> Add Organisation" cannot be created because of the restriction on that a user cannot have an Org with same 'Type and Industry' feature. 

As I cannot add another Organisation with Type = Company and Industry = Automobile. 
Please see below screenshot.
Please note this is just for e.g. to explain a test scenario:
https://share.getcloudapp.com/lluY7rEe

**Comment by Zaydme** [comment]
@rabbi08 

> Use case: As an individual user, say, an automobile dealer, so this user have Automobile stores in different cities and states or countries.
> And the name, location, email of each dealership is different, as expected.
> https://share.getcloudapp.com/lluY7rEe

This is exactly what this pull request is trying to prevent, we shouldn't let this user create 3 organizations, the owner is one, and contacting them through one organization name is enough.
what will be reasonable in this case is that this user creates one organization named for example "Company_name auto group".

**Comment by rabbi08** [comment]
> @rabbi08 
> 
> 
> 
> > Use case: As an individual user, say, an automobile dealer, so this user have Automobile stores in different cities and states or countries.
> 
> > And the name, location, email of each dealership is different, as expected.
> 
> > https://share.getcloudapp.com/lluY7rEe
> 
> 
> 
> This is exactly what this pull request is trying to prevent, we shouldn't let this user create 3 organizations, the owner is one, and contacting them through one organization name is enough.
> 
> what will be reasonable in this case is that this user creates one organization named for example "Company_name auto group".
> 
> 

@Zaydme 
Yes owner is one, but each of its dealer have different location and different contact. So, referring my example screenshot, if user need to connect to Freehold NJ location, they will contact the main org and then they will find and share the contact details of the dealers available as per the user's request. 

Though agree that we are blocking such users but they are real and that's how their organisation are existing and working.

**Comment by Zaydme** [comment]
@rabbi08 do you suggest not checking the org type and industry? that would solve the problem

**Comment by rabbi08** [comment]
> @rabbi08 do you suggest not checking the org type and industry? that would solve the problem

Yes @Zaydme as per me, but I would say let's have more thoughts/ brainstorm on this scenario. 

But overall if we remove validation from type/industry, that will not lead to bad/duplicate data in our app.

**Comment by emtay** [comment]
I agree that I don’t think we need so many restrictions at this time. I think just unique email per organization is enough of a validation. 

That said, we should monitor usage after launch to see if people are creating inappropriate numbers of organizations.

**Comment by nivetheatha** [comment]
The bug is able to create organization profile with same name,same addresses, same type.
Ex: A has automobile industry in the name xyz at abcd address,xyz@gmail.com.
A able to create the same record again with different email I'd like name:xyz address:abcd  type:automobile email:xyz1@gmail.com.FP is not restricting to create a duplicate record.
Here emailid is considered as primary key.
Instead we can combine organization name,organization address, organization type as combined key.

**Review by sheeba1 — COMMENTED** [review]
Is this ready for review

**Comment by mannykary** [comment]
Closing as this is stale.

**Pull request closed without merging**
