### PR TITLE
Change Org social media links validation

### LINKED ISSUE #1140: While adding social media links special character '/' should also be allowed.
1. Open "https://staging.fightpandemics.work"
2. Login using valid email/password
3. Click on 'Profile' -> select Org-> 'EDIT Profile icon'
4. Click 'EDIT Profile'
5. EDIT the Organisation Linkedin/twitter link [as shown in below screenshot]

Issue: You will observe that:

Following errors are displayed if there are max characters or special character like '/'
- Invalid entry: only alphanumeric characters and _ are allowed
- Max. length is 15 characters [Not Critical]

Please note earlier #795, was also fixed similar to this one, as now I am able to user '. DOT, - hypen' in the URLs.
Marking it as critical because, as an Organisation, unable to add my Organisation Linkedin URL.

Screen Shot 2020-07-13 at 2 50 02 PM

@vikjoshi : Feel free to change the labels

### PR DESCRIPTION
**Pull request by jyclam**
### What does this pull request aim to achieve? 💯
Changes OrgProfile social media link validation 

_Please be concise and link any related issue(s):_
closes #1140

### CODE REVIEW

**Comment by jyclam** [comment]
@joshmorel I'm not familiar with our BE do I need to worry about removing the regex validation on AppStore and Google Play urls? Is the user input sanitized by mongoose-connector or some other middleware?

**Comment by joshmorel** [comment]
@jyclam  All it does is check that it's a string so that aspect is okay.

**Comment by vikjoshi** [comment]
@joshmorel @idjevm can we merge this in if it looks good to you guys? Needed for soft launch

CC: @jyclam

**Comment by joshmorel** [comment]
I'll test soon so hopefully we can merge today.

**Comment by jyclam** [comment]
Yeah, if we need to account for `/company` or `/school` or anything else then we should just use the base linked in url `www.linkedin.com` and then allow `-_/` in the validation

**Pull request merged**
