### PR TITLE
Fixed the Linkedin url validation in edit profile

### LINKED ISSUE #1682: LinkedIn URL in Edit Profile should have validation for '/'  like the rest of other media types
https://staging.fightpandemics.work/
Chrome - Window 10
Login as Individual
Click on Profile =>Edit pen =>Edit Profile

provide all the values for these below and see all except LinkedIn URL give the error validation message when entering /
Facebook URL 
Installgram URL
LinkedIn URL
Twitter URL
Github URL

Without providing the error message for LinkedIn URL when entering the / at the end, click on Save Changes button , we have this message on the top
Failed updating profile, reason: error.http.body.urls.linkedin should be null, body.urls.linkedin should match pattern "^[a-zA-Z0-9-]*$", body.urls.linkedin should match some schema in anyOf
image

Further more , we are unable to save any valid values for the rest of other media types and we have to re-type again.     in Summary       
1-LinkedIn URL should have the validation  message for input with / like other media type
2- It is nice to have the page retain the values entered (option)
please see the record attached 

EditProfile_LinkedURL

### PR DESCRIPTION
**Pull request by sujatha-m**
### What does this pull request aim to achieve? 💯

_Please be concise and link any related issue(s):_This PR Resolves #1682 

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Comment by galeza** [comment]
FYI @adorapham

**Comment by adorapham** [comment]
@galeza  @sujatha-m check on Fixed the Linkedin url validation in edit profile, confirm it passed.  Please see the attached screenshot.  
image

**Review by rabbi08 — APPROVED** [review]
Verified below fix/changes on the feature build: 
1. error is displayed if user enter '/' for Linkedin URL as for other social media links. refer below screenshot.
image

2. user is able to EDIT and save the changes successfully for the user profile social links. refer below GIF.
ezgif com-gif-maker (24)

Thanks

**Comment by rabbi08** [comment]
On a side note, Organization profile EDIT show error after user clicks on 'Save changes' but for Individual profile error are displayed when user enter invalid character. We can have separate bug to keep the functionality in sync for **EDIT** of Individual Profile and Org Profile.

**Comment by sujatha-m** [comment]
> On a side note, Organization profile EDIT show error after user clicks on 'Save changes' but for Individual profile error are displayed when user enter invalid character. We can have separate bug to keep the functionality in sync for **EDIT** of Individual Profile and Org Profile.

@rabbi08 we can fix the Organization profile Edit in the same issue

**Comment by rabbi08** [comment]
> > On a side note, Organization profile EDIT show error after user clicks on 'Save changes' but for Individual profile error are displayed when user enter invalid character. We can have separate bug to keep the functionality in sync for **EDIT** of Individual Profile and Org Profile.
> 
> @rabbi08 we can fix the Organization profile Edit in the same issue

@sujatha-m 
We can update same 'EDIT profile' for Individual and Org profile.

Below is the current behavior of Individual profile EDIT profile GIF, the error message is displayed when user enter the '/' in the respective text box.

ezgif com-gif-maker (29)

Next this one is the current behavior of Orgnaisation profile EDIT profile GIF, the error message is displayed after user enter the '/' in the respective text box and CLICK on 'Save changes' button.

ezgif com-gif-maker (30)

So for Organization profile below mismatch should be fixed:
- the error message should be displayed when user enter the '/' as for individual profile.
- Same 'Linkedin - '/' error needs to be fixed for Organization profile EDIT.

Please note, 
- this video is from STG, so "linkedin-'/' "issue exist for 'Individual profile EDIT' : expected in this GIF from STG
- Please don't apply conditions on 'Google and Apple' links textboxes as they need to accept special characters.

Let me know if there is any questions/query.

**Comment by rabbi08** [comment]
> > > On a side note, Organization profile EDIT show error after user clicks on 'Save changes' but for Individual profile error are displayed when user enter invalid character. We can have separate bug to keep the functionality in sync for **EDIT** of Individual Profile and Org Profile.
> > 
> > 
> > @rabbi08 we can fix the Organization profile Edit in the same issue
> 
> @sujatha-m
> We can update same 'EDIT profile' for Individual and Org profile.
> 
> Below is the current behavior of Individual profile EDIT profile GIF, the error message is displayed when user enter the '/' in the respective text box.
> 
> ezgif com-gif-maker (29)
> 
> Next this one is the current behavior of Orgnaisation profile EDIT profile GIF, the error message is displayed after user enter the '/' in the respective text box and CLICK on 'Save changes' button.
> 
> ezgif com-gif-maker (30)
> 
> So for Organization profile below mismatch should be fixed:
> 
> * the error message should be displayed when user enter the '/' as for individual profile.
> * Same 'Linkedin - '/' error needs to be fixed for Organization profile EDIT.
> 
> Please note,
> 
> * this video is from STG, so "linkedin-'/' "issue exist for 'Individual profile EDIT' : expected in this GIF from STG
> * Please don't apply conditions on 'Google and Apple' links textboxes as they need to accept special characters.
> 
> Let me know if there is any questions/query.

@sujatha-m 
we can fix the Organization profile in another PR, lets merge this PR for Individual profile to fix #1682 issue.

**Review by Zaydme — APPROVED** [review]
LGTM, thank you @sujatha-m!

**Comment by rabbi08** [comment]
Re-verified the fix, it is working fine. Thanks
LGTM

**Pull request merged**
