### PR TITLE
Add transition to NeedHelp and OfferHelp from Home

### PR DESCRIPTION
**Pull request by nr431207**
### What does this pull request aim to achieve? 💯
Add transition when transitioning from `Home` page to `Need Help` and `Give Help` to be more smooth using the `react-transition-group` library.
_Please be concise and link any related issue(s):_
#689

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](https://github.com/FightPandemics/FightPandemics/blob/master/README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`** (need to have cloned the repo not forked).
- [x] This branch is rebased/merged with the **latest master**.
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

### CODE REVIEW

**Comment by ppagarawal** [comment]
> @ppagarawal I am gonna mark this as request changes, so you can review, and ask Sonia to make any changes if needed. 
> 
> Please check the build URL and test it out so you can ask what changes you would want for the transitions. 

Lgtm

**Comment by galeza** [comment]
Hi @idjevm @ppagarawal 
I tested transitions from Home to NeedHelp/OfferHelp Question1. Do you accept time needed to load the Question 1 screen? I have an impression that it's slow. 
Transitions between Question 1/2/3 are much faster.

**Comment by idjevm** [comment]
@galeza I agree, I did notice that it could be a bit faster, perhaps by half more time?

**Comment by galeza** [comment]
yes,
I was using chrome dev tools to see load time.

**Comment by galeza** [comment]
@idjevm 
Is there an issue related to this PR? I would reopen an existing issue. Or add a new one?

**Comment by idjevm** [comment]
Just add a new one instead. Let's close the last one.

**Comment by galeza** [comment]
@idjevm 

I'll add a new issue.

**Pull request merged**
