### PR TITLE
Google play store + Apple store icons/links added to org profile

### LINKED ISSUE #1089: Get AppStore & PlayStore icons/links working properly
@vikjoshi - we require a design for icons to complete this fully.

Once that is done we can update the icons here.

* [x] Also `appleStore` should be `appStore` in the form - it's not updating B/E otherwise. (this specific issue is resolved with #1099 )

image

Affects also post page - see #1038

### PR DESCRIPTION
**Pull request by paulms1**
This PR resolves #1089

Displays links to Google Play store and Apple store on organisation profile when link added.

### CODE REVIEW

**Comment by doheekim93** [comment]
@paulms1 I just checked on the Build URL and they work! I think the apple app url should start with `apps.apple.com/`, but `itunes.apple.com/` seems to still direct to the correct page. Would this be a quick fix to implement?

**Comment by joshmorel** [comment]
Looks good @paulms1 but I agree let's change itunes->app while we're here.

**Comment by paulms1** [comment]
Hey @doheekim93 @joshmorel Great guys, I will make that change now.

**Review by joshmorel — APPROVED** [review]
LGTM!

**Review by idjevm — APPROVED** [review]
LGTM!

**Comment by doheekim93** [comment]
Thanks @paulms1!!

**Comment by rabbi08** [comment]
Verified in STG and it is working fine as in below screenshot.

image

**Pull request merged**
