### PR TITLE
#1916 - added missing translation keys for messaging and notifications

### LINKED ISSUE #1916: Words/phases need to be translated to designed languages
1-Cancel from sending Post message
image

2-Offer/Request from inbox - post type 
image

3- No more Notifications 
image

4-Edit Organization Notification
on/off instant Digest
image
image

### PR DESCRIPTION
**Pull request by Zaydme**
### What does this pull request aim to achieve? 💯

Words/phases need to be translated to designed languages
closes #1916
_Please be concise and link any related issue(s):_

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Review by ddveloper — APPROVED** [review]
LGTM

**Comment by Zaydme** [comment]
Not sure how QA can test this, since the keys would need to be translated on lokalize first.
What do you think @ddveloper @rabbi08?

**Comment by ddveloper** [comment]
I think we merge it first, so lokalize can translate them, QA can make a note to test this afterward, @rabbi08 

@ddveloper @Zaydme , i can check if you have the url link is valid.

**Comment by rabbi08** [comment]
> I think we merge it first, so lokalize can translate them, QA can make a note to test this afterward, @rabbi08

Yeah we can merge as currently the build is also not working. Thanks.

**Comment by adorapham** [comment]
> > I think we merge it first, so lokalize can translate them, QA can make a note to test this afterward, @rabbi08
> 
> Yeah we can merge as currently the build is also not working. Thanks.
the link is working now, give me sometime

**Comment by Zaydme** [comment]
Sorry @adorapham 😅
I didn't see the comment

**Comment by adorapham** [comment]
@Zaydme that is fine since i still have a hard time to create an account in the new link.
can you please check the verification on #1916, seem number 3 is not fixed

**Comment by Zaydme** [comment]
@adorapham for number 3, the new key was sent to lokalize where it will be translated. Now you will still see only English. But once we get the new translations in it should change

**Pull request merged**
