### PR TITLE
made uselection of tag is visible when its unselected

### LINKED ISSUE #1698: Create Post: Unselection of Tags is to be more intuitive
Please refer to the Video to understand the issue.
https://hippolms-storage.s3-accelerate.amazonaws.com/wiz/videos/thumbnails/v2/J0SdkzPi0Dun4ireMhYseaKkjwXSW8ykXI1DY49xnyM_play.jpg?_=1603316550

### PR DESCRIPTION
**Pull request by mathigayathri2001**
### What does this pull request aim to achieve? 💯
This PR resolves the uselection of tag and make it visible after unselection
_Please be concise and link any related issue(s):_This PR resolves #1698 

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [ x The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Review by rabbi08 — APPROVED** [review]
Verified the fix in feature branch, it is working fine i.e. the color of the text in TABs change and tab is blue when selected only. 
Refer below GIF.

ezgif com-gif-maker (36)

**Comment by shrutigupta1981** [comment]
Its still not intuitive. When we select Tag X, it becomes blue but when we unselect it doesnt turn to white unless we move cursor away but experience should be same like what we have in buttons....Please let me know if my understanding is not correct. Kindly see the video of what I am trying to say
[Tagunselection.zip](https://github.com/FightPandemics/FightPandemics/files/5470130/Tagunselection.zip)

**Comment by rabbi08** [comment]
@shrutigupta1981 please see the gif  I attached as in that it is behaving differently.

**Comment by rabbi08** [comment]
@mathigayathri2001 
Great if we can implement this logic for the TAB selection under the filters as well?

**Comment by shrutigupta1981** [comment]
image

**Comment by shrutigupta1981** [comment]
I checked on Staging so couldn't find changes as you wouldn't have merged.

**Comment by rabbi08** [comment]
> I checked on Staging so couldn't find changes as you wouldn't have merged.

@shrutigupta1981 
This is NOT merged into STG yet. 
Please note, that the feature is merged into STG after it is reviewed and approved by the involved parties. So you have to test and verify the feature on the feature branch to ensure the fix is working as expected. Also, the feature branch is up and running now for testing.

**Comment by galeza** [comment]
Tested on desktop and mobile Android.

**Review by galeza — APPROVED** [review]
LGTM

**Comment by mathigayathri2001** [comment]
> @mathigayathri2001
> Great if we can implement this logic for the TAB selection under the filters as well?

The solution implemented already resolve this issue as well . Please refer the video, and let me know the feedback
Recording-_1

**Comment by rabbi08** [comment]
> > @mathigayathri2001
> > Great if we can implement this logic for the TAB selection under the filters as well?
> 
> The solution implemented already resolve this issue as well . Please refer the video, and let me know the feedback
> Recording-_1

Thanks @mathigayathri2001 
This is working as expected already approved though. :)

**Comment by shrutigupta1981** [comment]
Tested. Superb. Working both in case of filters and tags !

**Review by joshmorel — APPROVED** [review]
LGTM! THanks @mathigayathri2001

**Pull request merged**
