### PR TITLE
E2E fix failing tests - Cypress

### PR DESCRIPTION
**Pull request by galeza**
Fixed two failing tests.

- [ ] I have checked that no one else is working on similar changes.
- [ ] I have read the latest [**README**](README.md) and understand the development workflow.
- [ ] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [ ] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [ ] There are no merge conflicts.
- [ ] There are no console warnings and errors.
- [ ] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [ ] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Comment by galeza** [comment]
Screen Shot 2020-12-18 at 15 20 19

**Review by TimeaKovacs86 — DISMISSED** [review]
LGTM! Thank you! @galeza 
E2E fix failing tests result passing here too
E2E fix failing tests result passing

**Review by jessica-lau — DISMISSED** [review]
LGTM thank you

image

**Review by JayashreeSamantasinghar — DISMISSED** [review]
Thanks @galeza  for fixing this

**Comment by adorapham** [comment]
LGTM. TY
image

**Review by adorapham — DISMISSED** [review]

**Pull request merged**
