### PR TITLE
Feature/cypress remove memory errors

### PR DESCRIPTION
**Pull request by galeza**
Remove following errors:
```
cypress-e2e-tests     | Browserslist: caniuse-lite is outdated. Please run:
cypress-e2e-tests     | npx browserslist@latest --update-db


cypress-e2e-tests     | We detected that the Chromium Renderer process just crashed.
cypress-e2e-tests     | 
cypress-e2e-tests     | This is the equivalent to seeing the 'sad face' when Chrome dies.
cypress-e2e-tests     | 
cypress-e2e-tests     | This can happen for a number of different reasons:
cypress-e2e-tests     | 
cypress-e2e-tests     | - You wrote an endless loop and you must fix your own code
cypress-e2e-tests     | - There is a memory leak in Cypress (unlikely but possible)
cypress-e2e-tests     | - You are running Docker (there is an easy fix for this: see link below)
cypress-e2e-tests     | - You are running lots of tests on a memory intense application
cypress-e2e-tests     | - You are running in a memory starved VM environment
cypress-e2e-tests     | - There are problems with your GPU / GPU drivers
cypress-e2e-tests     | - There are browser bugs in Chromium
cypress-e2e-tests     | 
cypress-e2e-tests     | You can learn more including how to fix Docker here:
cypress-e2e-tests     | 
cypress-e2e-tests     | https://on.cypress.io/renderer-process-crashed
cypress-e2e-tests     | 
cypress-e2e-tests     | We detected that the Chromium Renderer process just crashed.
cypress-e2e-tests     | 
cypress-e2e-tests     | This is the equivalent to seeing the 'sad face' when Chrome dies.
cypress-e2e-tests     | 
cypress-e2e-tests     | This can happen for a number of different reasons:
cypress-e2e-tests     | 
cypress-e2e-tests     | - You wrote an endless loop and you must fix your own code
cypress-e2e-tests     | - There is a memory leak in Cypress (unlikely but possible)
cypress-e2e-tests     | - You are running Docker (there is an easy fix for this: see link below)
cypress-e2e-tests     | - You are running lots of tests on a memory intense application
cypress-e2e-tests     | - You are running in a memory starved VM environment
cypress-e2e-tests     | - There are problems with your GPU / GPU drivers
cypress-e2e-tests     | - There are browser bugs in Chromium
cypress-e2e-tests     | 
cypress-e2e-tests     | You can learn more including how to fix Docker here:
cypress-e2e-tests     | 
cypress-e2e-tests     | https://on.cypress.io/renderer-process-crashed
```

- [] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Comment by galeza** [comment]
Hi,

Please do: `docker-compose up --build`
This PR contains major updates for:
- cypress - updated to the 6.0.1 version.
- we run tests on --headless --browser chrome (no more on Electron)
- we have a cypress/included:6.0.1 as a builder in the Dockerfile
- DOCKERIZE_VERSION is 0.6.1 (we use dockerize-linux-amd64)
- docker-compose file was modified
- cypress.json contains changes: added:
```
"numTestsKeptInMemory": 0,
  "defaultCommandTimeout": 10000,
  "pageLoadTimeout": 60000,
  "viewportWidth": 1280,
  "viewportHeight": 720,
```

Please check also if report works fine.

**Review by jessica-lau — APPROVED** [review]
LGTM! I tested using docker-compose and also ran the mochawesome report. I no longer see the error. Thank you for fixing this @galeza 

image

image

image

**Comment by adorapham** [comment]
LGTM, I am able to run mochawesome report.  TY @galeza 
image

image

**Review by adorapham — APPROVED** [review]

**Review by TimeaKovacs86 — APPROVED** [review]
LGTM! Get the same result as @jessica-lau  and @adorapham ! Thank you @galeza 
cypress-remove-errors all specs pass

**Review by JayashreeSamantasinghar — APPROVED** [review]
previous
Previously the some spec.js files were failing and now all tests passed. Thanks @galeza 
new

**Pull request merged**
