### PR TITLE
Correct test for Header.spec.js

### PR DESCRIPTION
**Pull request by galeza**
Correct test for Header.spec.js

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Review by TimeaKovacs86 — APPROVED** [review]
That's it. Well done!

**Comment by adorapham** [comment]
LGTM , thank for quick fix @galeza 
image

**Review by adorapham — APPROVED** [review]

**Review by jessica-lau — APPROVED** [review]
LGTM! Thank you for fixing this

**Review by JayashreeSamantasinghar — APPROVED** [review]
Thanks for fixing this @galeza . I think my localhost is not updated so test failed in localhost:3000 but test passed for https://staging.fightpandemics.work/

**Pull request merged**
