### PR TITLE
#1988 - fix Swagger URL

### LINKED ISSUE #1988: Swagger - change URL
env: Prod Swagger
URL: https://fightpandemics.com/api/documentation/index.html

Please change base URL to current URL:
Screen Shot 2020-11-25 at 15 08 06

### PR DESCRIPTION
**Pull request by Zaydme**
### What does this pull request aim to achieve? 💯
set the base URL to the current URL in Swagger

_Please be concise and link any related issue(s):_
closes #1988 

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Comment by galeza** [comment]
@Zaydme 

tested using:
GET /api/posts:
Screen Shot 2020-11-30 at 20 15 23
GET /api/organizations:
Screen Shot 2020-11-30 at 20 15 04

For POST I get an error:
```
{
  "statusCode": 415,
  "code": "FST_ERR_CTP_INVALID_MEDIA_TYPE",
  "error": "Unsupported Media Type",
  "message": "FST_ERR_CTP_INVALID_MEDIA_TYPE: Unsupported Media Type: */*"
}
```
Screen Shot 2020-11-30 at 20 20 09

**Review by galeza — CHANGES_REQUESTED** [review]
Could you check POST example /api/auth/login

**Comment by Zaydme** [comment]
I think this is the content type header, which should be `application/json` and Swagger is using `*/*` now.

**Review by galeza — APPROVED** [review]
LGTM
tested:
GET api/posts
GET api/users
POST api/login
POST api/feedback

**Pull request merged**
