### PR TITLE
1672 - BUG FIX: On enter or shift + return, allow a newline to be created on comment, do not submit

### LINKED ISSUE #1672: [Mobile-Android]During commting the post user press newline key it acts as Enter instead of creating new line.
Device used : Samsung Galaxy s8
Environment:staging 
Browser:Google chrome 
1.Login with valid user name and password. 
2.Go to help board.
3.Comment on any post and click newline key in mobile keyboard. 
Expected result 
It has to create new line
Actual Result
It acts as enter key.
GIF-201019_145135

### PR DESCRIPTION
**Pull request by BMariscal**
### What does this pull request aim to achieve? 💯

https://user-images.githubusercontent.com/13512876/102723594-e6997180-42bd-11eb-925b-5b8db1e3a674.mov

Closes #1672 

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Comment by rabbi08** [comment]
@BMariscal 
The review URL is not working, below error is displayed. I tried to re-run the jobs but still the error is displayed:

fight pandemics - welcome!
404 Page Not Found

**Review by OzkanAbdullahoglu — APPROVED** [review]
LGTM!

**Review by idjevm — APPROVED** [review]
LGTM!

**Comment by nivetheatha** [comment]
Tested in Android mobile.
Newline creates new line and not acting as Enter key.
Tested in staging works as expected.

**Pull request merged**
