### PR TITLE
Added accessiBe script tag

### LINKED ISSUE #1309: [Accessibility] Create standards for accessibility or use a third party
### We currently don't have any accessibility standards for our Product, Design, or Front End Engineering Team to follow. Although I don't have a lot of experience with accessibility, I've done a bit of research and it actually looks like it would be easier to just use a third party company that uses AI to add accessibility. 
---
### Here is a website I found that would do just that: https://accessibe.com/ and it would cover WCAG 2.1, Section 508, ADA Title III, and EAA/EN 301549. 

It's not free though, at **49/month**, so we may want to see if someone can reach out to them on whether they would provide a service for us at no cost. 

Any other ideas are welcome. This was created more to just get the conversation started.

### PR DESCRIPTION
**Pull request by kterry1**
### What does this pull request aim to achieve? 💯
We've been given an account with AccessiBe so I added the script tag that will allow accessibility on the platform. 

**fightpandemics.com** is the website that the account is under, but I added a 7-day trial for **staging.fightpandemics.work**

It will need to be push to staging in order to test it as it won't work with localhost:3000 but it can be tested here in the meantime: https://feature1309.fightpandemics.xyz

It takes about 5 minutes until the Accessibility screen will begin to show: https://share.getcloudapp.com/2NuylXnk

And Accessible said it takes about 48 hours for the AI to scan the UI and allow it to fully function. 

_Please be concise and link any related issue(s):_
Resolves: #1309 

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix. The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

### CODE REVIEW

**Comment by joshmorel** [comment]
Thanks @kterry1 I'll take a look today.

**Comment by kterry1** [comment]
@joshmorel Thanks! The trial for https://feature1309.fightpandemics.xyz and http://staging.fightpandemics.work are only available for 7 days. The subscription that AccessiBe gave Yegor is just for https://fightpandemics.com, so after 7 days this won't be seen on staging, but will be available when pushed to production. Let me know if that's confusing at all or if I need to explain further.

**Comment by joshmorel** [comment]
@kterry1  that makes sense.

The review service in fargate was stopped as it had not been deployed to for X days (I think 2?).

I added a commit to resolve the conflict and hopefully it will restart.

I see the video but it would be nice to see it in action before merging to staging.

**Comment by joshmorel** [comment]
@kterry1  - the new commit didn't work. I asked @mannykary if he has a suggestion.

**Comment by mannykary** [comment]
> @kterry1 - the new commit didn't work. I asked @mannykary if he has a suggestion.

Looks like revival of the review build never worked at all. I will open a PR to fix this issue, but in the meantime I manually revived the build in the AWS console by setting the Fargate service desired count to 1.

**Comment by joshmorel** [comment]
> in the meantime I manually revived the build in the AWS console by setting the Fargate service desired count to 1.

Thanks it's working. Now I know what to do as well if need be in AWS.

**Review by joshmorel — APPROVED** [review]
Got it to work by hitting tab - was able to change things, then disable it. Seems pretty good and shouldn't interfere with use by the typical user.

Pretty cool product!

Before you merge - let's squash and merge so it's just one commit.

**Review by idjevm — APPROVED** [review]
LGTM! Pretty cool! It worked well in the review build

**Comment by rabbi08** [comment]
@kterry1 
As discussed in slack, in the desktop/web the accessibility icon is displayed over the 'close' button for the cookie banner. we have to move it up so that user can use 'X' the cookie banner message.

image

**Pull request merged**
