### PR TITLE
#1476 - Added seo4Ajax logo in AboutUs page

### LINKED ISSUE #1476: Add SEO4Ajax logo to /about-us partners
From: https://www.seo4ajax.com/ for our social sharing & SEO.

```data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAT4AAAAeCAYAAAC143KyAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAIkQAACJEBafl3xgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA1zSURBVHja7V0LcBXVGV6RN3f37t0EKKhgLYJCbYGqBeojKaC0Qqu01goDVmXUylTEqjgWNCCCosUO+KDCTOsoFKMkN8+GGV5FO0ixCAURShGFyiOSCuFNQrb/v/ck2Vz28Z/ds3uXxJ35JjfJnte/e777n/9xjqTrumSGFI9fJiXkWVJCWQpYB9gPqAPoAnAI6t4EP8vg5wJJVXPS23cCXK0lVXkYyi8H/AdQI6hfziD2E2T3Tbi/CPBPQCVHG+UNdSTif3O5txJk8A/4mQ8yfE7SYn15ZOgXeXl5rYqLix8sKSraBzhcXFR0BFANOAo4BjjOcAJwsqSkpIfA9m8FHCbioTDl4gEHCGMY6rONgYCviPJ6VuDYugA2czwrxFyPbXUHfMzZ1qzGSRuLdYHJNB9wJhQyaQSS648IpAKEHP9XyH1zJT6jX5oyvZG45FWc9Z+RsuU+RlktfruH/p01vqRCIMCywsL+QHrrgdB0KgoLCy8V1H4rwBadflUCOkWY+E4RxjDCZxvlHPI6DviGwPH1BhzU+a48zjayGOnxXIvxXUpNVlnOYpqdniHUAXk4PmSm5elRIj4guR/A/4+we3JTf0t8B36vJdetKS8Z5S6WOsDvn/no50lsO4hJmp+fHwPCmwtEVstDeoKJb4zOfz3ZgolviAd5zRM8xgFMw+K5JhHrlgEbOOsuAbQ25hsjlSUZJL3GZbCmXWKjVQ3NaN8siE9SFA3+t6fxPnkzLMUvZIS4gFj3l1C3apRRlWkC+rpd6tw5JvLlLUkmbysqKtrLS3iCiQ/l+m8PE/l/gHgLJb7VHuR1GtBD8DivA5zg6EMd4C6XOjsA1nCODe9v32g2g2VmBEiPEUz8RUvi0+RHI0d8mjLj3HvjDzCzQWf4/bB73ex+TbsYfj8upq/KXBEvbFlZWU8grhKvhCeY+O7RvV8zWiDxDfUhr4UBjBVNWWc4+lALuM2mrjaAMs4xbWAaoslfAGQTGeLT5JU2y9zXIkd8KeeKvQanyY8412vWEJXF4vorb/bzkq5evbo1aHiPMweFHgHiawv4zMdErma2oJZEfOt8yKsG0CuA8d4BOMvRD5TPMAs771LO8WwDZJ/rKAWPYmSIL6FUWRNfvDBKxCdld+zmarOTpDagfe1wqDOXEeQQwf2tlbp37+jl5Uwmk0OKk8ktIghPIPE9qPu/5rQg4hspQF5vBTTm+zn7cQwwyFT+dc7yuwEXWUeI0A3qFUaYi6qMM4z6mjIoEEhSKwvtKumuLcYLAuuTpilN+qOqA0he2oRyi41mu8w0tjcN25xIqGp/nheyIj9fAy3vdSCqOpGkJ4D40JbzhYCJfEKwxzKqxHcB4CMB8kLNrF9A457iwU57FeAFznL7nTRXiRSjx7SYTIFEfOBQCK0/Wny4S3/KTH2vSPvfKYz3i8oEBG/tOCCoSg+kVgNlqwImvkd0cde8FkB8twuU17IAx/6cB83PC1lKTsRHsb3d+zXxNXFsjCDIzYhNlLJiVzYNtJZnRWHigYbXBwKQV3nS5JLJQiwPn5MBEl+MxeK5XRig+2mGPJZRIr5WzJ5FkcNWond1YIDj/6MezJW+PLYlvt2ESVwNk/0P8HMiTNyRRqwa2rkkqe3XxGeLTzDThPV/HvvbPmq4CTo+wKywnnmH+aCqox2cF+2B8GYAKZ3mJjwIXi5NJq9v0BaDJb7fEV/0xwC/yKDHMirEN54og98DrifeWx7g+L04Krw4RGyJL+nTmH6EeTg/AJQCKfwZnBEvAKagpiip8k8MA76iXF7vxQyG+Iw+LHVFl05dQyI+DC2ZxOIQE+i4AVncxTdu/JLx9Ex+aaPlDQcy2ulBy9sF8Xx3MBuSFALxqUyTc7vQ29uOlfmA6LH8VjMkPgzx2EVcAmqsTCGRTIYEKIM2nNklXkNgLIgP0q1C9JAeS6V0yc/C5x9TiVAAOZvJ6KnQiC+hfAVZMdmpJW98GIz3Ag+kX+GX+IB8VCChJR40vCpY1k6GzA1LzT5A4nuG+LKPNZWhajFvNkPiu4849kf1pillNYQyqwKWAzqw3vNJergs/xXXvGKJ9dUZChXZCo6Cm0IlPlxuQqhJSMSHeNVXW+fYCPmJr6SwMIeT9E7BcvjF0tLShKNjJBjiwy+Ko4SX/cN0DRSQJHos+zYj4kONdy8xtKNdWtmXicQyNGBZxH16oydxz6tUeIYyPsOBy8uctD/BxIcYEyLxQd5up6t82jjnhUR8GM6yhEpWAREfNWzBKn+6D1GLeacZEd8korys3vnOgCOEsutCkAfu6LLDA+nleZpTpiDh57mS64UHCStPh0h860IkPtuMFHJ79TbCYImvGrS8qWAHHEEBbDeVTSE+sA2Oh3tvQvsiBEgPg+XzD+FzLvTpWouxdtNpeZ0lDvJ6lbg0GtAMiA93nzngUTuuxxNEghkZsDwwT/9zD8Q31xfxpQgm9m2Y1CsyRH61Upby/ZCIT4e2rgmN+Axil2/1qfVNDHGp60qS5eXlCoX4HOyHsy3GSVl6oRH7ShfNgbJULm0GxEclrVyHOjBxfw+hjo8cyNMvUPPc7mOpO9UX8TXalZRrYHJPZptd7g2R/F4JjfggYyJU4ksou2A5347PAGuEtDzU8BltohEgPtAM51OXujY4WlBQkJ4/24PFmLldmLY0AfCAA6jG8kHnMfGhXayKSPBjXeSVJMrr5wHZ9zYK8OpO9E18utUWTNlybyN9C72xmLYGoRrMI/wy29aqAn7fYExw9GZ627X5Pe/EB5uUYqwhFbi0t0iPC5D4sI9TPGh5Z+tT0AzPcOaJr66soKC3H+ID4rQK4l5EeLlRk8NwpHcFhUCsOI+JbzpRO+7L4cRwu7ax+LsoeXTN5ouxQonPEzmghoLbM2nyYMA9RM3xiFXIR+QCmLOUa4HE1vBDKaZqfcyud4iNb61JFkUZJb7i4jIe54bVMtlC2+tFdErUhyLdIDDoNSdDxHfGB/Gh/KqJ2jHefwUjBhHXOIExfH8VHMBcQ7VFhpl2NoamrSTiUSe+kOSV7sm9k2nfveDz6UwRH2Ru3OyL+JJJq7Md3iK81Pv0plvJbxI0Wd7PwPPtReybHfHNIZQ9xpxF9WWWC5LXLkZafrM23taDuU4CbowO8RkZHQTiy86WI6/xwRJZulRqLxqNsor1PTd2DzTmrl07MQ/8HJdttEYHRHyfmA3cHoivGneCSZNnP522T9uEtHL3CpwsI0ImvkXEflnFuOIuM8c9hHncIlBe9/kcP+/2UlWc92OIzkDnOZyQR6HHMRioo8EWONVY4tFCZQ75cG5UBDYOln1hIqZ+AThbluvu54vMTLWvKfBFctAhfKZJmhHa5GCJukAARvLG8UGZxabyVsukZYQXGQ8ZutDCPnRI0ET+ULc/pSxHENCrj46q9Rz9usKiT/MJ5XBLpvSccPzC2ilIXnstgqGpmMPZ1gGmIU/jLFfJ4jptc3W3R2gj0rXW2iLstReljUhR40soRwW2UVN/SprxRWR/H25pdVlKJvIEh/72DENzERDAPJBoe7I7hW+2QC3GKs+zQM/cVWOxpKR6vu/3GexMuSZ5eGee5GwD87XNB2i9xFl+j26zI4/EkvcjQnzWy1XmOY7Y1vOGs0JUG/MZobaFzztd7k2ayHej1WYNYS3ZBBAf5ewEJ89rDxZftskFe4haZbrHMi+DxLfDYrwLiZ5Xuywo3FB3A0FenxI1MZ7jO3l30kYb5WALrfVPHuTYxWqp+3iEiG+UjX1wcvQOG5J/K2q7fQwXYtreY7RMkPhw4341doOFDGefJ8Q3mBiiICLDohvRLnZnWrmfZZD4XvHo+R4lQF5oZ6ecifsEsb6xnF5l1GqH6/Yn7vFq4hv1tNP2UvYidy0jDCyx93Aa59dmkPhiN1o6OPgPD7dK1fuNUR9sl9VwRq87tpn2+ss3xQn+t55EzwPiW0l4Yd8Q2N/pRO3ArC215bTJibo+Z9oZr+d7jUB5/ZrodFBc6hlFJGxz7OFo3X1jhhWcMl3L7MLmTQrU/qkDqTNFLjBh4VBzZ68wbGQQtQPFszt2d3QyuOPjBgJT44v48n+VyezZ9WTPDnJ55evC9E76IL5cYljCJQL7G9Npea136+fmkH4ZIumhZjTMg+cby10tUF74XlLSyKY71JHDniPP2O/meJ68X0pl9XZTc8Ds98CD+a6RKRDq/nzKzPTDfCxJJqvDRZjZESXi0xsOFpdns7Fw7kqT2pILZD/Qg9wPQ4B4F6b1jcWzecOOR/NBfH8nvKRBLNkpp3ztZpqeuRw6nv7CtJEgL9yUs79Hz/eSAOT1U0K7dsd3Xq3TgqzN18Oc/cPVzVbONlBOrawm8uWw/JoGGsjC1NGTkAqGe9ipygFfSCj7jbNkU5kH8wy7XedO3CdfsUDoNwDvG7FtfvtFQVp4iGW/MEsF8mrZFv0QfiNvMsZsL4+3G8qq8jt0Gca3pJ6LvCBsDU8Q8aHt5pQLviAsobwAl7GbCe1PsCmPHvWZjATXMifAcUJ9VjjINBZ8D54H2D3L7+qpHWuc6kKCCeoAq5WEsTxj4XTayjRsKp722L/u7JnytPXU/wEsUT07IDvuwQAAAABJRU5ErkJggg==```

### PR DESCRIPTION
**Pull request by mathigayathri2001**
### What does this pull request aim to achieve? 💯

_Please be concise and link any related issue(s):_This PR resolves #1476 

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [X] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Review by joshmorel — CHANGES_REQUESTED** [review]
Thanks @mathigayathri2001.

It doesn't look as distorted as the pic you shared in slack so I'm cool with it but can we put it in alphabetical as we've been doing (before slack).

I'm also curious what it looks like as the original PNG (maybe not so good for whatever reason as I just tried it...).

**Review by idjevm — APPROVED** [review]
LGTM !

But keep in mind that a new About Us page is coming up, so this might not be relevant anymore. Would be nice to add it to that specific PR.

**Comment by mathigayathri2001** [comment]
> LGTM !
> 
> But keep in mind that a new About Us page is coming up, so this might not be relevant anymore. Would be nice to add it to that specific PR.

OK Thanks. Please let me know the specific PR number so i can go and review it .

**Comment by idjevm** [comment]
Here it is -> #1532 - Perahps you can combine forces and figure out the mobile version on this PR.

**Comment by mathigayathri2001** [comment]
> Here it is -> #1532 - Perahps you can combine forces and figure out the mobile version on this PR.

Thanks.. I have reviewed the details in  #1532 .  I could not able to access the following.
Design Mobile: https://zpl.io/aROKRRN
Design Mobile with popup: https://zpl.io/2GZ5L09
 I have received error message "You are not invited to this organization". Please provide the access and let me know.

**Comment by rabbi08** [comment]
@tejasm2 @mathigayathri2001 
It looks that after new 'About Us' page this issue is no longer valid. Kindly review and close if we do not need this update on About Us page anymore. Thanks

**Comment by rabbi08** [comment]
The issue have been already resolved the 'seo4Ajax' logo is displayed on the About Us page. Please refer below screenshot.
Screen Shot 2021-03-01 at 3 38 51 PM

Thanks

**Pull request closed without merging**
