### PR TITLE
Feature/fix the shivering elements across the platform

### LINKED ISSUE #1248: Fix the shivering elements across the platform
The text elements when hovered over distort the other elements. Please fix them to have stability and not distort other elements or introduce a scroll bar on the page
Please check this in the following pages/features
- [ ] filter with location
- [ ] header
- [ ] visibility of posts in the post modal window
- [ ] onboarding pages
- [ ] Individual profile
- [ ] Create org profile
- [ ] Sign in page
- [ ] Join now page

### PR DESCRIPTION
**Pull request by phuclb**
### What does this pull request aim to achieve? 💯
Resolves #1248

_Please be concise and link any related issue(s):_

- [ ] I have checked that no one else is working on similar changes.
- [ ] I have read the latest [**README**](https://github.com/FightPandemics/FightPandemics/blob/master/README.md) and understand the development workflow.
- [ ] The name of this branch is: **`feature/<branch_name>`** (need to have cloned the repo not forked).
- [ ] This branch is rebased/merged with the **latest master**.
- [ ] There are no merge conflicts.
- [ ] There are no console warnings and errors.
- [ ] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

### CODE REVIEW

**Comment by ppagarawal** [comment]
lgtm. The bold feature has been removed but the blue highlight shows the current page

**Comment by phuclb** [comment]
Yes, I just updated hover state only. For active state, bold should be used as current.

**Comment by ppagarawal** [comment]
@phuclb Please check for Profile tab as well. Currently, it isn't highlighted when a user selects my profile or any of his org profile.

**Comment by phuclb** [comment]
I will review it tomorrow.

**Comment by rabbi08** [comment]
@phuclb @ppagarawal 

I have verified first 2 options fixed from #1248 :
1. Shivering effect while user try to enter location during filter -> PASS
2. Shivering effect while hovering in the nav bar: PASS

https://share.getcloudapp.com/ApuA7qLe

3. On Profile TAB -> "Profile" TEXT is not BOLD like 'About Us/Helpboard', looks like @ppagarawal also mentions this.

https://share.getcloudapp.com/OAuBpvgl

Also, the extra space added in 'Filters Block' is not verified as there is no noticeable difference in the space. Let me know if I am missing something here.

**Comment by phuclb** [comment]
Hi @rabbi08,

For active state on Profile, we need to update code (Ant, React) to let the page know when subpage of Profile is active.
We need another guy who can update this.

Phuc.

**Comment by phuclb** [comment]
I also updated to resolve this effect in other places of the site (Profile, Post, SignUp, JoinIn,...)

Please review again.
We also need a solution for Profile active state, help from dev guy.

**Comment by phuclb** [comment]
Hi @ppagarawal,

As discussed with you, this issue is completed.
For Profile (on Header) and error message, we should consider is as another issues.

Phuc.

**Comment by rabbi08** [comment]
@phuclb 
Currently I am getting error while trying to access the feature link:

 https://featurefix-the-shivering-elements-across-the-platform.fightpandemics.xyz

503 Service Temporarily Unavailable

**Comment by phuclb** [comment]
Hi @idjevm, can you help to review this PR?

**Comment by phuclb** [comment]
Hi @idjevm, is this issue resolved?

**Comment by ppagarawal** [comment]
@idjevm pinging to raise bring this to closure

**Comment by phuclb** [comment]
I close this to reopen another new one.

**Pull request closed without merging**
