### PR TITLE
Feature/correct password change content

### LINKED ISSUE #821: [Desktop] [Mobile] Recovery password screens are incorrect when email with a recovery link was sent
env: staging

Steps:
1. Go to the login screen and press Forgot password? hyperlink
2. Enter email and click: Email me a recovery link
3. For a desktop you'll see:
Screen Shot 2020-06-25 at 19 55 25

For a mobile you'll see:
Screenshot_2020-06-25-19-57-24-003_com android chrome

In zeplin there is a screen for a MOBILE:
https://app.zeplin.io/project/5ecaed1b2522d9280f1a4792/screen/5ed562d60bba151f41673497

**We need the same screen for desktop.**
We have only this screen for sign-up confirmation:
https://app.zeplin.io/project/5ecaed1b2522d9280f1a4792/screen/5ed55f6ecb9fd341cc291344

### PR DESCRIPTION
**Pull request by joshmorel**
### What does this pull request aim to achieve? 💯

Resolves #821

I'm re-using the `verify-email` page here but renamed path to `check-email` so it makes sense for both. These auth pages - Login & VerifyEmail are in need of a refactor anyways. Instead of one page `Login` acting for multiple pages we should have one page per route BUT with common `auth` components so the layout etc align.

Also addresses un-aligned title & instructions:

before:
image

fixed:
image

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](https://github.com/FightPandemics/FightPandemics/blob/master/README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`** (need to have cloned the repo not forked).
- [x] This branch is rebased/merged with the **latest master**.
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

### CODE REVIEW

**Comment by idjevm** [comment]
Right now it just says that an email was sent but idk where :O and I left the screen open and when I came back, I don't know which test email I was using lol so it would be useful to know I guess?

**Comment by joshmorel** [comment]
> Right now it just says that an email was sent but idk where :O and I left the screen open and when I came back, I don't know which test email I was using lol so it would be useful to know I guess?

I'd prefer that as well I was just matching the design.

Another thing I don't really like is "Recover Password" title simply because we aren't recovering it we're changing it!

Thoughts @galeza @indirabhowmick @vikjoshi ?

**Comment by vikjoshi** [comment]
> > Right now it just says that an email was sent but idk where :O and I left the screen open and when I came back, I don't know which test email I was using lol so it would be useful to know I guess?
> 
> I'd prefer that as well I was just matching the design.
> 
> Another thing I don't really like is "Recover Password" title simply because we aren't recovering it we're changing it!
> 
> Thoughts @galeza @indirabhowmick @vikjoshi ?

I agree- would be good to have email url in the message like we do on the welcome email. Lets put this in on this PR if its quick and easy

@idjevm @joshmorel

**Comment by joshmorel** [comment]
@vikjoshi @indirabhowmick @idjevm 

I updated the content to include email, expand the note on checking other folders (both for verify email & change password). Generally I made them more consistent as I think we had discussed doing some time ago (when 1st implementing change password).

image

**Comment by joshmorel** [comment]
@idjevm Are you talking about what happens here:

image

Interesting it didn't work for me once then it did, now it's not at all. 

If this is the case - I'll try to look into Auth0 settings tomorrow or later. There's nothing in the code base here we can change so if all else is good once I get confirmation from @indirabhowmick  & @vikjoshi on the content let's merge this.

**Comment by idjevm** [comment]
No actually, I mean on the FP page, the `check-email` path, the logo there does not allow redirection to anywhere.

**Comment by joshmorel** [comment]
Oh that. It's something to do with our messy `RouteWithSubRoute` redirect logic that I created an issue to refactor here: https://github.com/FightPandemics/FightPandemics/issues/1164

In the interim I might be able to fix this specific issue although it's not necessarily as straight forward as it should be (thus the refactoring).

I do still need to fix the redirect settings in Auth0

**Comment by joshmorel** [comment]
@idjevm  Basically what's happening is you click on login and then it's redirecting you back to `auth/check-email` because of some condition within this giant nested if-then-else structure. Changing this condition is hard without breaking something else. 

Not sure why it was set this way up originally but it does need a refactor and I'd rather wait to refactor the whole thing as I don't think this is critical (also not straightforward).

If we can get Auth0 settings working then really the user's next actions would be to check email, then set password, then **ideally** redirected from Auth0 to our login page. Then the prior tab then becomes irrelevant.

So I'll look into the Auth0 settings tomorrow morning.

**Comment by vikjoshi** [comment]
@joshmorel @idjevm , I tested this on https://featurecorrect-password-change-content.fightpandemics.xyz.  I tried twice and both times did not receive the email- definitely put in the correct email. 

Any ideas?

**Comment by idjevm** [comment]
I think as mentioned by @joshmorel, it won't work on the review branch, but not sure though

**Comment by joshmorel** [comment]
@vikjoshi Interesting. It is enabled & actually did work for me. 

The whole flow will never work because of the variable subdomain we can't redirect after verify email or change password. 

Also on my email - I see dmarc=none (unlike with staging which passed). Might also be because of variable subdomain?

So long as the page is okay, let's test the full thing on staging. The not redirecting however - I need to fix in Auth0 https://github.com/FightPandemics/Auth0/issues/10

**Comment by vikjoshi** [comment]
> @vikjoshi Interesting. It is enabled & actually did work for me.
> 
> The whole flow will never work because of the variable subdomain we can't redirect after verify email or change password.
> 
> Also on my email - I see dmarc=none (unlike with staging which passed). Might also be because of variable subdomain?
> 
> So long as the page is okay, let's test the full thing on staging. The not redirecting however - I need to fix in Auth0 [FightPandemics/Auth0#10](https://github.com/FightPandemics/Auth0/issues/10)

Sounds good to me! Will test it on staging.

**Comment by rabbi08** [comment]
Verified and Tested on Desktop and iPhone:

Recovery Password feature and screens working as expected. I receive the email in my hotmail INBOX as shown below:
image

GIF Showing change password process:

https://share.getcloudapp.com/6qu249Ag

I am able to login with new updated password:

Below are screens captured from desktop and iPhone.
DESKTOP:

image

IPHONE:

image

**Comment by vikjoshi** [comment]
Tested on my end as well and it is looking good. Thank you!

**Pull request merged**
