### PR TITLE
Fixed email style to match desired outcome and enabled the email field

### PR DESCRIPTION
**Pull request by omarzoghayyer**
### What does this pull request aim to achieve? 💯

Fixed email style to match desired outcome and enabled the email field

### 🚨Before submitting this pull request🚨:

_Please do **NOT** submit this PR if you have not done the following:_

1. I have checked that no one else is working on similar changes.
2. I have read the latest [**README**](https://github.com/FightPandemics/FightPandemics/blob/master/README.md) and understand the development workflow.
3. The name of this branch is: **`feature/<branch_name>`** (need to have cloned the repo not forked).
4. This branch is rebased/merged with the **latest master**.
5. There are no merge conflicts.
6. There are no console warnings and errors.
7. On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

### CODE REVIEW

**Comment by robinv85** [comment]
@omarzoghayyer the email field is supposed to be dsiabled

**Comment by anniegiang** [comment]
> just going to mark this as requesting changes since @anniegiang approved this and i think this shouldn't be merged, looks like a misunderstanding?

We're talking about this email field right? Is the text for it supposed to be a gray color? If so I didn't know so I'll un-approve this.

**Comment by robinv85** [comment]
@anniegiang yes the email is currently always greyed out and disabled
For MVP we only have profiles that have a verified email through Auth0, either verified after signup with email or from a social media account.
This means that "create user profile:" step currently only allows to see the email
Later we can probably extend this so if you register for example through Twitter, you can also add an email there, and then the verify email step occurs after that
I think this issue can be closed?

**Comment by robinv85** [comment]
going to close this since it seems like it was a misunderstanding

**Pull request closed without merging**
