### PR TITLE
263

### PR DESCRIPTION
**Pull request by omarzoghayyer**
### PR Checklist:

Hey there! It's great to have you here. Here's a quick checklist to help you make a shiny PR:

* [x] Have you checked out the guidelines in our [Contributing](../CONTRIBUTING.md) document?
* [x] Have you looked if there might be other open [Pull Requests](../../../pulls) for the same update/change?

**### Quick Description of the PR**

      Reference ticket: #263 
      Imported ValidateEmail to validate if the input is following the validation conditions.

**What does it aim to achieve, and why?**
     This PR is aimed to fix the email validation form. Follow the steps below in order to examine it.
     env: https://staging.fightpandemics.work/offer-help

      steps:

         From main menu select Give Help. Question 1 screen is open.
         Do not select any checkbox
         Click on next arrow.
         Repeat for Question 2 and 3 pages.
         On the Question 3 screen click submit
         There should be error messages - select data

### An Overview of the Changes
* A few notes on your commits.
I imported Toast from antd-mobile in order show the invalid messege.
* To help understand them.

### CODE REVIEW

**Comment by manualzuru** [comment]
@omarzoghayyer what should we do with this issue?

**Comment by omarzoghayyer** [comment]
@manualzuru This is a duplicate issue. Robin has asked to implement a new way of validating emails, so my solution here is invalid.

**Comment by manualzuru** [comment]
@omarzoghayyer dyk which one is that issue?? Let's link them because I'm seeing the one that is link and is the other one where I made the comments

**Comment by omarzoghayyer** [comment]
@manualzuru Its already been linked to Add validation. Issue number #263

**Pull request closed without merging**
