### PR TITLE
Cypress test for Request Help questionnaire

### PR DESCRIPTION
**Pull request by jessica-lau**
### What does this pull request aim to achieve? 💯

Created automated test for Request Help questionnaire. **Please note question 3 will be removed completely so I did not write any test for it.** Refer to [PR#1422](https://github.com/FightPandemics/FightPandemics/issues/1422) for details.

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix. The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

### CODE REVIEW

**Review by galeza — CHANGES_REQUESTED** [review]
I would change only one thing: I would add a function. Something like:
    function xxxx(button){
        button.should('be.visible');
        button.find('img').click();
    }
and then do not repeat this code four times but call this function and keep code DRY.
Would you think about this?

**Comment by jessica-lau** [comment]
@galeza I think creating a function is a good idea in order to simplify and clean up the code. I'll make the changes. Also, thanks for reaching out to Emily about how we will proceed with the Next button and Post link that directs to Question 3. I'll need to make the necessary changes once we know what is going to be done.

**Comment by jessica-lau** [comment]
I just updated the code with a function for the back and next buttons.

**Review by galeza — APPROVED** [review]

**Review by idjevm — APPROVED** [review]
LGTM! @galeza Should I merge it or wait?

**Comment by galeza** [comment]
@idjevm 
Please, merge

**Pull request merged**
