### PR TITLE
test for share location for nearest hospital

### PR DESCRIPTION
**Pull request by JayashreeSamantasinghar**
### What does this pull request aim to achieve? 💯
tests for nearest hospital page
_Please be concise and link any related issue(s):_

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`** for a regular feature, **`hotfix/<branch_name>`** for a hotfix, and **`service/<branch_name>`** for a microservice, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Comment by adorapham** [comment]
@JayashreeSamantasinghar -shareLocationTextElement = " div.sc-gySEy.kVuBbU > h1";
i think sc-gySEy.kVuBbU is not consistent value across env.  just wait to see others's comment on it.

**Review by adorapham — CHANGES_REQUESTED** [review]
@JayashreeSamantasinghar -shareLocationTextElement = " div.**sc-gySEy.kVuBbU** > h1";
i think sc-gySEy.kVuBbU is not consistent value across env.  just wait to see others's comment on it.
similar like failedPredictionsMessage = "small[class='**sc-ksluoS doFBMb']**";
when I run on localhost the test is passed 
image
but when I run on staging , I get two failed
image
image

**Comment by JayashreeSamantasinghar** [comment]
@adorapham 
I changed locatorname for "shareLocationTextElement" and removed the test case for "failedPredictionMessage" as it is  difficult to capture the locator for this error message as well. 
Please run the latest codes in staging. Hopefully it will work

**Review by jessica-lau — CHANGES_REQUESTED** [review]
The below test failed

image

**Comment by adorapham** [comment]
@jessica-lau @JayashreeSamantasinghar I  pull the latest and it works , see the codes not containing the static value.  I test both localhost and staging , both are passed
  shareLocationTextElement = "//h1";
  adressSearchInput = "#NH_LS_EAZ";
  listOfNearestLocations = ".rc-virtual-list";
  nearestLocationsTagName = "div";
  enterAddressText = "//small";

image

image

**Review by adorapham — APPROVED** [review]

**Comment by JayashreeSamantasinghar** [comment]
@jessica-lau 
Please confirm ,was that test case failed in staging env?

**Comment by JayashreeSamantasinghar** [comment]
@adorapham Thanks for testing in both environments

**Review by jessica-lau — APPROVED** [review]
Works now. LGTM

image

**Review by Selbinyyaz — APPROVED** [review]
LGTM @JayashreeSamantasinghar  
Screen Shot 2021-03-12 at 11 22 03 AM

**Comment by JayashreeSamantasinghar** [comment]
Thanks everyone.
@ddveloper 
Please merge this PR in staging, whenever you will get time.
Thanks

**Comment by rabbi08** [comment]
LGTM
Thanks @JayashreeSamantasinghar

**Review by rabbi08 — COMMENTED** [review]
LGTM

**Pull request merged**
