### PR TITLE
Feature/symptom checker button refactor

### LINKED ISSUE #1364: Symptoms-Checker [Desktop]: Fix Previous and Next Arrow Buttons
**Goal**

Currently, the Desktop view for symptoms-checker previous and next arrow buttons are disproportional. Cosmetic fixes are required. Make sure those changes won't affect the Mobile view.

### PR DESCRIPTION
**Pull request by kterry1**
### What does this pull request aim to achieve? 💯
- Moved navigation buttons below the answers in the symptom checkers for Step 2 and Step 3: 
Before: https://share.getcloudapp.com/p9uGw4xD   After: https://share.getcloudapp.com/2NuyjQBk

- Removed the image margin in the nav buttons that was throwing off look of the buttons:
Before: https://share.getcloudapp.com/12uJrdxg  After: https://share.getcloudapp.com/NQur19yp

- Aligned the text for the page before the Symptoms Checker pages:
Before: https://share.getcloudapp.com/nOukn48e  After: https://share.getcloudapp.com/8LuPrW74

- Added a few missing colons in the styled components for SymptomsCheck.js

_Please be concise and link any related issue(s):_
Resolves: #1364 & #1363

- [x ] I have checked that no one else is working on similar changes.
- [x ] I have read the latest [**README**](README.md) and understand the development workflow.
- [x ] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix. The branch is created in a cloned version of this repo, **not a forked repo**.
- [x ] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x ] There are no merge conflicts.
- [x ] There are no console warnings and errors.
- [x ] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

### CODE REVIEW

**Comment by kterry1** [comment]
To clarify, the changes I made were for desktop only. I can go back and refactor the buttons for mobile view, or we can just create a new issue for desktop-mobile.

**Review by ralbach — CHANGES_REQUESTED** [review]
The WizardNav move buttons based on question length has already been fixed on [one of my other branches for staging](https://github.com/FightPandemics/FightPandemics/pull/1347). You can take that out and I'll add a comment that closes that ticket.

The other changes should be fine and won't make any conflicts. 

I should have documented better after the Sheeba requested changes in my code.

**Comment by kterry1** [comment]
@ralbach Sorry for the delay on this. I'll take that out tonight and re-request a review once the code is pushed up.

**Comment by kterry1** [comment]
Easier than I thought. I committed the changes and re-requested a review. Thanks!

**Review by ralbach — APPROVED** [review]
Nice thanks for knocking that out @kterry1 - we need to get some of these PRs done before we start to work on questions and mobile refactors or things are gonna get messy next.

**Comment by rabbi08** [comment]
Temporary closing this PR, but it will stay in 'Symptoms-Checker' as currently the priority for this feature is very low, hence trying to save some AWS credit by deleting the branches of low priority features.

Please feel free to re-open or create new when needed. Thanks.

**Pull request closed without merging**
