### PR TITLE
AboutUs page - Add IDs for e2e tests

### PR DESCRIPTION
**Pull request by galeza**
AboutUs page - Add IDs for e2e tests

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Comment by galeza** [comment]
@Zaydme 
Please check if I added IDs correctly.
Our goal is to have IDs for supporters containers and Press button.

**Review by TimeaKovacs86 — APPROVED** [review]
I think it's good.... I will refactor my tests based on these new IDs, then those tests will fail, but when both merged to staging it will work. ( Just to not bump in merge conflicts. )

**Review by Zaydme — APPROVED** [review]
LGTM

**Review by jessica-lau — APPROVED** [review]
LGTM. thanks for adding these @galeza

**Pull request merged**
