### PR TITLE
removed empty space on cookies policy page

### LINKED ISSUE #643: Content update on Cookies policy page
Please update the content to remove extra line in cookies policy page

image

Output should look like:
I. This website uses...

### PR DESCRIPTION
**Pull request by nadinejuraschek**
closes #643

### CODE REVIEW

**Comment by robinv85** [comment]
Ah oops yes good point @idjevm 
i wonder if something went wrong with that file if its showing up for everyone

**Comment by idjevm** [comment]
> can you remove package-lock?

I think it is because people are running `npm install` instead of `docker-compose run client npm installl`<-  Just a thought though, but from my side, running the client with docker doesn't affect the `package-lock.josn` file.

**Comment by robinv85** [comment]
Yeah possibly, unless someone forgot to add the lockfile after updating and somehow it causes this for more people that the lock file is also updating or something like that

**Comment by idjevm** [comment]
Closing this PR as it will be resolved with PR #665

**Comment by manualzuru** [comment]
@idjevm @nadinejuraschek should we move this to Done on the project?

**Comment by idjevm** [comment]
Yes please! This was resolved with another issue and PR for that other issue!

**Pull request closed without merging**
