### PR TITLE
Conditional Logo Link Based on Auth State

### LINKED ISSUE #1271: Redirect a logged in user to the help board when he clicks on the logo
As a logged in user, I want to be redirected to the Help Board when I click on the FightPandemics logo from any page.

For a non-logged in user, clicking on the FightPandemics logo will redirect them to the homepage.

### PR DESCRIPTION
**Pull request by RF9A5V**
### What does this pull request aim to achieve? 💯

Should bring you to the homepage when clicking the logo if you're not logged in, and bring you to the feed page if you are.

_Please be concise and link any related issue(s):_

Closes #1271 

- [X] I have checked that no one else is working on similar changes.
- [X] I have read the latest [**README**](README.md) and understand the development workflow.
- [X] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix. The branch is created in a cloned version of this repo, **not a forked repo**.
- [X] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [X] There are no merge conflicts.
- [X] There are no console warnings and errors.
- [X] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

### CODE REVIEW

**Comment by galeza** [comment]
I added also other QAs.
Now navigating to the home page is difficult. I navigated between pages and then I wanted to move back 
to the Home Page (I had to press Back button several times).
I'd like to hear the opinion of other QAs.

**Comment by jessica-lau** [comment]
While logged in, when I click on "Add Organisation" under "Profile" it brings me to the "Create Organisation Profile" page, and then from there when I click on the FP logo, it'll bring me to the homepage instead of the feed page.

**Comment by jessica-lau** [comment]
I agree with @galeza. Since there's already a Help Board link in the navigation bar, it would be helpful to either add a Home link in the navigation bar or just make the FP logo only redirect user to home page regardless if they're logged in or not. When the user is logged in, it's currently difficult for them to get to the home page if they wanted to.

**Review by rabbi08 — CHANGES_REQUESTED** [review]
1. For logged in user
Add Org -> Click FP logo : Lands on home page rather than Help Board

https://share.getcloudapp.com/DOuxQenL

As per the functionality implemented in this PR, yes the logged in user cannot navigate to home page, but all the functionality present on the home page is available to the logged in user in help board, i.e. logged in user can request or offer post through help board, he don't need home page to use that functionality.

**Comment by sheeba1** [comment]
As a logged -in user , when I click on FP logo, I would expect, to get back to **home page** as I can go to 'Feed' by clicking on 'Help Board' . The 'Help Board' link is available from different pages except for create Org for a logged in user

**Review by sheeba1 — COMMENTED** [review]
As a logged -in user , when I click on FP logo, I would expect, to get back to home page as I can go to 'Feed' by clicking on 'Help Board' . The 'Help Board' link is available from different pages except for create Org for a logged in user

**Review by jessica-lau — COMMENTED** [review]
Please see comments I left above.

**Comment by RF9A5V** [comment]
@rabbi08 @jessica-lau @sheeba1 

Required changes to the layout without the navigation links on the right have been made, sorry about that. According to @manualzuru, this should be the intended behavior. I don't believe there's any functionality that a logged in user has on the landing page that isn't just accessing the feed page. Perhaps going through the more interactive filter flow, but that's also possible via the sidebar on the feed page itself, though with less fanciness. Please review again when you get the chance.

Thanks!

**Review by jessica-lau — COMMENTED** [review]
When logged in, clicking the FP logo while on the "Create Organisation Profile" page now brings me to the Help Board as intended.

**Review by rabbi08 — APPROVED** [review]
-> For logged in user
Add Org -> Click FP logo : Lands on Help Board as expected. 

Thanks.

**Comment by pemika-me** [comment]
I have just tested recently, and the page was now developed and showing results as per the expectation. By the way, I agreed with Sheeba and JV (in the redirect link) that the logo should just navigate either logged in and non-logged in user to the homepage as we already have the Help Board bar at the top of the website no matter which pages the users are in (except Add Org. as Sheeba mentioned). 

In my view, it would be easier for some users in case the logged-in user want to apply filters through our onboarding survey at the homepage rather than manual selection. This can be another option for them. Also the home page is more fit to see all links at once for users to further navigate rather than Help Board page (users have to scroll down endlessly to reach the links at the end of the page in case they have no idea that they would have to navigate to About Us page to arrive those links faster). But well, because now the onboarding survey always asks all users to input their email in the last question although they already logged in to the website (as I tested), this solution would cause less complex coding at this moment.

**Review by jessica-lau — APPROVED** [review]

**Review by idjevm — APPROVED** [review]
LGTM! Just please confirm that this is good to go @ppagarawal so I can merge this!

**Comment by ppagarawal** [comment]
Please go ahead @idjevm ! :rocket:

**Comment by idjevm** [comment]
@ppagarawal not sure if this was implemented but please double check. This contradicts parts of the ticket requirements -> 
image

**Comment by ppagarawal** [comment]
> @ppagarawal not sure if this was implemented but please double check. This contradicts parts of the ticket requirements -> 
> image
> 

@idjevm ignore this comment please. It won't be required to get back to the homepage for a logged in user as he won't have anything to do there. All the questions he answers in onboarding can be settled in the help board as well.

**Comment by idjevm** [comment]
@galeza please add a new comment here instead, cuz it looks like @ppagarawal was the one who was calling himself. And I don't know, I am asking if that was implemented or not.

**Comment by galeza** [comment]
@idjevm 
Ok, I'm adding a new comment.

@ppagarawal 
Please review QAs comments where people stated that they expect to open Home screen.

**Review by galeza — APPROVED** [review]

**Comment by galeza** [comment]
Approved.

**Review by idjevm — APPROVED** [review]
Alrighty then, merging this now.

**Pull request merged**
