### PR TITLE
workaround for toggle show less/more

### LINKED ISSUE #2005: When creating a post , then right after creating more than 5 comments, the show more comments or show less comments doen't work
please see the below flow

1-Login as user
2-Navigate to Feed page
3-create a post
4-then on the post page, create 6 comments right away
5-click on show more comments or show less comments, the same last 5 comments on the display
6-user needs to click on page refresh icon in order to see the show less comments and show more comments are working
this is only for new post with new comments , for the existing post with already comments (adding or existing more than 5 comments  are working fine)
please see the screenshot
showMoreShowLessComment

### PR DESCRIPTION
**Pull request by ddveloper**
### What does this pull request aim to achieve? 💯

_Please be concise and link any related issue(s):_
 to fix comments `show more`, `show less` button not functioning when creating 5 + comments along with creating a new post

 to fix #2005 

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Comment by rabbi08** [comment]
@ddveloper 
- The button should be 'Show less comments' when user enter comments >5 and the button appears first time. Also, all the comments should be displayed and toggle instantly when clicked.
- The comments does not visible/appear if some comments are deleted. so it show no comment by the count say '1'
<this issue might be introduced by PR #1957 > Please investigate

Please note, These issues does not exist PROD as of today.

Refer below GIF.
ezgif com-video-to-gif-7

**Comment by adorapham** [comment]
@ddveloper , @rabbi08 , the fix is good for show more or less if comments >5. but it doesn't work when deleting comment in show less mode, i have the same thing like @rabbi08 , it is kind of when you delete a comment, you need to find out if the mode is show less or show more in order to have at least 5 comments in the display. and then when you delete a comment , the number of comments on the top matches correctly with list of comments in the display.

**Comment by rabbi08** [comment]
Adding GIF from PROD, showing the behavior of 'Show more/less comments'

ezgif com-video-to-gif-4

**Review by mannykary — APPROVED** [review]
LGTM

**Comment by ddveloper** [comment]
will merge this first, remain issues will be tracked in new tickets 🔢

**Comment by ddveloper** [comment]
@BMariscal  would you please review this workaround ❓ I didn't figure the root cause at that time, let me know if you have any ideas 😬

**Pull request merged**
