### PR TITLE
 Wrote additional tests for new languages on header section

### PR DESCRIPTION
**Pull request by adorapham**
1-Update the header.spec.js to check all new updated languages

### What does this pull request aim to achieve? 💯

_Please be concise and link any related issue(s):_

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Comment by adorapham** [comment]
Hi All, I fix the error on new id button with image and update the validation for all the new languages.  Please help to review. TY

**Review by TimeaKovacs86 — APPROVED** [review]
LGTM.  All tests passes! Thanks @adorapham

**Review by jessica-lau — APPROVED** [review]
LGTM. thanks @adorapham 

image

**Review by galeza — APPROVED** [review]

**Comment by JayashreeSamantasinghar** [comment]
Thanks for fixing this.

**Review by JayashreeSamantasinghar — APPROVED** [review]
code looks good for me.

**Comment by adorapham** [comment]
Thank you ALL for review this :)

**Comment by adorapham** [comment]
@ idjevm @galeza , please merge if you can at your convenience time.

**Review by idjevm — APPROVED** [review]
LGTM! Thank you @adorapham !

**Pull request merged**
