### PR TITLE
Feature/email sign up/1422

### LINKED ISSUE #1422: Remove Email Sign-up Question 3 from Initial Flows
As a user, I don't want to provide my email when I'm just starting to engage with the platform.

Remove email signup page as it is a barrier for entry for users and they're prompted to login as soon as they interact with the posts.

image

As part of this story, please also update first two onboarding pages to say "Question 1/2"  and "Question 2/2" and on the Location question (2/2), we should change the "Next" to "Submit"
image

(We can look to leverage email signup functionality we built on a separate part of the site when we know what we're going to use the emails, but that will be a future story)

### PR DESCRIPTION
**Pull request by kterry1**
### What does this pull request aim to achieve? 💯
Removes third question from Request Help and Offer Help questionnaire sections.
Example: https://share.getcloudapp.com/2NuyOKNq
_Please be concise and link any related issue(s):_
#1422 

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix. The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

### CODE REVIEW

**Review by joshmorel — CHANGES_REQUESTED** [review]
If we're removing this then the whole SendGrid backend is not relevant. We should remove that as well but I'm going to confirm on Slack - do we really want to do this @emtay ? There were some strong justifications and major efforts to include this prior to soft launch.

**Review by idjevm — CHANGES_REQUESTED** [review]
Please wait on @manualzuru's input, once we do get to analyze more on this, we can either close this up and its perspective issue or merge this. 

I should be able to take care of the backend once this gets merged, so please let me know !

**Comment by kterry1** [comment]
Going to re-request reviews here. Per our Slack conversation, we are going to keep the backend and just remove the frontend from the Request Help/Offer Help questionnaires. Another GitHub ticket will be opened for where the email sign-up should go.

**Comment by galeza** [comment]
Hi @kterry1 ,

Tested on desktop and Android 10 using https://featureemail-sign-up1422.fightpandemics.xyz.
LGTM
May I accept or we are going to wait?

**Review by rabbi08 — APPROVED** [review]
Verified the fix on following devices on the feature build and it is working fine. Refer below screen recording for the same:
Device: iOS (iphone 11 pro max), windows\chrome

https://share.getcloudapp.com/YEuo2988

**Review by sheeba1 — APPROVED** [review]
Verified the fix using build url on desktop.

**Review by galeza — APPROVED** [review]

**Review by idjevm — APPROVED** [review]
LGTM! Based of the conversation, go ahead and squash merge unless we need to do something else before. 

Please remember to use Squash and Merge option, and change the default commit message to the following format: `#issueNumber - short description of what this PR accomplishes`

**Comment by rabbi08** [comment]
Verified in STG as working fine, refer below GIF:

https://share.getcloudapp.com/L1uQ7wel

**Pull request merged**
