### PR TITLE
Feature/893 footer at bottom

### PR DESCRIPTION
**Pull request by Joeu**
### What does this pull request aim to achieve? 💯

_Please be concise and link any related issue(s):_ Fixes issue #893 

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](https://github.com/FightPandemics/FightPandemics/blob/master/README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`** (need to have cloned the repo not forked).
- [x] This branch is rebased/merged with the **latest master**.
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

### CODE REVIEW

**Comment by jyclam** [comment]
I'm seeing some issues:
* `/feed`'s left nav and tucked underneath header
* `/about-us` content tucked underneath header
* footer behaves as if it's `absolute`ly positioned and scrolls up with content
screencapture-localhost-3000-about-us-2020-06-30-12_39_49
screencapture-localhost-3000-feed-2020-06-30-12_37_04

**Comment by idjevm** [comment]
Yup that's right @jyclam, let's keep discussing in slack, I already rised up these issues and asked Joeu to take a look

**Comment by Joeu** [comment]
@idjevm , @jyclam , please check it. Moving forward with the flex layout approach should require more effort. We can keep discussing it in slack.

**Comment by idjevm** [comment]
Note, we will address other smaller issues that might come up with the header/footer @ppagarawal

**Pull request merged**
