### PR TITLE
Hid grey drawer handle and removed hidden overflow for "no post" sign

### LINKED ISSUE #1459: Make drawer draghandle not visible
### The issue

Handler of the drawer menu on the right-hand side is visible and looks like a bug, it doesn't provide useful information to the user either, as the hamburger icon already indicates how to access the menu.

image

### Suggestion to fix
Remove background colour
```
.am-drawer-draghandle {
    z-index: 1;
    position: absolute;
    background-color: rgba(50,50,50,.1);
}
```

### LINKED ISSUE #1510: Help Board -> No Post available -> 'Create Post' message displayed ->is overlapped with white screen on the phone
1. Open 'Staging.fightpandemics.work'
2. Navigate to Helpboard and add filter as "Provider = Individual and University"
You will observe that no results i.e. No posts are displayed under the given criteria.
"Sorry, there are currently no relevant posts available. Please try using a different filter search or create a post."

Issue: The user message is overlapped by the white screen and user need to scroll to see the complete message.
https://share.getcloudapp.com/nOukr4Br

### PR DESCRIPTION
**Pull request by kterry1**
### What does this pull request aim to achieve? 💯
The grey drawer that was sticking out on the right side has been removed and the "No Posts Available" sign is now visible on mobile devices.
https://share.getcloudapp.com/OAuqeR6j

_Please be concise and link any related issue(s):_
#1510 and #1459 

- [X] I have checked that no one else is working on similar changes.
- [X] I have read the latest [**README**](README.md) and understand the development workflow.
- [X] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix. The branch is created in a cloned version of this repo, **not a forked repo**.
- [X] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [X] There are no merge conflicts.
- [X] There are no console warnings and errors.
- [X] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

### CODE REVIEW

**Review by CamilaArias — APPROVED** [review]
LGTM 👍

**Review by idjevm — APPROVED** [review]
LGTM! Thanks @kterry1 ! I'd say let's wait for @rabbi08 so they can verify this before merging.

**Comment by kterry1** [comment]
@idjevm Sounds good, thanks!

**Review by rabbi08 — APPROVED** [review]
Validated the fix on feature build and it is working fine. Refer attached screenshots.
Device used: iphone 11 pro max, simulator of iphone XR, Samsung galaxy

Hid grey area: PASS
https://share.getcloudapp.com/WnuJPAyZ

Overflow hidden for no post: PASS
https://share.getcloudapp.com/geuzXYmX

**Comment by joshmorel** [comment]
@kterry1 This change seems to have caused a few different issues including #1526. We can't define a styled component within another component.

It was solved here #1528 but I'm not sure if it re-introduced the other issues. @CamilaArias can you check? If so we need to solve a different way.

**Comment by joshmorel** [comment]
Actually I'm pretty sure both issues are still fixed. But please confirm @CamilaArias @rabbi08.

**Comment by rabbi08** [comment]
> both issues are stil

@joshmorel @kterry1 
Verified in STG and both the issues are working fine in STG. Thanks

https://share.getcloudapp.com/o0u8dnDz

**Pull request merged**
