### PR TITLE
Displaying the Organizations list in the create post modal

### PR DESCRIPTION
**Pull request by nr431207**
#### displaying the organizations list in the create post modal and removing the default `notion` lists :

Screen Shot 2020-06-26 at 1 39 24 PM
_Please be concise and link any related issue(s):_
#738 

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](https://github.com/FightPandemics/FightPandemics/blob/master/README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`** (need to have cloned the repo not forked).
- [x] This branch is rebased/merged with the **latest master**.
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

### CODE REVIEW

**Comment by nr431207** [comment]
To populate the orgs I am using some of the changes @MohamedEl1 has implemented in this PR : https://github.com/FightPandemics/FightPandemics/pull/808

**Comment by ppagarawal** [comment]
@nr431207 This needs to be there for mobile as well

**Comment by kylejvh** [comment]
@ppagarawal  #886 should fix the mobile side of things for this.

**Comment by ppagarawal** [comment]
@kylejvh please do not remove the organization menu item if there are no organization associated with the account. The menu item has to be available with an option to create one if there are no organization profile associated. Even if there are org profiles associated, the option to create one should be available. All these changes are required in the side menu

**Pull request merged**
