### PR TITLE
initial draft feature 1412

### LINKED ISSUE #1412: Display the number of confirmed cases based on my location
** This issue is linked to https://github.com/FightPandemics/FightPandemics/issues/1201

As a user, I'd like to see the number of COVID confirmed cases for my city, country and the world when I select the "Health Facilities Tab"

**Acceptance Criteria**

- Display confirmed cases in my city
- Display confirmed cases in my country
- Display global confirmed cases

**Feature requirements**
https://www.notion.so/fightpandemics/3bef5f3ee2ff4b75bc906cc4b9227015?v=d09ab8ac28cc4690ad40e961ff98bf33
Parent Feature
https://www.notion.so/fightpandemics/Nearest-Facilities-1769f08b2b7e4044a7c67fd363bdcb51

**Design** 
image

### PR DESCRIPTION
**Pull request by cjohlmacher**
### What does this pull request aim to achieve? 💯

Closes #1412 

- [X ] I have checked that no one else is working on similar changes.
- [X ] I have read the latest [**README**](README.md) and understand the development workflow.
- [ X] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix. The branch is created in a cloned version of this repo, **not a forked repo**.
- [X ] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [X ] There are no merge conflicts.
- [X ] There are no console warnings and errors.
- [X ] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

### CODE REVIEW

**Comment by joshmorel** [comment]
It might be useful to try it with our formatted location object, e.g.:

```javascript
  {
    address: "Venice, Metropolitan City of Venice, Italy",
    city: "Venice",
    coordinates: [12.3155151, 45.4408474],
    country: "IT",
    state: "Veneto",
  },
```

There are a few more here: https://github.com/FightPandemics/FightPandemics/blob/staging/backend/lib/components/Geo/mock/index.js

And the `expected` results here: https://github.com/FightPandemics/FightPandemics/blob/staging/backend/lib/components/Geo/gmaps/utils/Location.test.js

**Comment by cjohlmacher** [comment]
Currently country and global seem to be working fine, but the local case count has been tricky.  
The best API I was able to find that had a global reach but also good specificity for local case data was 
https://www.trackcorona.live

In the United states it can narrow down to the local county level, but it needs the full name of the state, not just the abbreviation.  We provide the full state name in the Italy example, so that one works fine to provide case counts for the state of Veneto.

**Comment by joshmorel** [comment]
Thanks @cjohlmacher !

FYI see above @tejasm2 @davidoduk @manualzuru 

The fake data presented for "Miami" at (https://fightpandemics.com/nearest-hospital) or in the original design with Barcelona is not going to work with any global API.

image

At best we can get county level for **USA only** but this would require some more work on the backend location component (3-4 hours?) for something that is not used in any other place in the app. 

As an alternate we can use state (Florida/Catalonia instead of Miami/Barcelona) as the most local.

**Comment by tejasm2** [comment]
I think it should be fine for now if we are not able to get the most local data/number of cases. (Covid scenario is going to be a temporary one, and maybe for now what we have is good, the main would be the display of health facilities in my opinion).

**Comment by rabbi08** [comment]
Closing this issue as low priority as of now. Please feel free to reopen if priority changes in future. thanks.

**Pull request closed without merging**
