### PR TITLE
fix the shivering elements

### LINKED ISSUE #1248: Fix the shivering elements across the platform
The text elements when hovered over distort the other elements. Please fix them to have stability and not distort other elements or introduce a scroll bar on the page
Please check this in the following pages/features
- [ ] filter with location
- [ ] header
- [ ] visibility of posts in the post modal window
- [ ] onboarding pages
- [ ] Individual profile
- [ ] Create org profile
- [ ] Sign in page
- [ ] Join now page

### PR DESCRIPTION
**Pull request by phuclb**
### What does this pull request aim to achieve? 💯

Resolves #1248

_Please be concise and link any related issue(s):_

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix. The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

### CODE REVIEW

**Review by idjevm — APPROVED** [review]
LGTM! According to @ppagarawal this should cover alll the requested changes from the issue. Thanks Phuc!

**Review by rabbi08 — CHANGES_REQUESTED** [review]
Shivering elements in following pages/features are working fine:

 - filter with location
 - header
 - onboarding pages
 - Individual profile
 - Create org profile
 - Sign in page
 - Join now page

Adding an observation for "visibility of the post modal window", the dropdown changes size after selecting the options and reset after other selects and change size.

Refer below GIF.

https://share.getcloudapp.com/8LuP7xoL

Above issue exist in Mac-> safari and iPhone 11

**Comment by sheeba1** [comment]
FYI.. The observation @rabbi08  mentioned for create post-drop-down size change is NOT happening on WINDOWS OS -Chrome and Edge

**Comment by phuclb** [comment]
Hi @rabbi08, your request is updated.
Please check it out.

**Review by rabbi08 — APPROVED** [review]
@phuclb The dropdown for Post visibility are working fine in Mac -> safari and iPhone 11. 
Please refer below GIF.

https://share.getcloudapp.com/rRu7lzq8

Thanks

**Review by idjevm — APPROVED** [review]
LGTM ! Thank you Phuc!

**Pull request merged**
