### PR TITLE
Production Release as on 11-03-2020

### PR DESCRIPTION
**Pull request by joshmorel**

### CODE REVIEW

**Review by Zaydme — APPROVED** [review]
### I approve the search feature code.
image
(i did review all the code except cypress)

**Comment by galeza** [comment]
> ### I approve the search feature code.
> image
> (i did review all the code except cypress)

@Zaydme I love your comment!!!!

**Comment by galeza** [comment]
I verified cypress and Polish translation.

**Review by galeza — APPROVED** [review]

**Review by jessica-lau — APPROVED** [review]
Reviewed cypress

**Review by idjevm — APPROVED** [review]
LGTM! Let's see how it does in prod!

**Review by rabbi08 — CHANGES_REQUESTED** [review]
- Found new critical issue needs to be fixed: #1756 

Verified following PRs in STG as working fine: 

PR #1718, refer below GIF: PASS
PR-1718

PR #1652, refer below GIF: PASS
PR-1622

PR #1724, this issue exist on both andriod and iOS. Verified on both. refer below GIF: PASS
PR-1724

PR #1746, refer below GIF: PASS
PR-1745

PR #1726, refer below GIF: PASS
PR-1726

PR #1695, refer below GIF: PASS
PR-1695-3
PR-1695-2
PR-1695-1

Testing following scenarios:
- Non logged user - Requesting help : PASS
- Non logged user  - Offering help: PASS
- Create Individual User: PASS
- Create Org : PASS
- Create Individual Post: FAIL PR #1756 
- Create Org Post: FAIL PR #1756 
- Filter the post on base of location: PASS
- Filter the post on base of provider and type : PASS
- Filter the post on base of location, provider and type: PASS
- Search keyword 'chinese, german, spanish' : PASS
- Upload avatar: Fail with issue #1757 (low priority)
- Switch language: PASS
- Provide Feedback: PASS
- Like own and other user post: PASS
- Comment on the post: PASS
- EDIT user profile: PASS
- EDIT Org Profile: PASS
- share post via email: PASS
- Apply filter -> perform search -> filters are removed: FAIL PR#1709 and PR#1728 exist for this
- Perform Search -> Apply Filter -> Filters are applied to the results: PASS

**Review by rabbi08 — APPROVED** [review]
Verified the fix for issue#1756 in STG, as working fine. Please see below GIF.

ezgif com-gif-maker (43)

QA is done with verification of the issues and the PRs merged into STG along with smoke testing. 

@FedericaZn, you can start with the verification of the GTM tags in STG environment.

Thanks

**Comment by FedericaZn** [comment]
tested Search tags, all good fro me

**Review by FedericaZn — APPROVED** [review]

**Pull request merged**
