### PR TITLE
use same setting title for mobile/web

### LINKED ISSUE #1922: The Page title for Organization profile is not updated on Mobile
1. Open 'Staging.fightpandemics.work' on mobile.
2. Login using valid email/pwd
3. Switch to ORG profile -> view profile -> Edit Profile

Issue: You will observe that though edit profile options are displayed as options for Organization but the page title is still same as individual profile. Refer below GIF.
also, this issue works fin eon desktop.

ezgif com-video-to-gif 34

We need to have same page titles on mobile as on desktop version.
image

### PR DESCRIPTION
**Pull request by ddveloper**
### What does this pull request aim to achieve? 💯
use same setting titles for mobile and web
_Please be concise and link any related issue(s):_
to fix #1922 

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Comment by Zaydme** [comment]
@ddveloper 
"instant" and "digest" is not being translated.
maybe because those are under "profile.common" and not in the root of the json
https://github.com/FightPandemics/FightPandemics/blob/d2097539f8d91ae54429bbf33f17a7bb534a3718/client/src/components/Input/NotifyPreferenceInput.js#L96

**Comment by ddveloper** [comment]
> @ddveloper
> "instant" and "digest" is not being translated.
> maybe because those are under "profile.common" and not in the root of the json
> https://github.com/FightPandemics/FightPandemics/blob/d2097539f8d91ae54429bbf33f17a7bb534a3718/client/src/components/Input/NotifyPreferenceInput.js#L96

Thanks Zayd, will fix it

**Comment by CamilaArias** [comment]
Can we also fix here @ddveloper @Zaydme 
- [x] - Toggle colour on notifications should be #425AF2
- [x] - Toggle should be placed after the "Email Notification" Heading on desktop
- [x] - Click area for the settings sections on desktop should be the entire box, not just the text.
- [x] - Spacing of the screen layout should be the same for all sections on desktop

**Comment by ddveloper** [comment]
@CamilaArias I re-layout them following same checkboxes in the Account page, see if this looks good or not : )

image

**Comment by Zaydme** [comment]
Should we make them vertical like in mobile, so we don't have to worry about spacing 😂

**Comment by CamilaArias** [comment]
LGTM @ddveloper awesome! Well at least from the screenshot, can't see it in the build yet

**Comment by ddveloper** [comment]
> LGTM @ddveloper awesome! Well at least from the screenshot, can't see it in the build yet, maybe there's still AWS issues

I didn't push it, will do now, I was wondering to get your feedback first, will also see if I can make it vertical

**Comment by ddveloper** [comment]
@rabbi08 @CamilaArias please take a look the new build https://feature1922-sametitle-settingpages.fightpandemics.xyz/ thanks : )

**Review by Zaydme — APPROVED** [review]
code-wise, LGTM!

**Comment by rabbi08** [comment]
Verified the fix on the feature branch, working fine, Thanks @ddveloper 
- Titles on the mobile for Organisation profile are updated, refer below screenshot.
ezgif com-video-to-gif 41

- Notification Preferences: option is displayed below "Security Information": PASS

- Notification TAB changes:
  - Toggle colour on notifications should be #425AF2
  - Toggle should be placed after the "Email Notification" Heading on desktop
  - Click area for the settings sections on desktop should be the entire box, not just the text.
  - Spacing of the screen layout should be the same for all sections on desktop

Refer below screenshot.
Screen Shot 2020-11-28 at 8 40 08 PM

Note: @CamilaArias @zayd The notification options will look better if they are displayed in parallel. Please share your thoughts.

**Comment by ddveloper** [comment]
@rabbi08 sure, I will change that

**Comment by CamilaArias** [comment]
Hey @ddveloper sorry I think I didn't explained well one of the points. I was asking to make these settings sections clickable the whole box.
image
Please discard the changes on making the text on the checkboxes clickable, since it also makes the whole width clickable as well, let's keep it just the checkbox.
I'm sorry for the confusion!
image

**Comment by CamilaArias** [comment]
I mean you can close this without changing the **sections** click area I showed above, just thought we have to fix that so could do it here.

**Comment by CamilaArias** [comment]
@rabbi08 @ddveloper agree it would look better parallel
image

**Comment by ddveloper** [comment]
@CamilaArias @rabbi08  please take a look at this new layout, also the clickable section is expanded https://feature1922-sametitle-settingpages.fightpandemics.xyz/ thanks : )

**Review by rabbi08 — CHANGES_REQUESTED** [review]
@ddveloper 
The changes are displayed as expected:
-  the profile TABS are clickable in the whole box.
- The 'Instant/digest' aligned horizontally.

BUT, after user clicks on 'Save Changes' blank screen appears. this is having for on all TABs 'Save changes' button.
Please see below GIF.

ezgif com-video-to-gif-3

**Comment by Zaydme** [comment]
@rabbi08 this issue is caused by another PR, please check slack

**Comment by Zaydme** [comment]
It's because someone created a post with the new "Housing" tag, and that PR wasn't merged yet, so when this build tries to render it it crashes

**Review by rabbi08 — APPROVED** [review]
I am able to 'Save Changes' now. Thanks

**Review by Zaydme — APPROVED** [review]
LGTM

**Pull request merged**
