### PR TITLE
Automated test on sign up page using POM

### PR DESCRIPTION
**Pull request by jessica-lau**
### What does this pull request aim to achieve? 💯

Test sign up page's features using POM.

_Please be concise and link any related issue(s):_

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix. The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

### CODE REVIEW

**Review by rabbi08 — CHANGES_REQUESTED** [review]
@jessica-lau 
The test looks great, I would like to suggest to few updates as below:

- Update 'Join Now' button test: Rather than checking 'Join Now' visibility, we should check that the 'Join Now' button remain disable until user enter all the required details to create an account. After that the 'Join Now' button should be enable after user enter valid details for all the required fields. hence this test case should be for Join Now button is 'Enable/disable'

- Please update the social media test as visible and "Clickable"

- Please add test for "FightPandemics" logo, as visible and clickable.

Thanks

**Comment by jessica-lau** [comment]
@rabbi08 I added new tests for the Join Now button to test the enable & disable state. I also added a test for the FP logo to ensure it's visible and clickable.

As for updating the social media sign up buttons to test if they're clickable, Cypress prevents opening external URLs (facebook.com/linkedin.com etc.) when clicking the social media buttons, so it does not allow me to check if the buttons are clickable as it will redirect me to the external sites. See screen shot below. I can override the "chrome web security" in the cypress.json file to allow me to do the clickable test, but I'm not sure if this is recommended for security purposes.

image

**Review by rabbi08 — APPROVED** [review]
@jessica-lau 
thanks for the update.

And yes, you are right, disabling the browser security is not a good approach to test the clicking feature for social media buttons. They are being directed to other iframe "https://fp-staging.eu.auth0.com/" so it need different approach to test.

Currently this test looks good. Thanks

**Review by galeza — APPROVED** [review]

**Comment by galeza** [comment]
LGTM

@idjevm please merge.

**Review by idjevm — APPROVED** [review]
Thank you ! LGTM !

**Pull request merged**
