### PR TITLE
#1930-modify-create-post-button

### LINKED ISSUE #1930: Modify Create Post button
Should be [**-> This <-**](https://www.figma.com/file/EMKcg0eTnOlr7bRZGFdnZu/Web-app-product-spec?node-id=145%3A328)  (link to Figma file). Inspect on Figma for specs.
image

Current:
image

### PR DESCRIPTION
**Pull request by juandelima**
### What does this pull request aim to achieve? 💯

_Please be concise and link any related issue(s):_
closes #1930

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Comment by ddveloper** [comment]
@juandelima , about the `client/package-lock.json`, since you didn't use any new package, so we don't change that, also I see the mobile version `create` button is missing, please have a double check

**Comment by rabbi08** [comment]
Verified the fix, the button is change the it is working.
Refer below screenshot.

image

**Review by rabbi08 — CHANGES_REQUESTED** [review]
@juandelima 
The 'Create a Post' is not displayed correctly on 'Profile page of ORG'
Please refer below screenshot.

image

**Comment by rabbi08** [comment]
Closing the other duplicate #1955

**Comment by ddveloper** [comment]
> Closing the other duplicate #1955

@rabbi08 #1955 is a better version, @juandelima we're going to close this one and working on #1955  instead

**Pull request closed without merging**
