### PR TITLE
Feature/cookie banner test

### PR DESCRIPTION
**Pull request by Jennysgithub**
https://www.notion.so/fightpandemics/Add-test-cookie-dialog-box-f351aaf2857243858b0c3d33ef653c03

Add tests for the home page cookie banner.

- [x] Test that the cookie banner is displayed on the home page.
- [x] Test that we can close the cookie banner displayed on the home page.

### CODE REVIEW

**Comment by galeza** [comment]
Hi @idjevm @doheekim93 
If you have time, please look at client/src/components/CookieAlert.js file. There are new IDs added for Cookie alert. Could you check if they are conform with existing naming conventions? I'm not sure ... Can we keep them like this?

**Review by rabbi08 — CHANGES_REQUESTED** [review]
The test looks good, 'HTML ids' that are being added and further used in the test are working fine.

I would like to suggest that to complete this feature test:
- Add test cases to verify the links for 'Cookie policy, Privacy policy and Terms and conditions' existing in the cookie message that is being verified through this test.

**Review by sheeba1 — APPROVED** [review]
Successfully ran the tests. Thanks @Jennysgithub

**Review by jessica-lau — CHANGES_REQUESTED** [review]
As @rabbi08 mentioned, it would be helpful to add a test case to verify the 'Cookie policy, Privacy policy and Terms and conditions' link exists and is clickable.

The 'CookieAlert.js' file should lead with camel casing. Currently, it appears as follows:
client/src/components/CookieAlert.js file

**Comment by Jennysgithub** [comment]
@galeza @jessica-lau @sheeba1 @rabbi08  Thanks for reviewing. I will add additional test to verify the links in the cookie banner as suggested.

**Comment by Jennysgithub** [comment]
@galeza @jessica-lau @sheeba1 @rabbi08 I added test for cookie banner links as suggested.

**Comment by galeza** [comment]
Hi!
Follow up of my comment about ID naming convention: I will discuss with Federica the naming convention for IDs. I'll create a new issue for that and maybe we could change and also add more IDs for elements and simplify our tests. 
If tests are ok, we can merge it.
After discussion with Federica - for cookie alert we can leave our IDs. Currently BI team is not going to track it.

**Review by galeza — APPROVED** [review]

**Review by jessica-lau — APPROVED** [review]
LGTM

**Review by rabbi08 — APPROVED** [review]
New changes looks good, Thanks

**Review by idjevm — APPROVED** [review]
LGTM! Thanks everyone!

**Pull request merged**
