### PR TITLE
fixed editing comment timestamp

### LINKED ISSUE #1645: Edit comment -> the timestamp is not displayed correctly.
1. Login in FP using valid email/Pwd
2. Navigate to Help Board and add a comment to the Post.
3. Now EDIT the previously added comment.
Issue: You will observe that the timestamp for comment is not displayed in user readable form. Refer attached GIF and screenshot.
image

ezgif com-gif-maker

### PR DESCRIPTION
**Pull request by Zaydme**
### What does this pull request aim to achieve? 💯

correctly display timestamp on edited comments

closes #1645

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`**, or **`hotfix/<branch_name>`** if this is a hotfix, where `<branch_name>` briefly describes the issue(s) resolved and is prefixed with the issue number(s) (e.g. `1127-1130-update-git-branching-model`). The branch is created in a cloned version of this repo, **not a forked repo**.
- [x] This branch is rebased/merged with the **latest staging** (or the **latest production** if it is a hotfix).
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".
- [x] The title describes the issue(s) being addressed using format: **`<issue_numbers> - <brief_issue_description>`** (e.g. `#1127/#1130 - Update Git Branching Model`)

### CODE REVIEW

**Comment by rabbi08** [comment]
The edited comment for a post display both 'created and edited' time for the comment. This looks complicated to the end user. Can we display created time along with comment as 'edited'? Please refer below screenshot.

image

**Comment by Zaydme** [comment]
@rabbi08 
image

**Review by rabbi08 — APPROVED** [review]
Verified in feature branch, it is working fine. Thanks

image

FightPandemics (16)

**Review by joshmorel — APPROVED** [review]
Thanks @Zaydme ! I will merge.

@doheekim93 there is a new key to translate under "post" - "edited"

**Pull request merged**
