### PR TITLE
Fixed the profile explanation for need or want to help sentence

### LINKED ISSUE #820: Profile explanation for NEED/WANT TO help is displayed as one sentence
1. Open "https://staging.fightpandemics.work/"
2. Login using valid email/password
3. Click on 'Profile' 

Issue: You will observe that if user NEED help and WANT TO help, then the message is displayed as one sentence i.e. 
"I need help I want to help"
 in profile explanation, as shown in below screenshot.
Screen Shot 2020-06-25 at 12 51 50 PM

### PR DESCRIPTION
**Pull request by rockcoolsaint**
### What does this pull request aim to achieve? 💯

Profile explanation for NEED/WANT TO help is displayed with a demarcation instead of as one string

- [x] I have checked that no one else is working on similar changes.
- [x] I have read the latest [**README**](https://github.com/FightPandemics/FightPandemics/blob/master/README.md) and understand the development workflow.
- [x] The name of this branch is: **`feature/<branch_name>`** (need to have cloned the repo not forked).
- [x] This branch is rebased/merged with the **latest master**.
- [x] There are no merge conflicts.
- [x] There are no console warnings and errors.
- [x] On the right hand side of this PR, I have linked the appropriate issue(s) under "Issues" and added a project progress under "Projects".

### CODE REVIEW

**Review by OzkanAbdullahoglu — CHANGES_REQUESTED** [review]
I think we don't need string interpolation here anymore? Also, the address is required field while creating a profile in form. Do we have to check on that? Maybe this is not addressing to this ticket but I wonder your opinions? @joshmorel  @robinv85

**Comment by rockcoolsaint** [comment]
So what is the required step now?

**Comment by joshmorel** [comment]
> I think we don't need string interpolation here anymore? Also, the address is required field while creating a profile in form. Do we have to check on that? Maybe this is not addressing to this ticket but I wonder your opinions? @joshmorel @robinv85

@OzkanAbdullahoglu  Address is required BUT there is an option to hide it for the individual user so it might not be returned with the data (and therefore is null).

@rockcoolsaint - I'm going to also ask @Yu-Alexa-Zhao - We have these icons here instead of text, I guess we never implemented it.... Maybe we should here?

https://app.zeplin.io/project/5ecaed1b2522d9280f1a4792/screen/5ed569000face21f70a4dce9

image

**Comment by rockcoolsaint** [comment]
Ok, please do and let me have feedback.

**Comment by joshmorel** [comment]
> Ok, please do and let me have feedback.

Let's wait for feedback from design (Yu) on using the icons instead before continuing.

**Comment by rockcoolsaint** [comment]
Ok

**Comment by Yu-Zhao-UX** [comment]
Sorry I think I am not fully understanding here. Do you mean if we want to include "give help" and "need help" texts in the icons? OR do you mean whether we want to include the twitter icons, etc.? Sorry, the deployment env is showing a 503 error...

**Comment by yu-zhao-xyz** [comment]
Sorry I think I am not fully understanding here. Do you mean if we want to include "give help" and "need help" texts in the icons? OR do you mean whether we want to include the twitter icons, etc.? Sorry, the deployment env is showing a 503 error...

**Comment by joshmorel** [comment]
@Yu-Alexa-Zhao 

This is the current state:

image

The reported issue was that "I need help I want help" is all squished into once sentence which doesn't look good.

The fix in this branch is to add a bullet between those so it's not just one sentence:

image

However, I looked into Zeplin to see what is expected and the design has the icons in the screenshot. So I was proposing instead we actually use the icons just wanted to confirm. Also, do we use the same icons as the Home page or is there something new?

**Comment by rockcoolsaint** [comment]
Once there's a concensus, we can make progress

**Comment by yu-zhao-xyz** [comment]
Got it. I think both solutions work. But I slightly prefer using the icons instead of text. The positions of the icons can be on the next line, and we can use the new icons on the homepage. 
image
(the icons in the above image haven't been replaced by the latest icons).
Lastest icons link: https://zpl.io/V4WB1dQ, https://zpl.io/a8M0KvJ
Thank you for explaining!

**Comment by CamilaArias** [comment]
Not an issue anymore

**Pull request closed without merging**
